### ISSUE TITLE
Segmentation fault during chimera detection

### ISSUE THREAD

**Issue by bistace** [fenderglass/ABruijn#1]
Hi,
I tried using ABruijn with Oxford Nanopore reads but I get a segmentation fault error during the chimera detection phase.

Here is the command line I used : 
`python abruijn.py $(pwd)/BAM_10X.fasta BAM_10X`

Moreover here is the log : 
```
Running ABruijn
Assembling reads
[10:50:02] Reading FASTA
[10:50:05] Building kmer index
[10:50:05] First pass:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[10:55:39] Second pass:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[10:56:33] Trimming index
[10:56:36] Building read index
[10:56:37] Finding overlaps
[10:56:46] Detecting chimeric sequences
Error:  Error in assemble binary:
Command '['abruijn-assemble', '/env/cns/bigtmp1/ONT/ABruijn/BAM_10X.fasta', '/env/export/nfs6/bigtmp1/ONT/ABruijn/BAM_10X/read_edges.fasta']' returned non-zero exit status -11
```

If I run the faulty command manually, I get a segmentation fault.
```
abruijn-assemble /env/cns/bigtmp1/ONT/ABruijn/BAM_10X.fasta /env/export/nfs6/bigtmp1/ONT/ABruijn/BAM_10X/read_edges.fasta
``` 

Moreover, the output directory is empty.

Thanks for your help,
Benjamin

**Comment by fenderglass** [comment]
Thanks for your feedback!
I will try to fix it, we also preparing an updated version of the whole package, which should be released shortly.

Mikhail

**Comment by fenderglass** [comment]
This should be fixed now.

Also, what coverage do you have? If it is 10x (as I may guess from the filename), it would require lower values of minimum kmer frequency - consider running with "-m 4".

**Comment by bistace** [comment]
Hi,
thanks for fixing it! I will try to run it again shortly and report back. 
I have around 200X of reads, the file I used in my first post is a test file to verify that everything is working well.

**Comment by fenderglass** [comment]
Thanks, your feedback would be very important!

We haven't tested it on 200x so far, the polishing part might be
time-consuming - I suggest parallelize as much as possible (-t option).
Also, -m could be set to higher value (8-12). We are also working on
inferring these parameters automatically - I'll be in touch with it.

**Comment by bistace** [comment]
I tested it again and had an other problem during or just after the contig generation. I got this error : 
```
[17:42:05] root: DEBUG: terminate called after throwing an instance of 'std::out_of_range'
[17:42:05] root: DEBUG: what():  basic_string::substr: __pos (which is 6055) > this->size() (which is 5995)
[18:08:32] root: ERROR: Non-zero return code when calling abruijn-assemble module: -6
```

The full log is available at this [link](https://www.dropbox.com/s/z1h3jhcm2se935b/abruijn.log.txt?dl=0) (I added the .txt manually so it can be viewable from a browser).

**Comment by fenderglass** [comment]
Thanks!

Seems that we have issues with finding switch positions between reads when the coverage is high - I will try to fix it. 

Also, it is definitely strange that many sequences were marked as chimeric (and the high number of contigs as well). What kind of organism is that? What is the expected genome size, and which -m parameter did you use for that case?

**Comment by bistace** [comment]
I

**Comment by fenderglass** [comment]
Please try the updated version. We have tested it on Pacbio yeast dataset with about 100x coverage and got almost complete assembly. Polishing module was not fully tested though.

Now the program requires the assembly coverage estimate as an input, all other parameters are inferred automatically.

**Comment by bistace** [comment]
Hi,
just a quick update to tell you that ABruijn has passed the assembly step correctly and is now polishing the resulting sequence. I will report back at the end of the polishing.

**Comment by bistace** [comment]
ABruijn finished successfully after approximately 7 hours. I gave 120X of Nanopore reads as input and obtained 23 contigs as a result, so quite good results.
Do you have any recommendation concerning the input reads coverage or should I experiment myself case by case ?

**Comment by fenderglass** [comment]
Great to hear that!
Currently, I do not see any reason not to use all available reads except for performance purposes. We have not tested 200x nanopore coverage, though.
