### ISSUE TITLE
Minimum coverage requirement

### ISSUE THREAD

**Issue by danshu** [fenderglass/ABruijn#10]
May I know the minimum coverage requirement for ABruijn to assemble a genome of about 300Mb?

**Comment by fenderglass** [comment]
It is hard to generalize, but in principle 30-50x should be sufficient for an optimal contiguity / base quality. Theoretically, with 10-20x you still should be able to assemble a good portion of the genome, but you might loose in N50 and overall quality.

**Comment by danshu** [comment]
Thanks!
