### ISSUE TITLE
metaFlye and haplotye-aware assembly doubts

### ISSUE THREAD

**Issue by fmalmeida** [fenderglass/ABruijn#101]
Hello,

I am currently wanting to use your `metaFlye` assembly module in our dataset and I have a few questions about it.

When using the option `--meta` one still needs to set `--genome-size`? If yes, one needs to set it for the whole sum of genome sizes or just for the biggest?

Another question is, do you believe this `--meta` option is capable of separating not only **species** but also **strains**? 

And, there is a way to assembly **two haplotypes** of a genome with Flye?

Thanks in advance.

**Comment by mikolmogorov** [comment]
Hi,

>When using the option --meta one still needs to set --genome-size? If yes, one needs to set it for the whole sum of genome sizes or just for the biggest?

In meta mode, you need to provide the (expected) sum of all genome lengths. In fact, metaFlye is not very sensitive to this parameter - so you just need to provide a rough estimate.

>Another question is, do you believe this --meta option is capable of separating not only species but also strains?

It depends on how divergent these strains are, and also their coverage. If there is enough difference, you often can get partial assemblies of different strains. In some real metagenomic dataset we actually saw high strain variations for some bacteria, that led to extra complexity on the graph and less contiguous assembly as a result. I would suggest to visualize the assebmly graph with Bandage - different strains of same species will likely form knot-like structures on it.

>And, there is a way to assembly two haplotypes of a genome with Flye?

Diploid assembly is currently limited - you should be able to get the alternative allele sequences, but Flye does not recover small SNPs/indels. We are planning to add hapolotyping support in the future releases.

**Comment by fmalmeida** [comment]
Thank you very much, this response was quite enlightening. I am looking forward to this haplotyping support addition.

Thanks.

**Comment by mikolmogorov** [comment]
Closing the issue for now - feel free to reopen if you have more questions.
