### ISSUE TITLE
Invalid char while reading fasta file

### ISSUE THREAD

**Issue by leosanbu** [fenderglass/ABruijn#111]
Hi,

Many thanks for this tool, very promising! I have run it successfully on some Pacbios using corrected reads (--pacbio-corr) but for one of them it stops after:
[2019-05-17 10:49:53] INFO: Starting Flye 2.4.2-release
[2019-05-17 10:49:53] INFO: >>>STAGE: configure
[2019-05-17 10:49:53] INFO: Configuring run
[2019-05-17 10:49:54] ERROR: Invalid char while reading canu_correctedReads_edited.fasta.gz

I can't find any non-ACTG character on that file, and the fasta ids are the same format as other strains in which flye worked (contains a couple of / and an = apart from underscores). What can I be missing? Many thanks for your help :)

Best,
Leo

**Comment by mikolmogorov** [comment]
Hi,

Hard to tell what exactly causing the error without looking at the file. This error says that there is an unexpected character in the non-header string (not starting from ">"). In fact, most of the alphabetical characters are ok (like iupac codes). Maybe you have the ">" symbol in the middle of nucleotide string?

I haven't tried it myself, but maybe you can to do any kind of conversion with seqtk (https://github.com/lh3/seqtk) - it should output valid fasta/q in the end.

Best,
Mikhail

**Comment by mikolmogorov** [comment]
I assume the problem was resolved - feel free to reopen if it is still an issue.

**Comment by ptranvan** [comment]
Same issue, any solution ?
