### ISSUE TITLE
Help with Estimating genome size

### ISSUE THREAD

**Issue by mradz19** [fenderglass/ABruijn#113]
I'm attempting to assemble plasmid reads which were generated using Nanopore sequencing. I'm expecting several plasmids with the largest being approximately 50kb, what estimate should I use for the genome size?

**Comment by mikolmogorov** [comment]
Hi,

You can set it to the total expected assembly size (sum of plasmid lengths). I would also recommend to use `--meta` option,  which is not very sensitive to the genome size parameter.

Mikhail

**Comment by spe238** [comment]
What would be the consequence of setting a too low estimated genome size?
What happens, if the estimated genome size is not set at all?
What you always recommend to use the --meta option with plasmids, even though it is not a metagenome?

**Comment by mikolmogorov** [comment]
@spe238 current versions of Flye do not require genome size as input.

**Comment by spe238** [comment]
Thank you!
