### ISSUE TITLE
Feature request: option to run until a stage

### ISSUE THREAD

**Issue by kdm9** [fenderglass/ABruijn#114]
Hello,

I'd like to be able to run Flye until a certain stage. With our genome, the repeat graph creation step takes a very long time (>2 days) on a single thread, and I'd like to be able to run this step on a separate job on our cluster that has longer walltime limits for 1cpu jobs. Currently, we run flye normally, and then --resume it in a second job once the first has timed out and been killed. This is inefficient, as the stages before repeat graph creation are quite quick and parallelised well. 

If I were to implement an option `--run-until` that implemented this feature, would you merge this?

My plan: 

- `--run-until` should take one of `configuration`, `assembly`, `consensus`, `repeat_graph`, `trestle`, `plasmids`, `contigger`, `polishing`, `report`, `completion`, roughly corresponding to the steps laid out in the `_create_job_list` function [here](https://github.com/fenderglass/Flye/blob/flye/flye/main.py#L422) (default completion)
- make the _create_job_list function stop if --run-until is equal to each given step in that function

Any feedback on this plan?

Cheers,
Kevin

**Comment by mikolmogorov** [comment]
Hi Kevin,

Sure, this is a good suggestion - I like the plan.

Regarding the repeat graph slowdown - why are you using only one thread? Or you allowed multiple, but Flye was only using one? Maybe you could send me the log file so I can take a look?

Best,
Mikhail

**Comment by kdm9** [comment]
Sorry, I should clarify. The repeat graph step is run on 28 cpus. It spends ~1h at around 2800% utilisation (i.e. 100% on all 28 cores), and then drops to 1 cpu at 100% for as long as it takes for the job to be killed by the cluster. I'll send a log.
