### ISSUE TITLE
Possible stall while sorting k-mer index

### ISSUE THREAD

**Issue by EdHarry** [fenderglass/ABruijn#119]
[flye.log](https://github.com/fenderglass/Flye/files/3251982/flye.log)
Flye has been at the "sorting k-mer index" stage for 10 hours, the task is showing as running but the CPU usage is reported as 0.0%
![flye](https://user-images.githubusercontent.com/30314401/58874613-2ccdb680-86c1-11e9-945c-5e82b8a47be2.png)

**Comment by mikolmogorov** [comment]
Hi,

Thank you, could you provide the full log and some details about the dataset?

**Comment by EdHarry** [comment]
Actually never mind, it moved onto the disjointig assembling stage this morning. I think it took about 30 hours to sort the k-mer index.
