### ISSUE TITLE
--genome-size for de-novo genome?

### ISSUE THREAD

**Issue by jolespin** [fenderglass/ABruijn#120]
I'm trying to run `flye` to de-novo assemble a diatom.  I'm not sure what the genome size could be?  How should I proceed for this with `flye`?

Also, is there a way to use both `pacbio` and `nanopore` reads?

**Comment by mikolmogorov** [comment]
The assembly size parameter could be a rough estimate - and then you can adjust it based on the previous runs. You can also use `--meta` mode that is not sensitive to genome size parameter.

See #98 for PacBio + ONT assembly.
