### ISSUE TITLE
Suitable for very large genomes ？

### ISSUE THREAD

**Issue by luca-Wang** [fenderglass/ABruijn#123]
Hi,

Does Flye Suitable to assembly a 25Gb genomes （100X PacBio Sequel data coverage） ？ Are there any cpu and RAM recommendations for running this very large genome ?

And for a 4Gb genome (150X pacbio Sequel  data coverge) ？ How is the  cpu and RAM recommendations ？ 

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

No, Flye currently can not handle very large genomes. Please refer to this table for RAM / CPU usages: https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-flye-benchmarks

**Comment by luca-Wang** [comment]
Thanks, I have see the table for RAM / CPU usages, but the maximum genome is 2.9Gb and the data is only ~35X， so no information provided for genomes greater than 4Gb  (150X data coverage). Thus I am not sure whether Flye can handle a  4Gb genome (150X) and it's RAM / CPU 。

**Comment by mikolmogorov** [comment]
Genome of size 4Gb should be ok. RAM usage scales linearly with the input size - I suggest to use option `--asm-coverage 30` to use longest 30x for disjointig assembly. I think you will need around 800-900 Gb of RAM in this case (you can try lower values of `--asm-coverage` if you want to reduce it further). The performance varies for different genomes, but I would guess 7000-9000 CPU hours.

**Comment by luca-Wang** [comment]
Thanks !
