### ISSUE TITLE
Flye is extremely slow in assembling metagenomes

### ISSUE THREAD

**Issue by utritala** [fenderglass/ABruijn#126]
Hi Mikhail,

I have two questions: 

1. I noticed that Flye produces a polished assembly. Do we need to polish it with an external programs like nanopolish, CONSENT, etc ?

2. I am trying to assemble a metagenome using some nanopore data with --meta option and Flye seems to be running for a long time whereas it finished very quickly for a genome. Is this normal? Here is the log file if you need it: https://drive.google.com/file/d/1cX3hA9Nc0oV2JcfTTxyEbdifxj_jSjES/view?usp=sharing

Many thanks.

**Comment by mikolmogorov** [comment]
Hi,

1. See #110 for the PacBio polishing discussion. For ONT you will likely need an external polisher (nanopolish/Medaka) to get higher consensus quality. And currently, you might still need Illumina data to fix the remaining indels and get the reference quality assembly.

2. The running time depends on the input size (reads coverage + genome / metagenome length). In your case, for 44 Gb of ONT reads a few days of runtime (in 16 threads) seems normal to me. Metagenome also tend to be slower than regular isolate assemblies. You can try to increase the number for threads to make it faster.

Best,
Mikhail
