### ISSUE TITLE
Question about circular sequence output

### ISSUE THREAD

**Issue by russellj7** [fenderglass/ABruijn#131]
Hello,

First of all, thank you for creating Flye! It has been very useful for bacterial genome assembly.

In the `assembly_info.txt` output, there is a column for denoting circular contigs under "circ.". Just to confirm, "+" denotes a circular sequence? Also, if the sequence is denoted as circular, is the sequence already circularized in the Flye output `assembly.fasta` or would circularization need to take place after assembly?

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Thank you for the feedback.

Yes, "+" corresponds to a cricular sequence. You can also visualize the assembly graph with Bandage / AGB to have an overview of the assembly.

The sequence should be circularized already. Some people reported that Flye might delete a few (~10) bases at the contig's breakpoint. We are planning to fix this in the future. See the Ryan Wick's evaluation for the details (https://github.com/rrwick/Long-read-assembler-comparison).

**Comment by StevenJRobbins** [comment]
Thank you for this thread! I was hoping I could dig a little bit deeper. Is circulation determined simply by finding that the path in the assembly graph from the beginning of a contig ends at the end of the same contig? This seems intuitive but I wanted to confirm. 

And when you say that the sequence was "circularized", what does this mean? Is the sequence trimmed to remove overlap?

Thank you!

**Comment by mikolmogorov** [comment]
Yes to both!

**Comment by Fatma116** [comment]
Hello, what does it mean if chromosomal contig is denoted non-circular? Is it because there is a gap at the end between the last and first base, any possible overlap at the ends was not trimmed, or it is just simply the nature of the chromosome that it is linear?
Thanks

**Comment by mikolmogorov** [comment]
@Fatma116 it may mean all of these. If you visualize assembly graph, you may get a better idea wha is causing this.

**Comment by Fatma116** [comment]
@fenderglass  Thanks a lot for your reply. I looked at the assembly graph (largest contig )but I am confused about how to determine what is the reason, but I can see that it is not completely closed as in edges 8, 9, 10, 11, and 12. I am attaching the assembly graph as well as the assembly info. I would appreciate it if you can have a look. 
![assembly_graph](https://github.com/fenderglass/Flye/assets/140822350/e6e8e275-e2b0-4a0b-b595-9d93a02bc438)
[assembly_info.txt](https://github.com/fenderglass/Flye/files/13659283/assembly_info.txt)
Thanks a lot in advance

**Comment by mikolmogorov** [comment]
@Fatma116 it does look like a circular chromosome, and there is one unresolved region (represented by edge_3 and edge_3). This may mean that either you have a long tandem duplication in this region. Another possibility is that you may have heterogeneity in your population, with some clones having an expanded repeat. In this case, that creates ambiguity. If you could send me `flye.log` file, I may be able to distinguish these to cases.

**Comment by Fatma116** [comment]
Dear Mikhail
Attached you can find the flye log file
Thanks in advance
Best

Fatma Mahmoud
PhD Student
Research Unit of Comparative Microbiome (COMI)
Helmholtz Munich

________________________________
