### ISSUE TITLE
[Conda] Python 3-based version of Flye planned?

### ISSUE THREAD

**Issue by mjbeyeler** [fenderglass/ABruijn#132]
Hello!

First of all thanks for the awesome tool!

I was wondering if by any chance you are working on a Python 3-based version of Flye?

I am trying to build a comprehensive Conda assembly environment, and it's a real bummer if I want to have Flye in that environment I have to downgrade to Python 2.

Best

**Comment by mikolmogorov** [comment]
Hi,

Yes, Python 3 support is in our plans - hopefully sometime this Summer.

Mikhail

**Comment by mikolmogorov** [comment]
Version 2.6 now has Python 3 support!
