### ISSUE TITLE
Combining Pacbio and ONT

### ISSUE THREAD

**Issue by ghost** [fenderglass/ABruijn#137]
Hello,

What's the best strategy to combine both types of reads? Should I feed a single fasta file containing both ONT and PacBio as if it was an ONT reads file? 
Or is it best to assemble separately ONT and PacBio and then produce a consensus with the option subassemblies? 
The doc specifies "Mixing different read types is not yet supported. ", therefore am I right to think the second strategy is the way to go?

Thanks a lot!

**Comment by mikolmogorov** [comment]
Please refer to the FAQ: https://github.com/fenderglass/Flye/blob/flye/docs/FAQ.md
