### ISSUE TITLE
Error occured during assembly

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#138]
Dear all,

I used flye for assembly of nanopore raw reads. The code is below:
flye --nano-raw Crystal_all_porechop.fastq --out-dir Crystal_flye_3kb --genome-size 580m --threads 20 --debug --min-overlap 3000

However, I got error message after running for about 1 day in the out file. 

[2019-08-13 23:34:08] ERROR: Command '['flye-assemble', '--reads', 'Crystal_all_porechop.fastq', '--out-asm', '/home/hpc/crlee/HungWei/nanopore/mungbean/fastq/Crystal_all/Crystal_flye_3kb/00-assembly/draft_assembly.fasta', '--genome-size', '580000000', '--config', '/home/hpc/crlee/miniconda/envs/nanopore/lib/python2.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/home/hpc/crlee/HungWei/nanopore/mungbean/fastq/Crystal_all/Crystal_flye_3kb/flye.log', '--threads', '20', '--debug', '--min-ovlp', '3000', '--kmer', '17']' returned non-zero exit status -4
/var/spool/torque/mom_priv/jobs/181885.pbs.SC: line 13: 27473 Segmentation fault      (core dumped) flye --nano-raw Crystal_all_porechop.fastq --out-dir Crystal_flye_3kb --genome-size 580m --threads 20 --debug --min-overlap 3000

Can someone give me suggestions how to solve this problem? Thank you!

Best wishes,
Hung-Wei

**Comment by mikolmogorov** [comment]
Hi,

Could you post the flye.log file of your run? Could it be that the system ran out of memory?

**Comment by hungweichen0327** [comment]
Dear Mikhail Kolmogorov,
I am sorry for the late reply. I just used --resume option and it continued running. However, after one day, it stopped again. I ran the script on PBS cluster. The file below is the flye.log file:
[flye.log](https://github.com/fenderglass/Flye/files/3515207/flye.log)

And the below is the output file:
[job_Crystal_flye_10kb.txt](https://github.com/fenderglass/Flye/files/3515210/job_Crystal_flye_10kb.txt)

Thank you for the patience and I am willing to provide any information for debug if you need.

**Comment by mikolmogorov** [comment]
Ok, looks like it went though the first assembly stage and disjointigs look promising (N50 = 13mb). The rest of the pipeline is typically shorter (should be 1-2 days in your case), but it seems that for some reason the job gets killed.

Looks like you did two tries of the consensus stage - first time minimap2 alignment was completed, but the python consensus code failed. Do you have the terminal output for this crash as well? 

The second time it failed during minimap2 alignment. Because it fails on different stages of the pipeline, I think it is likely that Flye jobs are getting killed by the system, rather then it's a problem with Flye itself. I would double check if you are allocating resources right with PBS (threads, memory, etc.). Maybe it makes sense to ask for a bit more RAM/threads, then Flye will be actually using to make sure there is extra room. Could it also be running time limits?

**Comment by hungweichen0327** [comment]
Dear Mikhail Kolmogorov,
The qustion you asked before "Do you have the terminal output for this crash as well?"
Sorry, the terminal output for the first try is covered by the output of the second try.

And the following information is the resource right with PBS

The setting in the job.q file as below:
```
#!/bin/bash
#PBS -q large
#PBS -l nodes=1:ppn=20
#PBS -o job_Crystal_flye_10kb.out -j oe

cd $PBS_O_WORKDIR

source /home/hpc/crlee/miniconda/etc/profile.d/conda.sh
conda activate nanopore

flye --nano-raw Crystal_all_porechop.fastq --out-dir Crystal_flye_10kb --genome-size 580m --threads 20 --debug --min-overlap 10000 --resume 
conda deactivate
```

The hardware of server computer: 
large queue:
   Intel E7-8870 2.40GHz
   -80 CPU cores and 2TB memory

When I typed ``pbsstat`` on terminal, it showed:
```
Report node group for large
  Total nodes: 2
  Used nodes: 1 (50.00%)
  Free nodes (with at least 1 idle CPU cores): 2 (100.00%)
  Idle nodes (all CPU cores are idle): 1 (50.00%)
  Offline nodes: 0 ( 0.00%)
  Total CPU cores: 160 
  Used CPU cores: 20 (12.50%) 
  Free CPU cores: 140 (87.50%) 
```

When I typed ``qstat -Qf``, it showed:
```
Queue: large
    queue_type = Execution
    Priority = 20
    total_jobs = 1
    state_count = Transit:0 Queued:0 Held:0 Waiting:0 Running:1 Exiting:0 Comp
	lete:0 
    acl_hosts = smp02,smp01
    resources_max.nodes = 1
    resources_max.pvmem = 25gb
    resources_max.vmem = 2048gb
    resources_default.nodes = 1
    resources_default.walltime = 720:00:00
    mtime = 1559120066
    resources_assigned.mem = 0b
    resources_assigned.nodect = 1
    resources_assigned.vmem = 0b
    max_user_run = 100
    enabled = True
    started = True
```

Thank you for the patience.

**Comment by mikolmogorov** [comment]
Hard to tell what is going on, because all cluster environments are usually configured very differently. I would suggest to try to resume run with an increased number of requested threads (maybe 25 in PBS, but use -t 20 in Flye) and specify maximum RAM (say ~500Gb should be sufficient).

**Comment by hungweichen0327** [comment]
Thank you. I resume the process and set the maximum RAM to 500 Gb. The assembly finished.

**Comment by shubhamj1510112** [comment]
Dear Mikhail Kolmogorov,

Many thanks for making such a needed tool for long read assembly.

I have a genome of 16 Gb which is known to contain ~80% repeats and I have ~8X nanopore data.

Can you please suggest if it is possible to generate an assembly using this data using Flye and if there are any specific options to use.

Currently, I am running with g=16g, --asm-coverage=5, and --meta options. Please provide your valuable opinion on this.

Thanks a lot,

Regards,
Shubham

**Comment by mikolmogorov** [comment]
Hi Shubham,

Based on your information, I don't have any extra suggestions beyond what is mentioned in the FAQ. 8x ONT data most likely will be too shallow for a decent assembly, unfortunately (especially, if the genome is diploid).

**Comment by shubhamj1510112** [comment]
Thanks a lot for the reply. 

I will check if I can get more data.
