### ISSUE TITLE
Max Threads 128

### ISSUE THREAD

**Issue by matthewstuartedwards** [fenderglass/ABruijn#139]
Just wondering if there's any reason why the maximum number of threads is 128? I have a machine with 176 cores that I would like to make the most use of.  Just wondering if there's any reason for the max threads number before I go and change the line that checks the parameter.

check_int_range(v, 1, 128)

**Comment by mikolmogorov** [comment]
Hi,

No, this constant was arbitrary - feel free to increase it in the main.py. Note that we have not tested Flye with these many threads yet.

**Comment by matthewstuartedwards** [comment]
It definitely works to change that limit, although I ran out of memory in the assembly stage using 170 threads so I couldn't evaluate the output.  I'll leave this here an close the issue until this many threads can be tested properly.

**Comment by mikolmogorov** [comment]
Sure, each new thread consumes a bit of memory, so a lot of threads can consume significant amount of RAM, depending on the dataset. I'd try to start with 30-50 and see if it works better. Also feel free to post the details about your run - I may have other suggestions how to reduce RAM consumption.

**Comment by matthewstuartedwards** [comment]
Sure, what kind of details would you be interested in? Seems like the assembly stage is the high memory use stage.  Any improvements there could be a great improvement on these large compute boxes.

I'm running this on an IBM Power9 computer, 44 core - 4 threads per core. 512GB RAM.
