### ISSUE TITLE
Missing date in log

### ISSUE THREAD

**Issue by hliang** [fenderglass/ABruijn#14]
Hi developer,

Date is not shown in the log. In [logging.Formatter()](https://github.com/fenderglass/ABruijn/blob/333381f344e53f2bd8300d55b9a0d06ca81d08a0/abruijn/main.py#L211-L214]), `datefmt` is set to `"%H:%M:%S"`, so only hour:min:sec is shown:
```
[11:04:10] INFO: Running ABruijn
[11:04:10] INFO: Assembling reads
[11:04:17] INFO: Counting kmers (1/2):
...
```
It would be great to include the date (like `"%Y-%m-%d %H:%M:%S"`), especially for benchmarking long runs.
```
[2017-05-26 11:04:10] INFO: Running ABruijn
[2017-05-26 11:04:10] INFO: Assembling reads
[2017-05-26 11:04:17] INFO: Counting kmers (1/2):
...
```

**Comment by hliang** [comment]
oh, just noticed there is another logger written in c++ -- [`ABruijn/include/logger.h`](https://github.com/fenderglass/ABruijn/blob/333381f344e53f2bd8300d55b9a0d06ca81d08a0/include/logger.h#L91).

**Comment by fenderglass** [comment]
Just incorporated this into the mater version - thanks for the suggestion!
