### ISSUE TITLE
flye-assemble error

### ISSUE THREAD

**Issue by Giacomoggioli** [fenderglass/ABruijn#140]
Hi, 

I have first installed Flye in an anaconda2 environment with python 2.7 and then tried to run Flye on Pacbio raw data with this command:
flye --pacbio-raw path1/Oasisia_pb_raw.fastq.gz --genome-size 1g --out-dir path2/flye/

And I got this error:
root: ERROR: Command '['flye-assemble', '--reads', 'path1/Oasisia_pb_raw.fastq.gz', '--out-asm', 'path2/flye/00-assembly/draft_assembly.fasta', '--genome-size', '1000000000', '--config', '/data/home/btx604/.conda/envs/Flye/lib/python2.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/data/scratch/btx604/Oasisia/flye/flye.log', '--threads', '1', '--min-ovlp', '5000', '--kmer', '17']' returned non-zero exit status -7

[flye_v1.log](https://github.com/fenderglass/Flye/files/3516786/flye_v1.log)

What should I do to fix this?

Thank you very much!

**Comment by mikolmogorov** [comment]
Hi,

This looks a bit strange - it crashed during reading the read sequences. One possibility is that there was some kind of parsing error. Could you try to validate your reads file somehow (for example, with https://bioinf.shenwei.me/seqkit/)?

Also, 250Gb of RAM will likely be insufficient for the assembly in its current configuration, but if you add `--asm-coverage 30` option - it should fit. Try this one as well.

Best,
Mikhail

**Comment by Giacomoggioli** [comment]
Hi,

I have set 480 Gb of memory and now it seems to be working. 

Thank you for your help!

**Comment by mikolmogorov** [comment]
Glad that it worked - feel free to reopen if you run into any other problems.
