### ISSUE TITLE
Parameters for low-coverage assembly

### ISSUE THREAD

**Issue by adigenova** [fenderglass/ABruijn#141]
Hi,
I'm trying to determine the peak coverage of flye on a human genome. I'm using ONT data (flipflop) at the following coverage:

10X, 15X, 20X, 25X, 30X, 35X, 40X, 45X, 50X

What parameters should I tune to maximize the performance of flye?.

Thank in advance.
Best
Alex

**Comment by mikolmogorov** [comment]
Hi Alex, 

In general, no parameter tuning is needed beyond a few tips that are mentioned in the FAQ: https://github.com/fenderglass/Flye/blob/flye/docs/FAQ.md

Best,
Mikhail

**Comment by adigenova** [comment]
Thanks Mikhail.
Best

Alex
