### ISSUE TITLE
Memory issue minimap2

### ISSUE THREAD

**Issue by clsaetre** [fenderglass/ABruijn#142]
Hi!

I'm trying (for the first time) to assemble the genome of the Eurasian reed warbler with Flye, but it seems like the system always runs out of memory. I'm running it on a HPC cluster that runs on CentOS 6, and the nodes should have 1 TiB. 

The end of the flye.log file always looks like this: 

[2019-08-21 11:12:13] DEBUG: Writing Dot
[2019-08-21 11:12:22] DEBUG: Writing FASTA
[2019-08-21 11:12:53] DEBUG: Writing Gfa
[2019-08-21 11:13:04] DEBUG: Peak RAM usage: 72 Gb
-----------End assembly log------------
[2019-08-21 11:13:15] root: INFO: >>>STAGE: polishing
[2019-08-21 11:13:15] root: INFO: Polishing genome (1/1)
[2019-08-21 11:13:15] root: INFO: Running minimap2
[2019-08-21 12:14:17] root: INFO: Separating alignment into bubbles
[2019-08-21 13:58:51] root: ERROR: Looks like the system ran out of memory

I'll attach the entire log file for the latest run:
[flye.log](https://github.com/fenderglass/Flye/files/3533540/flye.log)

I tried to reduce the memory consumption by adding --asm-coverage, first 30, then 25 and then 20. For the previous runs I ran it with -t 64, but for this latest run I changed it to -t 48. I'm not sure if that was such a good idea, but either way, it's always the same error message. 

Do you know what the problem might be? I would be very grateful for any assistance!

Best regards,
Camilla

**Comment by mikolmogorov** [comment]
Hi Camilla,

I suggest to update to the latest release version (2.5) and try again - it will likely resolve the issue, since there were multiple improvements wrt to Python code memory consumption. With the new version, you probably don't need `--asm-coverage` as well.

Let me know if this works,
Mikhail

**Comment by clsaetre** [comment]
Hi,

Yes, that seems to have done the trick! Thank you!

All the best,
Camilla
