### ISSUE TITLE
How optimise memory and cpu resources?

### ISSUE THREAD

**Issue by deoliveira86** [fenderglass/ABruijn#143]
Dear all,

I'm running flye on a high memory node at the cluster of my University and some steps, for example the creation of the extended and merged minimap files at the Consensus step, are not demanding requiring almost no memory and cpu resources.  I've read that you can split the flye job into individual runs:

> Re-starting from a particular assembly stage
> 
> Use --resume to resume a previous run of the assembler that may have terminated prematurely (using the same output directory). The assembly will continue from the last previously completed step.
> 
> You might also resume from a particular stage with --resume-from stage_name, where stage_name is a choice of assembly, consensus, repeat, trestle, polishing. For example, you might supply different sets of reads for different stages.

However, my question is: if I kill flye during the sorting, merging and manipulation of big files, such as the .sam files, in order to save computation resources, and resume the run in another node with less computation resources specified, will that be a problem? Flye will repeat the process again, because it was incomplete? Or it will resume from the exact breaking point?

I really appreciate your help, and would be great to know the computation resources required in the steps involved in the flye algorithm.

Best regards,
André

**Comment by mikolmogorov** [comment]
Hi André,

Flye will only resume from fully completed steps (e.g. assembly, consensus, repeat, etc). Manipulation with .sam files are a part of larger steps, so they can not be run separately, unfortunately. Do they take significant time, comparing to the other parts of the pipeline?

**Comment by deoliveira86** [comment]
Hello Mikhail,

Thanks for answering me. Concerning your question:

> Do they take significant time, comparing to the other parts of the pipeline?

Yes, they do. That was the reason of my question initially. It took ~8 hours to sort and merge the .sam files produced at the end of the consensus step (please, see below). The minimap2 ran from 21:28:04 until ~02:00 am, and then the manipulation of huge files continued until 10:28:07. As I was using a high memory node at my University cluster set up to work with 20 cores some waste of computation power happened during this single thread procedure.

> [2019-08-24 21:27:19] root: INFO: >>>STAGE: consensus
> [2019-08-24 21:28:04] root: INFO: Running Minimap2
> [2019-08-25 10:28:07] root: INFO: Computing consensus
> [2019-08-25 14:31:07] root: INFO: Alignment error rate: 0.190289334521

The same happened with the polishing stage (see below, but realise that this job was performed using only 10 cores). Some hours were required to manipulate again the .sam file in a single thread.

> [2019-08-27 08:46:25] root: INFO: >>>STAGE: polishing
> [2019-08-27 08:46:25] root: INFO: Polishing genome (1/1)
> [2019-08-27 08:46:37] root: INFO: Running minimap2
> [2019-08-27 18:56:45] root: INFO: Separating alignment into bubbles

The .log files are useful because they discriminate the RAM usage in each step, so distinct jobs can be submitted with the adequate memory resources required. The manipulation of the big .sam is still the bottleneck (at least at my particular case). Thanks again!

bs: I have one question concerning the disjointigs step of flye (hearing your podcast helped me to sane some doubts, but still there is something that I do not get completely). Should I open another Issue or just ask here?

Cheers,
André

**Comment by mikolmogorov** [comment]
I see. In our tests, those steps are typically much faster than the other tasks - I think it is likely that your node has slower IO. Make sure you using a local file system for Flye output (e.g. not net-mounted). We currently do not have resources for optimizing IO performance, unfortunately (there are other priorities).

> I have one question concerning the disjointigs step of flye

Sure, feel free to open another issue with question.

**Comment by deoliveira86** [comment]
Thanks for the quick answer and for the advice.

> We currently do not have resources for optimizing IO performance, unfortunately (there are other priorities). 

No problem. I just wanted to know how I could improve the performance of my jobs in the cluster I am currently using. But, it seems to be more a localised hardware problem, than the performance of the software per se.

Cheers and see you in another issue,
André
