### ISSUE TITLE
Does flye break raw reads?

### ISSUE THREAD

**Issue by bbalog87** [fenderglass/ABruijn#145]
Hi Mikhail,

I have removed all raw reads shorter than 1kb. However the final polished flye assembly has contig shorter than 0.5kb. To my understanding of Flye algorithm, this shouldn't happen. Are some reads splitted in the consensus stage?

Best,
Julien

**Comment by mikolmogorov** [comment]
Hi Julien,

Contigs are generated from repeat graph edges and could be as short as 0.5kb. Usually, unique contigs will be longer because they are extended into adjacent repeats using the read information. However, repetitive contigs (or perhaps plasmids / phages) can remain short.

Best,
Mikhail
