### ISSUE TITLE
Can Flye subassemble ONT assembly and ONT corrected reads?

### ISSUE THREAD

**Issue by JingXia730** [fenderglass/ABruijn#146]
Hi!

It's nice that Flye can assemble the contigs with `--subassemblies`. Is it possible to input ONT assembly and ONT corrected reads (both generated by canu) for subassembly? Will it be better than inputing the ONT assembly data only?

Thanks!
Jing

**Comment by mikolmogorov** [comment]
Hi Jing,

No, `--subassemblies` mode designed for polished assemblies with error rate < 1%, which probably is not the case for corrected ONT reads. On the other hand, you can assemble reads with Flye, and then merge Flye and Canu assemblies instead.

Best,
Mikhail

**Comment by mradz19** [comment]
@fenderglass Hi, how do you go about merging assemblies from multiple programs?

**Comment by mikolmogorov** [comment]
@mradz19 it should work as long as the base quality of the assmeblies is good.
