### ISSUE TITLE
scaffolds.fasta

### ISSUE THREAD

**Issue by intikhab** [fenderglass/ABruijn#149]
Hi Flye.Developers,

I recently used Flye on one of our Plant Genome PacBio data, results show the following stats:
[2019-09-04 23:52:33] root: INFO: Assembly statistics:

        Total length:   1480800694
        Fragments:      28096
        Fragments N50:  350536
        Largest frg:    2447574
        Scaffolds:      12
        Mean coverage:  21

I do not see scaffolds.fasta file, althugh there is one assembly.fasta and another scaffold_links.txt is present in contigger folder. Assembly statistics shows scaffolds: 12, does it mean ~28096 fragments (contigs) are represented in 12 scaffolds? If not, how do we use scaffolds_links.txt 

assembly.fasta shows 28096 sequences, these are fragments (contigs) only, does Flye not provide scaffolds.fasta anymore?

Thanks for your help,

IA

**Comment by mikolmogorov** [comment]
Hi,

Flye can join some contigs into scaffolds. In your case, it created 12 of them, and all other `28096 - 12` contigs remained unchanged. `assembly.fasta` is the final Flye output, it includes generated scaffolds. `scaffolds.fasta` was a symlink to `assembly.fasta` before the version 2.5. Please refer to USAGE.md for details.

Mikhail
