### ISSUE TITLE
flye meta for cDNA assembly?

### ISSUE THREAD

**Issue by michieitel** [fenderglass/ABruijn#157]
Hi!

I am wondering if I can use flye in metaassembly mode to assemble nanopore cDNA reads with transcripts showing different read coverage?

Thanks
Michael

**Comment by mikolmogorov** [comment]
Hi Michael,

We have not tested Flye on cDNA. In theory, it could work. Alternative splicing could be a challenge though.

Mikhail

**Comment by michieitel** [comment]
Dear Mikhail,

Thanks for your reply. I will give it a try and will report back.

Best
Michael

**Comment by mikolmogorov** [comment]
Closing the issue for now, feel free to reopen if you have updates/questions.

**Comment by michieitel** [comment]
Sorry for not getting back. In fact metafly did not work with my cDNA data....

**Comment by mikolmogorov** [comment]
Ok thanks for letting me know. We are not planning adding cDNA support currently.

**Comment by lpryszcz** [comment]
Hi @fenderglass , has anything been done regarding cDNA support?
Flye works like a charm for DNA with our ONT data and I'd love to try it for cDNA as well!

**Comment by mikolmogorov** [comment]
@lpryszcz not at the moment. I wonder what are the goals for cDNA assembly? If you already have full transcripts - why do you need to assemble?
