### ISSUE TITLE
code for additional polishing iteration

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#158]
Dear community,

I remember the default value of iteration times is 1. I also saw the previous issue discuss about how to add additional polishing iteration. https://github.com/fenderglass/Flye/issues/6#issuecomment-258506945

I would like to check whether the code I wrote is correct if I want to have 2 more polishing iteration (total iteration 3 times). So far I already have assembly file generated by Flye named `` Crystal_flye_10kb.fasta``. The code is below for polishing:
```
flye --polish-target Crystal_flye_10kb.fasta --nano-raw Crystal_all_porechop.fastq --iterations 2 --out-dir Crystal_flye_10kb_2iter --threads 20
```

Besides, how do I know the alignment error rate or how much improvement after polishing. e.g. alignment error rate. Is there any files generated by Flye showed this result? Or can it be measured by other software? 

Thank you!

**Comment by mikolmogorov** [comment]
Yes, the command line if correct. Flye outputs mean alignment error into the log file (and terminal) - you can use it as a reference. However, since the read error rate is much higher than the consensus error, alignment error rate might not reveal the improvements from multiple iterations.

Mikhail

**Comment by hungweichen0327** [comment]
Is that possible to know the consensus error?

**Comment by mikolmogorov** [comment]
You would need a complementary data source, such as Illumina reads or a closely related reference.

**Comment by hungweichen0327** [comment]
I got it. Thank you!
