### ISSUE TITLE
How to set maximum error rate?

### ISSUE THREAD

**Issue by YaoZhou89** [fenderglass/ABruijn#163]
Hi, I noticed that you mentioned the maximum error rate was set to 1% for HG0002. But I didn't see any parameter for setting this value. Should we set in source script manually? Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Currently, you need to edit the config file `flye/config/bin_cfg/asm_corrected_reads.cfg`. If you are using system installation, edit the config before installing. Change the parameters at lines 19-21 from 0.03 to 0.01.

I know it is a bit inconvenient now, we are planning to create a separate option for PacBio CCS in the future.

Hope this helps,
Mikhail

**Comment by YaoZhou89** [comment]
Hi,

 

Thanks so much for your response! I have tried the new compiled Flye for assembly successfully on my own data, and the result of N50 was much better. Looking forward to your new version!

 

Best regards,

Yao
