### ISSUE TITLE
Should we remove organelle reads prior to assembly?

### ISSUE THREAD

**Issue by davidecarlson** [fenderglass/ABruijn#168]
Hi Mikhail,
Thanks for making this tool available.  I'm working on a medium size plant genome (~ 1.2 GB).  It's highly inbred, but also full of repeats.  I'm wondering if you recommend that we filter our reads to remove organelle sequences?  I've got about 90x coverage, and it appears that about 20% of the reads are coming from either the plastid or the mitochondrial genomes.  Will including these reads slow down (or confuse) the assembly process?

Thanks!
Dave

**Comment by mikolmogorov** [comment]
Hi Dave,

I don't think this should be a problem, unless those organelle sequences share some significant content with the nuclear sequence. And in the case they do, it could be complicated to filter them out anyway.

Let me know if you run into any issues,
Mikhail

**Comment by davidecarlson** [comment]
Thanks, Mikhail.

As it turns out, I am indeed having some issues with my assembly.  I've run Flye on both the full set of Pacbio subreads, and with the putative organelle reads filtered out.  

In both cases, I got a total assembly size of 400-500 Mb, with a contig N50 of around 80-90k.  As I mentioned before, the actual haploid genome size is around 1.2 Gb, so I'm hoping I can get a better assembly.  

A few things to note:
 - We have > 90x coverage, but the PacBio data are somewhat old.  They were sequenced between late 2014 and late 2016, using a mixture of P6-C2 and P6-C4 chemistries.  Most of the reads are P6-C4, and more than half of the data come from a Sequel 1.
- The N50 of the raw subreads is ~11,000
- Based on earlier iterations of the genome assembly, I suspect that around 70% of it consists of repeats, with perhaps as much as 50% of the genome being made of long terminal repeat retrotransposons.

Is it possible that my data are too old/short/noisy for Flye to successfully resolve the large number of repeats?  Would this explain why so little of the genome was assembled?

If so, is there any advice you can offer for getting better results with Flye? Would it be useful to try the Flye assembly with reads that have been error corrected first?

Thanks for your help!
Dave

**Comment by mikolmogorov** [comment]
I see. 70% repeats is extremely challenging - so it is not very surprising that assembly N50 is that low. And yes, because many repeat remained unresolved, the assembly size turns out much smaller.

What is the length of the LTR? It is possible that setting minimum overlap threshold can help to "skip" this repeat during assembly, which should improve the contiguity.

**Comment by davidecarlson** [comment]
LTR lengths are quite variable, but the average is probably around 7k, though unfortunately there are likely plenty that exceed the lengths of the PacBio reads.  

I will try to manually specifying the minimum overlap threshold.  But just to clarify, would I be increasing it or decreasing it?  I believe the automatically picked thresholds were 5k (full dataset) and 4k (organelle filtered dataset) when I ran Flye previously.  Should I drop the threshold lower than these values?

Thanks again for your advice!
Dave

**Comment by mikolmogorov** [comment]
Thanks - try to increase it instead. I would try 10k and see how it goes.

**Comment by davidecarlson** [comment]
Thanks, Mikhail.  I will try that and report back.
Dave

**Comment by davidecarlson** [comment]
Hi Mikhail,
Just wanted to follow up and report back on the latest assembly iteration.  I ran Flye again using 10k as the minimum overlap and did see some improvement.  The total assembly size was now about 808 Mb and the N50 was somewhat higher at 104K.  

If possible, I'd love to try to improve this further.  Are there any other parameter tweaks you can recommend (I'm currently running another assembly with 9k as the minimum overlap to see if there might be a "sweet spot" between 10k and the default setting).

Thanks again,
Dave

**Comment by mikolmogorov** [comment]
Hi Dave,

Thanks for following up. Seems like increasing minimum overlap at least helped to increase the assembly size. The contiguity improvement might be also more apparent if you use NG50 instead of N50, since the assembly sizes are so different.

There are not too many parameters to tweak, other than those that are exposed. If you could post / send me the log file of the run, I might have some suggestions based on it.

Best,
Mikhail

**Comment by davidecarlson** [comment]
You're right, the increase in overlap definitely improved things.  I'm honestly less concerned with the contiguity and more interested in just trying to assemble as much of the genome as possible, I have additional HI-C data (and mate pair data) that I can use to improve the contiguity downstream.  

I've attached the (gzip'd) log file.  It's fairly large, so if it ends up being too large to attach, please let me know.
Thanks again for all of your assistance.
Best,
Dave
[flye.log.gz](https://github.com/fenderglass/Flye/files/3817502/flye.log.gz)

**Comment by mikolmogorov** [comment]
Hi Dave,

Yes, definitely looks like the genome is highly repetitive - those are very difficult to assemble. You might want to try to decrease the sensitivity parameter for repeat graph construction, it potantially might help to collapse less sequence (and increase the assembly size).

Edit the config file `flye/config/bin_cfg/asm_raw_reads`, and change the parameter `repeat_graph_ovlp_divergence` from 0.15 to 0.10. Then restart the assembly using `--resume-from repeat`. Note that if you are using system installation, you will need to edit the file before installing.

Best,
Mikhail

**Comment by davidecarlson** [comment]
Thanks, Mikhail

I changed the repeat_graph_ovlp_divergence parameter as you suggested and recompiled.  I'm running from the repeat stage again.  I'll let you know what the output looks like.
Appreciate the help!
Dave

**Comment by davidecarlson** [comment]
Hi Mikhail,
Looks like changing the repeat_graph_ovlp_divergence from 0.15 to 0.10 had essentially no effect on the final assembly.  I'm going to go ahead and close the ticket.  Thanks for all your help.
Best,
Dave

**Comment by mikolmogorov** [comment]
Ok, thanks for the update.
