### ISSUE TITLE
effective CPU upper limit and effect on memory usage

### ISSUE THREAD

**Issue by lautimothy** [fenderglass/ABruijn#171]
Hello,

Just wondering if there would be proportional speed improvement for number of CPU>40 and whether using more CPU would increase memory usage?

Thanks,
Tim

**Comment by mikolmogorov** [comment]
Hi Tim,

Some stages of the pipeline can definitely effectively utilize more then 40 CPUs. This might depend on the machine and its state too (RAM / IO bottlenecks / cache misses etc). Each extra thread will use some extra RAM, but should not be very significant.

Best,
Mikhail

**Comment by lautimothy** [comment]
Thanks for the prompt reply!
