### ISSUE TITLE
Circular genome with Abruijn

### ISSUE THREAD

**Issue by lalalagartija** [fenderglass/ABruijn#173]
Hi, 

I assembled my PacBio reads with Abruijn and I got 2 final contigs : 
>contig1_circular:0_len:469421_cov:215
>contig3_circular:0_len:7603_cov:10

I am indeed looking for circular contigs but I cannot find overlapping edges. Does it mean that I can just loop the contigs and start somewhere else ? Or does it means that it is just assumed to be circular ? 

Thank you very much !

**Comment by mikolmogorov** [comment]
ABruijn is no longer supported, please use the latest Flye release. Flye does not have overlaps in circular contigs.
