### ISSUE TITLE
subassemblies : how reliable ?

### ISSUE THREAD

**Issue by lalalagartija** [fenderglass/ABruijn#174]
Hi, 

I have a circular genome that I aligned with several tools (flye, abruijn, HGAP, Canu worked well, Unicycler and Hinge did not work well with my data) and none of them gave me a circular output. I manage to get a circular genome when I cut all my best assemblies on the same gene and I created a new assemblage with flye using -subassemblies. 
It seams to have worked well even though the result is slightly smaller than the inputs. Is this method reliable ? Was this option ment to be used that way ? 

Thank you very much !

**Comment by mikolmogorov** [comment]
Hi,

Yes, `subassemblies` option was created for merging multiple high-quality assemblies. A word of caution is that it was not tested as extensive as the "normal" modes.

Best,
Mikhail
