### ISSUE TITLE
Run the Flye to repeat stage

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#178]
Dear community,

I Finish the assembly and it's good.  Unfortunately, I removed all the other output folders and files except assembly.fasta, assembly_graph.gfa, assembly_graph.gv, assembly_info.txt

If I want to see the repeat graph to understand how the Flye think two contigs can be scaffolded, How do I do?
How do I change the code of Flye to run until 2-repeat stage? (I think I don't need the output of later process)

Below is my code:
```
flye --nano-raw Crystal_all_porechop.fastq --out-dir Crystal_flye_10kb --genome-size 580m --threads 20 --debug --min-overlap 10000
```

Thank you.

**Comment by mikolmogorov** [comment]
Hi,

assembly_graph.gv and assembly_graph.gfa files encode your assembly graph.

Mikhail
