### ISSUE TITLE
subassembly and short read polishing 

### ISSUE THREAD

**Issue by MChiaraC** [fenderglass/ABruijn#179]
Hi, I have sequenced both with short reads (miseq) and long reads (minion) an intracellular bacterial genome, with the idea of assembling in hybrid mode using Pilon. 
To assemble long reads I am using both Canu and Flye (with corrected reads). Flye gives me a higher BUSCO while Canu makes the genome circular so I was thinking to combine the two assemblies with the subassembly option of Flye and see what is going to happen.

My doubt is if it is better to polish with short reads the single assemblies before subassembly or if to do that after the subassembly.

I have been thinking that if I polish after the subassembly step I have a better chance to have a wider "scheleton" to further align my short reads on (both assemblies are overall shorter than what they should) but on the other side if I run Pilon before subassembly I have the chance of having the highest possible quality contigs.

Any thoughts to share?  ##Thanks a lot
Chiara

**Comment by mikolmogorov** [comment]
Hi Chiara,

Not sure which one is the best, I would try both and see what gives you a better assembly.

Best,
Mikhail

**Comment by MChiaraC** [comment]
Just in case anybody is curious, it looks slightly better when performing subassembly before short reads polishing... Still, Flye by is own (no subassembly) gives the best results 💃

**Comment by mikolmogorov** [comment]
Thanks for the feedback!
