### ISSUE TITLE
Decreasing min-overlap value

### ISSUE THREAD

**Issue by bheimbu** [fenderglass/ABruijn#181]
Hi,

I'd like to de novo assemble mitochondrial genomes using ONT long reads. I already did it with Canu and now I'd like to try Flye. 
As my Minion run wasn't working as expected (low output, many short reads), I was wondering whether your min-overlap range is hardcoded? Using 1000 as min-overlap value gives me no assembly due to the fact of many short fragments (check [flye.log](https://github.com/fenderglass/Flye/files/3787656/flye.log)).

I checked the other threads about min-overlap (#92 and #37) but maybe there is a chance, to use this data with Flye. It worked out with Canu though.

Cheers Bastian

**Comment by mikolmogorov** [comment]
Hi Bastian,

I wouldn't recommend do decrease below 1kb, as it will not combine well with the other parameters.

Mikhail
