### ISSUE TITLE
Reference contigs as additional reads

### ISSUE THREAD

**Issue by dariober** [fenderglass/ABruijn#184]
Hi- I'm doing _de novo_ assembly for a species where we have a reference genome. The reference is fairly good but with known issues (gaps etc). Also, our samples may have structural variants (hence the _de novo_ route). 

I'm wondering if and how I can make best use of the reference genome since, to a large extent, it is correct and similar to our samples. 

A simple strategy may be to feed Flye with the raw reads and with the reference contigs as additional reads. Before I try it (and go down a rabbit hole), does it make sense? 

My crude reasoning is that the reference contigs should direct the assembly towards the reference. However, if enough raw reads support a structural variant, Flye should be able to disregard the reference contigs.

I know Flye as the option `--subassemblies` but without raw reads Flye cannot decide whether the reference or the assembly is more probable, right? 

Any thought much appreciated!

**Comment by mikolmogorov** [comment]
Hi,

The problem with this approach could be that the error rate of raw reads and contigs is very different. This could result into excessive graph complexity, as many more repeats will be collapsed though high-quality contigs. How large are the datasets? You can certainly give it a try, but I am not quite sure if it will actually improve the assembly and be robust to the structural variations between reference and assembled genomes.

I would also suggest to try assemble reads first, and then use another tool for reference scaffolding (for example, https://github.com/fenderglass/Ragout). 

Feel free to reopen the issue if you have more questions in the future!

Best,
Mikhail

**Comment by jdmontenegro** [comment]
Hi all,
I am trying to solve a similar problem with a different approach and so far it seems to be succesful. I have borrowed the approach from a reference-guided denovo assembly with a few tweaks. 
First I map the reads to the reference genome with minimap2, followed by sam to sorted bam conversion. Then I analyze the bam and identify loci with an homogeneous coverage across several thousands of bases (at least 20Kbp). I extract all reads whose primary alignments falls within those coordinates and perform a denovo assembly of those loci separately. That way I make use of mapping for graph simplification. I repeat the same steps with the new assembly and reassemble selected reads in every iteration until no more new reads can be recovered. Once we have reached this plateau I select the high confidence contigs (i.e. those >= 20Kbp, 99% horizontal coverage and 1 sd from expected depth). These contigs are then used as high confidence contigs for `--subassemblies`. 
So far the assembly of a 1Gbp plant genome (haploid estimate although this is a tetraploid plant) looks very promising. All done with under 100Gb of RAM and highly colinear with the original reference genome. I have been able to identify hundreds of small translocations and inversions form this approach and I am designing primers to validate those results.
For haplotyping I have considered using these tools:
https://whatshap.readthedocs.io/en/latest/
https://github.com/benedictpaten/marginPhase
It would be very useful if you could provide feedback or suggestions to improve the approach described above.
Kind regards,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
Hi Juan,

This sounds interesting. My only concern would be that if there are regions in the target genome that are not in the reference, then these regions will not be assembled locally and will lead to gaps. Maybe it also makes sense to also re-assemble reads that were not aligned to the reference and add those contigs to `--subassemblies` run?

Mikhail

**Comment by jdmontenegro** [comment]
Thank you Mikhail,

I also thought about that caveat, hence the iterative mapping and assembly
by blocks. Essentially, I would look for new reads that had not been mapped
before and redo the locus assembly with an extended dataset of reads. Im
most cases after 3 iterations I couldnt find new reads that mapped to the
latest versión of the assembly.

However, I just realized a small error. I was under the impression that  -
- subassemblies would work in a way similar to a contig extensión and gap
closure fashion. That does not seem to be the case, so I will be using
sspace to try to scaffold HC contigs using the unmapped reads and then fill
in the gaps where possible. Dbg2olc could also work in this step, but I am
not sure the HC contigs produce by flye can be used in the same fashion as
a shirt read assembly.

Is there any way we could use flye to try to scaffold and close gaps of an
incomplete assembly without going full de novo?

Cheers,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
No, Flye does not do scaffolding.

**Comment by jdmontenegro** [comment]
Hi all,

Just a quick revisit to this issue. The iterative mapping and assembly approach actually produced quite useful results. I have worked with 30X CLR pacbio data of a 840Mb genome. The reference was 720Mb and this approach produced a rather larger assembly (~100Mb larger) to the actual expected genome size.

It took around 3 iterations for the assemblies to reach a plateau (genome size of 822Mbp, N50 of 145Kb, largest contig of 5.4Mbp, mapping efficiency of 98.6%). Interestingly, removing extremely short and extremely long reads (>10Kb and <50Kb) produced more contiguous assemblies with similar mapping efficiency stats (~98.6%).

Unmapped reads were mostly short sequences (average size of 2.5Kb) and full of simple repeats and microsatellite sequences that failed to produce any useful assembly.

Now I would like to identify haplotypes and diploidize my assembly. Do you know of any useful strategy for doing this? I am thinking about using Longshot to identify SNV and Indels form the raw data and then WhatsHap to produce haploblocks.

I was also thinking of using the assembly graph to identify structural variants that were assembled into separate contigs. Would you recommend any tools for doing this?

Kind regards,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
@jdmontenegro thanks for the update! 

As I understand you want to separate contigs into diploid and haploid, and reconstruct collapsed haplotypes? I don't think there are standard approaches for this currently. This paper might be useful: https://www.biorxiv.org/content/10.1101/810341v1.abstract

>I was also thinking of using the assembly graph to identify structural variants that were assembled into separate contigs. Would you recommend any tools for doing this?

Definitely, you should be able to see large haplotype variations on the assembly graph. In fact, there is a new option `--keep-haplotypes` in the latest github code (not in releases yet) that preserves the haplotypes rather than collasing them, which might help the analysis. I'd also suggest to give try `--meta` mode for diploid assembly, since it is more robust to changes in coverage.

Best,
Mikhail

**Comment by jdmontenegro** [comment]
Hi Mikhail,

As I mentioned before, I redid the iterative mappig-assembly of reads and compared the results of flye2.7 with and without the `--keep-haplotypes` option. 
As far as I can see, the assemblies are quite similar, I was expecting a larger assembly in the --keep-haplotypes assembly, but instead I am getting the opposite:

```
==> standard <==

        Total length:   64945335
        Fragments:      1396
        Fragments N50:  107738
        Largest frg:    1010501
        Scaffolds:      5
        Mean coverage:  27

==> --keep-haplotypes <==

        Total length:   63173655
        Fragments:      1321
        Fragments N50:  84636
        Largest frg:    602320
        Scaffolds:      0
        Mean coverage:  27
```

Most of the contiguity metrics have worsen (N50, largest frgment, total length). There is a slight improvement in the average contig length (46K vs 48K). Is it possible that `--keep-haplotypes `is writing separate contigs for unresolved homozygous regions and that is why I can see larger N50 in the standard assembly compared to the haplotype assembly?

Would you recommend using higher sequencing depth to improve both: 1) resolved homozygous regions and better consensus of the haplotypes? I realize now that by using 34X depth of the genome, I should expect ~17X per chromatid, which does sound a bit too low, even for a tool as amazing as flye.

Any further commetns or suggestions would be more than welcome.

Kind regards,

Juan D. Montenegro
