### ISSUE TITLE
params.json contents

### ISSUE THREAD

**Issue by joegage** [fenderglass/ABruijn#185]
Hi,

I had an assembly fail during polishing, and due to a completely unrelated issue my params.json file got deleted so I am unable to restart flye with the --resume option.  Are the contents of the params.json file simple enough that I can recreate it manually?

**Comment by mikolmogorov** [comment]
Hi,

You can recreate the parameters file by running Flye with the same output directory without `--resume` option, and terminate it once it passes the configuration stage (and begins assembly). You can then use `--resume-from stage_name` to restart from a desired stage.

Best,
Mikhail
