### ISSUE TITLE
The Polishing stage report errors

### ISSUE THREAD

**Issue by taotaoyuan** [fenderglass/ABruijn#186]
[2019-11-08 17:38:58] INFO: >>>STAGE: polishing
[2019-11-08 17:38:58] INFO: Polishing genome (1/2)
[2019-11-08 17:39:59] INFO: Running minimap2
[2019-11-09 09:15:28] INFO: Separating alignment into bubbles
[2019-11-09 14:05:15] INFO: Alignment error rate: 0.147799
[2019-11-09 14:05:15] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-11-10 01:37:26] INFO: Polishing genome (2/2)
[2019-11-10 01:38:25] INFO: Running minimap2
[2019-11-10 16:27:12] INFO: Separating alignment into bubbles
[2019-11-11 00:58:26] INFO: Alignment error rate: 0.124223
[2019-11-11 00:58:26] INFO: Correcting bubbles
0% 10% 20% 30% *** glibc detected *** flye-polish: invalid fastbin entry (free): 0x00007f05ac023170 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x353ae76166)[0x7f0600592166]
flye-polish(+0x7cda)[0x7f0600f7acda]
/data1/spider/ytbiosoft/miniconda3/envs/python3/bin/../lib/libstdc++.so.6(+0xc819d)[0x7f0600ea219d]
/lib64/libpthread.so.0(+0x353b2079d1)[0x7f06008b79d1]
/lib64/libc.so.6(clone+0x6d)[0x7f0600604b6d]
======= Memory map: ========
7f0568000000-7f056bf37000 rw-p 00000000 00:00 0 
7f056bf37000-7f056c000000 ---p 00000000 00:00 0 
7f0570000000-7f0573fbc000 rw-p 00000000 00:00 0 
7f0573fbc000-7f0574000000 ---p 00000000 00:00 0 
7f0588000000-7f058bf5b000 rw-p 00000000 00:00 0 
7f058bf5b000-7f058c000000 ---p 00000000 00:00 0 
7f058c000000-7f0590000000 rw-p 00000000 00:00 0 
7f0590000000-7f0594000000 rw-p 00000000 00:00 0 
7f0594000000-7f0598000000 rw-p 00000000 00:00 0 
7f0598000000-7f059c000000 rw-p 00000000 00:00 0 
7f059c000000-7f05a0000000 rw-p 00000000 00:00 0 
7f05a0000000-7f05a4000000 rw-p 00000000 00:00 0 
7f05a4000000-7f05a8000000 rw-p 00000000 00:00 0 
7f05a8000000-7f05ac000000 rw-p 00000000 00:00 0 
7f05ac000000-7f05b0000000 rw-p 00000000 00:00 0 
7f05b0000000-7f05b4000000 rw-p 00000000 00:00 0 
7f05b4000000-7f05b8000000 rw-p 00000000 00:00 0 
7f05b8000000-7f05bc000000 rw-p 00000000 00:00 0 
7f05bc000000-7f05c0000000 rw-p 00000000 00:00 0 
7f05c0000000-7f05c4000000 rw-p 00000000 00:00 0 
7f05c4000000-7f05c8000000 rw-p 00000000 00:00 0 
7f05c8000000-7f05cc000000 rw-p 00000000 00:00 0 
7f05cc000000-7f05d0000000 rw-p 00000000 00:00 0 
7f05d03fa000-7f05d03fb000 ---p 00000000 00:00 0 
7f05d03fb000-7f05d0dfb000 rw-p 00000000 00:00 0 
7f05d0dfb000-7f05d0dfc000 ---p 00000000 00:00 0 
7f05d0dfc000-7f05d17fc000 rw-p 00000000 00:00 0 
7f05d17fc000-7f05d17fd000 ---p 00000000 00:00 0 
7f05d17fd000-7f05d21fd000 rw-p 00000000 00:00 0 
7f05d21fd000-7f05d21fe000 ---p 00000000 00:00 0 
7f05d21fe000-7f05d2bfe000 rw-p 00000000 00:00 0 
7f05d2bfe000-7f05d2bff000 ---p 00000000 00:00 0 
7f05d2bff000-7f05d35ff000 rw-p 00000000 00:00 0 
7f05d35ff000-7f05d3600000 ---p 00000000 00:00 0 
7f05d3600000-7f05d4000000 rw-p 00000000 00:00 0 
7f05d4000000-7f05d8000000 rw-p 00000000 00:00 0 
7f05d83fa000-7f05d83fb000 ---p 00000000 00:00 0 
7f05d83fb000-7f05d8dfb000 rw-p 00000000 00:00 0 
7f05d8dfb000-7f05d8dfc000 ---p 00000000 00:00 0 
7f05d8dfc000-7f05d97fc000 rw-p 00000000 00:00 0 
7f05d97fc000-7f05d97fd000 ---p 00000000 00:00 0 
7f05d97fd000-7f05da1fd000 rw-p 00000000 00:00 0 
7f05da1fd000-7f05da1fe000 ---p 00000000 00:00 0 
7f05da1fe000-7f05dabfe000 rw-p 00000000 00:00 0 
7f05dabfe000-7f05dabff000 ---p 00000000 00:00 0 
7f05dabff000-7f05db5ff000 rw-p 00000000 00:00 0 
7f05db5ff000-7f05db600000 ---p 00000000 00:00 0 
7f05db600000-7f05dc000000 rw-p 00000000 00:00 0 
7f05dc000000-7f05e0000000 rw-p 00000000 00:00 0 
7f05e0000000-7f05e4000000 rw-p 00000000 00:00 0 
7f05e4000000-7f05e8000000 rw-p 00000000 00:00 0 
7f05e8000000-7f05ec000000 rw-p 00000000 00:00 0 
7f05ec000000-7f05f0000000 rw-p 00000000 00:00 0 
7f05f03fa000-7f05f03fb000 ---p 00000000 00:00 0 
7f05f03fb000-7f05f0dfb000 rw-p 00000000 00:00 0 
7f05f0dfb000-7f05f0dfc000 ---p 00000000 00:00 0 
7f05f0dfc000-7f05f17fc000 rw-p 00000000 00:00 0 
7f05f17fc000-7f05f17fd000 ---p 00000000 00:00 0 
7f05f17fd000-7f05f21fd000 rw-p 00000000 00:00 0 
7f05f21fd000-7f05f21fe000 ---p 00000000 00:00 0 
7f05f21fe000-7f05f2bfe000 rw-p 00000000 00:00 0 
7f05f2bfe000-7f05f2bff000 ---p 00000000 00:00 0 
7f05f2bff000-7f05f35ff000 rw-p 00000000 00:00 0 
7f05f35ff000-7f05f3600000 ---p 00000000 00:00 0 
7f05f3600000-7f05f4000000 rw-p 00000000 00:00 0 
7f05f4000000-7f05f8000000 rw-p 00000000 00:00 0 
7f05f8896000-7f05f8897000 ---p 00000000 00:00 0 
7f05f8897000-7f05f9297000 rw-p 00000000 00:00 0 
7f05f9297000-7f05f9298000 ---p 00000000 00:00 0 
7f05f9298000-7f05f9c98000 rw-p 00000000 00:00 0 
7f05f9c98000-7f05f9c99000 ---p 00000000 00:00 0 
7f05f9c99000-7f05fa699000 rw-p 00000000 00:00 0 
7f05fa699000-7f05fa69a000 ---p 00000000 00:00 0 
7f05fa69a000-7f05fb09a000 rw-p 00000000 00:00 0 
7f05fb09a000-7f05fb09b000 ---p 00000000 00:00 0 
7f05fb09b000-7f05fba9b000 rw-p 00000000 00:00 0 
7f05fba9b000-7f05fba9c000 ---p 00000000 00:00 0 
7f05fba9c000-7f060051c000 rw-p 00000000 00:00 0 
7f060051c000-7f06006a7000 r-xp 00000000 fd:00 164914                     /lib64/libc-2.12.so
7f06006a7000-7f06008a6000 ---p 0018b000 fd:00 164914                     /lib64/libc-2.12.so
7f06008a6000-7f06008aa000 r--p 0018a000 fd:00 164914                     /lib64/libc-2.12.so
7f06008aa000-7f06008ab000 rw-p 0018e000 fd:00 164914                     /lib64/libc-2.12.so
7f06008ab000-7f06008b0000 rw-p 00000000 00:00 0 
7f06008b0000-7f06008c7000 r-xp 00000000 fd:00 164917                     /lib64/libpthread-2.12.so
7f06008c7000-7f0600ac7000 ---p 00017000 fd:00 164917                     /lib64/libpthread-2.12.so
7f0600ac7000-7f0600ac8000 r--p 00017000 fd:00 164917                     /lib64/libpthread-2.12.so
7f0600ac8000-7f0600ac9000 rw-p 00018000 fd:00 164917                     /lib64/libpthread-2.12.so
7f0600ac9000-7f0600acd000 rw-p 00000000 00:00 0 
7f0600acd000-7f0600b50000 r-xp 00000000 fd:00 164915                     /lib64/libm-2.12.so
7f0600b50000-7f0600d4f000 ---p 00083000 fd:00 164915                     /lib64/libm-2.12.so
7f0600d4f000-7f0600d50000 r--p 00082000 fd:00 164915                     /lib64/libm-2.12.so
7f0600d50000-7f0600d51000 rw-p 00083000 fd:00 164915                     /lib64/libm-2.12.so
7f0600d51000-7f0600d71000 r-xp 00000000 fd:00 164913                     /lib64/ld-2.12.so
7f0600d91000-7f0600d96000 rw-p 00000000 00:00 0 
7f0600d96000-7f0600d99000 r--p 00000000 fd:04 2406544                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libgcc_s.so.1
7f0600d99000-7f0600da5000 r-xp 00003000 fd:04 2406544                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libgcc_s.so.1
7f0600da5000-7f0600da8000 r--p 0000f000 fd:04 2406544                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libgcc_s.so.1
7f0600da8000-7f0600da9000 r--p 00011000 fd:04 2406544                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libgcc_s.so.1
7f0600da9000-7f0600daa000 rw-p 00012000 fd:04 2406544                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libgcc_s.so.1
7f0600dd9000-7f0600dda000 rw-p 00000000 00:00 0 
7f0600dda000-7f0600e7c000 r--p 00000000 fd:04 2420239                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libstdc++.so.6.0.26
7f0600e7c000-7f0600efb000 r-xp 000a2000 fd:04 2420239                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libstdc++.so.6.0.26
7f0600efb000-7f0600f3c000 r--p 00121000 fd:04 2420239                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libstdc++.so.6.0.26
7f0600f3c000-7f0600f47000 r--p 00161000 fd:04 2420239                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libstdc++.so.6.0.26
7f0600f47000-7f0600f4b000 rw-p 0016c000 fd:04 2420239                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libstdc++.so.6.0.26
7f0600f4b000-7f0600f4f000 rw-p 00000000 00:00 0 
7f0600f4f000-7f0600f52000 r--p 00000000 fd:04 2408405                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libz.so.1.2.11
7f0600f52000-7f0600f66000 r-xp 00003000 fd:04 2408405                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libz.so.1.2.11
7f0600f66000-7f0600f6d000 r--p 00017000 fd:04 2408405                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libz.so.1.2.11
7f0600f6d000-7f0600f6e000 r--p 0001d000 fd:04 2408405                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libz.so.1.2.11
7f0600f6e000-7f0600f6f000 rw-p 0001e000 fd:04 2408405                    /data1/spider/ytbiosoft/miniconda3/envs/python3/lib/libz.so.1.2.11
7f0600f6f000-7f0600f70000 rw-p 00000000 00:00 0 
7f0600f70000-7f0600f71000 r--p 0001f000 fd:00 164913                     /lib64/ld-2.12.so
7f0600f71000-7f0600f72000 rw-p 00020000 fd:00 164913                     /lib64/ld-2.12.so
7f0600f72000-7f0600f73000 rw-p 00000000 00:00 0 
7f0600f73000-7f0600f76000 r--p 00000000 fd:04 2454846                    /data1/spider/ytbiosoft/miniconda3/envs/python3/bin/flye-polish
7f0600f76000-7f0600f88000 r-xp 00003000 fd:04 2454846                    /data1/spider/ytbiosoft/miniconda3/envs/python3/bin/flye-polish
7f0600f88000-7f0600f8b000 r--p 00015000 fd:04 2454846                    /data1/spider/ytbiosoft/miniconda3/envs/python3/bin/flye-polish
7f0600f8b000-7f0600f8c000 r--p 00017000 fd:04 2454846                    /data1/spider/ytbiosoft/miniconda3/envs/python3/bin/flye-polish
7f0600f8c000-7f0600f8d000 rw-p 00018000 fd:04 2454846                    /data1/spider/ytbiosoft/miniconda3/envs/python3/bin/flye-polish
7f06020aa000-7f06026f7000 rw-p 00000000 00:00 0                          [heap]
7fffe18de000-7fffe18f5000 rw-p 00000000 00:00 0                          [stack]
7fffe19ff000-7fffe1a00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
[2019-11-11 07:23:15] ERROR: Command '['flye-polish', '--bubbles', '/data1/spider/project/nephila/40-polishing/bubbles_2.fasta', '--subs-mat', '/data1/spider/ytbiosoft/miniconda3/envs/python3/lib/python3.6/site-packages/flye/config/bin_cfg/pacbio_substitutions.mat', '--hopo-mat', '/data1/spider/ytbiosoft/miniconda3/envs/python3/lib/python3.6/site-packages/flye/config/bin_cfg/pacbio_homopolymers.mat', '--out', '/data1/spider/project/nephila/40-polishing/consensus_2.fasta', '--threads', '24']' died with <Signals.SIGABRT: 6>.

**Comment by mikolmogorov** [comment]
Hi,

What flye version are you using? Could you also post the log file?

Mikhail

**Comment by mikolmogorov** [comment]
Closed due to inactivity.
