### ISSUE TITLE
estimate the expected memory

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [fenderglass/ABruijn#191]
Hello Mikhail,
I am trying Flye to assemble a plant genome using pacbio error-prone data. The genome size is roughly 1.8G and my pacbio reads are roughly 170X coverage. 
Is there a way to estimate the required RAM? I am asking because I am going to submit the job into a PBS cluster and i want to have a good idea of the RAM before submission.
Thanks,
Zhenzhen

**Comment by mikolmogorov** [comment]
Please refer to the FAQ.

**Comment by zhenzhenyang-psu** [comment]
thanks!
