### ISSUE TITLE
Classify repeats within a long read

### ISSUE THREAD

**Issue by smaguire-neb** [fenderglass/ABruijn#193]
Hello, 

I was wondering if this program can be used to identify subreads within a long noisy concatemeric read? I have ONT data that is produced by a rolling circle process that produces many repetitive concatamers, somewhat similar to what the raw circular consensus reads from pacbio would look like. What I would like to do is compute the repeat graph from each read aligned with itself and identify the starting and stopping points of the "subreads". Then assemble the subreads to get an error corrected consensus sequence. The process would be somewhat similar to the one described here: https://www.pnas.org/content/115/39/9726. I think the A-de bruijn graph approach like you implemented here would make more sense (and be faster) than the approach that they used to analyze the data, and would also be applicable to concatamers that do not contain a known sequence motif.

Any insights you might have would be hugely appreciated.

Thanks,
Sean Maguire

**Comment by mikolmogorov** [comment]
Hi Sean,

I think some ideas/methods from Flye could be applicable, but the current pipeline as it is will not solve the read correction problem. You'd need to figure out the subreads coordinates and split them, and afterwards you probably can use any long-read polisher. 

Mikhail
