### ISSUE TITLE
can Flye use more than 1 node?

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [fenderglass/ABruijn#194]
Hello,
I am running an assembly job using Flye on a pbs system.
I requested 2nodes of 64 thread/node, but found that only 64 threads were used.
Is Flye able to run multiple nodes?

In addition, my job was killed because out of memory (requested 1Tb)
The genome size of the species I used is 1.74G, and I had around 170x coverage in which I only selected the longest 100X reads to run. 

Is there a way to run Flye using fewer reads to start and later use the remaining reads?
My commands is below:
#PBS -N flye_run2
#PBS -l nodes=2:ppn=64
#PBS -l mem=1T
#PBS -l walltime=360:00:00
#PBS -S /bin/bash
#PBS -q slst_fat

cd $PBS_O_WORKDIR

DATA=/public/home/yangzhzh/projects/0_aiden_lab/2_pepper_genome/2_assembly/1_pacbio/1_bam2fa

. ~/miniconda3/bin/activate
conda activate assembly_tools
flye --pacbio-raw $DATA/m54193_190201_221529.subreads.fasta $DATA/m54193_190204_145244.subreads.fasta $DATA/m54193_190205_010646.subreads.fasta $DATA/m54193_190205_112040.subreads.fasta $DATA/m54193_190205_213450.subreads.fasta $DATA/m54193_190219_220726.subreads.fasta $DATA/m54193_190220_082139.subreads.fasta $DATA/m54193_190221_045031.subreads.fasta $DATA/m64060_190901_174350.subreads.fasta $DATA/m64060_190903_190940.subreads.fasta  --genome-size 1.8g -o fly_out_run1 --threads 128 --asm-coverage 100

Thanks,
Zhenzhen

**Comment by zhenzhenyang-psu** [comment]
The pbs error output is as follows:

[2019-12-05 15:53:51] INFO: Computing consensus
=>> PBS: job killed: mem job total 1079097356 kb exceeded limit 1073741824 kb

**Comment by mikolmogorov** [comment]
No, Flye does not support running on multiple machines. Please refer to FAQ for recommendations on how to reduce memory footprint.
