### ISSUE TITLE
how to define genome size with --meta option

### ISSUE THREAD

**Issue by wangpeng407** [fenderglass/ABruijn#195]
Usually, It's not difficult to choose genome size when perform single microbes assembly, 3M, 5M or 10M may be all okay.

But when do  metagenome assembly, it's still obscure about how to choose the genome size.

Assume that there is 20G Nanopore sequence data from soil, is it ok to choose 5M, 500M, or any other?

Is there any recommended gsize with --meta option?

Thanks~

**Comment by mikolmogorov** [comment]
Meta mode is almost not sensitive to the genome size parameter, so feel free to use any reasonable guess.
