### ISSUE TITLE
less contigs and bp after polishing

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#196]
Hello,
I polished a second time s Flye assembly and I notice that during the polishing I lost about 10% of the bases. Stats of the flye assembly:
```
(base) bash-4.2$ assembly-stats CMS281_191206/assembly.fasta
stats for CMS281_191206/assembly.fasta
sum = 3481660072, n = 28243, ave = 123275.15, largest = 3651323
N50 = 350348, n = 2935
N60 = 277293, n = 4049
N70 = 209125, n = 5494
N80 = 146275, n = 7480
N90 = 79280, n = 10668
N100 = 157, n = 28243
N_count = 4500
Gaps = 45
```
stats after polishing:

```(base) bash-4.2$ assembly-stats CMS281_191206_p2/polished_1.fasta
stats for CMS281_191206_p2/polished_1.fasta
sum = 3102782107, n = 27997, ave = 110825.52, largest = 3332674
N50 = 318440, n = 2890
N60 = 252150, n = 3983
N70 = 189066, n = 5406
N80 = 132543, n = 7357
N90 = 71722, n = 10482
N100 = 10, n = 27997
N_count = 0
Gaps = 0
```
the command was: 
`flye --polish-target CMS281_191206/assembly.fasta --nano-raw Rabiosa_G303_all_5kb_q7.fq --iterations 1 --out-dir CMS281_191206_p2 --threads 46`
and the flye.log says:
```
[2019-12-11 09:19:05] root: INFO: Running Flye polisher
[2019-12-11 09:19:05] root: DEBUG: Cmd: /home/copettid/anaconda3/bin/flye --polish-target CMS281_191206/assembly.fasta --nano-raw Rabiosa_G303_all_5kb_q7.fq --iterations 1 --out-dir CMS281_191206_p2 --threads 46
[2019-12-11 09:19:05] root: INFO: Polishing genome (1/1)
[2019-12-11 09:19:33] root: WARNING: Input contain non-ACGT characters - they will be converted to arbitrary ACGTs
[2019-12-11 09:20:00] root: INFO: Running minimap2
[2019-12-12 23:52:14] root: INFO: Separating alignment into bubbles
[2019-12-13 02:56:03] root: DEBUG: Generated 91874211 bubbles
[2019-12-13 02:56:03] root: DEBUG: Split 581395 long bubbles
[2019-12-13 02:56:03] root: DEBUG: Skipped 1305412 empty bubbles
[2019-12-13 02:56:03] root: DEBUG: Skipped 2311 bubbles with long branches
[2019-12-13 02:56:04] root: INFO: Alignment error rate: 0.174684
[2019-12-13 02:56:04] root: INFO: Correcting bubbles
```

is it normal to have such a drop in bases? or did maybe the run not close properly? the difference is 246 sequences, whose N50 is 2155 bp - though they sum up to almost 400 kb. 
Just wondering if it is normal,
thanks

**Comment by mikolmogorov** [comment]
Hi,

What is the mean dataset coverage? After polishing Flye filters out contigs that have coverage below 0.2 * mean - so this is probably what you are seeing. You can turn this behavior off by adding `--meta` option (it will remove contigs with absolute coverage below 3).

**Comment by dcopetti** [comment]
There is about 16x coverage, and in fact there is no contig with coverage lower than 3.
It makes sense to discard the low coverage contigs, good to know.

One more observation: there seems to have been also a restructuring of the contigs during the polishing (N50 clearly lower, largest contig 12% shorter): is this also normal? What kind of operations are made during polishing besides correcting at small scale? I guess breaking contigs with low support of realigned reads

**Comment by mikolmogorov** [comment]
This seems odd. Contigs should not be split into parts, but if there are any runs with zero read coverage - those will be removed. This could be the explanation - you can check this by visualizing read alignments to the target sequence (with IGV).

**Comment by mikolmogorov** [comment]
Closing this one for now - feel free to re-open if you have any follow up questions!

**Comment by dcopetti** [comment]
I figured it out: I had the reads file from another line, so it was creating lots of incomplete alignments and low coverage contigs. The changes when polishing with the right file were neglectable.

**Comment by mikolmogorov** [comment]
Thanks for clarifying!
