### ISSUE TITLE
subassembly of ccs assembly and raw read assembly

### ISSUE THREAD

**Issue by bresyd** [fenderglass/ABruijn#197]
Hello,

I recently received pacbio sequencing data from a complex environmental metagenome. I received ccs reads and also raw reads. Using flye, I made one assembly with only the ccs reads and one assembly using only the raw reads.
Here are the assembly statistics for the ccs read assembly:

[2019-12-12 16:53:07] INFO: Assembly statistics:

	Total length:	218883047
	Fragments:	5194
	Fragments N50:	56536
	Largest frg:	1241591
	Scaffolds:	1
	Mean coverage:	25

and here are the assembly statistics for the raw read assembly:
[2019-12-12 01:08:28] INFO: Assembly statistics:

	Total length:	531226521
	Fragments:	16054
	Fragments N50:	55173
	Largest frg:	2699783
	Scaffolds:	46
	Mean coverage:	230

I read about the --subassemblies option in flye and thought it would be great if I could use this option to combine the two assemblies. I gave it a first try which resulted in an error:

flye --subassemblies flye_out/assembly.fasta flye_out_ccs/assembly.fasta --meta --genome-size 600m --threads 40 --out-dir flye_out_combined
[2019-12-13 12:11:40] INFO: Starting Flye 2.6-release
[2019-12-13 12:11:40] INFO: >>>STAGE: configure
[2019-12-13 12:11:40] INFO: Configuring run
[2019-12-13 12:11:46] WARNING: Input contain non-ACGT characters - they will be converted to arbitrary ACGTs
[2019-12-13 12:11:49] INFO: Total read length: 750109568
[2019-12-13 12:11:49] INFO: Input genome size: 600000000
[2019-12-13 12:11:49] INFO: Estimated coverage: 1
[2019-12-13 12:11:49] WARNING: Expected read coverage is 1, the assembly is not guaranteed to be optimal in this setting. Are you sure that the genome size was entered correctly?
[2019-12-13 12:11:49] INFO: Reads N50/N90: 55600 / 21132
[2019-12-13 12:11:49] INFO: Minimum overlap set to 1000
[2019-12-13 12:11:49] INFO: Selected k-mer size: 31
[2019-12-13 12:11:49] INFO: >>>STAGE: assembly
[2019-12-13 12:11:49] INFO: Assembling disjointigs
[2019-12-13 12:11:49] INFO: Reading sequences
[2019-12-13 12:11:56] ERROR: The input contain reads with duplicated IDs. Make sure all reads have unique IDs and restart. The first problematic ID was: contig_1
[2019-12-13 12:11:56] ERROR: Command '['flye-assemble', '--reads', 'flye_out/assembly.fasta,flye_out_ccs/assembly.fasta', '--out-asm', '/scratch/btschits/pacbio_assembly/flye_out_combined/00-assembly/draft_assembly.fasta', '--genome-size', '600000000', '--config', '/home/btschits/miniconda3/envs/flye/lib/python3.7/site-packages/flye/config/bin_cfg/asm_subasm.cfg', '--log', '/scratch/btschits/pacbio_assembly/flye_out_combined/flye.log', '--threads', '40', '--meta', '--min-ovlp', '1000', '--kmer', '31']' returned non-zero exit status 1.

My questions are
- is the error because the contig IDs are to a large part identical in both assemblies? So I could just rename the contigs in one assembly file and rerun the subassembly?
- Do I need to worry about the warning regarding the expected coverage of 1 (I read in some of your answers to other questions that the genome size variable is not too critical in meta mode)?
- Before I troubleshoot further I wanted to ask if you generally agree with this workflow (separate assemblies from ccs and raw reads and then combining them with --subassemblies) or is there a different way to use both read sets for one combined assembly?

Thanks a lot for your help.
 
Cheers

bresyd

**Comment by mikolmogorov** [comment]
Hi,

>is the error because the contig IDs are to a large part identical in both assemblies? So I could just rename the contigs in one assembly file and rerun the subassembly?

Yes, renaming should address this.

>Do I need to worry about the warning regarding the expected coverage of 1 (I read in some of your answers to other questions that the genome size variable is not too critical in meta mode)

Yes, `--subassemblies` mode is designed to handle low coverage - so it should be ok. In fact, I don't think that `--meta` mode will make any difference for merging two assmeblies - I would try both with and without it.

>Before I troubleshoot further I wanted to ask if you generally agree with this workflow (separate assemblies from ccs and raw reads and then combining them with --subassemblies) or is there a different way to use both read sets for one combined assembly?

I think it's a valid workflow. You can alternatively try to assemble raw reads and then mix the contigs with CCS reads - the results should be somewhat similar I think.

**Comment by bresyd** [comment]
Hi Mikhail,

thanks a lot for your response.

Indeed, renaming the contigs in one assembly resolved the subassembly error I got.

I did as you suggested and run the subassembly with and without the --meta option. Here are the results:
including --meta:
flye --subassemblies flye_out/assembly.fasta renamed_assembly_ccs_new.fasta --meta --genome-size 600m --threads 40 --out-dir flye_out_subassembly_meta
[2019-12-19 10:49:30] INFO: Assembly statistics:

	Total length:	713311763
	Fragments:	18544
	Fragments N50:	58206
	Largest frg:	1582457
	Scaffolds:	4
	Mean coverage:	1

without --meta
flye --subassemblies flye_out/assembly.fasta renamed_assembly_ccs_new.fasta --genome-size 600m --threads 40 --out-dir flye_out_subassembly_NOmeta
[2019-12-19 12:17:13] INFO: Assembly statistics:

	Total length:	716888367
	Fragments:	18396
	Fragments N50:	58776
	Largest frg:	2728659
	Scaffolds:	15
	Mean coverage:	1

Overall I think the results are quite similar in total length and N50. The longest contig is clearly longer without the --meta option, hence I think I will go with subassembly without the --meta option. 

One thing that surprised me a little bit was that the size of the subassemblies (~710 Mb) is only ~80 Mb smaller than the sum of the ccs assembly (~270 Mb, this number has changed compared to my initial post since I had a mistake in my initial ccs read assembly command) plus the raw read assembly (~530 Mb). I interpret this that both assemblies (the one with only the ccs reads and the one with only the raw reads) have rather unique content, with relatively little overlap. I assumed that most of the content of the ccs assembly would also be present in the raw read assembly, hence I expected the size of the subassembly to be only a bit bigger than the size of the raw read assembly. Do you have any thoughts on this.

I also tried the alternative assembly approach you suggested, namely first assembling the raw reads and then mixing the resulting contigs with the ccs reads and using them as input for a new assembly (with the --pacbio-corr option). Here are the results:
flye --pacbio-corr ccs_reads_plus_raw_contigs.fasta --meta --genome-size 600m --threads 40 --out-dir flye_out_ccs_reads_plus_raw_contigs
[2019-12-18 19:52:17] INFO: Assembly statistics:

	Total length:	343938416
	Fragments:	6330
	Fragments N50:	73358
	Largest frg:	1239265
	Scaffolds:	0
	Mean coverage:	17

The total assembly size is considerably smaller using this approach, ~343 Mb compared to ~710 Mb using --subassembly (the assembly of the raw reads alone produced ~530 Mb). Hence I feel like I am losing a lot of information with this approach.

Overall, I think I am going with the subassembly without the --meta option.

Thanks again for your help and for providing this great software.

**Comment by mikolmogorov** [comment]
Thanks for the update!

From our experience, for large environmental metagenomes it is not surprising that two different samples cover different sequence. You might have the most abundant bacteria at high coverage shared between samples, and the "tails" of less abundant organisms to be disjoint. 

One thing to be aware of is  that `--subassemblies` mode assumes <1% error rate between contigs, which might be too strict for raw PB metagenomic reads. Before finalizing the assembly, I would check if there are significant overlaps between contigs sets with an orthogonal method (such as SibeliaZ, or simple alignment with minimap2).

Let me know if you have more questions!
Mikhail

**Comment by bresyd** [comment]
Dear Mikhail,



thanks a lot for you last reply and please apologize my late response (I was on a research cruise the past few weeks). 



Just to clarify this response of yours:



"From our experience, for large environmental metagenomes it is not surprising that two different samples cover different sequence."



I did not combine assemblies from 2 different samples but two assemblies from one and the same sample; one generated from the ccs reads and the other one generated from the raw reads. However, I will now try what you said and test if there are any large overlaps between my sets of contigs.



I have another question that I would like to ask you:



In addition to the long read metagenome (which I successfully assembled using metafly), I also have illumina data for the same sample. I would now like to create one combined assembly (pacbio plus illumina).



In your metafly paper you suggest the following for combining long and short read data:

"Although metaFlye is currently limited to assembling long reads only, we plan to extend it to assembling hybrid datasets that combine long and short reads. The existing hybrid assemblers, such as hybridSPAdes (Antipov et al., 2016) and Unicycler (Wick et al., 2017), first assemble short reads using SPAdes or metaSPAdes and further scaffold the resulting contigs using individual long reads. As a result, they do not fully utilize long-read assemblies. metaFlye enables an alternative approach based on (i) assembling long reads into metaFlye contigs, (ii) assembling short reads into metaSPAdes contigs, and (iii) combining metaFlye and metaSPAdes contigs and assembling them together using Flye."



I wanted to ask if you still think that this is the best way to create a combined assembly of long and short read data? Alternatively I thought I could use the metaflye assembly and provide it as --trusted-contigs to a short read metaspades assembly. If you have any advice/experience that you can share I would be very appreciative. 



Thanks a lot for your help and with best wishes,



Bernhard





-----Original message-----

**Comment by mikolmogorov** [comment]
Hi Bernhard,

>I did not combine assemblies from 2 different samples but two assemblies from one and the same sample;

Even for the same sample, different sequencing runs may cover different "parts" of a large metagenome, thus leading to different assemblies. The deeper the coverage, the higher overlap is expected.

The paragraph from this paper describes future plans, but it has not been implemented yet. There are many ongoing developments in long-read metagenomics, and the best assembly strategy is to be determined. Flye only supports long-read input - but you can use Illumina reads for polishing (for example, using Pilon). Exploring other strategies makes sense too.

**Comment by neptuneyt** [comment]
Dear Mikhail,
I am very interested in your discussion with [Bernhard's issue](https://github.com/fenderglass/Flye/issues/197). At the same time, I have a similar problem. I have many Illumina 150bp metagenomic sequences that are not third-generation sequences. Using megahit to assemble many short fragments 500bp-3k bp (accounting for > 90% of the total assembly contig numbers), - Q1: so I wonder if Flye can be used to reassemble these fragments (or combined with longer than 3k long contigs), does it make sense？In fact, I have done a test and the results are as follows:
command:
```bash
flye --subassemblies Megahit_assembly/A_Megahit.fa Megahit_assembly/B_Megahit.fa --threads 40 --meta  --min-overlap 1000 -o TGS_assembly/
```
Sample | Clean base(Gb) | ≥3k | ≥3k (%) | ≥5k | ≥10k | ≥20k | ≥30k | ≥40k | ≥50k | ≥100k | ≥150k | ≥200k | Contigs number | Size | Min | Max | Avg | N50
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
A | 23.16 | 37575 | 3.36 | 12515 | 2433 | 485 | 203 | 113 | 55 | 10 | 3 | 0 | 1117940 | 1169680655 | 500 | 193635 | 1046 | 1080
B | 32.13 | 40707 | 3.39 | 14119 | 3184 | 788 | 308 | 165 | 96 | 19 | 5 | 1 | 1199364 | 1252382137 | 500 | 203031 | 1044 | 1080
FLYE_meta_A-B_Megahit   Assembly | - | 66884 | 11.66 | 24147 | 5438 | 1251 | 508 | 256 | 148 | 32 | 13 | 2 | 573736 | 1148709708 | 500 | 303986 | 2002 | 2011

and ,we can see Flye meta model (--meta) can  truely increase the short contigs using rate (from 3.36%, 3.39% to 11.66%),and the same as doubled N50(from 1080 to 2011). 
 
How do you evaluate this result? Is it possible that the extended segment is incorrectly assembled? Do you think this approach is reasonable? 

- Q2: Another question is, if the above method is feasible, when I assemble a large genome, I am prompted that there is not enough memory. Is there any way Flye can reduce memory overhead?
>input contig size ：25Gb
>memory: 500 Gb
>core: 128

Thank you from the bottom of my heart! Looking forward your reply!
