### ISSUE TITLE
Do I need to trim the assembly result from circular result?

### ISSUE THREAD

**Issue by qjoypark** [fenderglass/ABruijn#199]
we used flye to assem the bacteria, and the result show we have got the final circular result. The software we used before (like Canu) suggest us to trim the result if they have the overlap from the start to the end. should we excute this procedure? any suggestion? what about using the software Circlator?

**Comment by qjoypark** [comment]
we used flye to assem the bacteria, and the result show we have got the final circular result. The software we used before (like Canu) suggest us to trim the result if they have the overlap from the start to the end. should we excute this procedure? any suggestion? what about using the software Circlator?

**Comment by mikolmogorov** [comment]
No need for additional synchronization if If Flye reports a circular contig.
