### ISSUE TITLE
question about the contig and scaffolds files

### ISSUE THREAD

**Issue by longzhangnation** [fenderglass/ABruijn#200]
Thanks for your developing this useful software. And I have run the software successfully. But I was puzzled about the final results. my flye version is 2.6
I know the final output file naming "assembly.fasta" containing scaffods sequencing . But the file "filtered_contigs.fasta" in the dictiory "40-polishing" is a pure contig file if I just want to use contigs file for my downstream analysis?
thanks for you reply.

**Comment by mikolmogorov** [comment]
Hi,

Yes, "filtered_contigs.fasta" contains the final contigs before they are scaffolded - feel free to use it instead. Alternatively, you would get the same result by breaking the sequences in "assembly.fasta" at the locations of Ns.

Mikhail
