### ISSUE TITLE
too much disk space for the minimap2

### ISSUE THREAD

**Issue by longzhangnation** [fenderglass/ABruijn#203]
OK , when I use this software , the minimap2 generate too big  alignment files ,although these files are cleared at last . My genome is about 3g , and sequence file is 100X . The alignment and sorted files are almost near 20T ， this consuming much disk space on my server. So do you have any idea to improve this situation ?

**Comment by mikolmogorov** [comment]
I am planning to work on reducing the storage requirements in the future, see #135. 20TB sounds too much though: the sam alignment for your data should be about 300G, plus another 300G for buffer, overall should not be more than 1TB. How did you get this number? Also, is the genome highly repetitive by chance?

**Comment by longzhangnation** [comment]
Thx . During the consensus which is after assembly , it really generates that much  alignment data . First it generates a 5T alignment data , then the alignment data was splited it 5 samll data about 1T . After the small data was sorted . So it will generates 15T data during the stage . That's too much . Hoping you can solve this problem soon. 
As for my genome , I can't tell you whether it's highly repetitive because I don't know , either . But during  my another assembly it also take up 10~12T diskspace , and the repetitive component of  that genome  is around 45% .

**Comment by mikolmogorov** [comment]
Closing this one, feel free to continue discussing in #135.
