### ISSUE TITLE
Mixing corrected PacBio and raw ONT reads?

### ISSUE THREAD

**Issue by AbigailShockey** [fenderglass/ABruijn#205]
I'm working on assembling bacterial genomes, and I have both PacBio CCS reads and ONT raw reads. My initial strategy was to use Flye to assemble the raw ONT reads and then polish them with the CCS reads (using a separate polisher), but I see in your FAQ that Flye supports assembly with raw PacBio and raw Nanopore reads for assembly using the --pacbio-raw/--nano-raw options. Is it possible (and valid?) to mix the CCS reads and raw ONT reads for assembly? If so, what flags should I use?

**Comment by mikolmogorov** [comment]
Hi,

No, mixing corrected (or CCS) and raw output is currently not possible - the error rate is too different.
