### ISSUE TITLE
Effect of asm-coverage and meta on plasmid assemblies

### ISSUE THREAD

**Issue by caitlin-f** [fenderglass/ABruijn#206]
Hi, thanks so much for this tool. I have a query about some of the different parameters and the effect these are having on plasmids.

I'm assembling some 2.5Mbp Staph isolates and I ran into "ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct" on isolates with est. depth >800x (about half of them). I followed the suggestions in previous github issues for the same error by re-assembling all isolates with the arguments --asm-coverage 50 and --meta  as per #117 

However, on the re-run the plasmids have changed length or been dropped. I'm interested in knowing the effect of the asm-coverage and meta commands and what may have happened with the large 32-65kbp plasmids between the runs i.e. which results should I believe. Code and results are below:

Run 1: 
`flye --nano-raw ${DIR}/${SAMPLE}_filtered.fastq --genome-size 2.5m --out-dir ${DIR}/${SAMPLE}_flye --threads 8 --plasmids`
Run 2: 
`flye --nano-raw ${DIR}/${SAMPLE}_filtered.fastq --genome-size 2.5m --out-dir ${DIR}/${SAMPLE}_flye_2 --threads 8 --asm-coverage 50 --plasmids --meta`

#### Sample01
Run 1: 

seq_name | length | cov. | circ. | repeat | mult. | graph_path
---------- | ------ | ---- | ----- | ------ | ----- | ------------
contig_1 | 2568271 | 113 | + | - | 1 | 1
contig_2 | 40315 | 72 | + | - | 1 | 2
contig_3 | **65971** | 489 | + | + | 4  

Run 2: 

seq_name | length | cov. | circ. | repeat | mult. | graph_path
---------- | ------ | ---- | ----- | ------ | ----- | ------------
contig_1 | 2568271| 111 | + | - | 1 | 1
contig_2 | 40310 | 72 | + | - | 1 | 2
contig_3 | **32965** | 871 | + | - | 7 | 3
contig_4 | 2609 | 16 | + | - | 1 | 4
contig_5 | 2572 | 4 | + | - | 1 | 5   

#### Sample07
Run 1:

#seq_name | length | cov. | circ. | repeat | mult. | graph_path
------------ | ------ | ---- | ---- | ------ | ------ | -----------
contig_1 | 5134 | 700 | + | + | 1 | 1
contig_2 | 2572672 | 138 | + |  - | 1 | 2
contig_3 | 5013 | 719 | + | + | 1 | 3
contig_4 | **48384** | 712 | + | + | 9 | 4

Run 2:

seq_name | length | cov. | circ. | repeat | mult. | graph_path
---------- | ------ | ---- | ----- | ------ | ----- | ------------
contig_1 | 2572693 | 138 | + | - | 1 | 1
contig_2 | 2617 | 776 | + | - | 6 | 2

[sample01_1.log](https://github.com/fenderglass/Flye/files/4095335/sample01_1.log)
[sample01_2.log](https://github.com/fenderglass/Flye/files/4095336/sample01_2.log)
[sample07_1.log](https://github.com/fenderglass/Flye/files/4095337/sample07_1.log)
[sample07_2.log](https://github.com/fenderglass/Flye/files/4095338/sample07_2.log)

**Comment by mikolmogorov** [comment]
Hi,

In general, effects of different options on plasmid assembly have not been widely tested yet. `--asm-coverage` subsamples the longest reads (which in general designed to reduce memory usage, but may help if you have a large amount of nonsense reads too). `--meta` enables a different approach for k-mer selection, which is robust to large changes in coverage. Importantly, these two options are somewhat incompatible - because subsampling could be harmful in the case of metagenomes.

I would try to run with `--meta --plasmids`, but without `--asm-coverage` - this should give you more stable assembly (with hopefully more complete plasmid set).
