### ISSUE TITLE
Structural difference between fasta and gfa

### ISSUE THREAD

**Issue by samlipworth** [fenderglass/ABruijn#207]
Hi,

I am assembling some ONT data which has been multiplexed. The output fasta file for one of the barcodes lookes correct - it agrees with the hyrbid assembly and all short reads may to it. The gfa on the other hand (for the same assembly) has two additional spurious plasmids to which no short reads map - maybe this is displaying my lack of knowledge for how flye works but I don't understand this - do you?

Thanks,
Sam

**Comment by mikolmogorov** [comment]
Hi,

Seems strange - could you post your `flye.log`, `assembly_info.txt` and `assmebly.gfa` so I can take a look?

Mikhail
