### ISSUE TITLE
Question: Is it possible to do reference based assembly

### ISSUE THREAD

**Issue by jolespin** [fenderglass/ABruijn#209]
I have a “gold standard” genome and I’m looking for structural rearrangements. The Flye assembly is about twice the size as I expected.  I was wondering if there is a tweak for reference based assemblies?

**Comment by mikolmogorov** [comment]
No, Flye does not do reference-based assembly. One possible explanation could be that the genome is highly diploid and you got assemblies of both haplotypes. BUSCO analysis could be helpful to investigate.
