### ISSUE TITLE
Compilation fails in repeat_graph/haplotype_resolver

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/ABruijn#212]
Hi,

Compiling the latest version of Flye (source install, downloaded from this repo) fails on my machine with error 2. It seems that the problem is in file `repeat_graph/haplotype_resolver.cpp`:

```
no match call for '(HaplotypeResolver::findVariantSegment(GraphEdge*, const std::vector<std::vector<EdgeAlignment>>&, const std::unordered_set<GraphEdge*>&)::__lambda11) (std::vector<EdgeAlignment>&, const std::vector<EdgeAlignment>&)'
```

I am using GCC 4.8.5.

Thank you for your help.
Guillaume

**Comment by mikolmogorov** [comment]
Hi,

Can you post the full compilation log? 

Mikhail

**Comment by GuillaumeHolley** [comment]
Sure, please find the compilation log enclosed (I have redacted parts of some paths but it shouldn't be an issue).

Thanks for having a look at it.
[error.log](https://github.com/fenderglass/Flye/files/4160304/error.log)

**Comment by mikolmogorov** [comment]
Should be fixed now, thanks for reporting!
