### ISSUE TITLE
Draft assembly / consensus assembly

### ISSUE THREAD

**Issue by chopra29** [fenderglass/ABruijn#215]
Hi Mikhail,

This is a great tool for assembly and I was able to run this lot faster than canu for sure. 

I see that draft or consensus assembly have N50 of 3.1 Mb but after contiger step the final assembly N50 is 0.32 Mb

I don't understand how the assembly be fragmented after contigger step and I am wondering if I should proceed with the consensus version for scaffolding or other analysis.

I appreciate your help.
Ratan

**Comment by mikolmogorov** [comment]
Hi Ratan,

No, disjointigs sequences (before or after consensus) should not be used as Flye output, as they potentially contain misassemblies.

Best,
Mikhail
