### ISSUE TITLE
Identify reads making a contig in the final assembly

### ISSUE THREAD

**Issue by hrpelg** [fenderglass/ABruijn#216]
I got a final assembly and final info assembly file. I am interested in identifying the 7 reads (coverage 7 is showing in the summary info of the assembly) that made that contig in order to potentially validate a big insertion on my samples versus a reference genome. How can I do that?

Many thanks

**Comment by mikolmogorov** [comment]
See #49. Flye does not retain this information - you would need to align reads to assembly.
