### ISSUE TITLE
error running flye

### ISSUE THREAD

**Issue by emmannaemeka** [fenderglass/ABruijn#217]
Hi
I kept encountering this error with flye

root: ERROR: Command '['flye-assemble', '-l', '/mnt/data/emmanuel/flye_412/flye_412/flye.log', '-t', '1', '-v', '4000', '-k', '17', '/mnt/data/emmanuel/Mucuna_Conc_20190404.fq', '/mnt/data/emmanuel/flye_412/flye_412/00-assembly/draft_assembly.fasta', '412000000', '/home/emmanuel/Flye/flye/config/bin_cfg/asm_raw_reads.cfg']' returned non-zero exit status -6

**Comment by mikolmogorov** [comment]
Hi,

Could you send the full log and describe your datasets?
