### ISSUE TITLE
Empirically determine substitutions and homopolymers based on a first assembly?

### ISSUE THREAD

**Issue by ghost** [fenderglass/ABruijn#22]
Do you think that it would make a big difference for the assembly quality if one would determine the parameters contained in 'nano_homopolymers.mat' and 'nano_substitutions.mat' empirically for a specific ONP run. One could do a first "preliminary assembly" map the ONP data back, determine the parameters and then do a second assembly with refined tuning.

How did you generate the substitutions.mat?

**Comment by mikolmogorov** [comment]
Yes, ideally it should be possible to learn the frequencies from the assembly, maybe in an iterative manner. Also, current nanopore profiles might be a bit outdated (generated with older chemistry) - we are planning to update them. Probably, the profile should also depend on a basecaller.

On the other hand, it seems that currently any kind of consensus from basecalled nanopore reads will not be perfect and require further polishing with raw signal / Illumina reads - so a quality improvement due a "corrected" error profile might not make a big difference.

**Comment by mikolmogorov** [comment]
Also, I see that you guys are doing some work in the forked repository - this is exciting! Just a heads up - in the new version we are planning to change the repository structure / output format a bit (we are planning to release it in a week or two). I am trying to keep the commits as clean as possible to make the merging process easier (in case you will be interested).

**Comment by ghost** [comment]
Thanks for the detailed answers. So having a look at the code and reading your response I guess the substitution matrix / homopolymer.mat is mainly used during polishing and bubble correction? In this case it would indeed not be very important to us since we anyway do a round of polishing using nanopolish and mapping Illumina reads as you say.

Second point; yes I forked your repo and integrated GraphMap (as discussed in an earlier thread, used a different account there so don't be confused :) ). I integrated it to a point where the automated installation, integration and running of GraphMap works perfectly on my side. But there is no documentation about the changes. I roughly tested it, but did not have time yet to check what difference it makes. For sure it takes much longer with GraphMap. So I'll do a pull request later and if you feel like testing GraphMap I'd be glad. But as you stated earlier, probably does not help much.
