### ISSUE TITLE
polishing a PacBio assembly with Illumina reads

### ISSUE THREAD

**Issue by anapopov** [fenderglass/ABruijn#222]
Hi,
I've assembled a eukaryotic genome using Canu-corrected PacBio reads. It went through the default one polishing step. I would now like to run a couple of polishing iterations using MiSeq data, and I wanted to check the code for this. I found a similar question https://www.gitmemory.com/issue/fenderglass/Flye/158/534641652 which suggests using Illumina data. Is it best to use raw, quality-trimmed or assembled MiSeq data, and how would I input it? '--subassemblies' ? for assembled Illumina data? Do I need the --genome-size parameter here?

For e.g.: 
flye --polish-target assembly.fasta --iterations 2 --out-dir MiSeq_polished/ --threads 40 --subassemblies spades_MiSeq_contigs.fasta

For context, I also used the MaSuRCa hybrid assembler with Flye, but I get a much shorter genome.
estimated genome size: 199Mb
Masurca hybrid assembly: 158Mb
Flye assembly of Canu-corrected PacBio reads: 225Mb

Thanks!
Ana

**Comment by mikolmogorov** [comment]
Hi Ana,

Flye does not do short-read polishing. You can try Pilon or Racon instead.

Mikhail
