### ISSUE TITLE
SAM file becomes too big (disk space issues)

### ISSUE THREAD

**Issue by Kon19893** [fenderglass/ABruijn#224]
Hello! I am running flye for a genome of ~8G genome size with ~30x coverage data. The problem is that the size of SAM file for calling the consensus is quite enormous (~985G and still running). Is it possible to pipe the SAM file to BAM file so it will reduce the file size (also helps with #135)?

Thanks for the awesome tool you have provided.

**Comment by mikolmogorov** [comment]
Hi,

Yes, in fact BAM support is already implemented in the `flye-devel` branch, and will be integrated into the next release.

Mikhail

**Comment by mikolmogorov** [comment]
Duplicate of #135
