### ISSUE TITLE
Difference between --pacbio-corr and --pacbio-hifi

### ISSUE THREAD

**Issue by jelber2** [fenderglass/ABruijn#230]
Hi,

What is the difference between `--pacbio-corr` and `--pacbio-hifi`? Obviously, it seems like you would use `--pacbio-hifi` with PacBio HiFi reads, but is there a major difference or only minor?

**Comment by mikolmogorov** [comment]
Hi,

The only difference currently is the alignment identity thresholds.

**Comment by charlesfeigin** [comment]
Hi,

To this end, I just had a Flye assembly of some HiFi data finish up, but only just realized today that this --pacio-hifi option had been added. The 2.7 release of Flye. 2.7 produced a significantly better assembly than 2.6 had previously, but I used --pacbio-raw on my uncorrected HiFi reads. Do you think this is worth a re-assembly using --pacbio-hifi?

Kind Regards,
Charles

**Comment by mikolmogorov** [comment]
Hi @charlesfeigin 

I am not sure what you mean by "uncorrected HiFi reads". If those are original polymerase subreads (before CCS consensus), then running using `--pacbio-hifi` on high quality reads definitely makes sense.

Best,
Mikhail
