### ISSUE TITLE
Question about the result of assembly 

### ISSUE THREAD

**Issue by quliping** [fenderglass/ABruijn#233]
Hello, I have the Illumina sequcing data and a corresponding Nanopore data for one bacteria isolation. I’m using Spades v3.10.0 for Illumina assembly and Flye v2.7 for the Nanopore assembly, but the two assemblies are not identical. There are 261 unmatched nucleotides between them. The genome size is 5 Mb.

For the spades assembly, the command is:
spades.py --careful -1 1-11_trim.1.fastq -2 1-11_trim.2.fastq -o 1-11.spades.fasta -t 8

For the flye assembly:
1. Correlate raw reads using NECAT:
necat.pl correct 52-69.config.txt
[52-69.NECAT_config_file.txt](https://github.com/fenderglass/Flye/files/4316451/52-69.NECAT_config_file.txt)
2. flye assembly:
flye -g 5m -o 06_flye/52-69 -t 8 --nano-raw 52-69.nanodrop.fasta
[52-69.flye.log](https://github.com/fenderglass/Flye/files/4316453/52-69.flye.log)
3. Polish using racon and Nanopore reads:
racon -m 8 -x -6 -g -8 -w 500 -t 32 52-69.nanopore.raw.fastq 52-69.bwa.sam 52-69.flye.fasta > 52-69.racon.fasta
4. Polish using pilon and Illumina reads:
java -Xmx16G -jar pilon-1.23.jar --genome 52-69.racon.fasta --bam 52-69.sort.bam --output 52-69.pilon --changes --threads 32

There are still 261 unmatched nucleotides between two assembles after the polish. Actually, similar patterns are also shown in another two samples, which have 11 and 84 mismatches, respectively.

As I’m working on a population genomic analysis at the strain level, and I wonder if such mismatch may strongly affect the downstream analysis. I want to know if the mismatch between Illumina and Nanopore sequening is a normal phenomenon. Could you please help me to find out what’s going on? Thank you!

**Comment by mikolmogorov** [comment]
Hi,

Not surprising at all to see ~100 missmatches for ONT assemblies. Given the genome size, it would correspond to QV45 or so, which is basically a reference quality already.

You also can't 100% trust Illumina assembly, especially near contig breaks.

Finally, if you are providing error-corrected reads as input, you should use `--nano-corr` option. Or use raw reads as Flye input otherwise, which is the recommended option.

Mikhail

**Comment by quliping** [comment]
Thank you very much for your answer. I will try –nano-corr option with error-corrected reads.

Liping Qu

发件人: Mikhail Kolmogorov <notifications@github.com>
发送时间: 2020年3月13日 3:31
收件人: fenderglass/Flye <Flye@noreply.github.com>
抄送: 曲立平 <17lpqu@stu.edu.cn>; Author <author@noreply.github.com>
主题: Re: [fenderglass/Flye] Question about the result of assembly (#233)


Hi,

Not surprising at all to see ~100 missmatches for ONT assemblies. Given the genome size, it would correspond to QV45 or so, which is basically a reference quality already.

You also can't 100% trust Illumina assembly, especially near contig breaks.

Finally, if you are providing error-corrected reads as input, you should use --nano-corr option. Or use raw reads as Flye input otherwise, which is the recommended option.

Mikhail
