### ISSUE TITLE
minimum read length 

### ISSUE THREAD

**Issue by roshanahmed** [fenderglass/ABruijn#235]
Hi, I have a lot of coverage for my data and using other assemblers I have had to set a minimum read length at about 70K to get a decent assembly. Is there any such parameter with Flye? My assembly ran on default parameters for about 15 hours and failed. The genome is only around 5mb. I was unable to find any documentation about such a parameter, any help would be greatly appreciated.

**Comment by mikolmogorov** [comment]
Hi,

Flye does not have a parameter for minimum read length.

Mikhail
