### ISSUE TITLE
from where to resume for --keep-haplotypes?

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#236]
Hello,
I just saw the new (to me)option `--keep-haplotypes`. I wonder if I can add that option to a job with `--resume-from`, and how far I need to go for the resume haplotypes to have effect. I hope after the repeat stage!
thanks,
Dario

**Comment by mikolmogorov** [comment]
Hi,

Sure, you will need to resume from repeat stage (`--resume-from repeat`).

Best,
Mikhail
