### ISSUE TITLE
Error running minimap2

### ISSUE THREAD

**Issue by raw937** [fenderglass/ABruijn#237]
root: ERROR: Error running minimap2, terminating. See the alignment error log  for details: /minimap.stderr
[2020-03-12 12:07:35] root: ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 chunks.fasta m64041_191111_034310_subreads.fastq.gz -x map-pb -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T chunks.fasta -u - | flye-samtools sort -T Flye_micro/10-consensus/sort_200312_120734 -O bam -@ 4 -l 1 -m 4G']' returned non-zero exit status 1

more minimap.stderr 
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `set -o pipefail; flye-minimap2 10-consensus/chunks.fasta m64041_191111_034310_subreads.fastq.g
z -x map-pb -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T flye_micro/10-consensus/chunks.fas
ta -u - | flye-samtools sort -T flye_micro/10-consensus/sort_200312_120734 -O bam -@ 4 -l 1 -m 4G'

DOES IT NEED SAMTOOLS?

**Comment by mikolmogorov** [comment]
Hi,

In your original message, I've noticed that you had system paths containing spaces. I think this is likely what is causing the issue. Please remove spaces from read/output directories paths and try again.

**Comment by raw937** [comment]
I removed that in the post to make it cleaner.

This is the command:
python /data/friesen/bin/Flye/bin/flye --pacbio-raw m64041_191111_190658.subreads.fastq.gz --out-dir flye_biff --genome-size 500m --threads 60

Fails at the consensus step: 
10-consensus]$ more minimap.stderr 
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `set -o pipefail; flye-minimap2 /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/flye_biff/10-consensus/chunks.fasta m64041_191111_190658.subreads.fastq.gz -x ma
p-pb -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/flye_biff/10-consensus/chunks.fasta -u - | flye
-samtools sort -T /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/flye_biff/10-consensus/sort_200323_201357 -O bam -@ 4 -l 1 -m 4G'

It produces a draft assembly fails at the consenus step do I need to have samtools called?

**Comment by mikolmogorov** [comment]
@raw937 please follow my suggestion above.

**Comment by mikolmogorov** [comment]
Hmm, for some reason my email notification is showing a space in the path, but I don't see it on github. If there are no spaces, could you please send me the full log and minimap.err files?

**Comment by raw937** [comment]
[flye.log](https://github.com/fenderglass/Flye/files/4383223/flye.log)


[minimap_stderr.log](https://github.com/fenderglass/Flye/files/4383224/minimap_stderr.log)

**Comment by mikolmogorov** [comment]
Thank you! Based on the log, I think the bracket in path is causing the issue (but not the space, as I previously suspected).

I suggest to rename the folder `Trifolium-1_(microcephalum)_40pM` so that it does not contain brackets (or move reads and output directory to a different folder) and try again. 

You can use the same output folder (after moving/renaming) and add `--resume-from consensus` option to skip the assembly step that was completed.

**Comment by mikolmogorov** [comment]
Closed due to inactivity. Feel free to reopen if the issue is still unsolved.

**Comment by raw937** [comment]
Hello, 

It took forever over two months to get on the server again - ugh!?!?
Results from our experiment. 
--Command
/data/friesen/bin/Flye/bin/flye-minimap2 /data/friesen/clean/Trifolium/results/Trifolium_fucatum-1_CLR_35pM/flye_fuc/40-polishing/chunks_1.fasta m64041_200305_141913.subreads.fastq.gz -x map-pb -t 60 -a -
p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq

--Result
/var/spool/slurmd/job18799712/slurm_script: line 18: 102291 Segmentation fault      /data/friesen/bin/Flye/bin/flye-minimap2 /data/friesen/clean/Trifolium/results/Trifolium_fucatum-1_CLR_35pM/flye_fuc/40-
polishing/chunks_1.fasta m64041_200305_141913.subreads.fastq.gz -x map-pb -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq

Any thoughts for the Segmentation fault and why it doesn't finish mapping?

Let me know what else I can try? Its a big genome 1.8 GB thus far.

**Comment by raw937** [comment]
We tried this as well. 

python /data/friesen/bin/Flye/bin/flye-minimap2 /data/friesen/clean/Trifolium/results/Trifolium_fucatum-1_CLR_35pM/flye_fuc/40-polishing/chunks_1.fasta m64041_200305_141913.subreads.fastq.gz -x map-pb -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq



-N 10 (with)

File "/data/friesen/bin/Flye/bin/flye-minimap2", line 1
SyntaxError: Non-ASCII character '\xec' in file /data/friesen/bin/Flye/bin/flye-minimap2 on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

-N 10 (without)

File "/data/friesen/bin/Flye/bin/flye-minimap2", line 1
SyntaxError: Non-ASCII character '\xec' in file /data/friesen/bin/Flye/bin/flye-minimap2 on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by mikolmogorov** [comment]
@raw937 The last command lines did not work because you have `python` in the beginning of them. Please try the exact command line below. It has no `-N 10` argument in difference to the segfaulted version.

`/data/friesen/bin/Flye/bin/flye-minimap2 /data/friesen/clean/Trifolium/results/Trifolium_fucatum-1_CLR_35pM/flye_fuc/40-polishing/chunks_1.fasta m64041_200305_141913.subreads.fastq.gz -x map-pb -t 60 -a -p 0.5 --sam-hit-only -L -Q --secondary-seq`

**Comment by mikolmogorov** [comment]
Closed because of inactivity.
