### ISSUE TITLE
very long repeat stage 

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#239]
Hi Mikhail,
I am running an assembly (on the same 2.5 Gb, highly heterozygous and repeat-rich) plant genome - this time with a subset of the data (60x instead of 70x) to see how low I can go with sequencing and still get good assemblies.
The run started 23 days ago now, and the consensus step was completed 18 days ago.
I think that with higher coverage the repeat step (at its 18th day now!) was much shorter, can this be true? Furthermore, much of this time was spent using a single CPU: I wonder if this is a normal bottleneck at the repeat stage and if there is a way to speed it up.
The log file is here:
https://de.cyverse.org/dl/d/CE03354D-61B1-495B-91F6-9079FC2F3E2C/flye.log_30x_200328
Looking forward for your opinion,
Thanks,

Dario

**Comment by mikolmogorov** [comment]
Hi Dario,

Thanks for the detailed report. Highly repetitive genomes definitely could take much longer than usual. In this case, it does not depend much on the genome size or coverage, but rather on repeat content. For example a human genome with the same coverage would have been assembled in 4-5 days.

The log looks normal to me - I think it should finish within a day or two (if haven't yet). Note that you might have a slowdown with contigger stage diescribed in #234 . In this case, please compile the latest code from `flye` branch and resume from contigger stage.

Mikhail

**Comment by dcopetti** [comment]
Thank Mikhail,

I will update to the latest code.

**Comment by dcopetti** [comment]
Hi Mikhail,

I havenother quick question regarding this same assembly above.
The assembly is still ongoing, now at the graph stage. As you see
```
$ ls -lrth /path/rab_30x_flye/30-contigger/
total 163G
-rw-r--r--. 1 stlinus mpb 3.1G Apr  4 09:15 contigs.fasta
-rw-r--r--. 1 stlinus mpb 2.8M Apr  4 09:22 contigs_stats.txt
-rw-r--r--. 1 stlinus mpb 2.0K Apr  4 09:22 scaffolds_links.txt
-rw-r--r--. 1 stlinus mpb  14M Apr  4 18:35 graph_final.gv
-rw-r--r--. 1 stlinus mpb 3.0G Apr  4 18:36 graph_final.fasta
-rw-r--r--. 1 stlinus mpb 157G Apr 19 12:02 graph_final.gfa
```
The .gfa file is very big (in the ~45x assembly it was 15-25 GB) and it is still being written after two weeks. I wonder if this is normal, and expecially if the contigs.fasta file I have now will be the same that I would have as an input for the polishing. The goal of this assembly is to see the metrics (and runtime) of other assemblies carried at lower coverage, to see how much data we really need.
My guess here is that at lower coverage there are way more ambiguous paths, so the repeat step was longer and the gfa file is bigger.
Can I kill this assembly, get my N50 stats and go ahead with the next one?
Thanks!

**Comment by mikolmogorov** [comment]
Hi Dario,

This is answered in #234.

Mikhail

**Comment by dcopetti** [comment]
OK, thanks!
I have `Flye 2.7b-b1526`, so I guess this does not have the improved gfa generation step. I will update to the latest.

How about contig metrics, do you think they are going to change again before polishing?
Thanks

Dario

**Comment by mikolmogorov** [comment]
Polishing only slightly change contig lengths (because it fixes indels). 

As an alternative to restarting the run, you can take the generated unpolsihed contigs from `30-contigger/contigs.fasta` and use `--polish-target` option on them to manually run Flye polisher.

Best,
Mikhail
