### ISSUE TITLE
minimap2 is not installed

### ISSUE THREAD

**Issue by bioramg** [fenderglass/ABruijn#240]
Hi,
I installed minimap2 and flye through miniconda. When I tried to run flye with my ONT reads, I am getting "ERROR: minimap2 is not installed; ERROR: pipeline aborted" 

Please help me how to solve this issue

**Comment by mikolmogorov** [comment]
Hi,

This can't be right, as Flye bioconda package contains all required binaries (and provides its own minimap2). Please try to reinstall Flye through bioconda in a clean environment, and also make sure that you are running bioconda version (in case you might have any local installations): `which flye`.

Mikhail

**Comment by bioramg** [comment]
Thank you. I installed flye individually and it's working fine..
