### ISSUE TITLE
Trusted contigs - Reg

### ISSUE THREAD

**Issue by bioramg** [fenderglass/ABruijn#241]
Hi, 
I would like to assemble the plant mitochondrial genome using both Illumina and Nanopore reads.
I am having two types of contigs:
1. The same species - mitochondrial contigs obtained from hybrid assembly of using SPADES. But not able to get scaffold or draft genome
2. All land plants - mitochondrial contigs obtained from NCBI database (This is not closely related species - Contain all land plant mitochondrial genomes)

Shall I use both contigs at the same time? or should I check with one by one separately?

Also, I would like to know what does mean by Nanopore-corrected reads. I am having trimmed reads. So shall I give command --nanopore-raw or --nanopore-corr commands.

Thank you for your suggestion

**Comment by mikolmogorov** [comment]
@bioramg 

Not sure what exactly you want to do with those contigs - could you explain? Flye does not have a trustued contigs option (as in SPAdes).

Please use `--nanopore-raw` opion.

Mikhail

**Comment by bioramg** [comment]
I would like to use contigs which are obtained by previously assembled with different assembler. for eg. SPADES. Shall I use the subassemblies option with these contigs?

**Comment by mikolmogorov** [comment]
Answered in #245
