### ISSUE TITLE
assembly worsens with --keep-haplotypes

### ISSUE THREAD

**Issue by jdmontenegro** [fenderglass/ABruijn#242]
Hi Mikhail,

As I mentioned in another thread, I did an iterative mappig-assembly of reads and compared the results of flye2.7 with and without the `--keep-haplotypes` option. 
As far as I can see, the assemblies are quite similar, I was expecting a larger assembly in the --keep-haplotypes assembly, but instead I am getting the opposite:

```
==> standard <==

        Total length:   64945335
        Fragments:      1396
        Fragments N50:  107738
        Largest frg:    1010501
        Scaffolds:      5
        Mean coverage:  27

==> --keep-haplotypes <==

        Total length:   63173655
        Fragments:      1321
        Fragments N50:  84636
        Largest frg:    602320
        Scaffolds:      0
        Mean coverage:  27
```

Most of the contiguity metrics have worsen (N50, largest frgment, total length). There is a slight improvement in the average contig length (46K vs 48K). Is it possible that `--keep-haplotypes `is writing separate contigs for unresolved homozygous regions and that is why I can see larger N50 in the standard assembly compared to the haplotype assembly?

Would you recommend using higher sequencing depth to improve both: 1) resolved homozygous regions and better consensus of the haplotypes? I realize now that by using 34X depth of the genome, I should expect ~17X per chromatid, which does sound a bit too low, even for a tool as amazing as flye.

Any further comments or suggestions would be more than welcome.

Kind regards,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
Hi Juan,

Yes, this is exactly what `--keep-haoplotype` does - it preserves heterozygous regions instead of collapsing them and producing pseudo-haplotyes. Thus, every heterozygous regions will break the assembly, and the contiguity is expected to be lower.

I think increasing the coverage might help to resolve additional repeats as well as improve consensus quality. But read length distribution is even more important. Note that Flye currently is not optimized for highly heterozygous regions.

MIkhail

**Comment by jdmontenegro** [comment]
One final question, how can I differentiate between homologous haplotigs? Is there any information in the assembly_info.txt? Or somewhere else? Or do we need to look for them manually in the assembly graph?

Cheers,

Juan D.

**Comment by mikolmogorov** [comment]
@jdmontenegro 

Yes, you can check `alt_group` field in `assembly_info.txt`

Alternative contigs (representing alternative haplotypes) will have the same alt. group ID. Primary contigs are marked by `*`.
