### ISSUE TITLE
Ability to specific a random seed for reproduction of assemblies

### ISSUE THREAD

**Issue by maxgmarin** [fenderglass/ABruijn#244]
Hello,

I have noticed that the there is some variability in the output of Assemblies by Flye (v2.5). I noticed this when I was using PacBio subreads as input for assembly of bacterial genomes. 
I found that (for a few samples) the same data would sometimes produce circularized chromosome when I ran Flye and other times it did not successfully generate a circular contig (as defined by Flye in assembly_info.txt)

Would it be possible to set a seed for Flye's assembly for the exact reproduction of a specific assembly? This would be helpful for sharing a SnakeMake pipeline that reproduces the exact same assemblies I have been using for analysis.

Thank you!
Max

**Comment by mikolmogorov** [comment]
Hi Max,

It is currently not possible unfortunately. There is a multiprocessing stage (disjointig generation) where the results slightly dependind on the thread scheduling by OS (e.g. which thread finishes first). 

There were some improvements in the version 2.7 wrt to results stability - so I would give it a try. However, there still no guarantee in 100% identical output.

Mikhail

**Comment by jdmontenegro** [comment]
Dear Mikhail,
I am not sure if this is related. As of versión 2.6 I was getting organelles assemblies as circularized contigs. I just did some down sampling from 5000x to 60-100x. Howevere, I am getting fragmented and smaller assemblies in the current version. Would enabling - - plasmid improve things or this is only to tell flye to expect higher that expected coverage in some edges of the graph?
I will get back to you with some comparisons between versions for this specific test.
Kind regards, 
Juan D. Montenegro

**Comment by mikolmogorov** [comment]
@jdmontenegro I don't think it is related. `--plasmids` can improve the assemblies of short circular sequence (typically <10kb).

**Comment by mikolmogorov** [comment]
Closing this thread, discussion continues in https://github.com/fenderglass/Flye/issues/509
