### ISSUE TITLE
The assemble quality is not as well as I expected, and how to improve?

### ISSUE THREAD

**Issue by Liuzixuan2020** [fenderglass/ABruijn#247]
Dear community,

I compared two assembly results of wtdbg2 and flye and I found there is no large 
improvement of the assembly results of flye especcially in largest contig、N50 and also two genome size have big difference.（wtdbg2: 1.0G flye: 1.2G).Result of flye seems has slightly higher heterozygosity than we expected. As a result, I want to know if I need to change some required parameters in my code. The following document is my " flye assemble log" and hope you could help me adjust my code.

[flye.zip](https://github.com/fenderglass/Flye/files/4444835/flye.zip)

Thank you!

**Comment by mikolmogorov** [comment]
Hi,

Please refer the the FAQ for some advice on parameter settings. I also suggest to try the latest Flye release.
