### ISSUE TITLE
Mitochondrial contigs could not identified

### ISSUE THREAD

**Issue by bioramg** [fenderglass/ABruijn#248]
Hi, 
I am trying to assemble the plant mitochondrial genome from the whole genome sequence of Nanopore reads and the size is ~8.7 GB (raw data) and the expected mitochondrial genome size is ~1 MB. I can able to get long contigs and the highest length is ~350 kb. When I tried to map with mitochondrial genes, I can able to find only one contig is matching with the reference gene and the remaining contigs does not show any similarity. Also, I am having contigs of hybrid assembly (Illumina and Nanopore) using SPADES and can able to see so many genes in these contigs.
1. How can I get mitochondrial contigs from nanopore sequences using flye? Should I change any parameters?
I have used "./bin/flye --nao-raw nanpore.fastq.gz --genome-size 1m -o nano
Thank you.

**Comment by mikolmogorov** [comment]
Hi,

If you are using whole genome sequencing as input, you need to set genome size to the expected total assembly size, not just the size of your regions of interest. This is what is likely causing the issue.

**Comment by bioramg** [comment]
Thank you. By the way, I would like to know what is the input parameter for RAM usage?
