### ISSUE TITLE
How to remove contigs from assembly?

### ISSUE THREAD

**Issue by fernmoss** [fenderglass/ABruijn#251]
Hi,
I have some contigs in my assemblies that I wish to remove, because they originate from contaminating organisms.

What is the best way to go about removing contigs from a flye assembly?

Is there a way to get a new assembly graph and assembly stats from flye, without the unwanted contigs? Could it work to use `--subassemblies` option and `assembly.fasta` file (with unwanted contigs edited out) as input?

If no, how can I get coverage statistics for my assemblies? 
I'm quite new to bioinformatics, so I don't have a good overview of the tools available.
What tool(s) can I use to assess read coverage across my assemblies? I use nanopore reads for (mostly de novo) assembly of small genomes.

Thank you.

**Comment by mikolmogorov** [comment]
Hi,

Flye does not have any options for additional contig filtering, but you can get the information about coverage from assembly_info.txt and use it to extract the contigs of interest.

Mikhail
