### ISSUE TITLE
Merging two ONT datasets

### ISSUE THREAD

**Issue by a-89** [fenderglass/ABruijn#253]
Hi Mikhail,
First of all, thanks for developing Flye. It is working nicely with ONT data.
I have a question regarding the best approach to follow with the datasets I have. We have extracted DNA from a fecal sample to do metagenomics. The same sample was extracted twice: a) using a HMW extraction; b) using conventional procedure (with bead-beating). Each one of the extractions was run in a single flowcell.
Which is your recommended approach to merge this data?
1)	Merging the datasets in the beginning and pre-process them, by trimming short reads
2)	Performing two independent assemblies and merging them with subassemblies
3)	Using HMW data to perform the assembly and maybe further polishing the reads (racon and medaka) with the whole data?
4)	Another?
Any opinions on this issue will be appreciated. Many thanks for your time!
Best regards,
Anna

**Comment by mikolmogorov** [comment]
Hi Anna,

For the best assembly results, try to merge both read sets in a single assembly. It makes sense to filter out reads shorter than 1 kb, since they will not be used by Flye. Polishing with Medaka afterwards is a good idea too.

Best,
Mikhail

**Comment by a-89** [comment]
Many thanks for your answer, Mikhail!

I have tried different approaches. With the HMW assembly, I am getting 10 contigs with lengths > 2 Mb whereas when merging the two datasets I retrieved only 4 contigs with those sizes when filtering out those reads shorter than 1,000 bp and 6 contigs when filtering reads shorter than 3,000 bp. 

Would you further proceed with the HMW assembly? I would like to know your thoughts on this, thanks.

Many thanks again!!

Best, 
Anna

**Comment by mikolmogorov** [comment]
Hi Anna,

It is hard to tell without looking on the detailed assembly statistics. Simply counting the number of contigs >2Mb could be misleading. If you can provide logs of all runs and contiguity statistics, I might be able to give a better advice.

Best,
Mikhail

**Comment by a-89** [comment]
Thanks, Mikhail for your time. Find here the files:

[ALL_1000_assembly_info.txt](https://github.com/fenderglass/Flye/files/4591719/ALL_1000_assembly_info.txt)
[ALL_1000_flye.log](https://github.com/fenderglass/Flye/files/4591720/ALL_1000_flye.log)
[ALL_3000_assembly_info.txt](https://github.com/fenderglass/Flye/files/4591721/ALL_3000_assembly_info.txt)
[ALL_3000_flye.log](https://github.com/fenderglass/Flye/files/4591723/ALL_3000_flye.log)
[HMW_assembly_info.txt](https://github.com/fenderglass/Flye/files/4591724/HMW_assembly_info.txt)
[HMW_flye.log](https://github.com/fenderglass/Flye/files/4591725/HMW_flye.log)

Best,
Anna

**Comment by mikolmogorov** [comment]
Hi Anna,

Yes, it seems that HMW assembly indeed turned out to be more contiguous, even though merged assembly is a bit longer. 

Sometimes we see a lot of closely-related species and strains in a single metagenomic sample (e.g. human gut). Many related genomes overcomplicate the graph and make it more difficult to assemble. I think it is possible that HMW extraction "prunes" some parts of the metagenome, making it a bit easier to assemble organisms that are more abundant. 

Best,
Mikhail

**Comment by a-89** [comment]
Thanks for having a look, Mikhail!
