### ISSUE TITLE
how does Flye determine start of circular chromosomes/plasmids?

### ISSUE THREAD

**Issue by jmodlis** [fenderglass/ABruijn#254]
Hi, 
I am wondering how Flye determines the start of circular chromosomes?  I noticed that the start of Flye assemblies was very similar to other assemblies on the same samples created through pacbio's software, which apparently uses GC skew.

Thanks,
Jen

**Comment by mikolmogorov** [comment]
Hi Jen,

Flye currently does not do anything specific to locate the start of the circular chromosome (like replication origin) - so in general start position should be arbitrary.

Mikhail
