### ISSUE TITLE
hybrid assembly using illumina draft

### ISSUE THREAD

**Issue by ramcn** [fenderglass/ABruijn#255]
Hello,

I am trying to establish a motivation that Flye can do real-time assembly (ONT sequencing is still happening and long reads are being generated). Assuming the draft of the sample assembled using second generation reads and tools is already available before sequencing.

So tried to skip the assembly stage and resume from consensus stage using draft built from second generation read assemblers like Spades.  I tried the below set of commands and it seems to run without any issue.

1. Copy the draft assembled by spades 
cp Kp2146_spades.fasta out_nano/00-assembly/draft_assembly.fasta
2. bin/flye --resume-from consensus --nano-raw Kp2146_ONT.fastq --out-dir out_nano --genome-size 4m --threads 4

So can we say that Flye supports real-time hybrid assembly and can use draft assembled from second generation reads.

Thanks,
Ram
Thanks,
Ram

**Comment by mikolmogorov** [comment]
Hi Ram,

I don't think this is a valid way to do a hybrid assembly with Flye, as there are many potential issues. So I wouldn't claim that.

Best,
Mikhail
