### ISSUE TITLE
Output merged or removed bubble sequences.

### ISSUE THREAD

**Issue by xiekunwhy** [fenderglass/ABruijn#256]
Hi,

Can flye output merged or removed bubble sequences? Or is there a small tool or method to get bubble sequences? Bubble sequences are usefull for scaffolding using NGS mate-paired data.

Best,
Kun

**Comment by mikolmogorov** [comment]
Hi Kun,

I think the you might find the option `--keep-haplotypes` helpful - it keeps bubbles on the graph for the final assembly. Additionally, assembly_info file provides some information about alternative contigs (originating from bubbles) - please refer to the manual.

Best,
Mikhail
