### ISSUE TITLE
Fastq format error

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/ABruijn#257]
Hello,

I am trying to run the latest version of Flye on a corrected ONT dataset and Fly fails on an error very similar to https://github.com/fenderglass/Flye/issues/89#issuecomment-473574186_

Here is my error message:
```
INFO: Starting Flye 2.7.1-b1590
INFO: >>>STAGE: configure
INFO: Configuring run
ERROR: Fastq format error: /my/path/to/file.fastq at line 0
ERROR: Pipeline aborted
```

The first line of the problematic file is:
```
>242251ed-cc88-4a88-9c18-d688c16c0731
```
which seems to be a valid FASTQ record header to me. Furthermore, minimap2 didn't complain about it when I mapped the file. Any thoughts on the issue?

Thank you for your time and help.

Guillaume

**Comment by mikolmogorov** [comment]
Hi Guillaume,

This is FASTA file you have, not FASTQ. https://en.wikipedia.org/wiki/FASTA_format

Mikhail
