### ISSUE TITLE
To make scaffold -reg.

### ISSUE THREAD

**Issue by bioramg** [fenderglass/ABruijn#258]
Hi,
I have used the following commands:
./flye --nanopore-raw ONT.fastq --genome-size 1.7g -o flye_ONT
I assembled plant whole genome nanopore sequencing and obtained ~4400 contigs and the longest contig size is 373 Kb.  But, I already had contigs (the longest scaffold is ~500 Kb) which is generated by hybrid assembly of both Illumina and nanopore using spades. Also, I mapped both assembler contigs with reference mitochondrial genes and few contigs contain those genes.  I am having more than ~25 contigs which are having mitochondrial genes. When I tried to make scaffold with ONT contigs, none of the contigs are similar to spades contigs or did not generate scaffold. So, how to improve my assembly and how to make a scaffold? 
Thank you.

**Comment by mikolmogorov** [comment]
Hi,

I am not sure I understand the question. Is there something in Flye assembly process that is misbehaving?

**Comment by bioramg** [comment]
Hi,
I am not saying like that. I would like to know how to improve the assembly quality from flye.

**Comment by mikolmogorov** [comment]
Hi,

Some suggestions are described in the FAQ and other issue threads. I would be able to answer more specific questions if you have any.
