### ISSUE TITLE
de novo plant genome

### ISSUE THREAD

**Issue by hidvegin** [fenderglass/ABruijn#259]
I have got a long read raw dataset from PacBio Sequel II. The coverage is about 30x. The plant genome size is about 4 Gbp and diploid.

What is the recommended parameters for `flye` with this raw dataset. How many CPU threads and memory usage recommended?

I have got a HPC with one node. The node maximum capacity is 360 CPU core and 1.5 TB memory.

**Comment by mikolmogorov** [comment]
Please refer to the manual and FAQ for recommendations.
