### ISSUE TITLE
Conceptual: N50 increase or decrease expected between draft 00 and final assemblies?

### ISSUE THREAD

**Issue by chocotwig** [fenderglass/ABruijn#262]
Hi,

I was wondering, between the 00-draft assembly and the final corrected assemblies, should we expect a decrease in N50 in general? (Specifically wondering for reasonably large and repetitive genomes with moderate coverage.)

Thanks a lot!

**Comment by mikolmogorov** [comment]
Hi,

It can go both ways: I've seen both increase and decrease of N50, going from disjointigs to final contigs. It may be decreased for highly repetitive genomes, as the graph becomes very tangled.

Higher N50 does not always mean better assembly though.

**Comment by raw937** [comment]
Any idea why you get tons of small contigs at polishing? And, maybe what they are?

**Comment by mikolmogorov** [comment]
@raw937 it is very common for all assemblies for relatively complex organisms to have many short contigs. They can represent many different things: unresolved repeats, chimeric sequence, actual short DNA fragments that were in the sequenced library. Every assembly is be different, depending on the library, sequencing technology and organism, so there is no general explanation of what these sequences are.
