### ISSUE TITLE
Permission denied to install 

### ISSUE THREAD

**Issue by wwongwiw** [fenderglass/ABruijn#265]
I'm installing Flye from github but I got the error message during installation process. I try many times and it still be a problem.
![flye failed](https://user-images.githubusercontent.com/63127753/82350569-6f33f480-99f3-11ea-923f-83c6f4140a56.jpg)

I use Ubuntu under WSL2. I'm not sure the real problems might be the permission from window or from elsewhere. Do you have any idea or any experience to sort out the problems? 
Any comments and suggestions are welcome.

Thank you guys!!!

**Comment by mikolmogorov** [comment]
Hi,

You need root permissions to install Flye into the system. The alternatives are: (i) using without installation and (ii) bioconda package. Please refer to the installation manual for details.
