### ISSUE TITLE
Coverage calculation for pacbio data

### ISSUE THREAD

**Issue by jgarbe256** [fenderglass/ABruijn#269]
Flye works with raw pacbio data, which means for every library insert that was sequenced there will be one or more subread sequences. When Flye reports coverage numbers in log files or the assembly _info.txt file, the coverage is based on subreads, right?. When coverage is discussed in the usage and FAQ sections of the documentation is that also based on subreads?  
What do you consider to be a typical number of subreads per sequenced insert?
For example, if 40x (subread) coverage is recommended, then if I’m supplying CCS reads as input would a (ccs) coverage of 20x or 10x be equivalent?

**Comment by mikolmogorov** [comment]
Hi,

Yes, all numbers are given for subreads, which Flye treats independently.

Regarding CCS, the requirements are similar to CLR subreads. While you will get a good nucleotide consensus with much shallow CCS coverage, you still need a decent number of overlapping reads to stitch them together, which only achievable at certain coverage. We see good human assemblies with 30x coverage and insert size 10kb+, so this is what I would recommend.

Best,
Mikhail
