### ISSUE TITLE
circular question

### ISSUE THREAD

**Issue by zhaoxvwahaha** [fenderglass/ABruijn#272]
Hi @fenderglass ,

Thank you for this amazing software, I have 2 questions about the judge of chromosome circularization:
(1) The contig is circular (circ. is Y in assembly_info.txt) based on Flye, but after some polishes by such as racon/medaka/polin, the sequence is different, is the polished contig still circular?
(2) Because my data is bacteria, so they are circular generally, and if the contig(especially plasmids) isn't circular based on Flye, how can I resolve it, could you give me some advice?

Thanks in advance.

**Comment by mikolmogorov** [comment]
Hi,

(1) Circular contigs might have small indels (tens of bp) at the beginning/end, either before or after additional polishing. I would recommend to doble-check read alignnments that span over contig ends to ensure that no sequence was missed. There also some tools that can do this for you, like Circlator.

(2) This might be due to either (i) low coverage or (ii) unresolved repeat. I would recommend to look on the assembly graph to see what the reason was (you can visualize GFA output with Bandage).

Best,
Mikhail

**Comment by zhaoxvwahaha** [comment]
@fenderglass ,Thank you for prompt and helpful advice.
(1) I will use the Circlator to check whether the contig is still circular after some runs of polish.
(2) Do you have any instruction or examples for how to revise the 2 issues you mentioned above based on assembly graph? I could visualize the graph, but still have no idea how to handle it.

Best Wishes

**Comment by mikolmogorov** [comment]
Hi,

Regarding (2) - hard to give any specific instructions, as it requires some intuition about assembly graphs. I'd suggest to read some papers on that topic, this one might be a good start - https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005595

**Comment by zhaoxvwahaha** [comment]
Hi @fenderglass ,
I still have a question that, after Flye, should I polish the contig and do circlator finally, or should do circlator firstly then do polish？ I have polished my contig and did the last circlator, but I noticed on the circlator wiki page that "We recommend that the output assembly is polished using Quiver, or Nanopolish." so I'm confused about the order, could you please give some advice?

**Comment by zhaoxvwahaha** [comment]
And, Flye judge the contig is circular if the assembly graph consists of a single loop-edge, right? Don't further considered the overap information?

**Comment by mikolmogorov** [comment]
@zhaoxvwahaha I am not an active user of Circlator, so can't comment on that. Wrt to circular contigs output by Flye, they are annotated in `assembly_info.txt`.

**Comment by zhaoxvwahaha** [comment]
@fenderglass ,Yes the Flye could give the circular state of contig, which is a very nice function, but after some runs of polish, the contig is different from the original contig by Flye, so how could I judge the circular state of new polished contig, does Flye has a separate module to judge the circularization or any other tools I can used?

**Comment by mikolmogorov** [comment]
@zhaoxvwahaha Flye relies on the internal graph algorithms to classify contigs, and this could not be used separately.
