### ISSUE TITLE
Number of sequences in the assembly.gfa and assembly.fasta does not add up

### ISSUE THREAD

**Issue by Kirk3gaard** [fenderglass/ABruijn#273]
Hi

First of all thanks for an awesome tool. It is amazing to have this kind of assembly speed with this level of assembly quality.

I have been playing around with some genome and metagenome datasets with Flye and visualised the assembly graphs in bandage. I wanted to use the graph information to manually curate some of the genomes that did not form perfect circular chromosomes. However, I noticed that the number of sequences in the assembly.gfa and assembly.fasta does not add up. 

The graph:
![image](https://user-images.githubusercontent.com/4373417/83714627-9a415980-a62b-11ea-9a65-6a49200b3257.png)

The contigs in the assembly:
>contig_1
>contig_2
>contig_3
>contig_5
>contig_7
>contig_9
>contig_10

So I appear to be "missing" contig 4, 6, and 8. I extracted the sequence information of edge_4 in the gfa and found that it was present in both contig 1 and contig 2. Edge 6 and 8 seems to be included in contig 1 as well but not other contigs.

From the documentation I found:
"Five unique edges will correspond to five contigs in the final assembly."

1. Does this mean that edges without a matching contig number in the final assembly represent non unique sequence?
2. If yes, how do I get the link between edges and contigs e.g. edge_X is part of contig_Y and contig_Z

From one of the metagenomes I have the following
![image](https://user-images.githubusercontent.com/4373417/83717817-f4461d00-a633-11ea-9a6e-2f3310880d7d.png)

And would expect this to represent two strain variants of the same organism. 
Genome 1 circularised consisting of edge 2734 and edge 6583
Genome 2 circularised consisting of edge 2734 and edge 6582
Which could leave me to keep two genomes or just pick the one with the highest coverage.

3. Does it make some sort of sense to use the graph links to curate the assemblies or is it too far fetched?
4. Does flye provide information about whether contigs are circular? (Since edges!=contigs I expect that it is not trivial to extract this from the graph)
5. If yes, are does it do some trimming to ensure that overlaps are removed?

Best regards
Rasmus

**Comment by mikolmogorov** [comment]
Hi Rasmus,

1. Yes, contigs are formed by a single unique edge and possible multiply repetitive edges. If a repetitive edge in the graph is covered by at least one contig in full, it will not be output as a separate contig. In rare cases, when a repetitive edge is not covered by any contigs, it will be output as a separate sequence in the final assmebly. `.gv` graph visualization annotates repetitive edges with colors, so it could be easier to see which edges are unique or repetitive.

2. This is given in `assembly_info.txt`, in the graph path column.

3. Yes, I'd say it looks like a large variant between two related strains or species - not uncommon to see in metagenomic assemblies. In fact, metaFlye does collapse such variants when it generates metagenomic assembliy - you can prevent metaFlye from doing it by using `--keep-haplotypes` option. There is a size limit for variations that are collapsed (currently, 50kb) - so the variation that you see was most likely larger than that. It makes sense to manually select one of the branches of the bubbles as a "primary" variant and circularize the genome. But keep mind, that as a result you will get a somewhat mosaic representation of multiple strains/species in a single consensus genome, similarly to a diploid genome assembly with collapsed haplotype variants.

4. Yes, it's given in the `assembly_info.txt`

5. Yes, Flye circular contigs should have no overlaps at their ends. We've seen reports that Flye might delete small number of bases (tenths) within the circularization point, so if you are aiming for a reference-quality assembly, it makes sense to manually check read alignments in this region.

Hope this helps,
Mikhail

**Comment by Kirk3gaard** [comment]
Hi Mikhail

Thanks a lot for the fast and extremely useful reply 👍 😃 

Best regards
Rasmus
