### ISSUE TITLE
saving time with large genomes

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#274]
Hi,
I have a question/suggestion to help reduce time loss during the assembly
I am assembling a ~5 Gb plant genome on a 20 TB drive (I have some other files from other jobs too) and I run out of space during step 1-consensus. The `minimap.sam_*` were 3-8 TB and filled up my space. So after making some space I restarted with `--resume`, and Flye restarted repeating the minimap2 alignment.
I wonder if it would be possible to have flye checking better the files in the folder upon restart. E.g. if there is a `minimap.sam` file and more recent `minimap.sam_merged`, just do the sorting/merging steps (already pretty long themselves). This will help mitigating the time lost I think. Of course, it would be better that users monitor better their resources first, but I could not foresee to need 2-3x more space than the sam file size.
What do you think, would it make sense?

**Comment by mikolmogorov** [comment]
Hi,

The latest Flye 2.7 is using bam files to store alignments and should be much better in terms of storage requirements and IO intensity. You restart the existing assembly from consensus stage using v2.7, but you'll need to change `pipeline_version` parameter in `params.json` from 2 to 3.

Best,
Mikhail
