### ISSUE TITLE
lh3/minimap2 please adopt your --secondary-seq patch

### ISSUE THREAD

**Issue by smoe** [fenderglass/ABruijn#275]
Hello,

Debian Med wants to help where it can, hoping that bringing the Nanopore and associated software closer to a regular Linux distribution may attract additional eyeballs and help spread the technology.

These Linux distributions are a bit peculiar in their ambition to package every software only once and so it happened that the straight-forward attempt to reuse the distribution's package of minimap2 overlooked your [--secondary-seq contribution](https://github.com/fenderglass/Flye/commit/da64ddf12f30ec9d1cf1053dc10507391c966f06) to it.

I went through https://github.com/lh3/minimap2/pulls but did not find a respective pull request. Are you in contact with @lh3 about it? I had a look at the patch and did not find anything overly risky about adopting it for our distribution - but that would be confusing

To help finding (and recording for everyone's inspection), instead of shipping minimap2 within the lib directory you may consider forking https://github.com/lh3/minimap2 and have it as git submodule. Then, please create a pull request :o) If you are too busy but would appreciate that happening then I can do that for you.

Many thanks and regards

Steffen

**Comment by mikolmogorov** [comment]
Hi Steffen,

Yes, I am planning to submit a pull request in the near future. Will keep you posted.

Thanks,
Mikhail

**Comment by mikolmogorov** [comment]
Opened a pull request: https://github.com/lh3/minimap2/pull/687

**Comment by tillea** [comment]
I realised your pull request is marked "This branch has conflicts that must be resolved" Would you mind to revise your patch?  I'd love to package flye for Debian but it seems this issue has stalled.

**Comment by mikolmogorov** [comment]
@tillea I'm waiting for a confirmation from minimap2 developers that they are interested in adopting the patch. Then I'll be happy to update the pull request. Thanks for checking.

**Comment by mikolmogorov** [comment]
Looks like https://github.com/lh3/minimap2/pull/687 is now merged

**Comment by lh3** [comment]
Thank you, @fenderglass for the PR. I am likely to cut a minimap2 release next week after some pre-release testing.
