### ISSUE TITLE
Input sequence limit

### ISSUE THREAD

**Issue by ramsayl** [fenderglass/ABruijn#276]
ERROR: Maximum sequence limit reached (549755813888)
This is not even 50x coverage of the genome I'm trying to assemble and I have more than twice this amount of sequence to assemble. Is it possible to increase the maximum further?

**Comment by mikolmogorov** [comment]
Hi,

Currently it is a hard limit and it would be technically difficult to change it. Flye does not work well with extra large genomes in general.

Mikhail
