### ISSUE TITLE
Wrong parameters in get_consensus?

### ISSUE THREAD

**Issue by olekto** [fenderglass/ABruijn#28]
From main.py:
https://github.com/fenderglass/Flye/blob/e5b1903e5ce7fbf687b44e2c46f50587453e50e7/flye/main.py#L179-L182

From consensus.py:

https://github.com/fenderglass/Flye/blob/e5b1903e5ce7fbf687b44e2c46f50587453e50e7/flye/consensus.py#L48-L49

self.args.threads should change place with self.args.min_overlap, as far as I can see.

Thank you.

Ole

**Comment by mikolmogorov** [comment]
Crazy, but seems so.. It's fixed now, thanks for catching it!
