### ISSUE TITLE
High contamination rate contigs generated by metaFlye

### ISSUE THREAD

**Issue by jinhao94** [fenderglass/ABruijn#281]
Hi!
I work with a Nanopore human gut metagenom using `metaFlye`, followed by polishing with 4 round `Racon `+ 1 round `Pilon`. I found many contigs large than 1 Mbp,  than I estimated the completeness and contamination of these large contigs using `CheckM `. Then I got the following results:
61 contigs > 1Mbp,14 of them wiith contamination > 1% and 2 of them wiith contamination > 5%, the highest contamination is up to 43%.
![图片](https://user-images.githubusercontent.com/35567826/85940784-2146d080-b951-11ea-93e0-a7a76ceee74c.png)

In the case if `C162_contig_781_np1212_3999608`, which has 98.24% completeness and 43.70% contamination, I mapped the Nanopore reads and Illumina reads to the assembles, and only kept the unique mapped reads. Than I calculated the per-window (1000 bp) depth of  `C162_contig_781_np1212_3999608`.   The result like this:
Nanopore reads coverage
![图片](https://user-images.githubusercontent.com/35567826/85941302-b8f9ee00-b954-11ea-8016-9f80be08395c.png)

Illumina reads coverage
![图片](https://user-images.githubusercontent.com/35567826/85941329-d62ebc80-b954-11ea-9a47-fc9262ec2239.png)

As shown in the figures, the Nanopore and Illumina coverage is consistent, which rising steeply at 953000. So I cut off the contigs  at this position, then I got 
![图片](https://user-images.githubusercontent.com/35567826/85941513-1d697d00-b956-11ea-8061-25e76dd71a69.png)

My quistion is, how to deal with this issue? Any suggestions?

Thank you in advance.

**Comment by mikolmogorov** [comment]
Hi,

Typically, contamination levels below 5% (as estimated by CheckM) are considered low, and suggest that there is no chimerism. A few % contamination may be attributed to various things, e.g. noisy gene alignments, imperfections of the CheckM model or real gene duplications. Among the contigs you have shown - 611 looks borderline, and 781 definitely seems chimeric (which your coverage plots also suggest). Other contigs seem perfectly fine to me.

Having one (or a couple) misassemblies in large metagenomes is not uncommon - no assembly algorithm is perfect. We are continuously working on improving Flye (and metaFlye), but there is usually little value in investigating every single error, unless it is something systematic. I'd suggest to go ahead with cut version of the contig.

Best.
Mikhail
