### ISSUE TITLE
not getting whole structure of chromosome after flye 

### ISSUE THREAD

**Issue by sd141288** [fenderglass/ABruijn#283]
after sequencing from minion, i used the porechop, flitlong and flye. after flye i have not got full chromosome structure. below i attached a snapshot. why this happened, how to resolve this to get whole chromosome?

<img width="943" alt="Screen Shot 2020-06-29 at 4 01 45 pm" src="https://user-images.githubusercontent.com/64576919/85978539-45261700-ba22-11ea-8f77-ae081a596e75.png">

**Comment by mikolmogorov** [comment]
Hi,

The graph is showing an unresolved repeat - that means there were no reads long enough to span it. Flye thinks that it is not possible to reconstruct the whole chromosome using the provided reads.
