### ISSUE TITLE
About --keep-haoplotype

### ISSUE THREAD

**Issue by EugeneKim76** [fenderglass/ABruijn#284]
Hi all,
I have plan for assembling a plant genome which is expected to be triploid.

1. Can --keep-haoplotype be used for producing pseudo-haplotyes of triploid genome?
    
2. According to the manual, alternative contigs (representing alternative haplotypes) will have the same alt. group ID. and Primary contigs will be marked by *. In flye, how alt. group ID and primary contigs are determined?

Best,

**Comment by mikolmogorov** [comment]
Hi,

1. This option does the opposite: it keeps alternative bubble branches rather than collapsing them, thus avoiding pseudo-haplotype output.

2. The contigs within the same bubble/superbubble will have the same alt group ID. Contigs that do not belong to any bubbles are considered primary.

Best,
Mikhail

**Comment by xiekunwhy** [comment]
Hi,
@fenderglass, for those contigs with the same alt group ID, keep the longer one is OK?

> Hi,
> 
> 1. This option does the opposite: it keeps alternative bubble branches rather than collapsing them, thus avoiding pseudo-haplotype output.
> 2. The contigs within the same bubble/superbubble will have the same alt group ID. Contigs that do not belong to any bubbles are considered primary.
> 
> Best,
> Mikhail

**Comment by mikolmogorov** [comment]
@xiekunwhy depends on your assembly goals. I am assuming you are using `--keep-haplotypes` to produce more accurate haplotigs. But then, you are only interested in keeping one of the haplotypes? Selecting the longest sequences in haplotig group could be one of the strategies, but it will not guarantee that the selected contigs are phased.
