### ISSUE TITLE
'Poorer' bacterial genome assemblies following changes in Flye 4.4.0 > 4.4.1

### ISSUE THREAD

**Issue by ramjet10** [fenderglass/ABruijn#286]
This is not a critical issue but more a general observation. 

I use flye primarily for bacterial genome assemblies from raw pacbio and nanopore reads. I find the assemblies using uncorrected reads is the only way to prevent incorrect collapsing of repeats and  joining of separate replicons with large near-identical duplications. However, I noticed a while back that flye was not working as well in this regard as it previously was, not producing as many circular contigs as it used to. I thought perhaps this was just to do with the specific genomes I was looking at but then I decided to test my hunch by systematically assembling a genome using identical parameters with each of the Flye releases from 4.4.0 through to 4.7. The particular genome is an E. coli genome sequenced with nanopore (~300-fold coverage of reads >5kb and q10) and the genome has a large (15kb) duplication on two of the plasmids. Not an easy genome but somewhat representative of the sorts of genomes I get handed to me by collaborators. 

For Flye 4.4.0 the assembly produces 5 contigs, all predicted to be circular and this matches up with the molecular evidence we have for the genome.
seq_name	length	cov.	circ.	repeat	mult.	graph_path
contig_1	15111	1001	+	+	3	1
contig_2	5124720	318	+	-	1	2
contig_3	123544	126	+	-	1	3
contig_4	21306	786	+	+	3	4
contig_5	85322	156	+	-	1	5

In all assemblies carried out with Flye versions 4.4.1 > 4.7, the assembled genome is always 6 contigs. Here is the assembly info for Flye 4.4.1:
seq_name	length	cov.	circ.	repeat	mult.	graph_path
contig_1	5123715	318	+	-	1	1
contig_2	123550	127	+	-	1	2
contig_3	21310	837	+	+	3	3
contig_4	85351	139	+	-	1	4
contig_5	15082	1041	+	+	3	5
contig_6	4710	271	-	-	1	*,6,*

The other assemblies for versions >4.4.1 produce similar assemblies and never produce the same 5 circular contigs as 4.4.0. 

While I realise that less contigs is not always better, my general experience has been that for genomes with large near-identical duplicated regions that Flye 4.4.0 performs better than >4.4.1 in terms of producing all circular contigs and matching up with what we already know about the genome structure from gels etc.

**Comment by mikolmogorov** [comment]
Thanks for the information. Not sure what I can do in this case, since I don't have access to your benchmarks. 

In general, I would trust more to the latest Flye versions. Based on what you showed I can't make any conclusions that one version is better than the other.

**Comment by ramjet10** [comment]
Thanks - yeah wasn't expecting any solution just wondering if there was any insight into the parameters (especially if there was an option to select different parameters) that might have changed between 4.4.0 and 4.4.1 that could explain the difference. 
Thanks for the response.

**Comment by mikolmogorov** [comment]
The latest Flye release is 2.7.1 - can you double check the versions you are referring to?

**Comment by ramjet10** [comment]
Sorry I meant to say all release versions from 2.4.0 > 2.7.1 were tested (just had the number 4 in my head!). The change seems to be something that occurred between 2.4.0 and 2.4.1.
