### ISSUE TITLE
gfa file taking more than 30 days to write

### ISSUE THREAD

**Issue by Psy-Fer** [fenderglass/ABruijn#290]
Hello there.

Me again.
Still trying to assemble this really tricky repeat rich genome.
I'm using version `2.7.1-b1590`

Flye started writing the gfa file in the 30-contigger step on the 28th of june.
It's not the 30th of July, and it's still going. It's up to 199GB, and running on a single thread.

Any ideas when this will complete, or why it is taking so long? I was hoping the fix made would get past this.

I still maintain Flye is amazing. Thanks for all the great work.

James

**Comment by mikolmogorov** [comment]
Hi!

Hmm, I thought I've fixed the issue with long gfa generation in 2.7.1, but apparently not.. The good news is that contigs should already be generated. If you don't need gfa - you can do the following: (i) stop the run, (ii) do `touch 30-contigger/graph_final.gfa`, (iii) restart using `--resume-from polishing`. Alternatively, you can use `--polish-target` option on 30-contigger/contigs.fasta to get a polished assembly.

Could you also send me `flye.log` if possible? Might give me an idea where the bottleneck is.

Mikhail

**Comment by xiekunwhy** [comment]
Hi,

Flye v2.8.1 still need long long long time to write gfa, but for the same assembly, v2.5 implemented in masurca is very fast(~1 day to write 420Gb gfa with same threads number). By the way, the assembly generated from v2.8.1 is much worse than v2.5 using the same mega-reads as input (half reduce of N50 and contig number is twiced), which version is reliable?

Best wishes,
Kun

**Comment by mikolmogorov** [comment]
@xiekunwhy I expect newer Flye versions to do better then the older ones in general. N50 is not always a reliable measure of quality. If you can post the log files and assembly statistics from both runs - I might be able to comment more on that.

**Comment by mikolmogorov** [comment]
I believe that gfa generation issue should now be fixed in 87c9c2c  for good :) Will keep the issue open until the code makes it into a new release.

**Comment by mikolmogorov** [comment]
Should now be resolved in 2.8.2.
