### ISSUE TITLE
after conda installation version 2.7.1

### ISSUE THREAD

**Issue by dabitz** [fenderglass/ABruijn#292]
Hi,

I want to try the newest version 2.8 but after just install it with conda and checking the version, it is reporting version 2.7 not 2.8...

Best
André

**Comment by mikolmogorov** [comment]
Hi,

Uploading 2.8 to bioconda is now in process - taking a bit longer than usual. I'll post here once it's up. Once it's there, you will be able to see version 2.8 on this page - https://bioconda.github.io/recipes/flye/README.html.

**Comment by mikolmogorov** [comment]
Ok, Flye 2.8 is on bioconda now.
