### ISSUE TITLE
question regarding --subassemblies option

### ISSUE THREAD

**Issue by dabitz** [fenderglass/ABruijn#293]
Hi,

I have some question regarding the --subassemblies option:

1- When do you recommend to use this option?
2- Can I mix different assemblies generated with HiCanu, Hifiasm and HiFlye plus the set of hifi reads together, in order to increase assembly contiguity?
3- How reliable would that work? I will check anyway the mapping accuracy afterward...

Thanks
André

**Comment by mikolmogorov** [comment]
Hi,

1. This option is designed for merging multiple high-quality assemblies. Please refer to the documentation for the details.
2-3. You can mix different assemblies, but not reads. You can assemble reads first, and then merge the resulting contigs with other assemblies.
