### ISSUE TITLE
Flye2.8 pac-bio-hifi error

### ISSUE THREAD

**Issue by jliu-nj** [fenderglass/ABruijn#294]
Hi I am using Flye2.8 with some PacBio HiFi fastq file using the basic command:
flye --pacbio-hifi $run1 --out-dir EF --threads 56.

But it stopped and gave me following error ( "Overlap-based coverage: 0", root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct).

I tried to run with --meta or --asm-coverage 50 as you recommended in another Issue. But still got same error.

Then instead of using --pacbio-hifi, I used --pacbio-raw option. It gets over this error and could run forward. 

Is it okay to use --pacbio-raw on the hifi dataset? 
What is the main difference of --pacbio-hifi and --pacbio-raw option to handle the HiFi data?

Thank you!

Jie

[2020-08-11 14:04:03] DEBUG: Estimating overlap coverage
[2020-08-11 14:04:37] WARNING: No overlaps found!
[2020-08-11 14:04:37] INFO: Overlap-based coverage: 0
[2020-08-11 14:04:37] INFO: Median overlap divergence: 0.155217
[2020-08-11 14:04:37] DEBUG: Sequence divergence distribution: 

    |  |                        *                                                                        
    |  |                        * * **                                                                   
    |  |                        *******                                                                  
    |  |                        *******                                                                  
    |  |                       ********                                                                  
    |  |                      *********                                                                  
    |  |                      **********                                                                 
    |  |                      **********                                                                 
    |  |                      ***********                                                                
    |  |                      ***********                                                                
    |  |                    ************* *                                                              
    |  |                    ****************                                                             
    |  |                    ****************                                                             
    |  |                    **************** *                                                           
    |  |                    **************** *                                                           
    |  |                    **************** **                                                          
    |  |                  * *******************                                                          
    |  |                 ***********************                                                         
    |  |                 ****************************                                                    
    |  |                 ******************************   **       * *                * *                
    ----------------------------------------------------------------------------------------------------
    0%        5%        10%       15%       20%       25%       30%       35%       40%       45%       

    Q25 = 0.14, Q50 = 0.16, Q75 = 0.17

[2020-08-11 14:28:53] INFO: Assembled 0 disjointigs
[2020-08-11 14:29:20] INFO: Generating sequence
[2020-08-11 14:29:20] DEBUG: Writing FASTA
[2020-08-11 14:29:20] DEBUG: Peak RAM usage: 86 Gb
-----------End assembly log------------
[2020-08-11 14:29:32] root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct

**Comment by mikolmogorov** [comment]
@catcatzilla based on the error rate (~15%), your reads are closer to PacBio CLR, than CCS/HiFi. Therefore, using `--pacbio-raw` makes more sense.

**Comment by bishopia** [comment]
Hi, I am not getting the above error, but i have a similarly high error rate (with different spread) based on your Sequence divergence distribution, using provided CCS reads. 

In this context should flye (with --meta option) be run with subreads rather than CCS (--pacbio-raw or --pacbio-hifi)?

<img width="749" alt="Screen Shot 2021-03-14 at 10 19 37 AM" src="https://user-images.githubusercontent.com/15176325/111072528-52e8d300-84b1-11eb-97df-b99b4ab8c92b.png">

Thanks! -ian

**Comment by mikolmogorov** [comment]
@bishopia yes, that's correct.
