### ISSUE TITLE
Question regarding additional small contigs with complete bacterial genomes 

### ISSUE THREAD

**Issue by maxgmarin** [fenderglass/ABruijn#296]
Hello,

I have been using Flye to generate assemblies from PacBio (RS II, P6C4) data for bacterial genomes.

Overall, Flye has been performing great and generates completed circular genomes for a majority of my bacterial isolates.

I have a question regarding how to interpret Flye outputting a single circular bacterial genome assembly, along with a few very short contigs.

For this example, I am running Flye (v2.8) with the following command:
```
flye --pacbio-raw ${pb_subreads_fq_PATH} --out-dir ${OutputDir_PATH}  --genome-size 5m --threads ${threads} --iterations 3
```
NOTE: Flye.log attached here 
[MGM_flye.log](https://github.com/fenderglass/Flye/files/5075927/MGM_flye.log)

After running, the "assembly_info.txt" file looks like the following

```
#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_1	4406374	172	Y	N	1	*	1
contig_9	22798	114	N	N	1	*	*,9,*
contig_2	10065	67	N	N	1	*	*,2,*
contig_14	9304	77	N	N	1	*	*,14,*
contig_13	8099	49	N	N	1	*	*,13,*
contig_5	7592	39	N	N	1	*	*,5,*
contig_4	7309	52	N	N	1	*	*,4,*
contig_12	7118	46	N	N	1	*	*,12,*
```

What is the most likely explanation for the following assembly statistics?

**contig_1** is a completed circular assembly (with length and sequence content right around where I would expect).

There are additional contigs, all with relatively short lengths and lower coverage, which don't connect to any other contigs in the graph. 

I can blast these contigs and observe they contain short sequences from genomes of the organism of interest. So I believe they are in-fact real.

How would you interpret this output by Flye?

Could it be that the population sequenced is mixed to a limited degree and "**contig_1**" represents the complete consensus assembly? 

If that is the case:
1) should I interpret **contig_1** as the completed consensus assembly, while the other contigs represent minority sequences that didn't agree with the majority consensus?

2) Would you then expect using --keep-haplotypes would produce a graph that incorporates these alternative paths into the graph?

For my current purposes, I want to use a single circular assembly for my analysis (even if it has removed minority haplotypes in building the consensus).

Thank you!
- Max

**Comment by mikolmogorov** [comment]
Hi Max,

These sequences might either be artificial or indeed represent strain variation. Sometimes it's a bit difficult to tell. I suggest to try the following: 

1. First, try run Flye v2.7 on the same sample and check if the output is similar. In version 2.8, we turned off a PacBio-specific chimera filtering function, that can potentially be responsible for an increased number of artifacts.
2. Do assembly with `--meta --keep-haplotypes` (using the version 2.8). In this case, real variations should be retained on the graph.

In any case, I think it is safe to say that your current `contig_1` represents a complete consensus assembly.

Mikhail

**Comment by mikolmogorov** [comment]
Closing the issue - feel free to reopen if you have any follow-ups!
