### ISSUE TITLE
Different outputs from repeat runs? 

### ISSUE THREAD

**Issue by gettl008** [fenderglass/ABruijn#298]
I've found Flye to work great on the  yeast  PacBio reads we have! However, after repeating the  exact  same run on our samples (Flye w/ default  parameters) I've encountered some significant differences in outputs. The most striking difference is shown in the attached dotplots which show essentially a chromosomal fusion in  one run and not the other but there are other much more subtle ones. My  main concern  is  replicability. Since  there clearly is some  underlying  pseudorandomness in  the code would you be able to  create an option  to set the seed. Also it would probably save a  headache  for the next  chap who tries this  program if you provide a warning  about this aspect of the algorithm. 

[JXXY16_1.flye.1.pdf](https://github.com/fenderglass/Flye/files/5141993/JXXY16_1.flye.1.pdf)
[JXXY16_1.flye.2.pdf](https://github.com/fenderglass/Flye/files/5141996/JXXY16_1.flye.2.pdf)

**Comment by mikolmogorov** [comment]
Hi,

Thanks for reporting this, please see the discussion in https://github.com/fenderglass/Flye/issues/244. There is one multiprocessing stage which is very difficult to make deterministic, as thread scheduling can potentially affect the result slightly. The differences on your plots indeed look substantial, but from the algorithmic point of view it could be a result of a single extra connection (e.g. very small change).

Mikhail

**Comment by gettl008** [comment]
I absolutely understand how different stages of you algorithm may be difficult to make deterministic. But it is clear this can have major effects on the ultimate predicted assembly. And it is jarring to find despite reading the paper on this program and the Readme file that this can happen. As good as Flye may be at assemblies, it is hard to defend using it when its results are so stochastic and unreproducible. It is the best assembly program I've found but this is a major problem.
