### ISSUE TITLE
unassembled reads info

### ISSUE THREAD

**Issue by bresyd** [fenderglass/ABruijn#299]
Hi Mikhail,

I was wondering if the flye output also somewhere contains the information about the proportion of reads that ended up in the assembly/that could not be assembled? I am asking because following the assembly (microbial metagenome), I would like to also use all the reads that could not be assembled for downstream analysis. 

Thanks for your help

Benni

**Comment by mikolmogorov** [comment]
Hi Benni,

No, currently Flye does not have this functionality. You can map reads on the final assembly and extract the ones that do not  align in full to get a sense what is not assembled.

Mikhail
