### ISSUE TITLE
"samtools not installed" in flye2.7.1-2.8.1

### ISSUE THREAD

**Issue by estolle** [fenderglass/ABruijn#302]
Hi

I am encounering a strange error with the more recent flye versions on our Linux 16.04 Machine. I previously ran successfully flye 2.5 and 2.6, but with 2.7.1, 2.8 and 2.8.1 I am getting a weird samtools is not installed error message.

Samtools (1.10, along with htslib 1.10.2) is installed and in the PATH: 
samtools --version
samtools 1.10
Using htslib 1.10.2

But still flye says its not installed:
flye --nano-raw $ONT.fq.gz --out-dir $OUTF --threads $CPUs
[2020-09-12 13:11:26] ERROR: samtools is not installed
[2020-09-12 13:11:26] ERROR: Pipeline aborted

my old flye 2.5 still works with the same inputdata. I tried 2.6 and it also works, from 2.7.1 not. 

Any pointers what I am missing? 

Thanks 
Eckart

**Comment by mikolmogorov** [comment]
Hi,

Flye provides its own version of samtools. This message means that the flye-samtools binary is missing.

If you are using manual installation, it is very likely Flye was not properly build or installed. I suggest to use a bioconda package instead. If you choose to reinstall, make sure that there is only one version of Flye in the system.

Mikhail

**Comment by mikolmogorov** [comment]
I am assuming the issue has been resolved. Feel free to reopen if you have any follow-ups!
