### ISSUE TITLE
question about "Median overlap divergence"

### ISSUE THREAD

**Issue by longzhangnation** [fenderglass/ABruijn#303]
Hi , I have used flye2.7  to assemble several genomes ,sequenced by Sequel II ,and I find an interesting information in the flye.log file ， it shows that "Median overlap divergence: 0.160837 " and I notice that "repeat_graph_ovlp_divergence=0.10 " in the "asm_raw_reads.cfg" file . Should the  "repeat_graph_ovlp_divergence" changed as the "Median overlap divergence" or not ?

**Comment by mikolmogorov** [comment]
No, the default parameters for raw reads should not require tuning.
