### ISSUE TITLE
Final assembly has extremely short "contigs" (e.g. 1bp)?

### ISSUE THREAD

**Issue by kubu4** [fenderglass/ABruijn#304]
I ran `flye-2.8.1` on some ONT reads. The final assembly has "contigs" that are unbelievably short. Two contigs are <5bp. Eight contigs are <100bp. There are 81 contigs <500bp.

Off-hand, would you happen to have any idea what cause this? Why did these end up in the final assembly?

Here's the info file, if this helps:

- [20200917_cbai_flye_nanopore_genome_assembly/cbai_genome_v1.0_info.txt](https://gannet.fish.washington.edu/Atumefaciens/20200917_cbai_flye_nanopore_genome_assembly/cbai_genome_v1.0_info.txt)

This is my first usage of this type of assembler and it is impressively fast and easy to use! Thanks for this tool and thanks for any help.

**Comment by mikolmogorov** [comment]
Hi,

Seems strange - usually Flye should not output contigs shorter than 500bp. I think these might be artifacts of polishing - as it can trim the regions with no read coverage. Could you check the file in `30-contigger/contigs_stats.txt` and see if there are any contigs shorter than 500bp?

**Comment by kubu4** [comment]
Nothing shorter in the `contigs_stats.txt` file:

```shell
sort -n -k2,2 contigs_stats.txt | head | column -t
#seq_name    length  coverage  circular  repeat  mult  telomere  alt_group  graph_path
contig_1037  500     93        N         Y       2     none      *          1037
contig_2115  500     52        N         Y       1     none      *          2115
contig_1157  501     8         N         Y       1     none      *          1157
contig_1324  501     70        N         Y       1     none      *          1324
contig_4446  501     16        N         Y       1     none      *          4446
contig_1887  502     16        N         Y       1     none      *          1887
contig_2112  502     25        N         Y       1     none      *          2112
contig_2122  502     57        N         Y       1     none      *          2122
contig_2503  502     16        N         Y       1     none      *          2503
```

**Comment by mikolmogorov** [comment]
@kubu4 thanks - it means that some contigs were shortened during polishing due to the lack of coverage (or possible fixed structural errors). You can safely ignore those short contigs in your analysis.

Mikhail

**Comment by kubu4** [comment]
Thanks so much for looking into this and confirming! Much, much appreciated!
