### ISSUE TITLE
How to find out which contigs were excluded when using --subassemblies?

### ISSUE THREAD

**Issue by VGalata** [fenderglass/ABruijn#306]
Hello,

First of all, thank you very much for the tool!

I have some questions about the `--subassemblies` option:

We wanted to use `Flye` to merge multiple assemblies. I know that `Flye` removes short contigs but we would like to keep those in our final assembly.

Is there a way to find out which contigs were removed and were not used to build the merged assembly? Or is it better to remove short contigs before calling `Flye`? But then, would the tool use all contigs above 1kb if I set `--min-overlap` to 1000?

Thank you very much in advance!

**Comment by mikolmogorov** [comment]
Hi,

Flye will ignore contigs shorter than 1000bp, so  you may safely assume that they are not used, and you can manually add them to the final assembly. Note that if you are merging multiple assemblies, those short contigs might contain duplications.

For the contigs longer than 1kb, theoretically Flye should incorporate all of them, but there is no strict guarantees that each contig will be represented in full-length. E.g., imagine a chimeric contig that was split into multiple parts. You might try to align all input contigs on the final merged assembly to check if they align in full.

Mikhail

**Comment by VGalata** [comment]
Dear Mikhail,

Thank you very much for the detailed response!


Best,
Valentina
