### ISSUE TITLE
minimum overlap option

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#309]
Dear all,

I have basic question about **minimum overlap** parameter. I would like to clarify this parameter. According to the manual, minimum overlap parameter is used to adjust minimum overlap between reads. But as I know, it also means the minimum raw read length for assembly. Is that right?

If yes, I just curious why the parameter is not called minimum raw read length? If no, did the Flye filter the shorter raw reads before assemble the genome? 

Thank you.

**Comment by mikolmogorov** [comment]
Hi,

You are right, reads that are shorter than minimum overlap will not be used in the assembly.

Mikhail
