### ISSUE TITLE
Results diverse in different threads number

### ISSUE THREAD

**Issue by niuniumama** [fenderglass/ABruijn#310]
Hi,

Have run flye with data in both --thread -8 and --thread -1. but generate different assembly results. Would like to inquiry how the threads affect the assembly results. Thanks.  

flye --nano-raw     "$input_fastq" --out-dir "$output_folder"/flye     --genome-size 5m --threads 8     
the output Assembly statistics:      
Total length: 4897017     
Fragments: 3     
Fragments N50: 4775934     
Largest frg: 4775934     
Scaffolds: 0     
Mean coverage: 28     

flye --nano-raw     "$input_fastq" --out-dir "$output_folder"/flye     --genome-size 5m --threads 1     the output Assembly statistics:     
Total length: 4897018     
Fragments: 4     
Fragments N50: 4764882     
Largest frg: 4764882     
Scaffolds: 0     
Mean coverage: 26

**Comment by mikolmogorov** [comment]
Hi,

Please see #244. Some indeterminism is expected, but the assemblies should be very similar for the most part.
