### ISSUE TITLE
Begginner's question: difference between raw and corrected reads

### ISSUE THREAD

**Issue by MrTomRod** [fenderglass/ABruijn#311]
I have PacBio RS II data (`.bax.h5`-files) and ran HGAP on it to get standard data formats (`filtered_subreads.fastq`).

Should I use the `--pacbio-raw` or `--pacbio-corr` options in Flye? (PS: Consider adding this info to the manual.)

**Comment by mikolmogorov** [comment]
Hi,

Please use `--pacbio-raw`. Makes sense to add it to the manual - thanks for the suggestion!

Mikhail
