### ISSUE TITLE
multi-part index

### ISSUE THREAD

**Issue by jdmontenegro** [fenderglass/ABruijn#318]
Hello everyone,

I am not sure this has been adressed before, but it seems that minimap2 needs a speciel flag when using reference genome larger tha 4G for indexing. I am getting this warning in the minimap.stderr:

```
[samfaipath] build FASTA index...
[M::mm_idx_gen::121.453*1.73] collected minimizers
[M::mm_idx_gen::133.515*2.70] sorted minimizers
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::133.515*2.70] loaded/built the index for 51756 target sequence(s)
[M::mm_mapopt_update::143.602*2.58] mid_occ = 858
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 51756
[M::mm_idx_stat::147.691*2.54] distinct minimizers: 110872383 (49.60% are singletons); average occurrences: 4.949; average spacing: 7.362
[M::worker_pipeline::265.755*17.71] mapped 22344 sequences
[M::worker_pipeline::353.654*23.11] mapped 23210 sequences
```

As you can see, minimap2 suggests using the --split-prefix when there are more than 4G bases in the reference. It is also possible to increase the 4G limit in reference size to avoid using a split reference which produces incorrect MAPQ values:

`-I NUM | Load at most NUM target bases into RAM for indexing [4G]. If there are more than NUM bases in target.fa, minimap2 needs to read query.fa multiple times to map it against each batch of target sequences. NUM may be ending with k/K/m/M/g/G. NB: mapping quality is incorrect given a multi-part index.`

Is there an easy way to fix this for large genome assemblies?

Thank you,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
Hi @jdmontenegro 

Thanks for bringing this up. Indeed, looks like an issue. What is the error message that you are getting with the current version?

It seems that adding an `-I` option might be a solution - I will try to work on testing it in the near future. In case you don't want to wait, you can try adding `-I 12G` to the minimap2 command line at `flye/polishing/alignment.py line 225`.

**Comment by jdmontenegro** [comment]
Hi @fenderglass ,

Thanks for the reply. The current version finishes correctly despite this error, but it would be a good idea to add a few conditional statements before every mapping stage in the flye pipeline in order to adjust the index creation step in minimap2 for genomes larger than 4Gb and to ensure the reads get the correctly mapped.
I think it would be needed before:
1. consensus
2. repeat graph
3. polishing

I think those are all the instances minimap2 is used in the pipeline. Would that be correct?

Cheers,

Juan D.

**Comment by mikolmogorov** [comment]
Hi @jdmontenegro 

Ok, if the current pipeline does work correctly, why making a change? This minimap2 warning says that certain tags in sam output will not be generated, which should not be an issue in general.

Mikhail

**Comment by jdmontenegro** [comment]
Hi @fenderglass,

Although it is not clear from the minimap2 manual or issues page, this is what happens with the current code:

1. References longer than the default (4G) will be indexed on the fly into multipart indices
2. Reads are aligned to the indices in parallel, but the aligner is not aware they need to keep all the hits in all the parts of the index. This produces inaccurate mappings which may impact downstream analysis based on those alignments (bubble solving, polishing, repeat correction).

If we add the flag --split-prefix as suggested by minimap2 in the minimap2.sdterr file this will happen:
1. One top alignment will be written for every part of the index. MAPQ will be incorrect and removing the incorrect alignments will be non-trivial
2. no CS, MD or AS tags will be written in the output file

If we increase the indexing size with (e.g. -I 12G), this will happen:
1. Reference will be indexed in a single chunk, but will need more memory to map the reads
2. MAPQ will be correct and CS, MD and AS tags will be written to the output file.

That is why I suggest checking for the size of the reference before every mapping stage and choose the right reference size to avoid the problems related with incorrect mapping (when no --split-prefix is used) or incorrect MAPQ values (when using --split-prefix).

Cheers,

Juan D.

**Comment by mikolmogorov** [comment]
@jdmontenegro,

Ok, it makes sense now. Thanks a lot for digging into this. I will add the fix with an `-I` option shortly.

Mikhail

**Comment by mikolmogorov** [comment]
Added `-I 64G` to the minimap2 command line (8351991) - should fix the issue for the foreseeable future. Thanks again!
