### ISSUE TITLE
ERROR: No contigs were assembled - are you using corrected input instead of raw?

### ISSUE THREAD

**Issue by timometz** [fenderglass/ABruijn#32]
I am getting the above mentioned error: "ERROR: No contigs were assembled - are you using corrected input instead of raw?"
even though I am running flye with the --pacbio-corr option. I am running it like this:
flye --pacbio-corr /path/to/Corrected/*.fasta --genome-size 200m -o /path/to/Pacbio/ -t 15

do I need to provide the uncorrected as well? I though I could run it also just with corrected reads.

kind regards

**Comment by mikolmogorov** [comment]
Hi,

Do you know what is approximate error rate of the corrected reads? The current corrected reads settings are tweaked ~1% or less. I would try to run with raw reads and see how it works. Also, what is the mean read length of the dataset (and chemistry version)?

If you can send me the log file, I should be able to tell more about what might be the cause.

**Comment by timometz** [comment]
Thanks a lot for your reply. PacBio reads have been corrected with LoRDEC but unfortunately I do not know the error rate. However, I was running now with raw reads and got exactly the complement error saying: "are you using corrected input instead of raw?"

Attached is the log file of the raw run.
[raw_flye.log](https://github.com/fenderglass/Flye/files/1645731/raw_flye.log)

**Comment by mikolmogorov** [comment]
What is the expected coverage and read length of the dataset? According to the log, the coverage is 1x, and the mean read length is 1600, which is not enough for the whole genome assembly. On the other hand, it looks like there is ~18mb of unique sequence, not 200mb, so maybe the expected genome size is incorrect?

**Comment by timometz** [comment]
Thanks for your advice, totally my mistake. Using genomee size 18m instead
of 200m resolved the problem ! Thanks so much.

2018-01-19 20:03 GMT+01:00 Mikhail Kolmogorov <notifications@github.com>:

**Comment by mikolmogorov** [comment]
Glad that it helped!
