### ISSUE TITLE
processing multiple fastq files

### ISSUE THREAD

**Issue by ponomarevsy** [fenderglass/ABruijn#321]
Dear Flye Developers,

Is there an easy way to process multiple fastq files? Say we have ~1000 *.fastq files... what would the Flye command look like in this case (do we run Flye for each file separately or can we use multiple *.fastq files in one command)?

The program will be used on a HPC cluster but it looks like it is tuned-up for running on a single workstation with multiple cpus (does it support MPI?). What would you suggest?

Thank you in advance!

**Comment by mikolmogorov** [comment]
Hi @ponomarevsy 

You can provide any number of files as input, but it is typically limited by the OS maximum command line length. Because o the you might need to merge the fastq files into one/few files.

Mikhail

**Comment by DaRinker** [comment]
Just to clarify, providing multiple fastq files as input will still result in only one assembly out, correct?
