### ISSUE TITLE
Question about polishing parameter training

### ISSUE THREAD

**Issue by mwykes** [fenderglass/ABruijn#323]
Hi @fenderglass, 
Firstly, thanks for all your great work on Flye! 
I've recently been looking at R10 ONT assemblies and realised that the final Flye polishing step uses parameters trained on R9 so wondered if I might get an even better result with R10-specific parameters. I saw that the method is explained in the [ABruijn paper](https://www.pnas.org/content/pnas/113/52/E8396.full.pdf). Do you have some scripts which you could share to retrain the parameters from a reference sequence and reads?

**Comment by mikolmogorov** [comment]
Hi @mwykes,

Sure, it might make sense to retrain the model with the newest data. I attach the scripts that we used - they take sam alignment and a reference file as input. Not that currently homopolymer-based correction is disabled (we found that it rarely makes any improvements on new types of data). So you'd only need to retrain substitutions.mat files. Please let me know if you have any questions.

[flye_train_polisher.zip](https://github.com/fenderglass/Flye/files/5661048/flye_train_polisher.zip)

Mikhail

**Comment by mwykes** [comment]
Hi Mikhail,

Apologies for the slow reply and thanks for sharing those, they were indeed useful.

Mike
