### ISSUE TITLE
order assembly

### ISSUE THREAD

**Issue by aspitaleri** [fenderglass/ABruijn#324]
Hi,
I have been using flye to assemble circular bacteria genome (4.4Mb) and using pilon to polish them. This is a general question probably not an issue (I hope). I got from flye the circular chromosome directly. Then I blastn it to the reference genome and from the dotplot I see a nice diagonal from bottom right to up left, so basically it means that my assembly order is on the opposite with respect to the reference. I guess that this is normal since flye (any assembler) does not know where the chromosome starts, isn't? Then, is there any approach to reverse my assembly in order to make it ordered as the reference?
Best

**Comment by mikolmogorov** [comment]
Hi,

Typically, bacterial references start at the origin of replication. Flye does not check for this. I believe Circlator (https://github.com/sanger-pathogens/circlator) can "normalize" the assembly for you.

Mikhail
