### ISSUE TITLE
Question: Base quality/coverage scores?

### ISSUE THREAD

**Issue by davised** [fenderglass/ABruijn#325]
Thanks for this great software.

Is there any plan to implement either:

1. Per-base coverage output
2. Per-base quality score estimation

I run the flye assembler on pacbio reads that we generate for users at our University, and I've had some requests for these features as the Pacbio HGAP4 assembler produces these types of metrics.

I believe it would be trivial to get the per-base coverage from one or more of the intermediate minimap alignments. Determining a quality score estimation would likely take more thought/work.

I can run minimap on my own at the end to get the per-base coverage for now, but maybe if there is an option to save a bam alignment either from the consensus or polishing steps, that would reduce computational time. I took a look at the code and I think I see where the os.remove(bam) is called for this, so I could maybe even add it myself.

Do you have any thoughts? I understand if this isn't high priority.

**Comment by mikolmogorov** [comment]
Hi @davised, 

Flye currently outputs mean coverage for the contigs. The problem with per-base coverage is that the sequence is modified during polishing, therefore coordinates may shift and some read mapping positions can change too. The most accurate way therefore would be to align reads again and the compute coverage using samtools. I don't think it makes sense to add this functionality directly to Flye, since it seems a bit beyond the basic assembly functionality.

Mikhail

**Comment by gushiro** [comment]
@fenderglass should the coverage per contigs needs to be close to the expected coverage of the sequencing? I have ~90Gb for a genome size of 2.5 (highly heterozygous: ~3.5%, and with low repetitive content: ~8%) and the coverage per contigs range between 7 to over 100 (max 9000).  I wonder if I should do any filtering based on coverage here??

**Comment by mikolmogorov** [comment]
@gushiro you can use `--meta` for genomes with highly variable coverage.

**Comment by gushiro** [comment]
@fenderglass thanks. I have not read the literature yet about uneven coverage. Do you know the reasons? I wonder if it is a technical problem or common for certain clades. I known for meta genomes it is common due to different strains but mine is a marine invertebrate.

**Comment by gushiro** [comment]
@fenderglass in general, should I worry or do more analysis for contigs with coverage very far from the mean? I got 4000 max coverage but a mean of 12. Also, around 500 of my contigs has a coverage over 100.

**Comment by mikolmogorov** [comment]
@gushiro some contigs may represent genomic repeats, which have high coverage. Low coverage contigs may represent heterozygous/mosaic alleles, assembly artifacts or contamination.
