### ISSUE TITLE
Possibilities of Reassembly too many metagenomic NGS-assembled short contigs with Flye 

### ISSUE THREAD

**Issue by neptuneyt** [fenderglass/ABruijn#326]
Dear Mikhail,
I am very interested in your discussion with [Bernhard's issue](https://github.com/fenderglass/Flye/issues/197). At the same time, I have a similar problem. I have many Illumina paired-end 150bp metagenomic sequences. Using megahit to assemble many short contigs 500bp-3k bp (accounting for > 90% of the total assembly contig numbers).
- Q1: so I wonder if Flye can be used to reassemble these fragments (or combined with longer than 3k long contigs), does it make sense？In fact, I have done a test and the results are as follows:
command:
```bash
flye --subassemblies Megahit_assembly/A_Megahit.fa Megahit_assembly/B_Megahit.fa --threads 40 --meta  --min-overlap 1000 -o TGS_assembly/
```
Sample | Clean base(Gb) | ≥3k | ≥3k (%) | ≥5k | ≥10k | ≥20k | ≥30k | ≥40k | ≥50k | ≥100k | ≥150k | ≥200k | Contigs number | Size | Min | Max | Avg | N50
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
A | 23.16 | 37575 | 3.36 | 12515 | 2433 | 485 | 203 | 113 | 55 | 10 | 3 | 0 | 1117940 | 1169680655 | 500 | 193635 | 1046 | 1080
B | 32.13 | 40707 | 3.39 | 14119 | 3184 | 788 | 308 | 165 | 96 | 19 | 5 | 1 | 1199364 | 1252382137 | 500 | 203031 | 1044 | 1080
FLYE_meta_A-B_Megahit   Assembly | - | 66884 | 11.66 | 24147 | 5438 | 1251 | 508 | 256 | 148 | 32 | 13 | 2 | 573736 | 1148709708 | 500 | 303986 | 2002 | 2011

and ,we can see Flye meta model (--meta) can  truely increase the short contigs using rate (from 3.36%, 3.39% to 11.66%),and the same as doubled N50(from 1080 to 2011). 
 
How do you evaluate this result? Is it possible that the extended segment is incorrectly assembled? Do you think this approach is reasonable? 

- Q2: Another question is, if the above method is feasible, when I assemble a large genome, I am prompted that there is not enough memory. Is there any way Flye can reduce memory overhead?
>input contig size ：25Gb
>memory: 500 Gb
>core: 128

Thank you from the bottom of my heart! Looking forward your reply!

_Originally posted by @neptuneyt in https://github.com/fenderglass/Flye/issues/197#issuecomment-741629740_

**Comment by mikolmogorov** [comment]
Hi,

1. There is no single "right" way to evaluate metagenomic assembly, so hard to give a general advise here. You can read about some approaches we used in the metaFlye paper: https://www.nature.com/articles/s41592-020-00971-x

2. Currently, no way to decrease RAM usage unfortunately. Flye/metaFlye was not designed for assembly of very big genomes (e.g. 5G+).

Mikhail
