### ISSUE TITLE
Linear genome with terminal repeats

### ISSUE THREAD

**Issue by snayfach** [fenderglass/ABruijn#334]
Hello - thanks for the great tool. I'm using flye to assemble metagenomic reads and identify viral genomes. Looking at my results, I see quite a few circularized viral genomes, which is good. However, some viruses have linear genomes with a repeated sequence of a few hundred bases at the start / end of the genome. How does flye handle these kinds of sequences? Will the sequence be classified as circular? Will the terminal repeat be preserved or removed from the end of the contig?

**Comment by snayfach** [comment]
I simulated 100x nanopore reads from a 50 kb linear viral genome with 50-bp terminal repeats using [badread](https://github.com/rrwick/Badread/issues). After assembling with meta flye, the full linear genome was reconstructed, along with the repeats at the end of the sequence. The sequence was not classified as circular.

**Comment by mikolmogorov** [comment]
Sorry for the late response. As you have found, terminal repeats up to several hundreds basepairs should not be a problem - metaFlye usually considers repeats at least 1kb in length. In our analysis, we saw a couple examples of viral genomes that had 1 kbp+ repeats (inexact), and this resulted into a false join. But in my understanding such cases are quite rare.

**Comment by snayfach** [comment]
Thanks for the reply. What do you mean by false join? Are you saying this would be reported as a circular contig with the repeat removed?

**Comment by mikolmogorov** [comment]
If it is a single virus, it could be potentially reported as a circular contig. A single repeat copy will be somewhere in the conitg in this case. If there are multiple viral genomes sharing same long inexact repeat, then they theoretically could be falsely joined - but I think this is an unlikely scenario.
