### ISSUE TITLE
Anyone Assemble Genome >3.0 Gbp?

### ISSUE THREAD

**Issue by cement-head** [fenderglass/ABruijn#335]
Has anyone assembled a genome larger than 3.0 Gbp using FLYE yet? 

If so, how big and how long did it take (real time)?

Also, how long did the assembly for the human take (real time/wall time)?

**Comment by mikolmogorov** [comment]
There are some reports from users how assembled genomes of size 5Gb+ in the issues section, and theoretically there is not limit for bigger genomes, except for the RAM usage. Some results on the human genomes are given in the Usage document.
