### ISSUE TITLE
long run time for plasmid stage with bonito calls

### ISSUE THREAD

**Issue by jagos01** [fenderglass/ABruijn#338]
Hello,
I am assembling a nanopore run with Flye_v2.8.2-b1689.  When the reads have been basecalled with Guppy_V4.4.0, assembly with the following command takes 7.45hr.

flye --nano-raw guppy4.4.0_reads.fastq --out-dir /Analyzed_data/flyev2.8.plas.asm-cov50 -t 40 -i 0 --plasmid -g 5.4m --asm-coverage 50

When the reads have been basecalled with Guppy_v4.4.0 using bonito_v0.3.2 research model, assembly with the same command is taking much longer, particularly in stage: plasmids.  The bonito assembly was started on 2021-01-13 12:27:15 and has not completed yet. I have also noticed that this stage is mostly using a single thread (40 when minimap is running).  Is the extended run time expected with Bonito calls?  Should this stage be using more threads when specified?  The reads were filtered to 700mb with Filtlong.  I have attached flye.log
  
[flye.log](https://github.com/fenderglass/Flye/files/5823453/flye.log)

Any help would be appreciated.
Thanks,
Scott

**Comment by mikolmogorov** [comment]
Hi Scott,

It is definitely unexpected. I looked through the log and it seems that ~30% reads were not mapped to the assembly, which is surprising for a single organism assembly. It is possible that there is a fair amount of "artificial" reads (that do not actually encode any biological sequence). This might confuse the plasmid module and substantially increase running time.

I would simply try to drop the `--plasmid` option. You can instead try to use `--meta` - it should help to assemble any sequence with unusually high/low coverage (like plasmids).

**Comment by jagos01** [comment]
Hello Mikhail,
I have tried assembly with the default settings and with --meta flag.  Unfortunately in both cases the smaller plasmid fails to assemble.  Even with the --plasmid flag, the small plasmid is assembled as multimers (dimer/trimer) depending if the data is filtered or not.  Would it help if the reads we sub-sampled to a lower coverage before assembly?
Thanks for your help,
Scott

**Comment by mikolmogorov** [comment]
Interesting! What is the size and coverage of the plasmid? I am assuming its length is comparable to read size? Could it then be that ~30% of reads cover this single plasmid?

Downsampling will certainly help to speed things up for the plasmid module.

**Comment by jagos01** [comment]
The size of the plasmid is 12.4kb.  Coverage reported by assembly_info.txt is 

#seq_name	length	cov.	   circ.	repeat	mult.	alt_group	   graph_path
contig_1	      5224248	177	    Y	           N	          1	              *	                 1
contig_2	      181513	446	    Y	           N	          2	              *	                 2
contig_3	      24424	815	    Y	           N	          4	             *      	         3

When mapped to a reference, qualimap reports

Name        Length      Mapped bases  Mean coverage 
contig_1   5229965     1020243579            195.07 
contig_2   181642           85490060            470.65 
contig_3   12489           317612263       25,431.36

The mean read length of the filtered reads is 25kb (10kb for unfiltered) and ~30% of the reads map to the plasmid.  Any thoughts on how to recover the monomeric plasmid.
Thanks again for your help.
Scott

**Comment by mikolmogorov** [comment]
Ok, so it indeed seems that the plasmid has huge coverage and ~30% of all reads are from the plasmid.

There is a slightly modified version of Flye that might help - the code is currently in `short_disj` branch. I think it might make sense to try it on a downsampled set of reads (using `--meta`, but not `--plasmid`). I think even if you take ~1% of the read data, the plasmid should be recovered. Note that you'd need to build Flye manually from source - let me know if you have any issues with that.

**Comment by jagos01** [comment]
I tested a range of read coverage using the short-disj branch (10x-200x coverage based on 5.4Gb genome) with the --meta flag.  Unfortunately the 12.4kb plasmid was not assembled into a single circular contig.  
- 10x coverage resulted in 47 contigs, none of which mapped to the 12.4kb plasmid. The 181kb plasmid assembled as a single circular contig.  
- 30x coverage resulted in 5 contigs with none mapping to the small plasmid.  The 181kb plasmid assembled into a single circular contig.
- 50x and 60x coverage resulted in 4 contigs. A 3.5kb fragment mapped to the small plasmid and the again the 181kb plasmid assembled into a single circular contig.  
- 80x coverage resulted in 5 contigs, two 3.4kb and one 3.8kb fragment mapped to the small plasmid.  Both the 5.2mb chromosome and 181kb plasmid assembled as single circular contigs. 
- 100x coverage resulted in 6 contigs, three 3.2kb and one 3.6kb fragment mapped to the small plasmid.  Both the 5.2mb chromosome and 181kb plasmid assembled as single circular contigs.
- 200x coverage resulted in 10 contigs 8 of which mapped to the small plasmid (~27kb combined size).  Both the 5.2mb chromosome and 181kb plasmid assembled as single circular contigs.
I also ran regular flye with  --meta and --meta --plasmid at 30x coverage.
with --meta, 2 contigs were assembled, the 5.2mb chromosome and 181kb plasmid.
with --meta --plasmid all 3 contigs were assembled as single circular contigs of the correct size.  At the reduced coverage the assembly with --plasmid only took 40 min.
Are there any other options to run with the short-disj version that might assemble the 12.4kb plasmid?
Thanks for you help,
Scott

**Comment by mikolmogorov** [comment]
Thanks for the detailed benchmark! It seems like the plamid does not relally want to assemble without `--plasmid` option.

So I think in this case downsampling + `--meta --plasmid` is the preferred configuration - no need to use `short_disj` version. The performance is indeed an issue, but you also have a very unusual case when a lot of reads are coming from a single short plasmid.

Mikhail

**Comment by jagos01** [comment]
Thanks for all your help.
Scott
