### ISSUE TITLE
Any plans for supporting gfa format for assembly graphs?

### ISSUE THREAD

**Issue by lfaller** [fenderglass/ABruijn#34]
Hello all,

I've been trying to assemble some small microbes with flye and so far the results look very encouraging!

I'm used to looking at assembly graphs with [Bandage](http://rrwick.github.io/Bandage/). Do you have any plans for providing gfa-formatted assembly graphs in the near future?

Cheers,
~Lina

**Comment by mikolmogorov** [comment]
Hi,

The gfa graphs are actually there, you can find them in the "2-repeat" folder. "graph_before_rr.gfa" / "graph_final.gfa" correspond to the graphs before / after repeat resolution.

Best,
Mikhail

**Comment by lfaller** [comment]
Ah, that's great -- thank you for clarifying! I only saw the *.dot graph file.
