### ISSUE TITLE
(Beginner) Unable to polish Canu assembly with Flye

### ISSUE THREAD

**Issue by rongji84** [fenderglass/ABruijn#342]
Hi, I'm very new to genome assembly workflows and Linux command lines so I might have missed something really basic. I'm trying to polish my Canu assembly in Fasta format with the raw Pacbio fastq file but it returns an error when it's trying to run Minimap2. I have attached the error log. Thank you for your time
[flye.log](https://github.com/fenderglass/Flye/files/5865695/flye.log)

**Comment by mikolmogorov** [comment]
Hi,

One of the directories on the paths to your reads contain spaces - which is causing the error. Renaming the directory / moving reads file should fix the issue. I will add a warning to the future releases.

**Comment by rongji84** [comment]
It worked. Thank you!
