### ISSUE TITLE
Question: Oxford Nanopore Reads input after calling with Bonito

### ISSUE THREAD

**Issue by ter56** [fenderglass/ABruijn#343]
Question: After using ONT-Bonito to call our reads we have an approximate error rate of 4%. Which flag would be most appropriate to specify error rates: the `--nano-raw` or the `--nano-corr`?

**Comment by mikolmogorov** [comment]
Please use `--nano-raw`. `--nano-corr` assumes about ~1-2% error rate. Plus, Bonito basecalls typically still a have a heavy tail of reads with error well above 4%

**Comment by ter56** [comment]
Thank you - and thank you for the quick reply.
