### ISSUE TITLE
edges with tandem repeat?

### ISSUE THREAD

**Issue by dikshyantg** [fenderglass/ABruijn#344]
Hi , The .gfa output from file gave big visualization of different contigs. I have question about my chromosome contig which I have attached here. It looks like a tandem repeat is present at the edge and I don' t think I have a read to span it and resolve it.  The chromosome  looks like it isn't  complete/ circular. Would you be able to help me verify ? 

<img width="354" alt="Screen Shot 2021-01-26 at 1 30 07 PM" src="https://user-images.githubusercontent.com/46819356/105895635-5f859a80-5fdb-11eb-81eb-47be156d8d66.png">

**Comment by mikolmogorov** [comment]
Yes, I think your interpretation is correct - looks like a single unresolved tandem repeat. 

Alternatively, it might also be a structural variation between two bacterial strains (a large insertion) - in case you suspect there might be heterogeneity in your sample.
