### ISSUE TITLE
Problem installing newversion of flye

### ISSUE THREAD

**Issue by dikshyantg** [fenderglass/ABruijn#345]
Hi , I had a previous version of flye 2.6 and wanted to install the newest version 2.8 above. I tried the conda install option and installed it. When I tried to run flye I am getting following error
Traceback (most recent call last):
  File "/home/dikshyant/anaconda3/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.8.2', 'console_scripts', 'flye')())
  File "/home/dikshyant/anaconda3/bin/flye", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

**Comment by mikolmogorov** [comment]
Very likely something is wrong with the bioconda environment. I think installing into a new clean environment should fix the problem.

**Comment by mikolmogorov** [comment]
Closed due to inactivity - feel free to follow-up if the problem is not resolved.
