### ISSUE TITLE
flye: error: the following arguments are required: -o/--out-dir

### ISSUE THREAD

**Issue by jdobry-lab** [fenderglass/ABruijn#346]
I am a beginner and trying to get this to work so that I can play with the sample data.  Not sure what is going on here.

usage: flye (--pacbio-raw | --pacbio-corr | --pacbio-hifi | --nano-raw |
	     --nano-corr | --subassemblies) file1 [file_2 ...]
	     --out-dir PATH

	     [--genome-size SIZE] [--threads int] [--iterations int]
	     [--meta] [--plasmids] [--trestle] [--polish-target]
	     [--keep-haplotypes] [--debug] [--version] [--help] 
	     [--resume] [--resume-from] [--stop-after] 
	     [--hifi-error] [--min-overlap SIZE]
flye: error: the following arguments are required: -o/--out-dir

This is what I got after following the installation instructions.  Please advise

**Comment by mikolmogorov** [comment]
@jdobry-lab this is the expected output from calling `flye` with no arguments - it provides brief usage instructions. 

What are you trying to accomplish here and what is the output you expect? The manual provides example command lines to run Flye on test datasets.
