### ISSUE TITLE
Building repeat graphs from assembled genomes

### ISSUE THREAD

**Issue by devonorourke** [fenderglass/ABruijn#347]
Hi Flye developers,
I have a problem that I think Flye might be a great solution for. I have a handful of genomes from different related mammalian species. Let’s say they are all chromosome-length assemblies, and all are from organisms that share a common ancestor in the last 10-20 MYA. 
My goal is to find the shared regions, while identifying where major differences exist. Certainly there are other alignment tools to tackle this problem, but I was curious if Flye might be up to it talk. In particular, I was wondering if by breaking down the assemblies into long (pseudo?)reads, maybe Flye could provide a graph of some sort that indicated where the species specific differences are most evident .
Related to this challenge, it would be great to map the original coordinate of the reference assembly with the graph position, and I think that can be done by including it in the fasta header?
Very grateful for any tips and tricks.
Cheers,
Devon

**Comment by mikolmogorov** [comment]
Hi Devon,

Yes, it is possible to construct a graph from (multiple) assemblies - and this might indeed work to help identifying major structural differences. 

The code is currently in the separate `flye-repeat` branch: https://github.com/fenderglass/Flye/tree/flye-repeat. You will need to compile it from source, as it is not a part of the release (yet).

After compiling (using `make`), run `scripts/build-repeat-graph`. You can specify minimum alignment length and identity that are used to build the graph. In addition, there are several alignment modes: "dovetail" (only use end-to-beginning alignments between input sequences), "local" (all alignments) and "semi", which is a mix between the first two modes (alignment should be at the end in at least one of the sequences, but not both). 

Let me know if that works for you, or if you have any questions.

Mikhail

**Comment by mikolmogorov** [comment]
In case there are no follow-ups, I am marking this resolved. Feel free to post here if there are any new questions.
