### ISSUE TITLE
threading across mulitple nodes

### ISSUE THREAD

**Issue by Imoteph** [fenderglass/ABruijn#35]
Hi
Just reading in and I was wondering about this question.
Does Flye expect all open threads to be on the same node? The question is going if I can Flye threads to be spread around multiple nodes sharing a common filesystem?

kind regards

**Comment by mikolmogorov** [comment]
Hi,

Yes, the current implementation was designed to run on a single node. Cluster configuration is something that we consider for the future releases.

**Comment by Imoteph** [comment]
Thx, for answering. Do you actually know when a possible future release is to be expected ;)

**Comment by mikolmogorov** [comment]
Hard to tell, it is not a priority currently. Are you having issues with a particular dataset/configuration?

**Comment by Imoteph** [comment]
Not yet, I guess. I am exploring repeat aware assemblers for plant genome assembly and as I have a huge dataset I thought of an comparison internal here with canu, where I know how to scale through the cluster.

I have another comment, but I will open a new issue for that
