### ISSUE TITLE
Error: system ran out of memory

### ISSUE THREAD

**Issue by aliphatic1** [fenderglass/ABruijn#350]
[flye.log](https://github.com/fenderglass/Flye/files/5921595/flye.log)

Provided above is the log file for the failed run.

When running Flye on --meta setting for 13gb worth of reads, the program stops after attempting to build tables and gives the "Error: looks like the system ran out of memory" line. I'm fairly new to the world of bioinformatics, so I don't exactly know what is going on. Obviously enough RAM is allocated to Flye--the one thing I'm concerned about though are allocated threads. I tried Canu with the same specifications, and received a similar error message concerning the requirement of 8 threads. I'm running an Intel I5 processor, and I'm worried it may not be enough.

If the processor is the issue, would there be a way to run Flye on batches of fastq files and run those product files through Flye again? If not, what am I missing?

~L

**Comment by mikolmogorov** [comment]
Flye ran out of memory - you will likely need more than 32 Gb RAM for 13Gb of reads. If it is a single genome (not a metagenome), you can try to use `--asm-coverage` option to reduce the memory consumption (as described in the manual). Some insights wrt to memory consumption estimation are in the FAQ.

Mikhail

**Comment by Kirk3gaard** [comment]
Hi Mikhail

Do you have some rule of thumb for calculating the needed RAM for a metagenome? e.g. RAM usage = X Gbp reads * k 

Best regards
Rasmus

**Comment by mikolmogorov** [comment]
@Kirk3gaard there are some insights in the FAQ/Manual wrt to RAM usage of a single genome. It is more complicated for metagenomes, since the coverage of each bacteria is highly uneven. Plus, the repeat complexity and heterogeneity plays a role. So in short, it is proportional to read size and could be estimated from similar runs, but I don't have an exact formula.

**Comment by mikolmogorov** [comment]
Since there are no follow-ups, I'm marking this as resolved. Feel free to post here if you have more questions in the future.
