### ISSUE TITLE
Flye does not assemble short amplicon data

### ISSUE THREAD

**Issue by RemiMaglione** [fenderglass/ABruijn#352]
Hello Flye team,
Wanted to try Flye on my new Nanopore data. It's multiple ~550-750 amplicon sequence and I just want to get a consensus. 
I installed flye with the github approach (wget/make) and I ran the flye_toy_test without any issue. 

Here's the command I used:
`nano_dir="/var/lib/minknow/data"`
`project="HGI-FNP1"`
`project_dir=${nano_dir}"/"${project}`
`BASECALLS=${project_dir}"/M1_1/M1_1.fastq"`
`threads=15`
`mkdir ${project_dir}"/draft"`
`draft_dir=${project_dir}"/draft"`

`flye \`
`--nano-raw \`
`${BASECALLS} \`
`--out-dir ${draft_dir} \`
`--threads ${threads}`

M1_1.fastq has 39276 sequences. I'm running flye 2.8.2-b1695 on a 9900K Intel CPU (16 threads) with 32Go RAM.

Here's the log: (EDIT: see Attached log instead)
[flye.log](https://github.com/fenderglass/Flye/files/5959863/flye.log)

Any help will be welcome

**Comment by RemiMaglione** [comment]
I also ran flye --nano-raw Loman_E.coli_MAP006-1_2D_50x.fasta --out-dir out_nano --threads 15 without any problem.

TO DO: try to assemble my data as .fasta input instead of .fastq
EDIT: .fasta input also failed. I saw that my sequence name differ from the Loman data: I have space between words where Loman have underscore.

TO DO2: fix sequence name
EDIT2: still fail after changing every character to _ (I now only have letter, digit and underscore on my seq)  

TO DO3: Tried another assembler (spades)
EDIT3: Spades failed with error saying that there's an issue with not even kmer distribution. My current test file has only one amplicon.

TO DO4: Try to assemble a file with multiple amplicons
EDIT4: Spades successfully assemble a mixed amplicons file but Flye still send me the same error message 

TO DO5: don't know what to do at this stage

**Comment by mikolmogorov** [comment]
Hi,

Flye was not designed to assemble very short sequences, unfortunately. It looks like in your case there were no (or almost no) reads longer than 1000 bp, that is a required minimum. In you case you probably don't need to assemble though, as reads probably cover your fragment in full. You may simply need to call a consensus using Racon or (standalone) Flye polisher.

Mikhail
