### ISSUE TITLE
Relative paths to reads cause minimap2 error on some systems

### ISSUE THREAD

**Issue by rckeerthivasan** [fenderglass/ABruijn#354]
I have been getting an error in consensus when I try to assemble the genome of a normal human cell-line. So, I tried with the example nanopore data-set provided. Same error!! I have the latest version 2.8.3-b1695. 

Command used: flye --nano-raw Loman_E.coli_MAP006-1_2D_50x.fasta --out-dir out_nano --threads 8 
Log file attached here -> [flye.log](https://github.com/fenderglass/Flye/files/5970120/flye.log)

**Comment by mikolmogorov** [comment]
This seems strange - could it be that you have any file system restrictions? Do other assemblers work for you on this machine? The terminal output that you sent suggests that Flye successfully assembled the initial disjointig set, minimap alignment of reads against the disjointigs was empty.

Could you post the full log files from both runs (not the terminal output)?

**Comment by rckeerthivasan** [comment]
Hi, 

Thank you for the reply. Yes, other assemblers work. I have successfully executed multiple assemblers. I am attaching the log files 
[flye.data1.log](https://github.com/fenderglass/Flye/files/6000029/flye.data1.log)
[flye.test.log](https://github.com/fenderglass/Flye/files/6000030/flye.test.log)

Let me know if you wanna know any other details. 
Thank you.

**Comment by mikolmogorov** [comment]
Hi,

Something weird is going on, but not quite sure what exactly. Seems like minimap2 is not producing any alignments, but not "failing" either (e.g. does not return error signal).

How did you install Flye? If you compiled it from source, can you also try to the bioconda package? Could you also invoke `flye-minimap2` and see if outputs any error? If not, try to use it to generate alignment manually (e.g. `flye-minimap2 00-assmebly/draft_assembly.fasta path_to_reads -t 30 -ax map-ont`.

**Comment by rckeerthivasan** [comment]
I did not build it from the source. I downloaded and did the local installation. I would try the conda installation. In the meanwhile, flye-minimap2 runs successfully. I used the command as you suggested and am copying the terminal output below. 

[M::mm_idx_gen::0.264*0.93] collected minimizers
[M::mm_idx_gen::0.399*0.95] sorted minimizers
[M::main::0.399*0.95] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.419*0.95] mid_occ = 6
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.434*0.95] distinct minimizers: 880468 (98.89% are singletons); average occurrences: 1.014; average spacing: 5.351
[M::worker_pipeline::28.293*7.39] mapped 25483 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: flye-minimap2 -t 10 -ax map-ont out_nano/00-assembly/draft_assembly.fasta Loman_E.coli_MAP006-1_2D_50x.fasta
[M::main] Real time: 28.328 sec; CPU: 209.057 sec; Peak RSS: 2.709 GB

**Comment by mikolmogorov** [comment]
@rckeerthivasan interesting. Did the bioconda installation work for you? If not, does the invocation of `flye-samtools` gives you any errors?

**Comment by rckeerthivasan** [comment]
No luck with conda installation as well. flye-samtools works. No errors.

**Comment by mikolmogorov** [comment]
Ok, let's run the full test alignment command line then. From the flye output directory of the test dataset, run (substitute the path to the reads as needed):

`flye-minimap2 00-assembly/draft_assembly.fasta Loman_E.coli_MAP006-1_2D_50x.fasta -x map-ont -t 10 -a -p 0.5 -N 10 --sam-hit-only -L -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T 00-assembly/draft_assembly.fasta -u - | flye-samtools sort -T sort_210301_092045 -O bam -@ 4 -l 1 -m 1G > minimap.bam`

If the command exists correctly, please send the output of `tail minimap.bam` and run the same test for your real assembly.

**Comment by rckeerthivasan** [comment]
Hi, the above command runs successfully and a bam file is created. I am attaching the tail output of the samtools view. 
[tmp.txt](https://github.com/fenderglass/Flye/files/6066187/tmp.txt)

I will upload the tail output once the command finished on our assembly.

**Comment by mikolmogorov** [comment]
Thanks, it gets more confusing.. The command works if you invoke it manually, but fails if called from Python.

My only guess now is that something is wrong with Python subprocess or piping part. Let's try the following, I've created a new branch which retain some additional debugging information: `iss354`. Could you locally install it and try to assemble the test data? Also, this time try to use python3 (e.g. you command line might looks like this: `python3 bin/flye <flye_args>`. If it still fails, could you post `cat 10-consensus/minimap.stderr` and `samtools view 10-consensus/minimap.bam | tail`?

**Comment by rckeerthivasan** [comment]
I ran it using the commands 'python Flye/bin/flye --nano-raw Loman_E.coli_MAP006-1_2D_50x.fasta --out-dir out_nano --threads 4'. It failed and the above-mentioned files are not created at all.

**Comment by rckeerthivasan** [comment]
I am attaching log file here 
[flye.log](https://github.com/fenderglass/Flye/files/6073524/flye.log)

**Comment by mikolmogorov** [comment]
@rckeerthivasan you are using the version from the `flye` (main) github branch, but not `iss354` branch. Make sure you fetch the code from the right branch, the version (`flye --version`) should show `2.8.3-b1696`, the one you've just used is `2.8.3-b1695`.

**Comment by rckeerthivasan** [comment]
Hi, 
sorry about that. I missed it somehow. I redid with 2.8.3-b1696 and I am attaching the files that you asked for. 
[minimap.stderr.txt](https://github.com/fenderglass/Flye/files/6094731/minimap.stderr.txt)
"samtools view 10-consensus/minimap.bam | tail" yields no result. I mean empty file.

**Comment by mikolmogorov** [comment]
Ok, thanks! I think we are getting somewhere - the minimap2 log says it could find the read file. My guess is that for some reason on your machine a child process (minimap2 in this case) does not inherit working directory. 

I've just pushed an update to `iss354` that should fix the problem - could you give it a try? The new version should be `2.8.3-b1697`.

**Comment by rckeerthivasan** [comment]
"assembly.fasta" was created. Yay!! thank you very much @fenderglass

**Comment by mikolmogorov** [comment]
@rckeerthivasan great to hear, yay! You can now restart your original run using `--resume-from consensus` option. I will incorporate this fix into the next Flye release.

**Comment by mikolmogorov** [comment]
Fixed in 8120b3d
