### ISSUE TITLE
No disjointigs for viral genome

### ISSUE THREAD

**Issue by phcompeau** [fenderglass/ABruijn#356]
Hi,

I'm trying to run Flye on Oxford nanopore reads sampled from SARS-CoV-2 (e.g., https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11178056), for an educational module.

Because the coverage is high, I set asm-coverage to 50 and the genome length to 30k. Flye flames out even with meta parameter on and asm-coverage 10, with "No disjointigs were assembled - please check if the read type and genome size parameters are correct".

I haven't seen anything saying that Flye would not de facto run on viral assemblies. Is this the case? Log provided below.

[flye.log](https://github.com/fenderglass/Flye/files/6012799/flye.log)

**Comment by mikolmogorov** [comment]
Hi Phillip,

Flye/metaFlye was not originally optimized for assembling very short genomes unfortunately, so it often struggles with viral genomes. Basically, Flye wants a contig (disjointig) to consist of at least a few reads, and if the viral genome is covered by single reads - the pipeline fails.

There is a modified experimental version in the `short_disj` branch which might help. But this is not yet a part of any release, so might not be the most convenient for educational purposes.

Mikhail

**Comment by phcompeau** [comment]
Sure, makes sense. SPAdes with short accurate reads works quite well for teaching my students but I was hoping to show another assembler that can assemble the virus only from iontorrent reads as a teachable moment for how differing sources of data require different approaches. From what I can tell there isn't a de novo tool that handles this well. (It is admittedly a strange application.)

**Comment by mikolmogorov** [comment]
I see. You might try Canu - I think it should be better with short viral fragments, but takes somewhat longer to assemble. Or maybe Unicycler (based on miniasm, so should be fast).

**Comment by phcompeau** [comment]
No luck, but thank you :(
