### ISSUE TITLE
Question regarding the use of quality scores and advice in solving tandem repeats

### ISSUE THREAD

**Issue by lbal-biomat** [fenderglass/ABruijn#357]
Hi, first I'd like to thank you for this great tool. 
Now to the question: is there any difference starting the assembly with fasta instead of fastq file? Does flye use the quality scores of the fastq at all?
I also would like to ask for some advice in choosing the best parameters to solve tandem repeats.
Some details of the biological problem in case it helps: I'm assembling some trypanosomatid genomes and I'm trying to resolve the tandem repeats the best I can, since the VSG genes are arranged in tandems. There are thousands of these genes, but only one is expressed at a time. I have the high quality sequence of the genes that are expressed in different stages if parasitaemia, and I would like to find that copies in the genome to study the genomic context, but it seems like the tandems are collapsed in the assembly and so the diversity in the VSG copies is lost (also the expected genome size is 45M and the obtained one is ~35M). I know this callapse is quite expected, but maybe you have some idea of how to optimize this. 
Best regards,

Lucia

**Comment by mikolmogorov** [comment]
Hi Lucia,

There is no difference in fasta and fastq input. What kind of sequencing data do you have? In general, Flye does not have too many parameters to tweak. If you could post `flye.log` file, I can check if everything looks right and may have some suggestions.

Mikhail

**Comment by mikolmogorov** [comment]
Forgot to ask - what is the length of each VSG gene?
