### ISSUE TITLE
No disjointigs were assembled error - using Minion corrected dataset that arises from Canu

### ISSUE THREAD

**Issue by AstrMary** [fenderglass/ABruijn#358]
Hallo,
first of all I want to thank you for your tool..
I am trying to run it using the below command over minion data

nohup /data2/maria/tools/Flye/bin/flye  --nano-corr   /data2/maria/tools/canu-1.9/Linux-amd64/koroneiki_allReads/olea_allReads.correctedReads.fasta.gz   --asm-coverage 50 --out-dir  /data2/maria/tools/Flye/out_stats_Olea_corrected_all_reads  --genome-size 1.4g --threads 24

As input I use the corrected output data from canu 
But i get the below error 
No disjointigs were assembled - please check if the read type and genome size parameters are correct 

What am I doing wrong?

PS, Flye assembler run just fine with the raw data of the same sample 
Thank you in advance,
Maria

**Comment by mikolmogorov** [comment]
Hi Maria,

Hard to tell based on this information. Please send `flye.log` file.

Mikhail

**Comment by AstrMary** [comment]
Hi ,
thank you for your reply. 
 Please, find the flye.log  attached
I  really hope to find a solution :-), 
Have a good month, 
[flye.log](https://github.com/fenderglass/Flye/files/6059663/flye.log)

Maria

**Comment by mikolmogorov** [comment]
Thanks Maria,

The mean error rate of your reads is 7.5% which is more than expected for error-corrected reads (1%). Please use the `--nano-raw` option instead. I also recommend to start with the original ONT reads, rather than error-corrected.

Mikhail
