### ISSUE TITLE
Are there parameters for more aggressively merging bubbles?

### ISSUE THREAD

**Issue by charles-plessy** [fenderglass/ABruijn#363]
I am assembling small genomes (~60 Mb) using Nanopore reads (N50 ~30 kb) from single individuals. Assemblies of the X and Y sex-specific regions, haploid and long of 3 to 8 Mb are often resulting in single contigs, which is excellent. Other parts of the genome are more fragmented, and we know from previous work that they do not contain longer repeats than the X and Y regions. So I suspect haplotypes to be the problem.

Indeed, `purge_dups` finds haplotigs in the assembly and `BUSCO` reports the presence of duplicates.

When I inspect the assembly graph with Bandage, I see that some bubbles remain, and the coverage information suggests that they are haplotypes; see the image below where darker colour marks lower coverage.

![image](https://user-images.githubusercontent.com/1834905/109923134-af096580-7d01-11eb-83ba-2193ebe381e3.png)

For the sake of comparison, I also ran Flye with `--keep-haplotypes` and the Bandage visualisation of the assembly graph showed many more bubbles.  So Flye does already an excellent job at removing haplotypes, but does not manage to find all of them.

So my question is: _are there parameters that I can tune for more aggressively merging bubbles?_

Thanks a lot for developing Flye, it is the workhorse of our genomics project!

Charles Plessy

**Comment by mikolmogorov** [comment]
Hi Charles,

You're right - there is a parameter that controls the maximum size of a bubble that could be collapsed. It is currently set to 50000. You can change this in the configuration file `flye/config/bin_cfg/asm_defaults`, in this case you'd need to use a local installation and compile Flye from source.

Hope that helps,
Mikhail

**Comment by charles-plessy** [comment]
Thank you very much! Judging by eye inspection of the resulting assembly graph, all the remaining bubbles were merged when I increased `max_bubble_length` to _300,000_.  Would it make sense to have it as a command-line parameter in a future release? This would allow us to use Flye from standard images distributed by biocontainers.pro.

**Comment by mikolmogorov** [comment]
Yes, that makes sense. As a more general solution, I am planning to add a command line parameter to overwrite any config file parameters.

Thanks,
Mikhail

**Comment by mikolmogorov** [comment]
Added an extra cmd option `--extra-params` in 25cd44d to overwrite hidden config arguments. For example, to control the bubble threshold you can add: `--extra-params max_bubble_length=50000`

**Comment by Yutang-ETH** [comment]
Hi Mikhail,

Thank you very much for developing the extra cmd option. I am very interested in changing the max bubble threshold. I installed flye on our Linux system via conda, is it possible for me to change the parameter in the configure file? Or how can I integrate your new code to current flye version?

Best,
Yutang

**Comment by mikolmogorov** [comment]
@Yutang-ETH currently this code is not a part of a release. You would need to get the latest source code from github and build it to use this option. Please refer to the installation manual for details: https://github.com/fenderglass/Flye/blob/flye/docs/INSTALL.md#local-building-without-installation

**Comment by Yutang-ETH** [comment]
@fenderglass Thank you very much, I will try.

**Comment by charles-plessy** [comment]
Hi Mikhail, do you think you could make a Flye release with that feature?  This would help a lot with workflows that prefer using released versions as a source for software (for instance https://github.com/nf-core/modules asks for bioconda images, etc.)

**Comment by mikolmogorov** [comment]
@charles-plessy this definitely will be incorporated into  the next release.
