### ISSUE TITLE
No disjointigs assembled

### ISSUE THREAD

**Issue by marco91sol** [fenderglass/ABruijn#364]
Dear all, 

I have installed flye version 2.8.1-b1676 through conda. 

I'm not able to reach the final assembly. Hence, I have tried as described in previous discussions using different parameters.
`flye --pacbio-corr correctedLRs.fasta --out-dir out_pacbio_flye --genome-size 1.2g --threads 32 | tee flye.log`
`flye --pacbio-corr correctedLRs.fasta --out-dir out_pacbio_flye --threads 64 --asm-coverage 50 --genome-size 1.2g  | tee flye.log`
`flye --pacbio-corr correctedLRs.fasta --out-dir out_pacbio_flye --threads 64 --meta --genome-size 1.2g  | tee flye.log`

How can I solve it? 

Thanks for your support!

![image](https://user-images.githubusercontent.com/42739946/109944754-d565db80-7cd6-11eb-9984-fe4e523f8d4e.png)

**Comment by mikolmogorov** [comment]
Hi,

Very likely similar problem to https://github.com/fenderglass/Flye/issues/358. Please check if that applies.

Mikhail
