### ISSUE TITLE
Strange behavior after consensus generation

### ISSUE THREAD

**Issue by tcb72** [fenderglass/ABruijn#368]
Hello,

Assembling a diploid algae using ~30x coverage HiFi (based on diploid size.) It has a diploid size of 200-205 Mbp, 1.5-2.0% heterozygosity, fairly complex with lots of large tandem repeats (one of the most common ones is a ~4300 bp repeat unit.) I had the same problem with Flye in the past, but we just got some more data and was hoping the problem would be fixed with more coverage.

Unfortunately, still getting the same issue. Essentially, the assembly produced during the consensus part is reasonable, but the eventual final assembly is highly fragmented. Here's the progression of the assembly stats, running default parameters:

00-assembly/draft_assembly.fasta: 202.892 Mbp in 231 contigs (N50 = 2.935 Mbp, Max = 7.419 Mbp)
10-consensus/consensus.fasta: 202.247 Mbp in 231 contigs (N50 = 2.926 Mbp, Max = 7.396 Mbp)
30-contigger/contigs.fasta: 200.872 Mbp in 1190 contigs (N50 = 608.715 Kbp, Max = 1.965 Mbp) 
final assembly: 200.799 Mbp in 1141 contigs (1113 scaffolds, N50 = 613.235 Kbp, Max = 1.965 Mbp)

It looks like something is going wrong during the repeat process, but I'm having a hard time figuring out why. Let me know what I can provide to help sort this out, if possible. hifiasm and canu produce a similar size/contig number as the assembly generated in the 10-consensus folder, so the issue seems fairly specific to the middle stages of Flye. 

Best,

Tom

**Comment by mikolmogorov** [comment]
Hi Tom,

This is not uncommon to see on highly diploid genomes. I suspect that during the repeat stage Flye recovers many heterozygosity bubbles, but fail to resolve them. Currently, hifiasm or HiCanu do better on such genomes because they take advantage of SNPs / small indels to untangle haplotypes.

Mikhail
