### ISSUE TITLE
Paths in GFA

### ISSUE THREAD

**Issue by asl** [fenderglass/ABruijn#376]
It would be great, if Flye would generate contig / scaffolds paths in GFA.

The following small .awk file converts assembly_info.txt to the appropriate format:
```
NR > 1 {
    name = $1
    chunk = 1
    split($8, path, ",")
    printf("P\t%s_%d\t", name, chunk)
    first = 1
    for (i in path) {
        edge = path[i]
        if (edge == "*")
          continue

        if (edge == "??") {
            printf("\t*\n")
            chunk += 1
            first = 1
            printf("P\t%s_%d\t", name, chunk)
            continue
        }

        edge = (substr(edge, 1, 1) == "-" ? "edge_" substr(edge, 2) "-" : "edge_" edge "+")
        printf("%s%s", first ? "" : ",", edge)
        first = 0
    }
    printf("\t*\n")
}
```

E.g.:
```
cat assembly_info.txt | awk -f flye2gfa.awl > assembly_graph_p.gfa
cat assembly_graph.gfa assembly_graph_p.gfa > assembly_graph_with_scaffolds.gfa
```

**Comment by ckeeling** [comment]
I'm interested in understanding this better @asl and @fenderglass 

I would like to use a gfa file from Flye for input into [SALSA2](https://github.com/marbl/SALSA), which optionally uses the input assembly's gfa to improve scaffolding in its process. I don't understand gfa and graphs very well, but I think the gfa that is included with the Flye output by default is not what is needed for SALSA2, and hence why @asl is suggesting this enhancement. With the solution @asl provides, I notice that all the contigs are suffixed with "_1" and scaffolds are suffixed with "_1" and "_2". These suffixes are not included in the output assembly.fasta, so presumably there won't be seqID correspondence between the assembly.fasta and the assembly_graph_with_scaffolds.gfa. Can you explain these suffixes and how they relate to the seqID of the final assembly.fa? Can you suggest a way to get proper correspondence of seqIDs between the assembly.fasta and the assembly_graph_with_scaffolds.gfa?

Thanks!
Chris

**Comment by mikolmogorov** [comment]
@ckeeling note that this is work in progress, not a finalized version yet.

@asl I am thinking about outputting only contigs in gfa, and in case of scaffolds output the original contig components. And therefore there will be no need in `_1, _2 ...` suffixes. Does that make sense? And overall, I am planning to disable scaffolding by default in the future versions, since the improvement is usually minor, but it is causing confusion.

**Comment by ckeeling** [comment]
Thanks @fenderglass !

I'm looking forward to trying this out when it becomes available.

Cheers,
Chris

**Comment by asl** [comment]
@ckeeling The problem is quite straightforward: there is no way to represent discontinuous paths as GFA paths. This means that we effectively could represent contig paths, but cannot scaffold paths. Different tools solve this problem in different way. I implemented the snippet in SPAdes-way, where GFA path is created for each contiguous path of the scaffold and different segments have the same prefix name, but different suffixes representing the order of them in the gapped path. The tools that consume SPAdes-generated paths are well aware about these limitation of GFA format and are aware of all

@fenderglass certainly works for me :)

**Comment by mikolmogorov** [comment]
Added in f6f6a1b
