### ISSUE TITLE
supply an external list of k-mers

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#377]
Hello Mikhail,

We have been discussing about the possibility to supply Flye with a custom set of k-mers for graph construction, it would be great if I can test my idea with your software.
I have 21-mers ready, though I could prepare also lists of shorter k-mers, let me know if you have any preference.

To ease the later steps it would be great if we can have a list (or fastq?) of the reads that did not make it into the graph produced from the custom k-mers - less important at this stage though.
Thanks,

Dario

**Comment by dcopetti** [comment]
Hello,
I wonder if you had time to think about this modification to the algorithm.
Thanks,
Dario

**Comment by dcopetti** [comment]
hello, just bouncing this up at the top of the list again
Thanks,
Dario

**Comment by mikolmogorov** [comment]
Sorry - was busy with the 2.9 release! This is next on my list.

**Comment by mikolmogorov** [comment]
Ok, finally done :)

The code is in the `kmer_whitelist` branch, you can now use an extra option `--kmer-whitelist` to provide a path to a fasta file with kmers. Flye will use only the specified k-mers for mapping though the pipeline (excluding the minimap2 steps).

Kmer size is 17 by default and could be changed with `--extra-params kmer_size=XX`. Note that k=17 is the maximum for *raw modes, but you can set it higher in *corr/*hq/*hifi modes.

**Comment by dcopetti** [comment]
Hi,
Thank you for working on this!
I tried to run the branch with this command, but I get an error
```
$ ~/bin/flye_whitelist/Flye/bin/flye --kmer-whitelist illumina_data/Rab_PE_17DKmers_40-110.fa.gz --extra-params kmer_size=17 -g 5.4g -o rab_whiteliist_1 -t 128 -m 10000 --keep-haplotypes -i 1 --nano-raw ONT_data/Rab*kf.fq.gz
[2021-10-21 11:42:09] ERROR: Command '['flye-modules', 'polisher', '-h']' returned non-zero exit status 1.
[2021-10-21 11:42:09] ERROR: Pipeline aborted
$ ~/bin/flye_whitelist/Flye/bin/flye --version
2.9-b1773
```
I am not sure whether it is in the command or in the script. Do you have any hint?

**Comment by mikolmogorov** [comment]
@dcopetti Is this the full log? Looks like the binary module is missing - did you run make?

**Comment by mikolmogorov** [comment]
Ok, marking this as resolved since it's been a while. Please feel free to follow up if you have more questions!
