### ISSUE TITLE
Assemble mitochondrial genome from total DNA reads?

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#378]
Dear community,

I would like to ask the extra question when I use Flye to assemble the plant genome. 
Recently I extracted the total DNA from plant leaves with Ampure beads and sequence using Nanopore. And I assemble the plant genome (predicted genome size ~500 Mb) by Flye (140X coverage sequencing data). When I extracted the total DNA from the leaves, I didn't extracted the nuclei first to decline the DNA from mitochondria and chloroplast. I would like to know whether the final assembly have the mitochondrial scaffolds/contigs or chloroplast in the Final.fasta file. 

If yes, which way is better to detect those mitochondrial and chloroplast scaffolds/contigs in the .fasta file?

I am sorry If I ask the basic questions. Thank you for the help.

**Comment by mikolmogorov** [comment]
Hi,

If you have a mitochondrial reference, you can use sequence similarity search methods, for example minimap2. But since the question is not directly related to Flye performance, you might want to post this question to a general bioinformatics forum instead.

Mikhail
