### ISSUE TITLE
Multiplicity and Repetitive

### ISSUE THREAD

**Issue by Imoteph** [fenderglass/ABruijn#38]
Hi,

would you be so nice to explain Multiplicity and Repetitive values? Just looking into the `assembly_info.txt` and from the description here and I have to admit I am bit confused. 

thx

**Comment by mikolmogorov** [comment]
Hi,

The multiplicity is how many times a particular edge appears in the genome (it is calculated based on coverage).

Repetitive means that the algorithm suggests that edge / contig appears in the assembly more than once - this is deduced based on coverage AND graph structure. The process of classifying edges into unique / repetitive is described in the current Flye preprint ("Classifying edges of the assembly graph" section).

**Comment by Imoteph** [comment]
THX!

**Comment by gushiro** [comment]
@fenderglass is repetitive “Y” and indication of contig duplication (a portion or the entire contig)?

**Comment by mikolmogorov** [comment]
@gushiro it indicates the entire contig appears at least twice in the genome.

**Comment by gushiro** [comment]
@fenderglass  thank you. Some more questions to clarify my output:

```
#seq_name       length  cov.    circ.   repeat  mult.   alt_group       graph_path
contig_79890    409074  22      N       Y       2       *       79890
contig_99384    305930  8       N       Y       1       *       99384
contig_74661    281575  23      N       Y       2       *       *,74661
contig_11414    837315  22      N       N       1       *       87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,87738,11414,175974
```

- The output means contig_99384 appears +1 more time in the genome and contig_79890 appears +2 more times, right?
- Is it OK-ish to assume that many/some of those contigs with repetitive "Y" perhaps represent the alternative allele? My species is highly heterozygous (~3.5%) and the genome size estimated by Flye is double the genome size estimated based on kmer profile.
- What is the meaning of **(*)** in ***,74661** ? and why is the number 74661 the same as in the contig name?
-  Could you explain me a little what happen in the graph of **contig_11414**  ?


Thanks in advance

**Comment by mikolmogorov** [comment]
1. Yes. Note that this is estimated from edge/contig coverage and could be subject to bias. Long sequences should be reliable though.
2. Some alternative contigs should be marked with an alt_group id, but I think it is possible that some other alternatives will be mislabeled as repeats. Heterozygous genome support is still limited, unfortunately.
3. Star means that path is a dead end on the graph. Contig consists from one or multiple edges, and in this case it consists of a single edge 74661. Contig ids are created based on edge ids.
4. This contig consists of multiple edges, and some of them (87738) are tandemly repeated.
