### ISSUE TITLE
ONT Q20+ Suggested Settings

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#384]
Hi Mikhail,

Do you have any suggested settings for the new ONT Q20+ data? `--nano-raw`?

Here is some example data: https://www.ebi.ac.uk/ena/browser/view/ERR5396170

Thanks,
Sam

**Comment by mikolmogorov** [comment]
Hi Sam,

Thanks for providing the link. I would try either `--nano-raw` or `--nano-corr` and see which works better. I expect that more optimizations will be possible in the future, once more benchmark data becomes available.

Mikhail
