### ISSUE TITLE
Inaccurate coverage information in assembly_info.txt if coverage beyond maximum

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#385]
I have very deep sequencing of a microbial community (eg. 5000X). I rely on the `assembly_info.txt` coverage information for downstream processing. Unfortunately it seems that the coverage in `assembly_info.txt` is capped at 1000? My understanding is this is determined by the maximum coverage (https://github.com/fenderglass/Flye/blob/38b6649a476b5c638d4c8f1088326d83ea228818/flye/config/py_cfg.py#L45) which is used when reading SAM file when making bubbles (https://github.com/fenderglass/Flye/blob/38b6649a476b5c638d4c8f1088326d83ea228818/flye/polishing/bubbles.py#L95-L97), which ultimately outputs the contig depths?

It would be nice to have accurate coverage information in the assembly info, even if this data wasn't/shouldn't be used for the assembly/polishing process. Is this possible?

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Yes, this is indeed an issue - I am planning to fix this in the near future.

Mikhail

**Comment by schorlton** [comment]
Awesome, thanks Mikhail!

**Comment by mikolmogorov** [comment]
The current code in the main github branch should solve the problem (commit 71fb2a2). In addition, it disables scaffolding by default (could be enabled with `--scaffold` option) - something that I was planning for a long time anyway :)

Not a part of a release yet - but will be incorporated into the next one.

**Comment by schorlton** [comment]
Thanks!
