### ISSUE TITLE
assembly of heterozygous regions

### ISSUE THREAD

**Issue by daggoo** [fenderglass/ABruijn#388]
Hello,

I am doing an assembly from Nanopore reads (coverage ~100x, pooled samples) and I know coordinates of a transposon insertion with a polymorphism that is non reference, heterozygous and located in euchromatin. Based on the repeat annotation of the assembly, I see this insertion with the polymorphism on a 'wrong' chromosome in a heterochromatic region. The contig with the insertion is 1 Mb long and half of it aligns uniquely to this 'wrong' chromosome, another half probably contains repeats as it aligns to different heterochromatic regions in the genome. 
The pipeline for assembly was Flye + Racon (1 round) + Medaka + RagTag. The BUSCO score after RagTag is 99.6%, NG50 after Medaka is 2.8 Mb, NG50 after RagTag 24 Mb, reference genome size ~ 140 Mb. Flye was run with `--nano-raw`.

Could you please let me know what parameters affect assembly of the heterozygous regions and what can I try to change to prevent possible misassembly in the situation above?

Many thanks,
Natalia

**Comment by mikolmogorov** [comment]
Hi Natalia,

Hard to give a general advice here. Are you sure that the misassembly is introduced by Flye, but not RagTag? Does Flye assembly contain the insertion breakpoints? In general, Flye rarely need parameter adjustments, but some of them are described in the FAQ.

Mikhail

**Comment by daggoo** [comment]
Hi Mikhail,

Thank you for your reply.

Yes, I checked the contig after Flye and before RagTag. 
I have not checked the insertion breakpoints yet. I looked only at the alignment to the reference of the contig in Ribbon. I will check them and get back you.  

Thanks!
Natalia

**Comment by mikolmogorov** [comment]
Ok, if you saw the misassmebly in Flye contigs, that the problem is certainly on our side. Although rare, misassmeblies do happen sometimes, especially in heavily repetitive regions and through telomeres. My only suggestion here would be trying increasing `--min-overlap` parameter (to maybe 7k or 10k) if you have sufficient read length.

**Comment by daggoo** [comment]
I will try it. I have several samples so there should be enough reads of sufficient length. Thanks!

**Comment by mikolmogorov** [comment]
Marking as resolved due to inactivity. Feel free to reopen/continue discussion if the problem remains.

**Comment by daggoo** [comment]
Hi Mikhail,

Sorry for not getting back to you sooner. I just finished new assembly with reads longer than 20kb and `--min-overlap 10000` . The resulting assembly is 5 % longer and the number of copies of the element I am looking at is increased. However the element with polymorphism is not present in the assembly at all. There is no misassembly of it on a wrong chromosome but it is also not present in the right place. Do you think I can try anything else in this situation?

Natalia

**Comment by mikolmogorov** [comment]
@daggoo hard to tell without looking into the data. It is possible that this is a heterozugous polymorphism?

**Comment by daggoo** [comment]
Yes, this is a heterozygous polymorphic transposon insertion with allele frequency slightly less than 0.5 .

**Comment by mikolmogorov** [comment]
Ok, it means that Flye assembled the allele without insertion then. Currently, the allele to assemble is randomly selected since we do not explicitly support diploid genomes.

**Comment by mikolmogorov** [comment]
UPD: You can try using `--keep-haplotypes` option to retain the insertion on the assmebly graph. It should how up as a looped edge. The assembly will likely be more fragmented, but you should be able to localize the insertion point.

**Comment by daggoo** [comment]
I'll try it. Thanks!
