### ISSUE TITLE
Minimum overlap length

### ISSUE THREAD

**Issue by Yutang-ETH** [fenderglass/ABruijn#391]
Hi Mikhail,

I am using the latest flye (2.8.3-b1695) and I didn't manually set a value to minimum overlap option, which means flye would automatically choose one value for me. According to the usage page, it is said the value would be set based on read N90. Does this mean the read N90 length will be used as the minimum overlap?

I checked the log file, my read N90 length is 10kb, but the minimum overlap used by flye is 5kb. It looks like read N90 length is not used as the minimum overlap but a smaller value will be set according to read N90 length, is my understanding correct?

Does it make sense to set minimum overlap greater than read N90 length?

Thank you very much.

Best wishes,
Yutang

**Comment by mikolmogorov** [comment]
Hi @Yutang-ETH, please see https://github.com/fenderglass/Flye/blob/flye/docs/FAQ.md#my-assembly-size--contiguity-is-not-what-i-expected-what-parameters-can-i-tweak-to-fix-it
