### ISSUE TITLE
Metagenome hybrid assembly?

### ISSUE THREAD

**Issue by cjfields** [fenderglass/ABruijn#401]
We're looking into approaches for hybrid assemblies (or merging independent assemblies) from very complex samples sequenced with both Illumina and PacBio HiFi reads.  We are currently running both metaSPAdes (Illumina only) and Flye (PacBio only) and have thought about trying metaSPAdes with the `--trusted_contigs` setting using the relevant Flye assemblies as input for a combined assembly.

We originally has planned on trying the converse, namely using the metaSPAdes assemblies with a Flye + PacBio HiFi assembly; I originally thought Flye had an analogous setting to `--trusted_contigs` but it doesn't seem to (I confused this with the `--subassemblies` parameter).  However, would `--subassemblies` be a possible option or recommended if we wanted to merge the two metagenome assemblies?

**Comment by mikolmogorov** [comment]
Yes, you can merge multiple assemblies using `--subassemblies` option, but the result will likely be a worse assembly than HiFi-only (makes sense to try at least). In our experience, if there is sufficient HiFi coverage, adding Illumina data has little benefit. One thing worth checking is if Illumina technology has better coverage of certain bacteria, but PacBio is known for being less biased in this respect (e.g. no gc-content bias).

**Comment by cjfields** [comment]
Thx @fenderglass !

**Comment by cjfields** [comment]
@fenderglass just a short addition to this: the various co-sequenced samples are extremely complex (Illumina assembly generated millions of scaffolds assemblies per sample, each with total size of 4-7Gb).  I expect the PacBio assembly to be possibly too shallow to capture everything so we will likely attempt a merged assembly, will let you know if Flye explodes :wink
