### ISSUE TITLE
Mis-assemblies or chimeric reads?

### ISSUE THREAD

**Issue by Yutang-ETH** [fenderglass/ABruijn#403]
Hi Mikhail,

I hope you are doing well.

I used flye (2.8.3-b1695) to assemble some ONT long reads obtained from a diploid plant genome. The estimated genome size is 2.6 gb and I got an assembly of 3.2 gb. Since the assembly size is larger than expected, I thought there might be some redundant allelic sequences, so I did BUSCO to see if the number of duplicated genes is high. Not surprisingly, the duplicated score is 60%, meaning that I did have some duplicated sequences in the assembly. Then I tried de-duplicating these redundant sequences and finally I had a assembly of 2.7 gb and the duplicated BUSCO score is 8%.

I aligned ONT reads to the final assembly using minimap2, however I found some reads are soft clipped (for example, I found one read is 60 kb long, but only 10 kb were mapped to the assembly and the remaining 50 kb were soft clipped) and there are also many chimeric alignment. If I only look at the read mapping rate reported by samtool flagstat, more than 99% reads were mapped, but I know some reads were not fully mapped given the chimeric and soft clipped case.

I am bit confused, are these chimeric or soft clipped alignment indicating mis-assemblies or implying that we have chimeric reads?

![image](https://user-images.githubusercontent.com/84848653/125066348-2fc2de80-e0b3-11eb-95f4-a7e11a24a4a5.png)

From the plot, we could see the alignment of some blue reads consistently start from the same position, these reads are soft clipped.

Could you please give me some opinions? Thank you very much.

Best wishes,
Yutang

**Comment by mikolmogorov** [comment]
Hi Yutang,

Since your genome is diploid, and you transformed your assembly into haploid, it is likely that these reads with structural variants are coming from the alternative haplotype.

**Comment by Yutang-ETH** [comment]
Thank you very much for your explanation. Yes, I understand and one of my collaborators also suggested these are structural variants between haplotypes.

Thanks again for your help.
Best wishes,
Yutang
