### ISSUE TITLE
trial set is not executing

### ISSUE THREAD

**Issue by ramnageena11** [fenderglass/ABruijn#408]
I installed the flye by open source option and made the directory. but when perform trial run app was not executed.
for python script. it is saying that i already have python3 installed.

I want to run Metagenome assembly, how select all the fastq files for assembly? Raw data is about 40 Gb ONT (Guppy super qc).

Thanks
Ram

**Comment by ramnageena11** [comment]
Pls anyone suggest

**Comment by mikolmogorov** [comment]
I suggest using the bioconda package instead - it is easier to install.
