### ISSUE TITLE
No progress from flye-repeat after two weeks

### ISSUE THREAD

**Issue by shanesturrock** [fenderglass/ABruijn#41]
I've been running Flye on some PacBio data which is high quality but for a long and highly repetitive genome and I don't have a lot of coverage (cost constraints). Progress was fine up to the point where it started flye-repeat and now it is just sitting there using a single CPU (even though 64 were specified) and hasn't produced any logs since Feb 16th. I've no way to tell how long this is likely to take looking at it and it is just sitting at Initializing edges. There's ample RAM and CPU on the machine (3TB and 72 cores) so I'm just hoping there's some way to tell if it is ever going to finish. The genome is 26Gb and I've only got about 6x coverage. I have a whole lot of Illumina data too but I was hoping to make some long runs from this that could help me join the many many contigs I got out of SOAPdenovo2 together.

**Comment by mikolmogorov** [comment]
Hi,

Yes, the graph construction algorithm might sometimes be slow on highly repetitive genomes, and it is not trivial to make it run in parallel. Given the size of the genome and high repeat content, the computation might take a while. Unfortunately, it is hard to predict how long it might take, since it varies greatly from one dataset to another. The largest genome that we tested so far was ~3G, so 26G genome might have some unexpected bottlenecks.

**Comment by shanesturrock** [comment]
It sounds like it is unlikely to finish any time soon in this case so I think I'll need to investigate other options. I have done an assembly using canu but it seems to only use about half the available data. The repetitiveness is killing all the various tools I've tried unfortunately. Thanks for getting back to me though.

**Comment by mikolmogorov** [comment]
You might also try MARVEL (https://github.com/schloi/MARVEL) - it looks like it was originally designed to assemble very large genomes.

**Comment by shanesturrock** [comment]
Yep, I've got that and it was on my list to try after I read the paper on the Axolotl assembly they did but they had 32x PacBio coverage so we're looking at possibly getting some more data. Theirs was also a lot less repetitive than ours. I'm hoping lots more longer reads could resolve the problems. Ilumina de-novo assembly with SOAPdenovo2 produces a lot of contigs (54 million last run) so that's not a great deal of help either. MaSuRCA got stuck (repeats again) and was likely to take 2000 days to finish. Tough one this.

**Comment by mikolmogorov** [comment]
Closing this year-old issue. Flye should now be better with respect to the resource usage (still does not scale to axolotl though).

**Comment by spe238** [comment]
How does the -t option behave? I have requested several CPUs in the SLURM script, but did not use the -t option, and flye is only using one CPU on the server node. Would you recommend using the option?

How long would you expect flye to run with a 50m genome, and 10 CPUs and 90g mem per CPU requested?

**Comment by mikolmogorov** [comment]
@spe238 `-t` option sets up the number of threads, which is one by default - please do use it. Some estimates of memory usage/running time are given in the FAQ/Manual.

**Comment by spe238** [comment]
Thank you!

**Comment by spe238** [comment]
Thank you!
