### ISSUE TITLE
Output gfa before repeat resolution

### ISSUE THREAD

**Issue by zouyinstein** [fenderglass/ABruijn#410]
I tried to assemble Arabidopsis (Col-0) mtDNA (367 kb, GenBank NC_037304.1) with HiFi reads.
Command line: flye --meta --pacbio-hifi ccs.fastq --hifi-error 0.003 -t 14  -o result
The reference contains two large repeats (6.5 kb and 4.2 kb). However, I only get the 4.2 kb repeat in the final graph "assembly_graph.gfa". It seems that the 6.5 kb repeat was lost in the repeat resolution step. How can I tweak the internal parameter to get both large repeats in the final graph (the 6.5kb repeat was in the "graph_before_rr.gv" file viewed by AGB)?
That is, how can I get a "graph_before_rr.gfa" file? Or, can I run the pipeline, while disabling the "repeat resolution" feature?

**Comment by zouyinstein** [comment]
The problem was solved by adding more input reads.

**Comment by mikolmogorov** [comment]
Resolving as many repeat as possible is the goal of the assembly, and therefore they will not show up on the final graph. The graph before repeat resolution might be something that you are looking for?

**Comment by zouyinstein** [comment]
Yes, but I didn't find a script that can convert graph_before_rr.gv into graph_before_rr.gfa.

**Comment by mikolmogorov** [comment]
You can uncomment line 248 in src/main_repeat.cpp to enable gfa output: https://github.com/fenderglass/Flye/blob/flye/src/repeat_graph/main_repeat.cpp#L248

**Comment by zouyinstein** [comment]
Thanks! It worked. And the result is exactly what I want. I still hope there will be some "--no-repeat-resolution" command-line option in the future.

**Comment by mikolmogorov** [comment]
Gfa output can now be activated by adding `--extra-params output_gfa_before_rr=1`
