### ISSUE TITLE
Installation issue on Ubuntu18.1

### ISSUE THREAD

**Issue by ramnageena11** [fenderglass/ABruijn#411]
running install
running build
running build_py
make release -C src -j 4
make[1]: Entering directory '/home/lab/Flye/src'
g++ assemble/main_assemble.o assemble/parameters_estimator.o assemble/chimera.o assemble/extender.o sequence/sequence.o sequence/consensus_generator.o sequence/alignment.o sequence/edlib.o sequence/vertex_index.o sequence/sequence_container.o sequence/overlap.o repeat_graph/multiplicity_inferer.o repeat_graph/repeat_resolver.o repeat_graph/read_aligner.o repeat_graph/graph_processing.o repeat_graph/repeat_graph.o repeat_graph/output_generator.o repeat_graph/main_repeat.o repeat_graph/haplotype_resolver.o contigger/contig_extender.o contigger/main_contigger.o polishing/dinucleotide_fixer.o polishing/homo_polisher.o polishing/main_polisher.o polishing/bubble_processor.o polishing/alignment.o polishing/subs_matrix.o polishing/general_polisher.o main.o -o /home/lab/Flye/bin/flye-modules -lz -L/home/lab/Flye/lib/minimap2 -lminimap2 -pthread -std=c++11 -rdynamic
make[1]: Leaving directory '/home/lab/Flye/src'
running install_lib
creating /usr/local/lib/python2.7/dist-packages/flye
error: could not create '/usr/local/lib/python2.7/dist-packages/flye': Permission denied

What permission it is looking for?

**Comment by mikolmogorov** [comment]
Please use the conda package for easier installation.

**Comment by ramnageena11** [comment]
Hi Mikhail,

If i will install conda, does it going to conflict with other programs? I'm not master of linux system, so bit careful and confused. Pls guide and help me.

Looking for support.
Thanks
RNS
