### ISSUE TITLE
ERROR: No disjointigs were assembled

### ISSUE THREAD

**Issue by arz19893** [fenderglass/ABruijn#412]
HI ,

I am using meta fly for metagenomic approach,
 flye --nano-raw zymo_even_filt.fastq.gz -t 8 --meta -o flye_meta 
I used -- meta as suggested as  
I followed log file 
 flye --nano-raw zymo_even_filt.fastq.gz -t 8 --meta -o flye_meta 

vim flye.log 

    |                                                ********             |
    |              *                                 ********             |
    |              *                               * ********             |
    |              *                               ***********            |
    |              *                               ***********            |
    |             ***                            *************            |
    |             ******                        ***************           |
    |            ********                       ****************          |
    |            ********   *           *     *******************  * **   |*  **
    |        ************** * ************** *********************** ******* **** *
    ----------------------------------------------------------------------------------------------------
    0%        5%        10%       15%       20%       25%       30%       35%       40%       45%

    Q25 = 0.22, Q50 = 0.25, Q75 = 0.27

[2021-08-03 21:47:25] INFO: Assembled 0 disjointigs
[2021-08-03 21:47:25] INFO: Generating sequence
[2021-08-03 21:47:25] DEBUG: Writing FASTA
[2021-08-03 21:47:25] DEBUG: Peak RAM usage: 8 Gb
-----------End assembly log------------
[2021-08-03 21:47:25] root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2021-08-03 21:47:25] root: ERROR: Pipeline aborted

**Comment by mikolmogorov** [comment]
Please see https://github.com/fenderglass/Flye/issues/128
