### ISSUE TITLE
Extreme 'contigger' run time

### ISSUE THREAD

**Issue by nhartwic** [fenderglass/ABruijn#413]
Any ideas what would cause the 'contiger' portion of the flye assembler to take an extremely long time to run?

For reference, I'm currently running assemblies on AWS using tibanna. This makes it easy for me to track resource usage of specific processes. A typical flye run for an 800 megabase genome looks roughly like [this](https://salk-tm-logs.s3.amazonaws.com/fYNNpVbfMwZz.metrics/metrics.html). If you scroll down to either of the per-process plots, you can see It spent about ten minutes on the 'contiger' step. 

I'm currently trying to assemble an ~1 gigabase genome. It has been running for 3 days and the 'contiger' step has been running for about 2400 minutes (about 2 days). During that time, the pipeline has been essentially operating in a single thread and memory usage has grown slowly up to about 200 gigs.

From experience, this doesn't feel like typical behavior. But I'm not really certain what I should be looking at to try to figure out what is going wrong.

Any help would be appreciated.

**Comment by mikolmogorov** [comment]
Which Flye version are you using? Before 2.8.2 there was a bug that caused exactly this: https://github.com/fenderglass/Flye/issues/290

**Comment by nhartwic** [comment]
I'm currently on "2.8.1-b1676" installed using conda. I'll update my container and relaunch the job. Give it a day or two for assembly and hopefully we can close this issue.

**Comment by nhartwic** [comment]
Well... Assembly seems to have gone fine. So, seems like it was just the bug. Apologies for duplicating another issue, especially since it was already solved. Didn't find it in my admittedly brief search.

Thanks for the help. Really appreciated.

**Comment by nhartwic** [comment]
@fenderglass If you don't mind a follow-up question. How concerned should I be about this bug having impacted previous assemblies? Is the bug only performance related? Or should I expect to get significantly different contigs/graphs if I reassemble old read sets on 2.8.3 that I originally assembled on 2.8.1?

**Comment by mikolmogorov** [comment]
@nhartwic contigs should be very similar between 2.8.3 and 2.8.1 - I don't think you need to reassemble. The bug only affected the gfa generation time and gfa representation.
