### ISSUE TITLE
flye2.9 viruses

### ISSUE THREAD

**Issue by wangyaxiang008** [fenderglass/ABruijn#415]
Hi，@fenderglass
     Excitement ,Flye 2.9 has improved the assembly of short sequences such as viruses.
     I have hifi metavirome  data and want to assemble it  , my previous parameter setting was (flye --pacbio-hifi *_CCS_subreads.fastq.gz  --genome-size 1g  --threads 30 --meta --out-dir ./) ,the previous flye version was 2.8.3.      For flye 2.9, I would like to ask how to set this parameter for virus.  

Hope to get your reply !
wyx

**Comment by mikolmogorov** [comment]
@wangyaxiang008 this command line looks right, note that genome size is not required any more.
