### ISSUE TITLE
Difference between "overlap divergence" and "error rate" ?

### ISSUE THREAD

**Issue by charles-plessy** [fenderglass/ABruijn#417]
Hi Mikhail,

may I ask you a quick explanation or a link to an explanation of what "overlap divergence" means and if it is related to the error rate?  I did not manage to find this information in GitHub or elsewhere…

Thanks a lot for your work on Flye.  Combined with the new Guppy basecalls, it starts to give us full chromosome assemblies!

**Comment by mikolmogorov** [comment]
Hi,

I used these terms somewhat interchangeably, they are both the opposite of "nucleotide identity", e.g. if the identity is 99%, divergence is 1%. Sometimes I "error rate" might refer to "read error rate", and the overlap divergence between two reads is a function of it.

Glad to hear that it works well for you!
