### ISSUE TITLE
Genome Size for version 2.4.2

### ISSUE THREAD

**Issue by saras224** [fenderglass/ABruijn#418]
Hi @fenderglass 
I am using an assembly tool called lathe which has integrated FLYE version 2.4.2. 
I want to assemble my ONT longread metagenome so what should be the approx genome size for the assembly? I assembled using the size 100m and 250m and both of which do not give good assembly results. The largest resulting contig from the above-selected genome size formed was 1.1mbps and the rest were in kilobase pairs which would probably be the genome size for the plasmids but my goal is to assemble bacterial genomes.

Thanks 
Saraswati

**Comment by mikolmogorov** [comment]
Hi,

Version 2.4.2 is very outdated, and starting version 2.8 Flye does not require genome size as input. I would recommend either switch to a newer version in the Lathe pipeline or just use newest Flye as is.
