### ISSUE TITLE
Can Flye use contigs in place of reads?

### ISSUE THREAD

**Issue by rvaser** [fenderglass/ABruijn#419]
Hi Mikhail,
I am wondering if Flye can combine an existing assembly and a read dataset as input, effectively running as a scaffolder?

Best regards,
Robert

**Comment by mikolmogorov** [comment]
Hi Robert,

Currently it is not possible. You can add contigs as regular reads, but there is no "special" treatment of such contigs, and if no other reads support their structure, the contigs will probably be marked as chimeric.

Assembling reads first and then merging two sets of contigs is an alternative. Flye has "--subassemblies" mode for that, but this option will actually be discontinued in the future versions.

Mikhail

**Comment by rvaser** [comment]
Thank you for the fast response!
