### ISSUE TITLE
Floating point exception of flye-assemble 

### ISSUE THREAD

**Issue by zhanglu295** [fenderglass/ABruijn#42]
Hi there,

I tried to use flye-assemble to extend the contigs in flye-input-contigs.fa, but I encountered a "floating point exception" (log showed below). Do you think it is a problem of my contig sequences or a bug in flye-assemble?

flye-assemble -l /oak/stanford/groups/arend/Eric/meta/readclouds-l-gasseri-example/results/olc/flye-asm-1/flye.log -t 4 -s -v 1000 ./results/olc/flye-input-contigs.fa /oak/stanford/groups/arend/Eric/meta/readclouds-l-gasseri-example/results/olc/flye-asm-1/0-assembly/draft_assembly.fasta 1857551 /scratch/users/zhanglu2/software/Flye-2.3.3/flye/resource/asm_subasm.cfg
[2018-04-01 19:31:29] INFO: Running with k-mer size: 31
[2018-04-01 19:31:29] INFO: Reading sequences
[2018-04-01 19:31:30] INFO: Reads N50/90: 64830 / 21423
[2018-04-01 19:31:30] INFO: Selected minimum overlap 1000
[2018-04-01 19:31:30] INFO: Expected read coverage: 7
[2018-04-01 19:31:30] INFO: Generating solid k-mer index
[2018-04-01 19:31:47] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-04-01 19:31:48] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-04-01 19:31:49] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-04-01 19:31:50] INFO: Extending reads
Floating point exception

**Comment by mikolmogorov** [comment]
Hi,

Are these input contigs produced by Athena? If so, why are you running the binary manually?

In general, if you want to run Flye manually, you should use "bin/flye" script, not flye-assemble. Also, could you send me "flye.log" file - it should give some extra information about what might gone wrong.

**Comment by LRTK** [comment]
Hi,
Yes, I used the contigs produced by Athena, but it reported an error when invoking flye on olc assembly. I went through the log of athena, the issue happed when running "flye --subassemblies". Later on, I also found the error message about flye-assemble in flye.log.

I attached two log files, AssembleOLCStep.log for athena-meta, flye.log for flye.
[flye.log](https://github.com/fenderglass/Flye/files/1868730/flye.log)
[AssembleOLCStep.log](https://github.com/fenderglass/Flye/files/1868723/AssembleOLCStep.log)

**Comment by zhanglu295** [comment]
Hi,
Yes, I used the contigs produced by Athena, but it reported an error when invoking flye on olc assembly. I went through the log of athena, the issue happed when running "flye --subassemblies". Later on, I also found the error message about flye-assemble in flye.log.

I attached two log files, AssembleOLCStep.log for athena-meta, flye.log for flye.
[AssembleOLCStep.log](https://github.com/fenderglass/Flye/files/1868734/AssembleOLCStep.log)
[flye.log](https://github.com/fenderglass/Flye/files/1868743/flye.log)

**Comment by mikolmogorov** [comment]
Thank you!

I think I know what might be the issue. I've pushed an updated version into flye-devel branch - could you take a look and see if it works for you? Also, this issue seems to be introduced in 2.3.3, so 2.3.2 version should not be affected.

**Comment by zhanglu295** [comment]
Hi,

The updated version works well on the contigs, thanks for the help.

Best,
Eric
