### ISSUE TITLE
Error in minimap, bad parse/truncated file

### ISSUE THREAD

**Issue by mvolar** [fenderglass/ABruijn#421]
Hello everyone,

similarly to #237 we have a Minimap2 failure, but in our case we do not have any "()" symbols our of the sort, and there shouldn't be any memory failures since we have a relatively small genome (200m) and only 13GB of reads (all are filtered to >35kB size since we are using a single node on a cluster in order to minimize space and file transfer time). I have tried running on multiple nodes of the cluster from 128GB RAM/500GB SSD all the way to a node with 384GB RAM/2TB SSD, and also locally on my machine with 32GB RAM/512GB SSD (here the failure was an obvious segmentation fault/lack of memory). I have also tried rerunning several times with `--asm-coverage, --genome-size` options included in order to minimize memory consumption but to no avail. 

Based on the logs we can see that the peak memory usage is around 40 GB so the memory _shouldn't_ be at fault but I am not certain to that, however the minimap2 part seems to break independently and always on the same step, no matter the load present at that time at the node.

The logs:

the main flye log
[flye.log](https://github.com/fenderglass/Flye/files/7082293/flye.log)
the minimap log (stderr log but github won't allow .stderr)
[minimap.log](https://github.com/fenderglass/Flye/files/7082295/minimap.log)
the stderr returned to the cluster
[flye_sge_3_err.log](https://github.com/fenderglass/Flye/files/7082305/flye_sge_3_err.log)

*PS I am running Flye through python via python Flye/bin/flye command, and flye was wget/compiled since my cluster doesn't support bioconda

**Comment by mikolmogorov** [comment]
Hi,

Interesting that minimap2 keeps failing at the same stage. Could you test the previous version of Flye (2.8.3) - it was using a different version of minimap2 with slightly different parameters? You could start a new run, or resume the existing run (`--resume-from consensus`).

`dmesg` output could also be helpful to identifying the reason of crashing (e.g. segfault, OOM etc).

**Comment by mvolar** [comment]
I have rerun with Flye 2.8.3 version and filtered all reads up to 40kb (cca. 6GB or 30x coverage) and now the output of the minimap2 (again broken on the consensus stage) really does state a lack of memory problem:

[minimap.log](https://github.com/fenderglass/Flye/files/7104569/minimap.log)



I was wondering would it be possible to run the minimap2 standalone on the cluster in "is_hpc=1" mode so that the memory overflow doesn't happen and then feed the output back to Flye? 

We are really hell bent on using Flye since our genome is really really repetitive, and we are studying the structure of the repeats ( with which Canu is very agressive) so there really isn't an alternative. Plus my PC is a potato so my only option is pushing through on the cluster.

PS* I already have run minimap2 in the standalone version and have it compiled on the server

**Comment by mikolmogorov** [comment]
Ok, good to know. hpc parameter in minimap2 actually refers to homopolymer compression, so no relevance to the machine type.

I think one possibility to make it work is to use less threads (at least for the parts that use minimap2), as extra threads initialize more buffer memory. I'd try to rerun the consensus stage with 10 threads and see if it helps.

**Comment by mvolar** [comment]
We rerun the consensus step with the `-threads=10` and it passed it, but it unfortunately crashed right on the next step with the following error:

`[2021-09-06 14:53:03] root: ERROR: Command '['flye-modules', 'repeat', '--disjointigs', '/storage/home/flye_try_dir6/10-consensus/consensus.fasta', '--reads', '/storage/home/flye.fasta', '--out-dir', '/storage/home/flye_try_dir6/20-repeat', '--config', '/storage/home/Flye-2.8/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/storage/home/flye_try_dir6/flye.log', '--threads', '16', '--min-ovlp', '10000']' returned non-zero exit status -6`

I tried deleting the created folder and rerunning multiple times but it crashes nevertheless. Maybe a compilation error for the "flye-modules" or some sort of permission error (which it shouldn't be since everything went smoothly until now)?

**Comment by mikolmogorov** [comment]
Could you send the latest log? But very likely a memory issue again. Unfortunately, I don't have any suggestions hot to reduce memory usage further at this point.

**Comment by mikolmogorov** [comment]
Closed due to inactivity, feel free to reopen is the issue is still there.
