### ISSUE TITLE
Is nano-hq only for guppy5 super accuracy mode?

### ISSUE THREAD

**Issue by sxh1136** [fenderglass/ABruijn#422]
Hi there,
Thank you for the continued improvements to Flye! Just wanted to know if the new nano-hq flag is to only be used for the super accuracy mode in guppy5 or anything basecalled by guppy5 (including HAC). 

All the best,
Stan

**Comment by mikolmogorov** [comment]
Good question - it's intended for super accuracy mode. Will update the manual.
