### ISSUE TITLE
Overlap-based coverage: 0

### ISSUE THREAD

**Issue by jhcaddisfly** [fenderglass/ABruijn#423]
Hi,

first of all, I really like flye and works excellent for my PacBio HiFi data.
However, I have some problems when assembling PacBio clr data:

This is my data:
There are 13010955 sequences
The N50 is: 33339
The average length is: 11510
The median length is 4246.000000
The total length is: 149762040452
The shortest length is: 50
The longest length is: 509794
Based on a genome size of 2Gb that means coverage of ~74x.

I used flye 2.8.2 to assemble the reads: 
flye --pacbio-raw ../TBG_1305.fa --threads 96 --out-dir TBG_1035_flye_redo --genome-size 2G

but no disjointigs were assembled because the overlap-based coverage is 0 (see log file attached).
Do you have any idea how to solve this problem?

Thanks,
J.
[flye.log](https://github.com/fenderglass/Flye/files/7115647/flye.log)
[flye.log](https://github.com/fenderglass/Flye/files/7115649/flye.log)

**Comment by mikolmogorov** [comment]
Please see if anything from this topic applies + try running the newest 2.9 release: https://github.com/fenderglass/Flye/issues/128
