### ISSUE TITLE
--nano-hq 

### ISSUE THREAD

**Issue by Sumsarium** [fenderglass/ABruijn#424]
hi @fenderglass  

I was wondering if is sufficient to just (blindly) use the `--nano-hq` option if I have basecalled my ONT data with the guppy SUP algorithm? While the SUP algorithm does provide higher q-scores, it is not that dramatic a difference (compared to the HAC algorithm).  

Asked in another way, are there other considerations that should be weighed when deciding between `--nano-raw `and `--nano-hq`?

**Comment by mikolmogorov** [comment]
Hi,

`--ont-hq` was optimized for roughly 4-5% error rate (that we observed from Guppy5 SUP reads). So the current recommendation is based on these tests, and we have not experimented extensively with HAC reads in this mode. I think it definitely makes sense to give it a try. You can also control the expected error by adjusting `--read-error` option. 

The other key difference is that `--nano-hq` and `--nano-raw` are using different k-mer indexing schemes. `--nano-raw` is more versatile, and `--nano-hq` might not work for very high error rates.

Hope this helps, let me know if something is unclear.
Mikhail

**Comment by Sumsarium** [comment]
Thanks for the input.

**Comment by cgjosephlee** [comment]
Hi @fenderglass ,

Guppy 5 SUP mode filters reads by mean Q>=10 (HAC filters >=7) by default. Do you suggest further filter Q>=15 to fit 4-5% error rate for `--nano-hq` option? Or default Q10 is enough?

Thank you.
