### ISSUE TITLE
amplicon assembly questions

### ISSUE THREAD

**Issue by brevans** [fenderglass/ABruijn#425]
We're looking for good routes to _de novo_ amplicon sequencing assembly starting from raw, demultiplexed ONT data. Problem is some of our expected fragment sizes are ~700bp-1kb. 

1) Is using Flye for this a bad idea?
2) Can we change some of the parameters to make things work? Mostly it seems a lot of minimum length/overlap related parameters/assumptions are (completely understandably) geared for larger assemblies.

**Comment by mikolmogorov** [comment]
Hi,

Flye will not assemble anything shorter than 1kb. You are right - it would not be simple to change that because many other parameters were set with the assumption of 1kb+ overlaps.
