### ISSUE TITLE
Genome with high heterozygosity and high duplication

### ISSUE THREAD

**Issue by fengyuanli304** [fenderglass/ABruijn#427]
Hi,
I am running FLye to assembly a 2.9G genome. The data was generated from Pacbio sequel II library, representing approximately 84-fold coverage of the genome. The genome feature high levels of repetitive sequences (60.05%) and heterozygosity(1.3%).

Data were assembled with the following parameters:
lye --pacbio-raw toxeusnomit.fastq.gz --out-dir /lfy/flye --genome-size 2.9g -t 24 --min-overlap 10000 --asm-coverage 50

The genome size was estimated to be 2.91Gb, but the total length is 5G.
What parameters do you recommend for my data? Thank you very much!

**Comment by mikolmogorov** [comment]
The default parameters should normally work for a wide range of genomes. If 2.9G is the expected diploid genome size, it likely means that Flye is assembling an extra 2Gb of the alternative haplotype - not uncommon to see for genomes with high heterozygosity. Note that Flye currently has somewhat limited support of highly heterozygous genomes in general, and does not produce pseudo-haplotypes.

**Comment by gushiro** [comment]
@fenderglass what is the limitation in flye for high heterozygous genomes? Am I correct to assume that it can create many disjointigs for the same genomic region and that will affect the assembly? Sorry maybe it is a naive question!

**Comment by mikolmogorov** [comment]
@gushiro it is a bit more complicated. Flye will likely separate highly divergent alleles, so that the assembly will have two copies of each. But the fragments of the genome with lower heterozygosity will likely remain collapsed as a single mosaic copy. Currently Flye does not annotate which is which.
