### ISSUE TITLE
-m option ignored

### ISSUE THREAD

**Issue by aldertzomer** [fenderglass/ABruijn#429]
Hi
I'm setting the -m option to 2000 bp, however when I read the logs the following gets reported:

[2021-09-26 14:00:12] root: INFO: Reads N50/N90: 23245 / 13645
[2021-09-26 14:00:12] root: INFO: Minimum overlap set to 10000

Is the -m option ignored?
thanks
Aldert

**Comment by mikolmogorov** [comment]
`-m` should work, could you send the full `flye.log`?

**Comment by aldertzomer** [comment]
I tried the following commands:
flye --nano-hq 3.coveragefiltered.fastq -o assembly --threads 16 --meta -m 1000
flye --nano-hq 3.coveragefiltered.fastq -o assembly --threads 16 --meta --min-overlap 1000 
flye --nano-hq 3.coveragefiltered.fastq -o assembly --threads 16 --meta --min-overlap 1000 --min-ovlp 1000 

Attached the log:
[flye.log](https://github.com/fenderglass/Flye/files/7236330/flye.log)

**Comment by aldertzomer** [comment]
Oddly enough it works when I run the commands by hand (?). When I run it as part of a script, the -m flag is not passed on

**Comment by aldertzomer** [comment]
I may have solved it. The issue was with passing on arguments. sorry for bothering you.
