### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by yanboANU** [fenderglass/ABruijn#43]
Hi there,
 
I tried to use Flye 2.3.3-release to assemble human chromosome 6, but I encountered a IOError (log showed below).  

Flye/2.3.3/bin/flye --pacbio-raw  chr6.read.fq --out-dir assembly_result --genome-size 171m --threads 16
…
[2018-04-04 19:47:55] INFO: Generating contigs
[2018-04-04 19:48:04] INFO: Generated 144 contigs
[2018-04-04 19:48:22] INFO: Polishing genome (1/1)
[2018-04-04 19:48:22] INFO: Running Minimap2
[2018-04-04 19:56:45] INFO: Separating alignment into bubbles
Traceback (most recent call last):
  File "/short/te53/software/Flye/2.3.3/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/short/te53/software/Flye/2.3.3/lib/python2.7/site-packages/flye/main.py", line 511, in main
    _run(args)
  File "/short/te53/software/Flye/2.3.3/lib/python2.7/site-packages/flye/main.py", line 348, in _run
    jobs[i].run()
  File "/short/te53/software/Flye/2.3.3/lib/python2.7/site-packages/flye/main.py", line 227, in run
    config.vals["min_aln_rate"], bubbles_file)
  File "/short/te53/software/Flye/2.3.3/lib/python2.7/site-packages/flye/bubbles.py", line 109, in make_bubbles
    raise error_queue.get()
IOError: bad message length
Any advice to help me get up and running would be appreciated.

**Comment by mikolmogorov** [comment]
Hi,

I probably can tel more if you send me the full log file, but most likely system ran out of memory. Usually this part is not a memory bottleneck, but it seems that sometimes it might be, What kind of dataset is it, do you happen to have very long reads? 

How much memory do you have? I suggest to try rerun polishing with a reduced number of threads (use --resume option).

**Comment by yanboANU** [comment]
Thanks, it works when I using threads 8.

**Comment by yanboANU** [comment]
Yanbo Li has shared OneDrive for Business files with you. To view them, click the links below.


<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EQh_y4aIDa9Pjd2cRfLP7PYBsnYf368aVug002ckh5fx-Q>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EQh_y4aIDa9Pjd2cRfLP7PYBsnYf368aVug002ckh5fx-Q>

flye.log<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EQh_y4aIDa9Pjd2cRfLP7PYBsnYf368aVug002ckh5fx-Q>

<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EVSqMBdg5gJLjJBX_K1PgWIBxCSf_qnwySo6QX0dHVLv2A>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EVSqMBdg5gJLjJBX_K1PgWIBxCSf_qnwySo6QX0dHVLv2A>

6552464.r-man2.OU<https://anu365-my.sharepoint.com/:u:/g/personal/u6260133_anu_edu_au/EVSqMBdg5gJLjJBX_K1PgWIBxCSf_qnwySo6QX0dHVLv2A>




Hi,


I meet this problem https://github.com/fenderglass/Flye/issues/43 again, attached the log file. I am truly appreciate for you help.

[https://avatars3.githubusercontent.com/u/32726694?s=400&v=4]<https://github.com/fenderglass/Flye/issues/43>

IOError · Issue #43 · fenderglass/Flye<https://github.com/fenderglass/Flye/issues/43>
github.com
Hi there, I tried to use Flye 2.3.3-release to assemble human chromosome 6, but I encountered a IOError (log showed below). Flye/2.3.3/bin/flye --pacbio-raw chr6.read.fq --out-dir assembly_result ...




Thanks,
Yanbo


-----------------------------------------------
Yanbo Li
N329, Building 108 (CS&IT)
Research School of Computer Science
The Australian National University

Email: yanbo.li@anu.edu.au<mailto:yu.lin@anu.edu.au>

________________________________

**Comment by mikolmogorov** [comment]
Please try the latest version from the 'flye' branch - it should now have more reasonable memory requirements for the alignment processing step.

**Comment by yanboANU** [comment]
Thank you for your reply. Since I requested 128.0GB memory and only used 46.19GB memory, I am not sure is memory problem.
 
======================================================================================
                  Resource Usage on 2018-05-01 15:52:55:
   Job Id:             6552464.r-man2
   Project:            te53
   Exit Status:        1
   Service Units:      9.15
   NCPUs Requested:    8                      NCPUs Used: 8
                                           CPU Time Used: 02:38:36
   Memory Requested:   128.0GB               Memory Used: 46.19GB
   Walltime requested: 10:00:00            Walltime Used: 01:08:37
   JobFS requested:    100.0MB                JobFS used: 0B
======================================================================================

**Comment by mikolmogorov** [comment]
Getting peak memory usage of multiple processes is not trivial, sometimes the monitors might under/overestimate it. From my experience, this IOError exception is very likely to be caused by the issues with resources (memory).
