### ISSUE TITLE
Flye '--scaffold' option with '--resume' or '--resume-from'

### ISSUE THREAD

**Issue by sjfleck** [fenderglass/ABruijn#431]
I'm attempting to assemble 3 genomes (all estimated to be ~900 MB in size) with limited ONT reads (a bit lower than the recommended 40x). I did some initial assemblies experimenting with some of the options (i.e. -m 10000, -i 3, --polish-target). My assemblies weren't especially contiguous, but they had relatively high BUSCO scores (93.1-95.2% complete eudicots_odb10 BUSCOs).  

**Here are one of the commands for one assembly:**
flye --nano-raw $RAW -m 10000 -i 3 -t 32 --genome-size 930m -o $OUT 

**and some of the stats:**
ONT_raw_reads.fastq.gz: 19.2GB
Total length: 795,920,351
Fragments: 3,966
Fragments N50: 1,037,385
Largest frg: 6,590,250
Scaffolds: 37
Mean coverage: 13
BUSCO (C): 93.1%

My question is about the scaffolds. As you see, I did not run Flye with the '--scaffold' option, but I want to try it out now. My Flye runs are already completed, but can I use the '--resume' or '--resume-from' options, to use the '--scaffolds' option now, or do I need to start a new Flye run altogether? 

Thank you for any help you can provide!

**Comment by sjfleck** [comment]
I read a little more carefully and I ran Flye with version 2.8.3, which ran with the scaffold option by default. 

I installed 2.9 now and am exploring the options. Thanks

**Comment by mikolmogorov** [comment]
@sjfleck if you still need to add scaffolds to an existing assembly, you can run `--scaffold --resume-from finalize`.

**Comment by sjfleck** [comment]
Thank you for answering this for me. 

I'm surprised that my first tries with Flye v2.9 didn't produce more contiguous results than v2.8.3 (I ran a few different options, but I'll only share the best one). The two biggest differences is the N50 decreasing and the coverage increasing.

Flye-2.8.3 command:
flye --nano-raw $RAW -m 10000 -i 3 -t 32 --genome-size 930m -o $OUT

Comparable Flye-2.9 command:
flye --nano-hq $RAW -i 3 -t 32 --genome-size 880m --scaffold -o $OUT 

Since the default minimum overlap changed to 10k, the only difference is that I only changed with v2.9 was the predicted assembly size (I had the incorrect value previously, but it's only a difference of 50m) and I doubt that would change much. I am surprised by how much better the mean coverage is and I was surprised by how low the coverage was when I used v2.8.3.

Results (v2.8.3 -> v2.9):
Total length: 795,920,351 -> 753,374,971
Fragments: 3,966 -> 4,067
Fragments N50: 1,037,385 -> 617,830
Largest frg: 6,590,250 -> 4,568,557
Scaffolds: 37 -> 73
Mean coverage: 13 -> 19
BUSCO (C): 93.1% -> 92.3%

I wonder why my largest contig is 2M bases smaller and my N50 is much smaller despite only having 101 more contigs.

I also have a final question. Using "-i 3" is the same as running "--polish-target -i 3", right? 
Thanks!

**Comment by mikolmogorov** [comment]
@sjfleck strange to see that N50 is decreasing with Flye 2.9. Could you send me the log files from both runs? What is the genome you are assembling and which basecaller are you using?

**Comment by sjfleck** [comment]
I'm assembling a few plants in the Oleaceae and our GridION uses Guppy v5.0.11. 

Here is the log file for flye-2.8.3:
[flye-2.8.3.m10k.i3.log.txt](https://github.com/fenderglass/Flye/files/7288348/flye-2.8.3.m10k.i3.log.txt)

Here is the log files for flye-2.9 (had to split them for uploading purposes):
[flye-2.9.i3.scaffold.log1.txt](https://github.com/fenderglass/Flye/files/7288647/flye-2.9.i3.scaffold.log1.txt)
[flye-2.9.i3.scaffold.log2.txt](https://github.com/fenderglass/Flye/files/7288649/flye-2.9.i3.scaffold.log2.txt)

**Comment by sjfleck** [comment]
I'll also attach a picture of the relevant assembly stats for my Flye assemblies. It seems like in most cases, v2.8.3 has better BUSCO stats and is more contiguous than v2.9. Species no. 3 is the only one that shows clear improvements. That said, I think Flye did a good job, especially with the coverage we currently have.

<img width="1104" alt="Screen Shot 2021-10-05 at 3 28 08 PM" src="https://user-images.githubusercontent.com/53409202/136090334-51272218-97a5-42b2-b90d-b78d6c9620c0.png">

**Comment by mikolmogorov** [comment]
@sjfleck thanks for the detailed report.

Looks like there are a couple of things going on. `--nano-hq` mode expects error rate at around 4-5% (e.g. Gupppy5 in SUP mode). Based on the logs, your reads have ~10% error. This could be either because you used basecalling mode other than SUP, or the Guppy model does not perform very well on your organism. This likely causes the differences between 2.8 and 2.9. You will likely get a similar, or slightly better assmebly with 2.9 and `--nano-raw`.

Another point is that your genome seems to be highly heterozygous - which is currently a challenge for Flye (and other ONT assemblers). As you can see, it currently produces highly duplicated assembly. And more interestingly, with the improvements in read quality you will likely experience further reduction in N50 and increase in duplicated genes, as more haplotype differences become apparent.

Hope this helps,
Mikhail
