### ISSUE TITLE
Unable to download Flye 2.9

### ISSUE THREAD

**Issue by katievigil** [fenderglass/ABruijn#434]
Hi when I download flye it stays at version 2.8.3.
I used:
conda install flye

and 

conda install -c bioconda flye=2.9

Here is my error:
(base) tiong_gim@ANR-Danns-1L:~$ conda install flye=2.9-0
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - flye=2.9-0
  - libgcc-ng[version='>=9.4.0']
  - flye=2.9-0
  - libstdcxx-ng[version='>=9.4.0']
  - flye=2.9-0
  - python_abi=2.7[build=*_cp27mu]

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(base) tiong_gim@ANR-Danns-1L:~$ conda update -n base -c defaults conda
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

(base) tiong_gim@ANR-Danns-1L:~$ conda --version
conda 4.5.11

(base) tiong_gim@ANR-Danns-1L:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
(base) tiong_gim@ANR-Danns-1L:~$ python --version
Python 3.10.0

**Comment by mikolmogorov** [comment]
Something must be inconsistent in your conda environemnt, very likely Python version. Creating a clean envoronment and installing flye there should help: `conda create -c bioconda -n flye flye=2.9`

**Comment by Yutang-ETH** [comment]
Hi, 

I tried conda create -c bioconda -n flye flye=2.9, it worked on one of our two virtual machines but failed on the other. I guess the issue is related to the environment setting.

Best wishes,
Yutang
