### ISSUE TITLE
Expected error rates - nano-hq

### ISSUE THREAD

**Issue by elor77** [fenderglass/ABruijn#435]
I have a very basic question - when discussing expected error rates do you mean (or median) error rate from the run (e.g. output from NanoStat)?
I've just run the Guppy5 SUP base caller and am wondering which option to use

```
General summary:
Active channels:                    510.0
Mean read length:                 7,874.2
Mean read quality:                   12.7
Median read length:               4,975.0
Median read quality:                 12.8
Number of reads:              1,026,012.0
Read length N50:                 14,033.0
STDEV read length:                8,195.9
Total bases:              8,079,019,631.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:    1004091 (97.9%) 7989.9Mb
>Q7:    950231 (92.6%) 7734.5Mb
>Q10:   843435 (82.2%) 7012.3Mb
>Q12:   618553 (60.3%) 5135.1Mb
>Q15:   279564 (27.2%) 2143.5M
```

**Comment by mikolmogorov** [comment]
The expected error is a median over the dataset. I would try running with `--nano-hq` first, and look into error rate distribution in the top of the log file (it will appear after "Overlap-based coverage" message). You'll also see a cutoff line on this plot. If a good part of distribution is below threshold, then you should be good with `--nano-hq`, and otherwise use `--nano-raw` instead. You can also adjust expected error rate with `--read-error` option.

**Comment by gushiro** [comment]
@fenderglass how does the median and the  max threshold is calculated? Also, is this value is affected by highly heterozygous species? Thanks in advance

**Comment by mikolmogorov** [comment]
@gushiro median is calculated from read-read alignment identity, and is sampled based from the first few thousand reads. Max threshold is set up in the config file in case of `--nano-hq`. `--nano-raw` threshold is 10% + median. And this may be affected by highly heterozygous alleles.

**Comment by gushiro** [comment]
@fenderglass thanks. should I modify the threshold value if I know that my species is highly heterozygous?

**Comment by mikolmogorov** [comment]
@gushiro no, the default thresholds should work as long as the error rate of reads is as expected.

**Comment by schorlton** [comment]
@fenderglass , will add on here as basically in line with this issue:
1. Thanks as always for the amazing tool
2. Could I/Flye automatically estimate the optimal `--read-error` and input parameter (ie `--nano-hq` vs `--nano-raw`) based on the Phred distribution in the input FASTQ? For example, if I see median Q>20 (or another statistical test), go to the Q20 suggested settings with `--nano-hq  {} --read-error 0.03`, if I see median Q>13 (<5% error) go with `--nano-hq`, else go with `--nano-raw`? I know Phreds aren't always 100% accurate but they do give a reasonable guess of the data. Thanks!

**Comment by mikolmogorov** [comment]
@schorlton that's currently not possible. One "manual" way to do it would be to make a first trial run, check the error rate distribution in the log file and readjust the parameter if needed.

**Comment by schorlton** [comment]
> @schorlton that's currently not possible. One "manual" way to do it would be to make a first trial run, check the error rate distribution in the log file and readjust the parameter if needed.

Thanks for your response! Why should I not just infer error rate from the Phred qualities?

**Comment by mikolmogorov** [comment]
@schorlton I have not tested that approach, but as long as quality values are accurate, that's a possibility.
