### ISSUE TITLE
Different results using differente versions of Flye 2.7 and 2.8

### ISSUE THREAD

**Issue by felipelira** [fenderglass/ABruijn#436]
It appears that I am facing one issue regarding the release versions of Flye 2.7 and 2.8. I know that 2.9 exists, but I want to share with you that the current version at conda is the 2.7. 
In the comments from each release I read that there are not many differences in the assembly's results, but sounds rare that I got this huge decrease in LL_0069
For the same dataset, I obtained a different number of contigs and distinct lengths.

> Datasets	Len_v2.7 	  Frgs_v2.7 Len_v2.8 	Frgs_v2.8
> LL_69	**2743596	  42	         503741   	21**
> LL_96	**2536785    8	         1793143 	61**
> ST_715	        1795343	  2             1796066 	3
> ST_77	1931478	  1             1923231 	1
> ST_53	1783339	  1             1784649 	3
> ST_353	1802370	  2             1801455 	3
> ST_389	1889216	  2             1889892 	5
> SX_86	2855045	  4             2860450 	6

Did anyone face the same problem and which version's results did you choose?

Cheers

**Comment by mikolmogorov** [comment]
@felipelira Flye 2.9 should be available on bioconda - you can use the clean new bioconda environment if you have troubles with installing into an existing environment.

**Comment by felipelira** [comment]
@fenderglass , even if I create a clean environment:

  $  conda env create -n flye29 python=3.6
  $  conda install -c bioconda flye

But when I search for the flye version it's not the latest version. Could you suggest what's the reason?
  $ flye --version
     2.7-b1585

When I try to install setting the version and build, that's what appears.

Found conflicts! Looking for incompatible packages.                                                                                                             failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - flye==2.9=py36hb377018_0 -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.6 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31


Could you help me?

**Comment by mikolmogorov** [comment]
Try using the following command: `conda create -n flye29 flye=2.9`. If it does not work, there is probably something wrong with your conda distribution (maybe old conda version).
