### ISSUE TITLE
Scaffolding in Flye 2.9 and Flye 2.8

### ISSUE THREAD

**Issue by laura-valencia** [fenderglass/ABruijn#438]
Dear Flye developers,

I am creating assemblies of my model organism, and I want to compare which assembly works best for me. First I tried with Flye 2.9 without scaffolding. Then I tried --scaffold with Flye 2.9 and there was no visible improvement in the graph. 
My PI had used Flye 2.8 last year, and her graph looks well scaffolded. So I am trying now Flye 2.8, but now I have an " Error running minimap2" assembly problem.

So I need help in figuring out why Flye 2.9 did not scaffold my assembly (or maybe it did), and why I cannot run Flye 2.8. My priority is the scaffolding, so getting Flye 2.8 to run may not be necessary. 

Here is the Flye 2.8 log and command

[flye2.8.log](https://github.com/fenderglass/Flye/files/7394945/flye2.8.log)
[minimap_stderr2.8.txt](https://github.com/fenderglass/Flye/files/7394980/minimap_stderr2.8.txt)
[minimap2.8.log](https://github.com/fenderglass/Flye/files/7395151/minimap2.8.log)

`python /cluster/home/lauramv/Flye2.8/Flye-2.8.2/bin/flye --pacbio-raw /cluster/work/users/lauramv/pacbio-data/m64101_200402_093540_subreads.fastq --out-dir /cluster/work/users/lauramv/flye2.8-pre-scaffolded/ --threads 30 --genome-size 1.8g --asm-coverage 50 > rflye.log 2>&1`

Flye 2.9 log: with --scaffold option
[flye2.9.log](https://github.com/fenderglass/Flye/files/7394988/flye2.9.log)
[minimap2.9.txt](https://github.com/fenderglass/Flye/files/7394994/minimap2.9.txt)
Command:
`python /cluster/home/lauramv/Flye/bin/flye --pacbio-raw /cluster/work/users/lauramv/data/m64101_200402_093540_subreads.fastq --out-dir /cluster/work/users/lauramv/flye-scaffolded/ --threads 30 --genome-size 1.8g --scaffold --asm-coverage 50 > rflye.log 2>&1`
graph: 

<img width="559" alt="graph-pre-scaffolded-0ct2021" src="https://user-images.githubusercontent.com/28049490/138409672-373d5f80-780f-49c3-9a0a-722c5f20e95a.png">

And the Graph made by my PI with Flye 2.8, when scaffolding was made by default.

![SLFlye2 8_graph](https://user-images.githubusercontent.com/28049490/138409764-57496123-2b2e-4599-ae6e-cdaa9ff1dee3.png)

A graph of my very first assembly with Flye 2.9 (no scaffolding)
<img width="576" alt="flye_first" src="https://user-images.githubusercontent.com/28049490/138409941-fcaa5cc4-301a-4f7d-8827-bb43ced8a15e.png">

**Comment by mikolmogorov** [comment]
Scaffolding with v2.9 did work for you, but scaffolding does not affect the graph structure - so you will not see the effect from gfa. On most genomes it does not make any substantial differences in terms of N50 either.

To me the your 2.9 graph looks better - it is much less tangled and looks like some chromosomes were separated. N50 of 18 Mb is pretty good for PacBio data with your read length distribution.

Hope this helps,
Mikhail

**Comment by laura-valencia** [comment]
> Scaffolding with v2.9 did work for you, but scaffolding does not affect the graph structure - so you will not see the effect from gfa. On most genomes it does not make any substantial differences in terms of N50 either.
> 
> To me the your 2.9 graph looks better - it is much less tangled and looks like some chromosomes were separated. N50 of 18 Mb is pretty good for PacBio data with your read length distribution.
> 
> Hope this helps, Mikhail

Thank you Mikhail! Very quick response. This helps and is good news. 
What factors could affect graph structure? I will read more on it, but I am very curious to learn what you know about it.
