### ISSUE TITLE
Speed Issues

### ISSUE THREAD

**Issue by fbemm** [fenderglass/ABruijn#441]
Dear Mikhail, I am reassembly data with 2.9 and it seems Flye is much slower on some very small contigs. I think your recently introduced heuristics which is fixing this. Could you make an release out of that? Thanks a lot! F

**Comment by mikolmogorov** [comment]
Hi,

Not sure I understand - could you be more specific? Which datasets are you having troubles with, and compared to what? Could you also send the log files?

**Comment by mikolmogorov** [comment]
Closed due to inactivity. Feel free to reopen if you have any follow-ups.
