### ISSUE TITLE
Auxiliary files of benchmark assemblies

### ISSUE THREAD

**Issue by ghost** [fenderglass/ABruijn#442]
Hi,

I wonder if flye 2.9's benchmark assemblies have accompany data available somewhere, i.e. the graph and the assembly_info.txt? Particularly, the circular information would be interesting for the metagenome assembly. Inferring this from assembly + Hifi reads is doable, but I'd love to use the hints provided by flye if possible.

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Sorry for the late response - I can send you the files tomorrow. Which particular dataset(s) are you interested in?

**Comment by ghost** [comment]
Hi, thanks for the reply! Actually it's fine now, we decided to do the runs locally.
