### ISSUE TITLE
GFA output may not follow GFA spec?

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#443]
Thank you as always for amazing tool. As per my [issue](https://github.com/ggonnella/gfapy/issues/22) on the `gfapy` repo, I was having some trouble parsing Flye GFAs in `gfapy`. Apparently the Flye GFAs may not follow spec by including paths with only 1 edge? I am not a GFA spec expert so just passing along the message. Would appreciate your help in figuring out a solution...thanks as always!

**Comment by mikolmogorov** [comment]
Thanks - yes, some (in fact most) contigs would typically consist of one edge. I'm outputting all contigs for the sake of completeness. Having a single edge in a path does not seem to contradict GFA 1 spec though.

**Comment by schorlton** [comment]
Closing here as @ggonnella pushed a fix to gfapy. Thanks for your help @fenderglass in solving!
