### ISSUE TITLE
error installinng

### ISSUE THREAD

**Issue by senidr** [fenderglass/ABruijn#444]
Hi ive got the following error when i try to install.
cd /home/uqsidris/Flye-flye/lib/samtools-1.9 && ./configure --without-curses --disable-bz2 --disable-lzma --enable-plugins
/bin/sh: 1: ./configure: Permission denied
make: *** [Makefile:28: /home/uqsidris/Flye-flye/bin/flye-samtools] Error 126

Cheers

**Comment by mikolmogorov** [comment]
It seems that your file system does not allow file execution - might be an issue with mounting parameters. I suggest to use bioconda for installing.
