### ISSUE TITLE
Long running time?

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/ABruijn#445]
Hi,

I am trying to use the latest Flye (2.9) to assemble Guppy5-SUP ONT reads that were Illumina corrected with Ratatosk. The dataset is HG002, about 80x data if I remember correctly. I am using the `--nano-hq` option but not the `--keep-haplotypes`. I gave the job 500 GB of RAM and 24 threads, it's been running for 5 days now and it is still doing the first step `00-assembly`. Is this running time more or less expected?

Thanks.
Guillaume

**Comment by mikolmogorov** [comment]
Hi,

It's definitely taking a bit longer than expected - could you send the `flye.log` file?

**Comment by GuillaumeHolley** [comment]
Sure, please find the Flye log file enclosed. This step is still running as we speak but the job is probably going to be running out of time soon.

[flye.log](https://github.com/fenderglass/Flye/files/7511576/flye.log)

**Comment by mikolmogorov** [comment]
@GuillaumeHolley ok, you have 500Gb of reads, which is probably why it is running for so long. I suggest adding `--asm-coverage 50`.

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

Indeed, I am just realizing that my coverage estimation was completely off.  Thanks for noticing and suggesting the coverage option. 

Guillaume
