### ISSUE TITLE
Error running minimap2

### ISSUE THREAD

**Issue by panpanchen123** [fenderglass/ABruijn#446]
Dear Flye developers,
     I have run into an error while running minimap2,the error is as follows:
    INFO: Starting Flye 2.9-b1768
[2021-11-09 19:58:42] INFO: Resuming previous run
[2021-11-09 19:58:42] INFO: >>>STAGE: consensus
[2021-11-09 19:58:42] INFO: Running Minimap2
[2021-11-09 20:28:20] ERROR: Error running minimap2, terminating. See the alignment error log  for details: /apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/g
uppy_basecall/flye_11_basecall_out/10-consensus/minimap.stderr
[2021-11-09 20:28:20] ERROR: Command '['/bin/bash', '-c', "set -eo pipefail; flye-minimap2 '/apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/guppy_basecall/fl
ye_11_basecall_out/00-assembly/draft_assembly.fasta' '/apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/guppy_basecall/fast5_basecall_all_pass.fastq' -x map-on
t -t 20 -a -p 0.5 -N 10 --sam-hit-only -L -K 5G -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T '/apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/gu
ppy_basecall/flye_11_basecall_out/00-assembly/draft_assembly.fasta' -u - | flye-samtools sort -T '/apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/guppy_basec
all/flye_11_basecall_out/10-consensus/sort_211109_195842' -O bam -@ 4 -l 1 -m 4G -o '/apps/users/Chenpanpan/11_sample_kxc/11_three_generation/modify_data/guppy_basecall/flye_11_b
asecall_out/10-consensus/minimap.bam'"]' returned non-zero exit status 137
[2021-11-09 20:28:20] ERROR: Pipeline aborted

please help me to show what I can do to slove this problem, I will appreciate it .

Thanks and cheers，
 ###
[flye.log](https://github.com/fenderglass/Flye/files/7505001/flye.log)
[minimap.stderr.txt](https://github.com/fenderglass/Flye/files/7505018/minimap.stderr.txt)
 panpan

**Comment by GuillaumeHolley** [comment]
Just had the same issue: from your _minimap.stderr.txt_, you can see that minimap2 was killed by your system, most likely because it ran out of memory. Just use a different machine with more RAM and use the `--resume` on your Flye command line to tell the assembler to continue from the last completed step.

Guillaume

**Comment by panpanchen123** [comment]
> Just had the same issue: from your _minimap.stderr.txt_, you can see that minimap2 was killed by your system, most likely because it ran out of memory. Just use a different machine with more RAM and use the `--resume` on your Flye command line to tell the assembler to continue from the last completed step.
> 
> Guillaume

Thank you for your help, and I will try it again with more RAM.

**Comment by mikolmogorov** [comment]
Closed doe to inactivity, feel free to follow up if you have more questions!
