### ISSUE TITLE
Why N50 reduced after repeat resolved?

### ISSUE THREAD

**Issue by zhangrengang** [fenderglass/ABruijn#447]
It seems that the N50 reduced from 1.8 Mb to 0.7 Mb after repeat resolved with a plant genome:
```
00-assembly/draft_assembly.fasta:  N50  1785828 bp              L50     288
10-consensus/consensus.fasta:  N50      1811777 bp              L50     284
30-contigger/contigs.fasta:  N50        743570 bp               L50     743
40-polishing/polished_1.fasta:  N50     749782 bp               L50     743
```
Why do repeat-resolving not improve the N50? Can I use the `10-consensus/consensus.fasta` as the primary assembly?

**Comment by mikolmogorov** [comment]
Not uncommon to see for highly repetitive genomes. The disjointig assembly process is optimistic and can assemble though "unresolvable" repeats. The disjointig/consensus files may contain many misassemblies and should not be used for downstream analysis.
