### ISSUE TITLE
Flye occasionally misjoined two different chromosomes (ONT data)

### ISSUE THREAD

**Issue by yjx1217** [fenderglass/ABruijn#45]
Hello,
I tested Flye on both pacbio and nanopore dataset from the budding yeast and in general I found Flye did a pretty good job with much shorter processing time than Canu (especially on the nanopore data). However, in my test with the nanopore data, Flye misjoined two different chromosomes, presumably based on their shared chromosome-end structure (e.g. telomere repeats). I checked the available parameters but didn't find much space to tweak. I was wondering if you have some specific recommendations. I can send my testing data for your check if this can help with the future development of Flye. Thanks in advance!

Best,
Jia-Xing

**Comment by mikolmogorov** [comment]
Hi,

There are not too many parameters to tweak for a user (a few of them are inside config files, but they require good knowledge of the internal algorithms). The main one would be minimum overlap size - if you have enough read length and coverage, you might try to increase it manually a bit (to say, 7k).

Otherwise I will be happy to take a look on the data - you can send me an email at fenderglass@gmail.com

**Comment by yjx1217** [comment]
Hi Mikhail ,

Thanks for the information! I have tried to increase the --min-overlap option to 6k and 7k respectively in two independent runs. The "7k" run solved the problem. 

Best,
Jia-Xing

**Comment by christinawu2008** [comment]
Hi Mikhail,

I'm wondering how FLYE dealt with nanopore chimeric reads? A few of my reads contain telo-like repeats (some are long) in the middle, will FLYE split/remove them? 

Thanks,
Chen

**Comment by mikolmogorov** [comment]
Hi Chen,

Flye is aiming to accurately resolve repeats, including telomere sequences.

Mikhail

**Comment by christinawu2008** [comment]
Hi Mikhail,

Thanks for your response. For my case, I don't really see all telomeres at the ends of contigs. Only two are located at the expected locations. I'm trying to figure out what is the problem. I found a relatively high ratio of raw reads containing telomeres in the middle in this dataset compared with other (may indicate more chimeric reads, not sure why), and my flye overlapped_length was 4k (auto-detected). The genome is over 500M. Do you a clue of what might cause the problem?

Thanks

Chen

**Comment by mikolmogorov** [comment]
Hi Chen,

Hard to tell what is going on without looking into the data, since the question is very specific. In general, Flye should assemble into telomeres as long as pericentromeric regions were also assembled. But pericentromeric regions might also be difficult to assemble.

Best,
Mikhail
