### ISSUE TITLE
lowering cutoff coverage for metagenomes and unused reads

### ISSUE THREAD

**Issue by nayden8** [fenderglass/ABruijn#450]
Hi, 
thanks a lot for Flye! It's been super handy using it in the last two years. I typically assemble metagenomes, i.e. a mix of two genomes - a vertebrate and a parasite, the latter represented in the sample at lower coverage. This works well without the meta flag from hifi reads, down to coverage of 5-7 for the underrepresented genome. 
I am interested how to make Flye (or some other tool) assemble reads with coverage which is occasionally lower than 3 and how you would recommend to keep or retrieve (and assemble) unused reads, which may still contribute to an assembly with hic data. Using the meta flag does not seem to do this trick. 
I realise that coverage of 1-2 means to accept the raw errors of the sequencing platform but for hifi this is relatively low and still better than no reads. Mapping to references does not always work because reference organisms may be too distant and sequence identity is often too low. I tried changing min_read_cov_cutoff in asm_hifi.cfg but this does not seem sufficient and maybe tweaking k-mer size and asm_defaults.cfg is necessary? What would you recommend? 
This is a snapshot of what the case looks like. None of these reads seem to have been assembled.
![lowcoverage_reads](https://user-images.githubusercontent.com/65156385/142648112-41645a8a-8fb5-4eda-9558-e407c59815e0.png)

**Comment by mikolmogorov** [comment]
I would make sure that you are running the latest release (2.9), and add `--read-error 0.01`, `-m 1000` in addition to `--meta`. Also check if the file `30-contigger/contigs.fasta` has more assembled sequence, as there is some additional filtering during polishing step.
