### ISSUE TITLE
--nano-hq in flye v 2.8.3

### ISSUE THREAD

**Issue by Hedi65** [fenderglass/ABruijn#453]
Dear all 

i tried to use --nano-hq option in flye v 2.8.3 but i got following error. 

flye --meta --plasmids --nano-hq --nano-raw /home/me/Documents/TINE_1_Barcode_11_Trimmed.fasta --out-dir /home/me/Documents/Flye_OUT

flye: error: unrecognized arguments: --nano-hq

AND

flye --meta --plasmids --nano-hq /home/me/Documents/TINE_1_Barcode_11_Trimmed.fasta --out-dir /home/me/Documents/Flye_OUT

flye: error: one of the arguments --pacbio-raw --pacbio-corr --pacbio-hifi --nano-raw --nano-corr --subassemblies is required

this option should be there or am i wrong ?

Best

**Comment by mikolmogorov** [comment]
`--nano-hq` was introduced in Flye 2.9
