### ISSUE TITLE
Polishing of assembly containing Ns

### ISSUE THREAD

**Issue by dominik-handler** [fenderglass/ABruijn#456]
Hi,

I would like to use the flye polishing module to polish my assembly after scaffolding. As far as I can tell flye automatically converts the Ns indicating assembly-gaps into random sequence. Is there an option to avoid this behavior? 

Thank you,
Dominik

**Comment by mikolmogorov** [comment]
Not possible with the current code, unfortunately. A workaround could be to manually split scaffolds, polish, and then reconnecting them back.
