### ISSUE TITLE
optimizing threads at various Flye stages

### ISSUE THREAD

**Issue by csgenomics-admin** [fenderglass/ABruijn#459]
Hello Mikhail,

Quick question regarding Flye and the usage of the `--threads` parameter. The [usage doc](https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md) describes this parameter as the number of parallel processes, but I noticed that some portions of the Flye pipeline may hard-code these parallel processes depending on the piece of software. For instance, I believe that **samtools sort** is set to 4 threads when your [alignment.py](https://github.com/fenderglass/Flye/blob/b5b74ead6d0e3e72288a48834fc6a613a733617b/flye/polishing/alignment.py#L237) script is launched. On the other hand, it looks like the **minimap** step in the same alignment script will use the same number of processed declared by the user based on their `--threads` value. 

It got me to wondering whether I've been over-allocating the amount of threads for the job, if there's a cap of 4 threads for the sorting process. Or perhaps the `samtools sort` command isn't much of a bottleneck, and that dedicating more threads (say 24) will certainly improve the workflow because the program spends more time mapping reads than it does sorting the alignment file?

Congrats on the Stadtman Investigator award, and best of luck as you begin your new gig at NCI.

**Comment by mikolmogorov** [comment]
Hi,

In my experience having more than 4 threads rarely makes a difference. And extra threads potentially consume more RAM and can overload IO. And you are right - overall it is a very small part of the entire pipeline when only `samtools sort` is working. Feel free to experiment with different value, but I doubt it will make significant difference.

**Comment by csgenomics-admin** [comment]
Great, thanks for the feedback.
