### ISSUE TITLE
what's the difference between repeat and mult. in 'assembly_info' file?

### ISSUE THREAD

**Issue by gyudae** [fenderglass/ABruijn#461]
hello, i just have a question about the assembly result.
As all know, we can get assembly_info file after assembly is finished.
and i cant understand what's difference between repeat and mult.

Anybody can explain.,.,.?
Thanks!

**Comment by mikolmogorov** [comment]
Repeat means a contig appears multiple times in the genome. Multiplicity is an estimate of how many times, based on coverage.
