### ISSUE TITLE
flye

### ISSUE THREAD

**Issue by kangxum** [fenderglass/ABruijn#462]
hallo, I'm learning flye now
I don't know how to deal with this problem
I need  help
thank you
![企业微信截图_16402479815364](https://user-images.githubusercontent.com/96557832/147211319-0478831f-03c9-4143-83d8-3eee9b710f63.png)

![企业微信截图_16402278537556](https://user-images.githubusercontent.com/96557832/147211263-7e8e7f2c-cd53-4ba3-9602-6579a6afb34e.png)

**Comment by gyudae** [comment]
i think you should write genome size like 2.5g, not 250000000

**Comment by mikolmogorov** [comment]
You have a fatsta formatting error
