### ISSUE TITLE
Different Flye assembly results with ONT data depending on version Guppy used to basecall the same data.

### ISSUE THREAD

**Issue by kneubehl** [fenderglass/ABruijn#463]
Hello,
A little background: I have a protocol which generates two full-length mitogenome amplicons (~14.5kb in length each) and sequence these with R10.3 flow cells with the rapid kits from ONT (~150x coverage). I have used ONT data basecalled with Guppy v5.0.7 and Flye 2.8.3 with the `--meta` and `--threads 35` and this worked great to generate a full-length, circularized mitogenome for this particular sample I am using. I have 90ish samples and I noticed this issue in a number of them. I recently re-basecalled all the data with Guppy v6.0.1 and processed the data the same as with the v5.0.7 data and noticed that I could not generate the same assembly despite repeated attempts using the same parameters for Flye. I also tried Flye 2.9 with the v5.0.7 data and v6.0.1 basecalled data and Flye 2.9 was not able to generate a complete mitogenome in either case. I tried `--nano-raw` and `--nano-hq` with `--meta ` Flye 2.9 as well as different numbers of threads just in case that was an issue (8 or 35) and tried `--scaffold` in combination with these as well but in any case the mitogenome was not generated. I have attached the log files as well as the nanostats reports for the Guppy v5.0.7 and v6.0.1 data which shows they are quite similar. Any help or guidance on what to do to get Flye 2.9 to work would be appreciated. Thanks!
[flye_2.9_v6.0.1_meta_t35.log](https://github.com/fenderglass/Flye/files/7817944/flye_2.9_v6.0.1_meta_t35.log)
[flye_2.9_v6.0.1_meta_t35_scaffold.log](https://github.com/fenderglass/Flye/files/7817946/flye_2.9_v6.0.1_meta_t35_scaffold.log)
[barcode08_guppyv5.0.7.nanostats.txt](https://github.com/fenderglass/Flye/files/7817947/barcode08_guppyv5.0.7.nanostats.txt)
[barcode08_guppyv6.0.1.nanostats.txt](https://github.com/fenderglass/Flye/files/7817948/barcode08_guppyv6.0.1.nanostats.txt)
[flye_2.8.3_v5.0.7_meta_t8.log](https://github.com/fenderglass/Flye/files/7817949/flye_2.8.3_v5.0.7_meta_t8.log)
[flye_2.8.3_v5.0.7_meta_t35.log](https://github.com/fenderglass/Flye/files/7817950/flye_2.8.3_v5.0.7_meta_t35.log)
[flye_2.8.3_v6.0.1_meta_t8.log](https://github.com/fenderglass/Flye/files/7817951/flye_2.8.3_v6.0.1_meta_t8.log)
[flye_2.8.3_v6.0.1_meta_t35.log](https://github.com/fenderglass/Flye/files/7817952/flye_2.8.3_v6.0.1_meta_t35.log)
[flye_2.9_v5.0.7_hq_meta_t8.log](https://github.com/fenderglass/Flye/files/7817953/flye_2.9_v5.0.7_hq_meta_t8.log)
[flye_2.9_v5.0.7_hq_meta_t8_scaffold.log](https://github.com/fenderglass/Flye/files/7817954/flye_2.9_v5.0.7_hq_meta_t8_scaffold.log)
[flye_2.9_v5.0.7_hq_meta_t35.log](https://github.com/fenderglass/Flye/files/7817955/flye_2.9_v5.0.7_hq_meta_t35.log)
[flye_2.9_v5.0.7_hq_meta_t35_scaffold.log](https://github.com/fenderglass/Flye/files/7817956/flye_2.9_v5.0.7_hq_meta_t35_scaffold.log)
[flye_2.9_v5.0.7_meta_t8.log](https://github.com/fenderglass/Flye/files/7817957/flye_2.9_v5.0.7_meta_t8.log)
[flye_2.9_v5.0.7_meta_t8_scaffold.log](https://github.com/fenderglass/Flye/files/7817958/flye_2.9_v5.0.7_meta_t8_scaffold.log)
[flye_2.9_v5.0.7_meta_t35.log](https://github.com/fenderglass/Flye/files/7817959/flye_2.9_v5.0.7_meta_t35.log)
[flye_2.9_v5.0.7_meta_t35_scaffold.log](https://github.com/fenderglass/Flye/files/7817960/flye_2.9_v5.0.7_meta_t35_scaffold.log)
[flye_2.9_v6.0.1_hq_meta_t8.log](https://github.com/fenderglass/Flye/files/7817961/flye_2.9_v6.0.1_hq_meta_t8.log)
[flye_2.9_v6.0.1_hq_meta_t8_scaffold.log](https://github.com/fenderglass/Flye/files/7817962/flye_2.9_v6.0.1_hq_meta_t8_scaffold.log)
[flye_2.9_v6.0.1_hq_meta_t35.log](https://github.com/fenderglass/Flye/files/7817963/flye_2.9_v6.0.1_hq_meta_t35.log)
[flye_2.9_v6.0.1_hq_meta_t35_scaffold.log](https://github.com/fenderglass/Flye/files/7817964/flye_2.9_v6.0.1_hq_meta_t35_scaffold.log)
[flye_2.9_v6.0.1_meta_t8.log](https://github.com/fenderglass/Flye/files/7817965/flye_2.9_v6.0.1_meta_t8.log)
[flye_2.9_v6.0.1_meta_t8_scaffold.log](https://github.com/fenderglass/Flye/files/7817966/flye_2.9_v6.0.1_meta_t8_scaffold.log)

**Comment by mikolmogorov** [comment]
Thanks for the report! I am expecting to be very busy within the next week or so, and will take a look once I have a chance.

**Comment by kneubehl** [comment]
Any thoughts on this?

**Comment by mikolmogorov** [comment]
Sorry for the detaled response! I see that the longest contig in Flye 2.9 assmebly is 13.4kb, and the longest one for 2.8 assemblies is 14.7kb. Most likely the difference is within a certain repetitive regions that is collapsed in 2.9 or expanded in 2.8. 

1. Did you try to compare the assemblies (e.g. visually using dot plots) to see what is exactly the difference? 
2. How do you know that 2.8, but not 2.9 version produces the right assembly (longer assembly does not always mean more accurate)?
3. Otherwise I do not see anything unexpected in the log files. I would need access to reads to dig in more - are you able to share them?

**Comment by kneubehl** [comment]
**1. Did you try to compare the assemblies (e.g. visually using dot plots) to see what is exactly the difference?**
This assembly is a mitogenome and in this particular sample there are duplicated control regions (this is consistent with this particular taxon). Dot plots show that in the 2.8 version the duplicated control region is present but the 2.9 version outputs the duplicated control region as a separate contig. These duplicated regions are not tandem duplications but are located about 4-5kb apart.
**2. How do you know that 2.8, but not 2.9 version produces the right assembly (longer assembly does not always mean more accurate)?**
The 2.8 version produces the longer contig which contains all the gene features of appropriate sizes consistent with mitogenomes of this and related taxa. Version 2.9 removes the duplicate control region and a tRNA.
**3. Otherwise I do not see anything unexpected in the log files. I would need access to reads to dig in more - are you able to share them?**
Sure. I can send these reads as well as reads from other problem assemblies via email. It is really interesting. I looked into if this duplicated control region issue was recapitulated in other samples that also have duplicated control regions and it is hit or miss. What still confuses me is why the v5.0.7 of guppy produces reads that generate a full mitogenome in flye v2.8 but that v6.0.1 produces reads from the same FAST5 files that don't produce a full mitogenome. The difference between flye v2.8 and v2.9 of the same data would make sense but differences in the basecaller version of the same data is odd. Particularly for this data set since according to the guppy release notes there weren't any changes that should change anything. I was wondering if others had experienced similar problems. For now I will revert the data to guppy v5.0.7 and use v2.8.3 and then try v2.9 if 2.8.3 fails. Trying both versions has saved some samples with this dataset. 

This appears (at least to me) to be a more involved problem than I thought it would be. I will send what data you need and maybe we can figure it out. I plan on using this workflow a lot in the future so it would be nice if I could make use of the newer versions of flye. Thanks for your help!

**Comment by mikolmogorov** [comment]
I see - please send reads to fenderglass@gmail.com and I'll take a look. It sounds like it could be an issue with version 2.9 incorrectly collapsing a tandem duplication.

**Comment by mikolmogorov** [comment]
Marking as resolved due to inactivity - but feel free to follow up if you are still interested in digging into this.
