### ISSUE TITLE
RAM to assemble very large Nanopore datasets

### ISSUE THREAD

**Issue by lauren-mak** [fenderglass/ABruijn#464]
I'm working on assembling metagenomic Nanopore reads that happen to be very large (20GB - 101GB in file size, 23 - 118 giga-nucleobases). My datasets are quite a bit larger than the datasets that RAM guidelines are provided for (250 GB RAM for 10GB). 

Do you have any suggestions for de novo assemblies with very large Nanopore datasets? If I'm not able to assemble all of the reads at once, I'm thinking of randomly downsampling the dataset, as well as partitioning them according to their kmer content. Thanks for your help!

**Comment by mikolmogorov** [comment]
Please see the manual / FAQ for the suggestion wrt to RAM usage. Feel free to follow up here if you have specific questions.

**Comment by mikolmogorov** [comment]
RAM requirements for metagenomes vary a lot from dataset to dataset. Downsampling could be a good strategy if you original dataset does not fit into memory.
