### ISSUE TITLE
Why do different fastQ data volumes of the same individual lead to different sizes of assembled genomes  

### ISSUE THREAD

**Issue by qianqianqian0717** [fenderglass/ABruijn#465]
At first, the size of the genome assembled with the data measured by 40G Nanopore was about 460M, which was basically consistent with the results of genome survey made with Illumina data and Nanopore data. However, Later I added 40G Nanopore data and I zcat the two measured data and assembled them again, but the obtained genome size became about 876M. 
Genomes were assembled with: 
flye --nano-raw <file.fastq> --out-dir out_nano --genome-size 500m --asm-coverage 40 --threads 40

Why such a result was generated? I was wondering if you have any suggestions. Thank you.
Fang Li

**Comment by mikolmogorov** [comment]
Flye rarely produces large assmebly duplications, so it is safe to assume that another ONT dataset contains additional sequence. You can map ONT reads from different datasets on the larger assembly to figure out which one each contig belongs to. If genome is highly heterogeneous, you may be capturing two copies of each haplotype.

**Comment by qianqianqian0717** [comment]
Thank you very much for your reply. Next, I will check the assembly result according to what you said.
