### ISSUE TITLE
I cannot execute flye from Bioconda

### ISSUE THREAD

**Issue by ashwin-epidote** [fenderglass/ABruijn#467]
I have installed Flye with conda.
I get the following error while trying to execute ' conda run flye ' -

ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['flye']' command failed.

I have installed this in conda version 4.11.0. I have python3 as the default python on my system as per the requirements.

As I am not used to running conda and thus this might be a mistake I am making while running conda itself.
Any help in this is appreciated.
I apologise if this is a non- Flye related error, but. I could not find a solution to error number 33.
Thanks,
Ashwin

**Comment by mikolmogorov** [comment]
You don't need to do `conda run`. Once the package is installed (and the environment activated), use `flye` to invoke.
