### ISSUE TITLE
Low sequencing coverage assembly options? Mixed reads?

### ISSUE THREAD

**Issue by alelim-bio** [fenderglass/ABruijn#469]
Hello,

I am currently working on a large plant genome assembly and wanted to use Flye as a potential assembler. My questions involve the usage of PacBio and ONT reads. Currently, due to the nature of our sequencing, we have ~15x coverage with ONT reads (raw) and ~14x coverage with PacBio HiFi reads. Additionally, there is also ~44x coverage of Illumina reads. However, as you can see neither the ONT nor PacBio HiFi reads reach the minimum threshold of 20-30x coverage however, combined they barely meet the requirement. 

Therefore, to my understanding from the FAQ guide (https://github.com/fenderglass/Flye/blob/flye/docs/FAQ.md) you are able to combine ONT-raw and PacBIO-raw reads for assembly by merging the reads. However, as mentioned in issue #205 you are unable to combine PacBIO HiFi/CCS reads with raw ONT reads due to the difference in error rate. 

Instead, I was curious if it was possible to mitigate this by first correcting the ONT reads with the Illumina short reads thus decreasing the difference in error rate, and then performing the Flye assembly with the ONT-corrected and PacBIO HiFi reads? Is this a reasonable possibility, if not given your expertise might there be other alternatives that I could pursue?

Thank you for your time.

Kind Regards,
Alex

**Comment by mikolmogorov** [comment]
I am not aware of any methods that can error-correct ONT reads to HiFi quality. You can use a mix of reads following the advice from FAQ and `--nano-raw` (or `--nano-hq`). This will not take advantage of HiFi read quality, but still should be better that ONT reads alone. An alternative would be to perform two separate assemblies and then scaffold / merge. Or do a hifi assembly and then scaffold with ONT.
