### ISSUE TITLE
Smaller contigs than input reads in assembly

### ISSUE THREAD

**Issue by AGmccoy** [fenderglass/ABruijn#470]
Hello,

We are assembling a protist genome of approximate size 65-70Mb and have tried filtering reads by various lengths before assembly (1000, 5000, and 10,000 bp minimum read length). When we get the results flye "assembly_info.txt" file we see that there are considerable contigs under the specified minimum read length. Is flye breaking or splitting reads when it makes it assembly, or could there be something else going on? For example, we have several contigs less than 500 bp when our input reads were all larger than 5000 bp (via nanoplot), how can this happen?

Austin

**Comment by mikolmogorov** [comment]
Yes, Flye generates contigs base on the assembly graph and some residual contigs may be shorter than reads. Those most likely represent parts of the repetitive sequences that have unresolved copies somewhere in the genome. Typically they could be safely ignored for most applications.

**Comment by ursadhip** [comment]
Hello @fenderglass !

Thanks to you and your team for such a fantastic help to the community in the form of metaflye.

My query is in the same line as of @AGmccoy but it is in a **viral metagenomic** context.

From **Nanoplot** I am getting contigs having this stat like: <google-sheets-html-origin><style type="text/css"></style>

Top 5 longest reads and their mean basecall quality score |  
-- | --
1 | 43848 (8.8)
2 | 42802 (9.8)
3 | 42623 (8.4)
4 | 41354 (8.3)
5 | 40620 (8.0)

But after assembling with the **--meta** mode, and keeping all other parameters in default mode, the **longest contig length is 39153**. This is the case for all my samples.

Is the process rejecting/trimming those long reads?  As it is a metagenomic context, please enlighten me on how I should go about it.

The assembly_info and the log file is attached for your kind perusal.

[assembly_info.txt](https://github.com/fenderglass/Flye/files/8037137/assembly_info.txt)

[flye.log](https://github.com/fenderglass/Flye/files/8037128/flye.log)

**Comment by mikolmogorov** [comment]
@ursadhip There are many possibilities why contigs are shorter than maximum read length. First, there might be diverse virus families that share repeats. If they complex enough, such families may not be resolved completely, shortening the assmebly.

Second, Flye will not use (i) singleton reads that do not have any other reads that support them and (ii) chimeric reads. In my experience,  viral sequencing datasets may be enriched with chimeras, and they will also naturally show up as the longest reads.

**Comment by ursadhip** [comment]
@fenderglass Thanks a lot for explaining the possibilities!
Regards

**Comment by katievigil** [comment]
@fenderglass  is there anywhere in the output where I can get the mean and median contig sizes (nt)?
