### ISSUE TITLE
Edges with 0.0X Coverage in the Assembly Graph

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#473]
Thanks for the amazing software!

As per title, is this a rounding error?
![image](https://user-images.githubusercontent.com/10245822/151632180-1b3a735f-f8d3-4791-b314-4dbbf6f3807e.png)

Here's the relevant line from `assembly_info.txt`:
`contig_7        14641   36      N       N       1       *       4,7,-11,-12`

**Comment by mikolmogorov** [comment]
The coverage values are reassigned after polishing, and it could be that no reads were aligned to these edges. You can see pre-polishing values in this graph: `30-contigger/graph_final.gfa` In general, coverage for very short edges - that represent unresolved repeat segments - is not very reliable.

**Comment by schorlton** [comment]
Thanks for your response! Silly question, but If no reads align, should these edges not be trimmed from the graph as they're likely to be incorrect?

**Comment by mikolmogorov** [comment]
There is no easy way to do it with the current implementation.

**Comment by schorlton** [comment]
OK, thanks!
