### ISSUE TITLE
Filtered reads and contig size

### ISSUE THREAD

**Issue by newbieSLC** [fenderglass/ABruijn#478]
Hello, I'm trying to understand the output from a Flye assembly of Nanopore sequencing reads. I have alot of read coverage and am attempting to filter out small phage genomes before assembling, so I used seqkit seq -m 60000 to select only reads greater than 60K in length for the assembly. After running Flye, I have several contigs less than 10kb in length. How can that be if I'm only using reads longer than 60k for the assembly? How can there be contigs so much smaller than the read size?

[assembly_info.txt](https://github.com/fenderglass/Flye/files/8075301/assembly_info.txt)

**Comment by mikolmogorov** [comment]
See #470
