### ISSUE TITLE
Q: FASTQ multi-line support

### ISSUE THREAD

**Issue by ptrebert** [fenderglass/ABruijn#480]
Hi,
I am running flye v2.9 and get `ERROR: Fastq format error` for line 2 of the input file. I checked the file, and it is a multi-line FASTQ (!) file, so I assume flye cannot process these (yes, I know, they are uncommon). Just asking for a quick confirmation, or if there is something else I should be looking for. Thanks.
Best,
Peter

edit: I've seen #89, but there was no final statement about the cause of the error as far as I could see

**Comment by mikolmogorov** [comment]
Hi Peter,

Yes, multi-line FASTQ is currently not supported.

Mikhail

**Comment by mikolmogorov** [comment]
Is there a particular use case for multi-ilne FASTQ in the context of assembly? I've never seen a long-read dataset in this format before.

**Comment by ptrebert** [comment]
not as far as I can tell; I am using a third-party input file here, so I just wanted to make sure that the problem is what I think it is before moving on. Thanks for confirming that!
