### ISSUE TITLE
Polisher chunking adds errors not supported by reads at some chunk boundaries

### ISSUE THREAD

**Issue by mwykes** [fenderglass/ABruijn#481]
Though the polisher in Flye generally does a very good job, we've noticed that the chunking causes a few bp indels at some chunk boundaries (which are not supported by the reads). 

A workaround for small genomes is to set [chunksize](https://github.com/fenderglass/Flye/blame/d7db8013d5b61d4d4119398fa6d721f26b1ed1b7/flye/polishing/bubbles.py#L116) to larger than the genome size, but it would be great to have a fix that would scale to large genomes. 

I have emailed you a link to download reads and assemblies of a small bacterial assembly test case.

**Comment by mikolmogorov** [comment]
Thanks for sending the data. This issue should now be fixed in the latest `flye` branch. Feel free to give it a try, and if everything looks good, I'll add it into the next release.

**Comment by mikolmogorov** [comment]
Added to the 2.9.1 release
