### ISSUE TITLE
How are multiple input files handled?

### ISSUE THREAD

**Issue by lcouper** [fenderglass/ABruijn#483]
Hello! I have PacBio ccs reads for both a Low and Ultra Low input library prep (from the same individual insect). I am trying to run a flye assembly using these two ccs files as input. I was able to run this successfully by simply passing in the two input files. But now I am trying to understand how exactly this was handled - is there any documentation about this?  
I see there used to be a --subassemblies option that is no longer supported, and that tools like quickmerge are now suggested. I did generate a consensus sequence using quickmerge, however when I ran the flye assembly on this merged file, I got the error 'ERROR: No contigs were assembled - pipeline stopped'

**Comment by mikolmogorov** [comment]
With multiple files, Flye simply combines all reads from these files together. This is the recommended way to handle multiple libraries from the same sequencing technology.
