### ISSUE TITLE
Q: keep-haplotypes parameter

### ISSUE THREAD

**Issue by ptrebert** [fenderglass/ABruijn#485]
Hi,
I have a question regarding the `--keep-haplotypes` parameter (`v2.9-b1768`). I was hoping that the assembly output (human) would be roughly twice the genome size, which I set to 3.1g, but it is always around ~3 Gbp. Is this actually correct, or do I need to set the genome size parameter to 6.2g when using the `--keep-haplotypes` option? Thanks for the clarification.
Best,
Peter

**Comment by mikolmogorov** [comment]
Hi,

Flye current only produces haploid assemblies of genomes with low heterozygosity (e.g. humans). You can try using https://github.com/fenderglass/hapdup to produce diploid assembly.

Mikhail

**Comment by ptrebert** [comment]
Thanks for the clarification and the pointer to hapdup.
