### ISSUE TITLE
Hope for some suggest for assemble quality

### ISSUE THREAD

**Issue by Neo-xbx-00** [fenderglass/ABruijn#486]
Hi! I found the usage of flye is quite convenient, however I still face some problems and hope for some solution.
My raw Pacbio data is 163.7G with 193X; and I set my parameters just like these: --pacio-raw … -g 850m --asm-coverage 40 --iterations
Q1: I got an assembly with total length > 900M, why this will happen and how can I got an assmbly with length near my estimation (~850M)?
Q2: The busco value of my assembly was 89.0% (with mollusc_db10), and my N50 is 0.6Mb. It seems that my assembly is quite fragmentary. How can I improve it by setting some parameters?
Waiting for your nice reply!

**Comment by Neo-xbx-00** [comment]
@fenderglass

**Comment by mikolmogorov** [comment]
1. If it is a diploid genome, Flye might have assembled some portions of alternative haplotypes, that are divergent enough.
2. Flye does not have a lot of parameter to tune, and some options are listed in FAQ. High fragmentation might be due to high repeat content of high heterozygosity.
