### ISSUE TITLE
Is 10x-linked reads available to combine with Pacbio HIFi by using Flye?

### ISSUE THREAD

**Issue by ClarenceHsiang** [fenderglass/ABruijn#487]
Dear Flye developer team:

Good evening.

As shown in the topic, our current datasets are 10x linked reads and HiFi, is it possible that we use these two datasets for diploid genome assembly?

Thank you so much

**Comment by mikolmogorov** [comment]
Flye does not support 10x reads. One way to do this is to use 10x to scaffold after Flye assembly.
