### ISSUE TITLE
Retreiving reads that correspond to an edge in the graph.

### ISSUE THREAD

**Issue by thekswenson** [fenderglass/ABruijn#49]
Given an edge ID, we are trying to retrieve the reads for that edge.  The documentation does not describe how to do this.

Grepping for the ID didn't turn up anything.

Could you please add this to the docs?

**Comment by mikolmogorov** [comment]
Hi,

Currently, we don't provide this kind of output - we will likely to add this functionality in the next release.

In the mean time, you can take a look at "3-polishing/minimap_1.sam" file - it contains alignments of the reads to contigs, so if you extract primary alignment for each read you will get read-contig assignments. Note that some contigs might consist of multiple graph edges (described in assembly_info.txt)

**Comment by thekswenson** [comment]
Thanks for the response!

**Comment by jdmontenegro** [comment]
An optional approach would be to use the GraphAligner tool to align the raw reads to the assembly_graph.gfa produced by Flye. Then you can just filter the GAF alignment and select all the reads aligned to a specific edge in the graph. I do not think there are any toolkits to handle GAF alignment format at the moment, but GFAtools for handling the GFA format produced by flye is working wonderfully for me.

Cheers,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
Closing an old discussion - the solution above with GraphAligner is currently the recommended way.
