### ISSUE TITLE
Uncollapsed assembly in heterozygous regions

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/ABruijn#492]
Hi,

I have used Flye & Hapdup to make a haplotype-resolved assembly from Illumina-corrected ONT reads (haploid assembly made with Flye 2.9) and I am particularly interested in a large 32kb deletion. Here is a screenshot of IGV (from top to bottom: HAP1, HAP2 from HapDup and haploid assembly from Flye):

![asm](https://user-images.githubusercontent.com/1068338/161299951-883ab9bf-4393-47e5-b717-c46a58097d53.PNG)

The deletion is homozygous in the haplotype-resolved assembly while it should be heterozygous. I believe this is because the region is uncollapsed in the haploid assembly (so I end up with 2 contigs, one for each haplotype, instead of just one). I also believe the region is uncollapsed in the Flye assembly because it is highly heterozygous (large deletion surrounded by a cluster of SNPs on each side for one of the haplotypes).

Ideally, the problem would be solved if the region would be collapsed and would have the non-deletion haplotype in the Flye assembly. Would you have any recommendation on how to achieve this?

Thanks,
Guillaume

PS: I originally opened this issue [here](https://github.com/fenderglass/hapdup/issues/14) but I believe this problem is not related to HapDup.

**Comment by mikolmogorov** [comment]
Hi @GuillaumeHolley 

Sorry for the late response! I think overall your interpretation of what is going on is correct. The problem is likely due to Flye outputting uncollapsed representation of this loci.

purge_dups would have been the right way to go, but since it's a large deletion, it probably won't be mapped.

The first thing to check is that Flye indeed recognizes this as a heterogeneity (and produces a bubble). In this case, there is a solution. Flye tags all sequences from collapsed bubbles with `alt_group`, which are given in `assembly_info.txt`. Does the bubble insertion sequence has non-empty value in this column? If so, you can simply remove all contigs with non-empty alt_group.

Could you also send me the log file, assmbly_info and names of the contigs from the IGV plot?

Mikhail

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

Thanks for these info! I have enclosed the files you requested below. The larger contig with the deletion is `contig_2295` and the shorter one below we suspect to be uncollapsed is `contig_2296`. As you can see, the `assembly_info.txt` for the two given contigs here is:
```
#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_2295	1100288	62	N	N	1	*	2294,2295,2303,2304,2303,2304
contig_2296	32891	26	N	Y	1	30	*,2296,*
```
Given that `contig_2296` has a non-empty `alt_group` field, I imagine that a bubble was indeed produced but ultimately not merged. As per your suggestion, is it safe to remove all contigs with non-empty alt_group? Won't I end up with the opposite problem which is deleting duplications which are real?

In the context of Flye + Hapdup, the problem won't be solved with just deleting this extra contig unfortunately. The reason is that when remapping the reads back to the assembly, all the reads that were mapping "inside" `contig_2296` will now be unmapped ("best" case scenario, worst case being they map somewhere unrelated). Since hapdup uses the Flye polishing module and no reassembly is performed, the deletion will not be replaced in one of the haplotype. 

The only solutions I see (just some rough ideas):
- Flye (somehow) makes an "insertion-biased" haploid assembly (this might not be possible).
- Hapdup, instead of polishing, reassemble completely each haplotype as determined by the phasing of Margin. This would probably fix the issue in this scenario because the reads overlapping `contig_2296` and the boundaries of `contig_2295` would be phased by Margin. Disadvantage is that each assembly now works with 50% of the initial coverage.
- Related to the first idea, womehow, we use the information of the `alt_group` field in `assembly_info.txt` to select reads which would produce an "insertion-bias" haploid assembly that we could use directly as input of hapdup.

[flye.redacted.log.gz](https://github.com/fenderglass/Flye/files/8411791/flye.redacted.log.gz)
[assembly_info.txt](https://github.com/fenderglass/Flye/files/8411794/assembly_info.txt)

**Comment by mikolmogorov** [comment]
Ok, glad to hear - yes, I think deleting all contigs for which `alt_group` is not `*` should help.

Have you tried to redo read mapping without the alternative contig? As long as you have a few reads mapped over the deletion, hapdup should be able to capture this and reconstruct the insertion. I am assuming that you might have at least a few reads that span the 32kb region. Also sometimes minimap2 fail to align kb-scale indels, and splits alignments instead. The latest release is doing better in this respect and the behavior could also be tweaked using some parameters. In your particular case, SNP-rich regions that flank the indel might be challenging to align through as well, but increasing `-z` minimap2 parameter might help.

I would try the mapping-based approach above first. If not, we will somehow need to force Flye to always output the longest branch of the bubble. I though that it should already be the case, but something indeed went not as expected here.

**Comment by GuillaumeHolley** [comment]
This is very helpful, thanks. I actually tried to delete from the assembly all contigs which had less than 50% and more than 200% of the average coverage, hence `contig_2296` was deleted. I have then remapped the reads to this new assembly using the latest `minimap2` (`r2.24`) but it didn't change much because I do not have any reads overlapping fully the deletion (N50 is around 20kb but deletion is 32kb). And this is also a tricky region with segmental duplications around. Finally, as you mentioned, the 2 clusters of SNPs make things complicated and I am a little bit afraid that by increasing the `-z` parameter of minimap2 to solve this one problem, I start making things worse for regions that don't have any issues.

**Comment by GuillaumeHolley** [comment]
Given that I do not have any reads spanning completely the uncollapsed contig `contig_2296`, I tried something new today: extract all reads overlapping `contig_2296`, assemble them and make artificial reads from the newly assembled contig. These artificial reads are at least twice the size of the deletion (so at least 64kb). I then remapped those reads to a new assembly which didn't contain `contig_2296`. The idea was to see if I could trick `minimap2` into showing me the 32kb insertion on  `contig_2295` rather than just softclips. And the result is that `minimap2` still doesn't show the insertion but only softclips (see screenshot below).

![hapdup2](https://user-images.githubusercontent.com/1068338/161813566-70f5a13d-31a3-43df-8488-f1987c4ea8f7.PNG)

What's interesting is that the breakpoint for the insertion is not clearly delimited by the start/end positions of softclips, there is a 800bp difference which could indicate these 800bp are duplicated ay the beginning and end of the insertion?
Something interesting is when I look at the supplementary alignments for the artificial reads, they map at quite a few places (as I said, this is a tricky region so it's not too surprising). See screenshot below:

![hapdup3](https://user-images.githubusercontent.com/1068338/161814284-5718f894-fc8c-4f18-b3b0-4e8747e73c74.PNG)

I don't really know if the issue (`minimap2` not mapping with the insertion) is because of the few supplementary alignments for each reads of the duplicated sequence at the beginning and end of the insertion. Do you have any recommendation for increasing the `-z` parameter of `minimap2`?

Thank you,
Guillaume

**Comment by GuillaumeHolley** [comment]
Funnily, I had mapped my artificial reads using the `map-ont` preset. Using the `map-hifi` preset, I get the following:

![hapdup4](https://user-images.githubusercontent.com/1068338/161815642-09775b0d-be06-433b-974e-b19bca960b2b.PNG)

Instead of having the 800bp gap, I have now a 150bp overlap of the softclips. Still no insertion though.

**Comment by mikolmogorov** [comment]
Hi @GuillaumeHolley 

I see, thanks for the info. I pushed an update to `flye-devel`, which should force Flye to assemble the insertion sequence into the primary contig. With that, detection of the deletion by hapdup should become an easier task. Let me know if that helps. You can restart from repeat graph stage to save time. 

In addition, I've added a new option `--no-alt-contigs` that will remove all sequences with alternative ids (+some more for tips). I haven't extensively tested it yet though.

**Comment by mikolmogorov** [comment]
@GuillaumeHolley just a heads up - there was a bug with `--no-alt-contigs` option that could potentially lead to a crash. It should now be fixed in `flye-devel`.

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

Thanks for the heads up :) Fortunately, I have started Flye (from the `flye-devel` branch) this morning without this option. I figured I could still remove these alt contigs afterwards by scanning the `assembly_info.txt`. It is at the polishing stage right now so I don't think I'll see the results before tomorrow. I'll update you as soon as it is finished. Thanks!

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

The `flye-devel` run without the `--no-alt-contigs` option has completed (after restarting from the repeat stage). The assembly is slightly longer than before (765 Mbp vs 757 Mbp). N50 and longest fragment length are mostly the same. There is however a noticeable increase in the number of contigs (4520 vs 3789). The number of alt contigs as per `assembly_info.txt` has increased from 125 to 425.

For the problem at hand, it is a lot better as Flye chose the non-deletion allele over the non-deletion allele. See screenshot below (up: flye-devel, bottom: flye):

![hapdup5](https://user-images.githubusercontent.com/1068338/162167400-88ac4835-67bb-473c-bd0d-ea0b5947ddd3.PNG)

As you can see on the screenshot, even though the primary contig has been patched, the alternate contig remains. Furthermore, when looking at the `assembly_info.txt` for this contig, I get:

```
contig_2297	32892	20	Y	Y	1	30	2297
```
While in the previous assembly, the alt contig was an alternate path in the graph, this one is now circular (and its own connected component I assume).

**Comment by mikolmogorov** [comment]
Ok, getting there! Could you please send me `flye.log`, '20-repeat/graph_before_rr.gv' and `graph_after_rr.gv`?

**Comment by GuillaumeHolley** [comment]
So I have been using the following method recently to remove what I think are haplotigs:
1. Remap reads to assembly
2. Create list of candidate haplotigs based on coverage: contig is candidate if it has less than 60% of the mean coverage of the entire assembly
3. Variant calling on these candidates with Pepper + Margin + DeepVariant
4. Remove from the assembly the candidate haplotigs with less than 2 heterozygous variants with GQ>=20

I think this is a reasonable approach in general. Using it on the `flye-devel` assembly, step 2 has 996 contigs as candidate haplotigs (purely based on coverage). Pepper+Margin+DeepVariant couldn't actually complete during the Margin step because no heterozygous variants were selected by pepper. Having a look at all the `PASS` variants from Pepper, only 12 variants were heterozygous out of 3600+ variants and there were all one one contig. Meaning that probably the 995 remaining candidates would be probably filtered out during step 4.

**Comment by GuillaumeHolley** [comment]
Sure thing, I'll prepare that for you.

**Comment by GuillaumeHolley** [comment]
Here it is @fenderglass. Sorry for the delay.

[flye.redacted.log.gz](https://github.com/fenderglass/Flye/files/8444416/flye.redacted.log.gz)
[graph_after_rr.redacted.gv.gz](https://github.com/fenderglass/Flye/files/8444422/graph_after_rr.redacted.gv.gz)
[graph_before_rr.redacted.gv.gz](https://github.com/fenderglass/Flye/files/8444423/graph_before_rr.redacted.gv.gz)

**Comment by GuillaumeHolley** [comment]
One last thing @fenderglass (sorry for all the message): would you recommend the usage of the extra parameter `max_bubble_length=300000` as a way to more "aggressively" merge bubbles in Flye?

**Comment by mikolmogorov** [comment]
Oh wait, so the contig `2297` does have alt_group, right? So that means everything is as expected. If you filter out all alt contigs (or use `--no-alt-contigs` option, does hapdup recover heterozygous insertion? Probably `--no-alt-contigs` should be the default mode for the future releases.

Yes, you can try increasing `max_bubble_length`. The only potential issue is that sometimes an unresolved repeat with two copies may appear as a bubble.

**Comment by GuillaumeHolley** [comment]
`contig_2297` has indeed an alt group. I was thinking that maybe something was not completely as expected since the primary contig has the no-deletion allele but an alt contig (`contig_2297`) with the same sequence was also created. Either way, the most important is that with this new Flye version, the primary contig does not have the deletion. In general, I also think that if the `--no-alt-contigs` becomes the default, it should write the alt contigs in a different file (`assembly.alt.fasta`) rather than completely deleting them.

I have redone the assembly completely using `max_bubble_length=300000` but without using `--no-alt-contigs`. Before removing the alt contigs, I have remapped the reads to the assembly and this is the result for the primary contig:
![hapdup5](https://user-images.githubusercontent.com/1068338/162726696-e535550f-d4a5-4c32-a7e0-93ed2642754e.PNG)
From the mapping, we can see the 32 kb deletion as expected. The alt contig has almost no read mapping to it.

Now, I have removed from the assembly the alt contig candidates based on the coverage and variant calls. I am remapping the reads to the "new" assembly and running Hapdup. I'll let you know whether the issue is solved or not but this is looking good :)

PS: I am using a custom filtering replacing the one in HapDup. I found the filtering in hapdup was rather strict for my data, even with setting the allowed read error rate set to the max, and it was removing too many reads.

**Comment by mikolmogorov** [comment]
I see, thanks for the update! Yes, it is indeed not ideal to output the duplicated alternative sequence, I think the best way would be to do `no-alt-contigs` by default (or output alternative contigs in a separate file).

Yeah, read alignment does not look very promising.. I think the issue are the flanking regions with high substitution rates around the indel. The "right" was to solve this in the future is to retain the long bubbles and make hapdup phasing work with graphs - but this will require some work though.

**Comment by GuillaumeHolley** [comment]
So from the mapping, you think there is a low chance to end up with the heterozygous deletion in the final hadup assembly? It seems to me that there are quite a few reads supporting the deletion no (even with the high subtitution rate around the indel)?

**Comment by mikolmogorov** [comment]
True, there is some support. I guess I was hoping that minimap2 will actually align though the gap, but just the absence of read coverage might be sufficient, if phasing is good. Once you have phased bam (after margin phase part), feel free to send the IGV region (with reads split/colored by HP tag).

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

Here is the deletion after Margin phasing:
![hapdup6](https://user-images.githubusercontent.com/1068338/162976056-d38a519a-872e-4073-b474-1b46db42ecf5.PNG)
As you can see, phasing is not great:
- Many reads with the softclips overlapping the right breakpoint are not phased
- Seems to me there is a phase switch within the deletion: the reads with the softclip overlapping the left breakpoint are colored in blue (HP:2) but the reads overlapping the right breakpoint with the cluster of SNPs matching the deletion allele are colored in red (HP:1). 

I checked the file `margin/MARGIN_PHASED.phaseset.bed` but I couldn't find anything matching approximately the location of the deletion within the contig.

This being said, I did try to make a full run of Pepper-Margin-DeepVariant instead of just Pepper on the filtered BAM file. Then I haplotagged the BAM file using the final VCF of Pepper-Margin-DeepVariant and here is the result:
![hapdup7](https://user-images.githubusercontent.com/1068338/162978609-ae5790e4-2e49-4714-9238-8b4ac97396a8.PNG)
Not only all the reads overlapping the breakpoints are phased but they have one single haplotype. I am polishing that haplotype at the moment, will let you know asap if it fixes the issue.

**Comment by mikolmogorov** [comment]
Interesting! So the sequence was P-M-DV, and then `margin phase` for haplotagging? How long DV run took compared to the other stages (Flye polisher in particular)?

**Comment by GuillaumeHolley** [comment]
Exactly. Using 24 threads, P-M-DV took about 80min wall-clock time and `margin phase` took another 27min. Polishing the one haplotype afterwards without applying the inversion script from hapdup took about 55min.

However, the haplotype wasn't polished with the deletion although I can see now the 2 clusters of SNPs on the same haplotype. When polishing, I used the option `--polish-haplotypes 0,1` as in hapdup. I guess it tells Flye to polish the haploid assembly with the reads from haplotype 1 (`HP:1`) and the unphased reads (`HP:0` or no HP tag). In this case, I suspect this might be an issue here given that the unphased reads match the non-deletion allele, so technically haplotype 2, but we're trying to polish the deletion which is haplotype 1. Is it important to polish the assembly using unphased reads? I mean, if they are unphased, it means they most likely match exact the haploid assembly so no polishing is required isn't it?

**Comment by GuillaumeHolley** [comment]
Polishing with `1` rather than with `0,1` didn't change anything. I think that the `0,1` really means "only use `HP:0` and `HP:1`" and since Margin doesn't seem to tag the unphased reads at all, unphased reads are not used for polishing.

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

After my disappointing results from yesterday, it seemed that even with the best phasing in the world, the polishing was never going to patch the haploid assembly with the deletion, even with these obvious soft-clips. To be fair, even Sniffles2 doesn't call the deletion so probably it isn't that obvious. So I decided to go back to one of your first advice which is to tune `minimap2 `a little bit. Changing the Z-drop scoring (`-z`) didn't seem to affect the mapping in that region. However, increasing the size of the band (`-r`) had a drastic effect:
![hapdup9](https://user-images.githubusercontent.com/1068338/163182144-a44be377-8b01-45c7-a9a0-cf3a1134d575.PNG)
As you can see, the deletion is now rather obvious and fits perfectly the phasing. I am not very fond of this solution because I have no particular insight in these parameters and I don't know really if the values I chose are enough for other variants which might be affected by the same issue. Still, it works for this case so I am happy with this for the moment :)

I then polished haplotype 1 using Flye and here is the result:
![hapdup8](https://user-images.githubusercontent.com/1068338/163183088-42f7d8ee-f902-4598-b525-011ddc6f4b9e.PNG)
Upper track is a 175kb window of the polished Flye assembly from ONT + Illumina, bottom track is the HifiAsm-trio assembly from PacBio HiFi. Both assemblies look almost identical for this locus.

This issue started as a Flye issue but it concerns HapDup as well so I'll also mention the thread into the original HapDup issue I had open if anyone runs into the same kind of troubles. Thank you very much for having a look at the matter with me and providing a fix for Flye :)

Guillaume

**Comment by mikolmogorov** [comment]
Ok, great to hear! Increasing `-r` was a common practice with minimap2 for SV discovery until the version 2.18 (if I remember correctly, the one that introduced new chaining algorithm). But looks like it may still be beneficial for complex cases. Which `-r` value did you use? Also could you tell the minimap2 version?

And to sum up, the existing Flye + hapdup pipeline required the following changes: (i) Flye fix that always outputs the longer branch of the bubble + using `--no-alt-contigs` and (ii) increasing `-r` for the minimap2 alignment. I remember you also mentioned increasing read error tolerance for hapdup filtering - what was the value that you were using?

**Comment by GuillaumeHolley** [comment]
Oh I see, I didn't know it was quite common for SV calling. I used `-r 1000,40000` which basically doubles the default values. This is for the latest `minimap2`, v2.24.

Your summary is correct, I have the following deviation from this summary though:
1. I do not use `--no-alt-contigs` to remove haplotigs (yet?) but I do rather a combination of coverage + variant calling + phasing analysis after remapping the reads to the assembly. It takes much longer to run this QC but I get more detected haplotigs out of this pipeline than with `--no-alt-contigs` and I am confident in the result.
2. `-r 1000,40000` for `minimap2`
3. I use now a custom script for filtering the BAM file in hapdup. The problem was that I thought hapdup was filtering out too many reads around this large deletion, even when setting the max error rate in hapdup to 1.0. The script I have does not filter on the error rate. Among other things, I keep only reads with MAPQ>=20.
4. I do a full P+M+DV run instead of "just" Pepper in HapDup.

**Comment by HenrivdGeest** [comment]
> Funnily, I had mapped my artificial reads using the `map-ont` preset. Using the `map-hifi` preset, I get the following:

Just a minor comment, you could try minimap with -xsplice, that alows for huge indels without penalties.  The cigar string is different in this mode, but for IGV it should not matter. For variant callers is does make a difference. Otherwise the -xasm settings  are maybe worth a try.(xsplice also has some splice-site heuristics, so do no the exact brakepoint as the truth, it might be a few bp off)
