### ISSUE TITLE
PromethION duplicated IDs error

### ISSUE THREAD

**Issue by maguileraf** [fenderglass/ABruijn#495]
Hello, I am trying to assemble metagenomes sequenced with the PromethION. I successfully assembled 2 samples but for the rest of my samples I get the error on the screenshot. However, when I check my Fastq files, there are no duplicated IDs. Any idea on how to fix this?
![unnamed](https://user-images.githubusercontent.com/49694113/162289689-4b92d9ec-5d24-4454-a460-e32ce2fad5d0.png)

**Comment by mikolmogorov** [comment]
Could you post the output of `cat Allbarcodes_cat.fastq | grep <duplicated_read_id_from_log>`?

**Comment by maguileraf** [comment]
I found the error. This was done by someone else so I was checking for duplicates in the wrong file.
