### ISSUE TITLE
change kmer length

### ISSUE THREAD

**Issue by zhaotao1987** [fenderglass/ABruijn#496]
I wondered how can I change the default kmer length (k=17), I'd like to raise it up to 51, like the one used in hifiasm. I'm using hifi reads. 
The genome assembled by flye is much smaller than expected, not sure why is that? 
genome estimated 800-900m (one hap), but assembled only 300m (for two haps), which is very wrong... 
```
flye --pacbio-hifi \
BMK210908-AN714-01P0001-01.ccs.fastq \
--threads 60 \
--keep-haplotypes \
-o output_psin \
--genome-size 900m
```

**Comment by mikolmogorov** [comment]
You can add `--extra-params kmer_size=X`. But 17 is currently the maximum size that you can set. Increasing k does not have substantial impact on the assembly in general.
