### ISSUE TITLE
Flye or LJA going forward?

### ISSUE THREAD

**Issue by JohnUrban** [fenderglass/ABruijn#499]
Hi all,

Thanks for the great tools as usual. I remember messing around with ABruijn way back, but haven't needed to do much more assembly until now. It appears that Flye replaced ABruijn (a while ago). It also appears like LJA, which has shared authors/developers, is aiming to replace Flye in some ways as long reads become more accurate in general. Is that interpretation true? 

Approaching that from a different angle, I have 10-20x coverage of ONT reads with an N50 of ~125 kb using the Ultra-Long Kit. I've basecalled using the "Super Accurate" mode with the GPU version of Guppy. Given that information, would you recommend using Flye or LJA? And with what parameters? Feel free to comment on any other assemblers you think I should try.

Many thanks,

John Urban

**Comment by mikolmogorov** [comment]
Hi John,

LJA only works with PacBio HiFi, and Flye work for all kinds of long reads, ONT in particular. So there are no intentions to replace Flye. I'd suggest Flye with `--nano-hq` for your data.

**Comment by JohnUrban** [comment]
Thanks @fenderglass. I appreciate the quick response and tip.
