### ISSUE TITLE
Using Flye for Athena_meta

### ISSUE THREAD

**Issue by knguyenjcvi** [fenderglass/ABruijn#50]
Hello,

I am trying to get Athena_meta to work, and part of the pipeline involves flye.
I have tried using version 2.3.4 and 2.3.1 but I always get the same error related to flye-polish.
Can you help me identify a solution for this issue?
```
launching Flye OLC assembly
cmd flye --subassemblies ./results/olc/flye-input-contigs.fa --out-dir ./results/olc/flye-asm-1 --genome-size 1857551 --threads 4 --min-overlap 1000
Traceback (most recent call last):
  File "/usr/local/devel/BCIS/kevin/Flye-2.3.1/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/usr/local/devel/BCIS/kevin/Flye-2.3.1/flye/main.py", line 513, in main
    pol.check_binaries()
  File "/usr/local/devel/BCIS/kevin/Flye-2.3.1/flye/polish.py", line 41, in check_binaries
    raise PolishException(str(e))
flye.polish.PolishException: Command '['flye-polish', '-h']' returned non-zero exit status 1
```

Thanks in Advance,
Kevin N.

**Comment by mikolmogorov** [comment]
Hi,

Looks like there is a problem with installation. How did you compile/install the program? Could you go to the Flye directory and run 'bin/flye-polish'? If you installed into the system, you can simply run 'flye-polish'.

**Comment by knguyenjcvi** [comment]
I get this message:
```
./bin/flye-polish: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./bin/flye-polish)
```

**Comment by mikolmogorov** [comment]
Looks like the compiled and runtime versions of your C++ libraries are different. Did you compile binaries on the same machine as you are using for running? If so, then you might have environment conflicts - e.g. you might have different compiler versions with different set of libraries.

**Comment by knguyenjcvi** [comment]
That was the issue
