### ISSUE TITLE
How to skip 20-repeat step?

### ISSUE THREAD

**Issue by YuChrming** [fenderglass/ABruijn#502]
Hi!
I find the size of `10-consensus/consensus.fasta` is quite suitable with predicted but within a little misjoin. After repeat step, `30-contigger/contigs.fasta` was  not enough .So I want to skip this step, and how could I do?
Thanks a lot!

**Comment by mikolmogorov** [comment]
Repeat resolution is an integral part of the pipeline and can't be skipped. As you noticed, there are likely assembly errors after the consensus stage that are corrected during repeat resolution.
