### ISSUE TITLE
Assembling tandem repeats

### ISSUE THREAD

**Issue by JohnUrban** [fenderglass/ABruijn#503]
Hi,

I'd like to update an "old" Hi-C scaffolded Canu assembly by paying special attention to tandem repeats such as rDNA arrays and centromeres -- i.e. I'd like to target these as regions to improve upon in the assembly.

I saw the "centroFlye" publication and wondered if the concepts used therein are now incorporated into Flye more generally (?).

Do you have any recommendations on how to use Flye (or centroFlye), perhaps with TandemTools, to optimize assembling rDNA arrays and centromeres? I'm not against generating an entirely new assembly with the old data if that will help, but I'm thinking it will still need special attention nonetheless.

Best,

John

**Comment by mikolmogorov** [comment]
Hi,

No, centroFlye is a separate tool, it has not been incorporated to Flye and it would be difficult to do so. centroFlye requires a fair amount of tuning for each particular centromere, as they are quite diffetent.

Is this a human dataset? I am not aware of any algorithm that can currently assemble rRDNa from non-HiFi reads, especially in the case of diploid genomes. This is still an unsolved problem.

Mikhail
