### ISSUE TITLE
Over- or underreporting of structural variants or repeats close to contig borders?

### ISSUE THREAD

**Issue by andreaswallberg** [fenderglass/ABruijn#504]
Dear @fenderglass & Co,

We are working on a genome assembly of a peculiar species that has intermediate (<1%) heterozygosity for SNPs but notable structural polymorphism, in particular those that alter genome size, which occupy several % of the genome.

We have produced various test assemblies and we note that many of these SVs are statistically depleted towards contig borders, as are various repeats. This is seemingly opposite to our expectations (i.e. SVs or repeats should be enriched close to borders if they act to limit contiguity) but on the other hand I am not deeply familiar with the Flye algorithm.

In cases where contigs can not be extended due to ambiguity raising from SVs or weird repeats (heterozygous weird repeats), does the algorithm "back out", leading to , in general, under-reporting rather than overreporting of such causative features close to contig borders?

I admit that there may be lower power to detect some of these features close to borders anyway, but our patterns are so striking we would appreciate a hint about this.

Cheers!

**Comment by mikolmogorov** [comment]
Hi,

Contigs normally break at repeats, so it is strange that you see less repeats at contig ends. How do you detect them though? Flye tries not to overrepresent repeats at contig ends: if a repeat is covered by one contig, it may not be covered by another. The best way to check would be to look at the assembly graph around contig ends and see if there are indeed adjacent long repeats.

With respect to heterozygous SVs, it depends on their size. Indels up to 50kb might actually be collapsed by the algorithm, so you won't see them at contig ends. This could by changed by using `--keep-haplotypes`, which will preserve the bubbles on the graph. The contigs will not be extended into the SV areas in this case.

Best,
Mikhail

**Comment by andreaswallberg** [comment]
Many thanks for the feedback and sorry for the delay on my part!

Repeats were detected using multiple tools, including scans for both microsats, tandem repeats and interspersed repeats. We see in particular that those types of repeats that have longer average length of their motif or cycle are enriched towards the ends of contigs (although at the very edge, less than maybe a few hundred bps, all repeats are depleted).

SVs were detected by mapping back the long reads of the reference specimen and running Sniffles, SViM and combiSV to derive a putative set. Insertions and deletions get depleted towards the ends, while duplications are enriched somewhat. Inversions appear to not change frequency at all across contigs.

The organism is very small with a very large genome (12 Gbp) and due to being DNA-limited, the depth of coverage is still low. The genome is also highly repeated. The resulting assembly from Flye is only 8.8 Gbp, undershooting the expected by quite a bit.

However, the genome assembly is very complete in terms of genes (BUSCOs >94%) and we map back nearly all DNA data and nearly all RNA-seq data (96% of transcripts) to the genome. 

We suspect that there may be extensive structural variation in the genome, perhaps with many hemizygous regions as a consequence.

Do you have any recommendation for how to tweak the settings in Flye to have it export more sequence and approach the expected 12 Gbps?

**Comment by mikolmogorov** [comment]
Thanks for the update, high BUSCO score in conjunction with lower-than-expected assembly size suggest a lot of collapsed repeats. These are the most challenging genomes to assemble. Flye does not have a lot of parameters to tweak beyond what is described in FAQ. Make sure you are using the right read mode, maybe try increasing the minimum overlap parameter. If you have ONT, re-basecall using the latest model and use `--nano-hq`.

**Comment by mikolmogorov** [comment]
Marking as answered, but feel free to follow up here!
