### ISSUE TITLE
Display of collapsed assemblies of diploid genomes 

### ISSUE THREAD

**Issue by hungweichen0327** [fenderglass/ABruijn#507]
Dear community, 
As the sentences mentioned in README.md: "Flye will produce collapsed assemblies of diploid genomes, represented by a single mosaic haplotype." I want to confirm the display of genetic variants in collapsed assemblies.

If there is a heterozygous site of SNP (A/G), the nucleotide symbol of this site in the final assembly is R. Is that correct?

How about the indels and repeats? 
For the indels, if there is a heterozygous site of insertion (AG/-), how would Flye represent this in the final assembly? 
For the repeats, if there is a heterozygous site of copy number variation of AGGTC (3 copies/2copies), how would Flye represent this in the final assembly?

Thank you for the patience and look forward to your kind response.

**Comment by mikolmogorov** [comment]
Hi,

This will be either A or G, whichever is supported by more reads. Flye does not explicitly resolve heterozygosities, but rather will treat them as errors in reads. For more complex variants it is the same, Flye will try to polish the sequence without knowing that its diploid, and will generate alleles that are supported by more reads. Which essentially means that every heterozygous allele is selected by random.

Mikhail

**Comment by mikolmogorov** [comment]
Marking as resolved, feel free to post here is there are any follow ups.
