### ISSUE TITLE
what are good parameters for FLO-MIN106 (SQK-LSK109 kit) Guppy 5.0.16 de novo?

### ISSUE THREAD

**Issue by algrgr** [fenderglass/ABruijn#508]
Hello all,

I have a set of Nanopore reads generated with FLO-MIN106 flow cell, using SQK-LSK109 kit. Softwares: MinKNOW 21.05.25, MinKNOW Core 4.3.12, Bream 6.2.6, Guppy 5.0.16. Reads come from a haploid fungus with estimated ~40 MB genome size. I have variable number of reads per sample, from 100k to 500k. Reads N50/N90 in the worst sample: 6200/1200, the best sample: 28000/3100.

I was wondering, what in your opinion would be a good set of Flye parameters to make a quality _de novo_ assembly?

cheers,
alex

**Comment by algrgr** [comment]
Just as a follow up info. I test-ran Flye in two modes:

**--nano-raw**
**--nano-hq --read-error 0.03**

And got these logs. I feel that **--nano-hq** option is not quite suitable, because from the graph distribution median read error rate is higher than **0.03**, but **--nano-raw** mode feels wrong as well, because it sets error rate way higher than what I have.

![snapshot_logs](https://user-images.githubusercontent.com/106706429/171604761-6143abb4-8afd-4389-80b8-9fc3719264b3.jpg)

I'm not sure what would be the best: to run Flye using **--nano-hq** but adjusting **--read-error** to **0.07**, or should I just stick to **--nano-raw** mode?

cheers,
alex

**Comment by jmtsuji** [comment]
@algrgr To confirm, did you use the "Super high accuracy" model in Guppy to perform basecalling? This will result in a better median error rate than using the "High accuracy" model.

I think you cannot use `--nano-hq` with a `--rate-error` > 0.05, so I agree with you that it would be better to just use the `--nano-raw` flag if you cannot reduce your median overlap divergence.

If you have lots of reads, one other option is to pre-filter the reads by Q-score (e.g., to a minimum Q-score of 13) to further reduce the median error rate, but I'm not sure if this is "standard practice". Hope this helps.

**Comment by algrgr** [comment]
@jmtsuji thanks much for feedback! Base calling was performed by the sequencing company, and the config file was likely to be _dna_r9.4.1_450bps_hac.cfg_. 
Does that mean "High accuracy" mode, and not "Super high accuracy"?

In the meantime I ran **--nano-hq --read-error 0.08** (it was able to run), and curiously, this did not result in much better assembly, when compared to just plain **--nano-raw** mode.

Interesting idea on Q13 filtering and then assembly. This is sort of a trade-off between quality, read sacrifice and coverage. I'm curious what is better: 
- to do Q13 filtering, lose half of reads, perform **--nano-hq** assembly on reduced coverage; 
- or do **--nano-raw** assembly on higher coverage and more low-quality reads?

**Comment by jmtsuji** [comment]
@algrgr Yes, `dna_r9.4.1_450bps_hac.cfg` is a "high accuracy" model. "Super high accuracy" basecalling models end with "sup" (instead of "hac").

It might be worth seeing if you can basecall your data again using a "sup" model. Otherwise, I think you should use `--nano-raw` with Flye.

**Comment by algrgr** [comment]
@jmtsuji indeed, I'm leaning towards that as well

**Comment by mikolmogorov** [comment]
All good advice! I would make sure you have the SUP model. You can indeed tweak `--nano-hq` by increasing `--read-error` by a little bit. In most cases, assemblies should not be very sensitive to 1-2% changes in thresholds.

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
