### ISSUE TITLE
No scaffold generated

### ISSUE THREAD

**Issue by vagmita** [fenderglass/ABruijn#510]
This is more of how to question? I have 6 birds all diff genotype in 6 barcodes and the experiment is run 4 times. 
I ran flye with just 1 bird and 1. Exp, I didn't get any scaffold.fa but only contigs in assembled.fa. 

Question, how do I include all the birds in 1, can I just put all fastq in one place and use all at once. 
Is it ok to not get scaffold.fa coz as per what I understand that should be the assembly output. 
Any suggestions will be helpful. 
Thanks. 
Vagmita

**Comment by mikolmogorov** [comment]
Hi Vagmita,

Flye does not produce a separate scaffolds file. Please refer to the manual.

Best,
Mikhail
