### ISSUE TITLE
Out of memory with --pacbio_raw and a small dataset

### ISSUE THREAD

**Issue by mirpedrol** [fenderglass/ABruijn#511]
Hi,

I am trying to add flye as an [nf-core module](https://github.com/nf-core/modules) to use it in analysis pipelines.

For that, I need to add some tests to ensure the functionality of the module that run as GitHub actions. I can run the tests with --pacbio_corr, --pacbio_hifi, --nano_corr and --nano_hq, but --pacbio_raw and --namo_raw fail with an out of memory error.
When running this command on Gitpod they fun fine. I have also used a really small subset dataset, and it still fails, I attach the flye.log file:
[flye.log](https://github.com/fenderglass/Flye/files/8898987/flye.log)

Any help on how to solve this will be appreciated, thank you!

**Comment by mikolmogorov** [comment]
You likely need more memory for this dataset. Typical resource requirements are given in the manual. There is a small test case here, which should require less RAM: https://github.com/fenderglass/Flye/tree/flye/flye/tests/data. But you will likely need at least 8Gb for all indexing structures.
