### ISSUE TITLE
question about assembly results

### ISSUE THREAD

**Issue by quliping** [fenderglass/ABruijn#514]
Thanks so much for your software, it help me a lot in my research. But I currently have some problems. 
1) Here are two different kinds of assemblies generated by the same version of flye (v2.6) based on the same sequencing data of the same genome, while I got two different results at different times. I asssembled ten times recently but I never got the same result as the result from one year ago. I have no idea that is it because some softwares required by flye on my server was updated?
2) What dose the new p2, p3, p4 mean in the assembly graph? Is the truth probably one of the following: "circular p2, p3, and p4", or "circular p2+3 and p4", or "circular p2 and p3+4", or "circular p2+4, p3", or "circular p2+3 and p3+4", or "circular p2+3+4", or "linear p2, p3, p4"?
Here is my command line:
`flye -g 5m -t 24 --plasmids -o ./03_flye/TC12-54 --nano-raw ../02_nanopore_clean/TC12-54.nanodrop.fasta`

Looking forward to your reply. 

![flye](https://user-images.githubusercontent.com/39583607/176822486-2fdc62c7-02b6-4f17-828a-205c34b101ca.png)

**Comment by mikolmogorov** [comment]
Please see https://github.com/fenderglass/Flye/issues/509, Flye is not completely deterministic. 

I also highly suggest to use the latest 2.9 release. Feel free to follow up if you still puzzled by the assemblies from 2.9 version.

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up here if you have more questions!
