### ISSUE TITLE
unknown guppy version

### ISSUE THREAD

**Issue by pbelmann** [fenderglass/ABruijn#515]
Thank you for developing this tool!

I have a Nanopore dataset where I do not have the information about which Guppy version was used to generate the fastq files.
Which input Parameter would you recommend?

```
--nano-raw path [path ...]
                        ONT regular reads, pre-Guppy5 (<20% error)
--nano-corr path [path ...]
                        ONT reads that were corrected with other methods (<3% error)
--nano-hq path [path ...]
                        ONT high-quality reads: Guppy5+ SUP or Q20 (<5% error)
```

**Comment by mikolmogorov** [comment]
The important factor is read error rate, so you can make a selection according to it.
