### ISSUE TITLE
Running Minimap2 causes Flye to abruptly close 

### ISSUE THREAD

**Issue by matteo1313** [fenderglass/ABruijn#518]
Hello,

Has anyone gotten the issue where Flye closes down during the Minimap2 portion of the pipeline?  I have attached the last 2 lines of my log to this thread. Once Minimap2 begins, the terminal shuts down. Within my output directory I only have draft assemblies. 

Has this issue happened to anyone? Please help!

THANK YOU!

Best,
Matteo

[2022-07-25 00:27:29] root: INFO: >>>STAGE: consensus
[2022-07-25 00:27:29] root: INFO: Running Minimap2

**Comment by mikolmogorov** [comment]
Please provide full `flye.log` and `10-consensus/minimap2.err` files. Also check if anything from this thread applies: https://github.com/fenderglass/Flye/issues/501

**Comment by matteo1313** [comment]
Hello Mikhail, The issue was because I was running --nano-hq instead of --nano-raw. If I were to run --nano-raw I am getting the right outputs! Thank you!
