### ISSUE TITLE
Contig circularity

### ISSUE THREAD

**Issue by herber4** [fenderglass/ABruijn#519]
According to flye, the resulting chromosome Contig is circular, and it appears so when view the assembly graph with bandage. 

However, when I blast the ends of the chromosome they don't align to the other end but instead to somewhere in the middle of the chromosome. does this mean that the generated chromosome is not circular? how do I deal with this? is there another way to confirm circularity? 

This is a bacterial genome assembly from nano pore data. Resulting chromosomal Contig is ~4.9 mb. I have generated assemblies with many different options of flye but get the same issue. 

I am happy to provide logs, plots, whatever. 

Thanks, 

Austin

**Comment by mikolmogorov** [comment]
Hi Austin,

Circular chromosome ends are not expected to overlap in Flye (as opposed to Canu, for example). The ends are trimmed to be a circular continuation of each other.

Mikhail
