### ISSUE TITLE
Question about dual assembly

### ISSUE THREAD

**Issue by RenzoTale88** [fenderglass/ABruijn#520]
Good morning,
Are there any plans to introduce the generation of dual assemblies (see [here](https://lh3.github.io/2021/10/10/introducing-dual-assembly)) along side the consensus? I'm just curious if it is a feature you are considering to implement, or if you plan to leave that to HapDup. Thank you :)

**Comment by mikolmogorov** [comment]
Dual assemblies are generated by HapDup. Perhaps in the future it may be integrated with Flye, but at that time HapDup is packaged separately because of the Docker environment.

Mikhail
