### ISSUE TITLE
Why does higher coverage bring more fragments in assembly?

### ISSUE THREAD

**Issue by winter709** [fenderglass/ABruijn#524]
Hi,
I am using Flye to assembly bacteria genomes based on public Pacbio data. In a case, the Flye gave a result containing 21 contigs, perhaps because previously described "high coverage confuses Flye". I have tried meta genome mode and --asm -coverage 50/80/100 which return results containing more fragments. How can I get a whole assembly? 
[flye.log](https://github.com/fenderglass/Flye/files/9291691/flye.log)

**Comment by mikolmogorov** [comment]
Hi,

Short fragments could arise from sequencing artifacts, not uncommon to see with older long-read data. The higher is the coverage, the more artifacts may show up.

However if you focus on large contigs with high coverage, this should filter out the artifacts. Visualizing assembly graph may help too - you should see a circular contig or connected component per bacterial genome.

May also be a bad quality data. Also, older PacBio datasets at NCBI may have a subread splitting issue - the solution to that is described in FAQ.

Hope this helps,
Mikhail
