### ISSUE TITLE
Some pipelines fail due to number of threads being capped at 128

### ISSUE THREAD

**Issue by DeadlineWasYesterday** [fenderglass/ABruijn#527]
Hi, 

We have a SuperMicro ATX server running pairs of Epyc processors. We have 256 threads per node. I was running MaSuRCA earlier and the pipeline crashed due to Flye's thread cap at 128. Since AMD recently announced 96 core processors (384 threads per node), I thought it would be a good time to let you know about this.

Thanks.

**Comment by mikolmogorov** [comment]
Thanks. Flye will unlikely to benefit from more than 128 threads.
