### ISSUE TITLE
No assembly generated by flye

### ISSUE THREAD

**Issue by olu2016** [fenderglass/ABruijn#528]
Hi,
I'm interested in generating TCR chain assemblies (contigs ~ 600bp) from nanopore reads. I used the following command:

`flye --nano-raw Reads --threads 20 --asm-coverage 50 --genome-size 0.6k  --out-dir FLYE_RESULTS`

For some reason, I got the following error in flye.log:

`[2022-09-02 18:58:23] root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2022-09-02 18:58:23] root: ERROR: Pipeline aborted`

What is the solution for this problem? 

Thanks

**Comment by matteo1313** [comment]
I just got this issue today as well. I believe there is a bigger thread with some troubleshooting you can do. 

search "no disjointigs were assembled" in issues.

**Comment by mikolmogorov** [comment]
Duplicate of https://github.com/fenderglass/Flye/issues/128

Please see if anything there or in the FAQ applies. If it does not resolve your issue, please post the full `flye.log` and details about your dataset in the other thread.
