### ISSUE TITLE
Many more indels than expected

### ISSUE THREAD

**Issue by wvuvectors** [fenderglass/ABruijn#529]
I have several ONT read sets on an AT-rich bacterial genome, N50 about 15kb and coverages ranging from 17X to 75X. When I assemble them with flye - using either nano-raw or nano-hq modes - the resulting assemblies are single contig but riddled with indels. As a result, the gene calls are full of split ORFs that we know should not be split. Attached is one partial example, where the insertion occurs at the first visible A. Is this something that flye should be able to correct? Or is there a recommended pre-processing step that can resolve these indels? They appear in all of our data sets regardless of coverage. Thank you for any thoughts or suggestions!

![indels](https://user-images.githubusercontent.com/65204824/188518588-35ec8566-1a3d-4c88-b24d-22aa46e93484.jpg)

**Comment by mikolmogorov** [comment]
Hi,

Consensus indels remain a known issue for nanopore data. Here is so older discussion: https://www.nature.com/articles/s41587-018-0004-z

It gets better with recent basecallers, e.g. Guppy5 with super accuracy can produce Q35-Q40, or 1 error per 10kb. Or even better with R10.4 pore: https://www.nature.com/articles/s41592-022-01539-7

Overall, make sure you are using the latest Guppy in super accuracy mode, you can also try Medaka, but it seems to make little difference with the latest basecaller improvements.

**Comment by mikolmogorov** [comment]
Marking this as answered, but feel free to follow up if you have more questions.
