### ISSUE TITLE
Decreasing assembly merge mode minium overlap threshold below 1000

### ISSUE THREAD

**Issue by ohickl** [fenderglass/ABruijn#530]
Hi,
i know it has been stated previously that decreasing the minimum overlap for the assembly merge function below 1000 is not supported and in general not advised. I anyway changed https://github.com/fenderglass/Flye/blob/39eb9acff398abf48c33d02ce6bfd6d6af81f8f1/flye/main.py#L708 to compare the results to other tools when trying to merge a quite fragmented metagenome and its matched metatranscriptome. Did that change actually make any sense? I did not dive too deep into the code, so i am unsure if it was sufficient. I also did get some quite puzzling quast results, it seems that changing the threshold doesn't really do anything and also the number of large contigs is actually reduced compared to the MG assembly:
![report_Page_01](https://user-images.githubusercontent.com/49027995/189929419-e309ef9e-4e95-4a8a-9417-8406bcadee9a.png)
Am I overlooking something and this is actually expected?
Running Flye the following way:
```
(
# rename contigs in input files
awk '/^>/{print ">mg_contig_" ++i; next}{print}' ${i1} > ${o1}
awk '/^>/{print ">mt_contig_" ++i; next}{print}' ${i2} > ${o2}
cat ${o1} ${o2} | seqkit seq -j ${threads} -m ${len_cutoff} - > ${o12}
# consensus assembly
time flye --meta \
          --subassemblies ${o1} ${o2} \
          --out-dir $(dirname ${flye})\
          --threads ${threads} \
          --read-error ${read_error} \
          --iterations ${polishing_iterations} \
          --min-overlap ${min_overlap} > ${log} 2>&1
# align input contigs to assembly | get unmapped contigs | get contig IDs
flye-minimap2 -ax asm5 ${flye} ${o12} | samtools view -f 4 - | cut -f1 > ${uids}
# filter input contigs by contig ID
seqkit grep -w 60 -f ${uids} ${o12} -o ${ufna}
# add unmapped contigs | rename contigs
cat ${flye} ${ufna} | awk -v var=${sample} '/^>/{print ">"var"_contig" ++i; next}{print}' > ${final}
rm -rf ${o1} ${o2} ${o12} ${uids} ${ufna}
) &> ${log}
```
Best

Oskar

**Comment by mikolmogorov** [comment]
Hi Oskar,

I would not recommend reducing the threshold below 1000, since other algorithms and parameters were designed with minimum 1000 overlap in mind.

The number of contigs after merge could be reduced if there are conflicts between the input sequences. Note that the `--subassemblies` functionality is deprecated, and flye may not be the best tool for this taks.

**Comment by ohickl** [comment]
Ok, thanks!
