### ISSUE TITLE
metaFlye: PermissionError (Errno 1), no assembly_graph and assembly_info.txt. What to do?

### ISSUE THREAD

**Issue by Metag3nOmics** [fenderglass/ABruijn#532]
Hi fenderglass and community,

after running metaFlye with no interruptions I received the following Tracebacks and Errors (see below). The main output files should be assembly.fasta, assembly_graph.{gfa|gv} and assembly_info.txt. I only got draft_assembly.fasta (maybe I had to enter a name for that) and none of the other two files. Can I get those files after the run or do I have to repeat it? Also Permission Error (Errno 1) occured which I'm not sure of why (I tried to run flye with sudo but it did not recognize it as a command). 

Do you have any suggestions how to proceed from here?

Code readout: 
Traceback (most recent call last):
  File "/home/mambaforge/envs/flye_29/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.9.1', 'console_scripts', 'flye')())
  File "/home/mambaforge/envs/flye_29/lib/python3.10/site-packages/flye/main.py", line 840, in main
    _run(args)
  File "/home/mambaforge/envs/flye_29/lib/python3.10/site-packages/flye/main.py", line 583, in _run
    jobs[i].run()
  File "/home/mambaforge/envs/flye_29/lib/python3.10/site-packages/flye/main.py", line 273, in run
    shutil.copy(self.graph_file, self.out_files["graph"])
  File "/home/mambaforge/envs/flye_29/lib/python3.10/shutil.py", line 418, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mambaforge/envs/flye_29/lib/python3.10/shutil.py", line 307, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/home/Exchange_metag/Data/n9/out_n9/assembly_graph.gv'

**Comment by mikolmogorov** [comment]
Sorry for the late response!

This is a strange error. It seems that Flye successfully generated some files, but the file copy operation failed. Maybe you got unlucky and ran out of space at this exact moment. Or it may be something to do with file system permissions.

What OS is that? I would check you have full access rights to the flye output folder, and maye try outputting to your home directory. Does the same error occur on small test datasets (from the manual)?

**Comment by Metag3nOmics** [comment]
Sorry for the late reply!

I think it had something to do with the mount I was working on. Didn't occure while running it locally. 
Thank you for your help!
