### ISSUE TITLE
bam files for polishing

### ISSUE THREAD

**Issue by rmormando** [fenderglass/ABruijn#533]
I just ran an assembly on yeast genomes and i want to polish with pilon for my next step but they require a BAM file that has sequencing reads aligned to the assembled genome

does flye have an option to output a BAM file like that? Or is there an easy way to create a BAM file from the assembled.fasta file that meets these requirements?

**Comment by mikolmogorov** [comment]
@rmormando Flye does not produce these bams, you will need to run to run Illumina alignment with `assembly.fasta` as a reference file (for example, using bwa).

**Comment by kullrich** [comment]
Hi, for me it is not clear and I have not found any documentation or example in your doc how to use a BAM file with the --polish-target option. Could you please add such an example and also suggest if one should run, e.g. `minimap2` with the `secondary=no` option to create such a BAM file for polishing.
Thank you in anticipation
Best regards
Kristian

**Comment by mikolmogorov** [comment]
Hi Kristian,

If your question is about using Pilon, then I suggest looking in its documentation.

If your question about using `--polish-target` (for long-read polishing), then you can provide a set of reads and the pipeline will perform the alignment.

**Comment by kullrich** [comment]
No, the question is about this statement:
```
Bam file input for the standalone polisher (same interface as for FASTA/Q)

Paths to reads are specified similarly to the assembly mode, **and bam file could also be proveded instead of reads**
```

I have not found a working example for this BAM option.

**Comment by mikolmogorov** [comment]
For example, for nanopore reads: `--polish-target reference.fasta --nano-raw alignment.bam`
