### ISSUE TITLE
--scaffold generates more small contigs without generating scaffolds

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [fenderglass/ABruijn#534]
I run flye once with `--scaffold` and once without. When run with `--scaffold` there were no scaffolds generated with, which is absolutely fine and also the log says `Added 0 scaffold connections`. However, in the final output there are few more short contigs generated, which I would expect for both as I always add the `--meta` parameter. Is there a difference in the final reporting or on other computationnal steps?

Full commands:
flye --meta --scaffold -t 80 --nano-raw M3_noPCR_pass_fail.fastq.gz -o flye_metaPlasmid_M3_scaff_v2.9.1
flye --meta -t 80 --nano-raw M3_noPCR_pass_fail.fastq.gz -o flye_metaPlasmid_M3_v2.9.1  

Used version: 2.9.1

**Comment by mikolmogorov** [comment]
Hi,

Sorry for the late response. A few short contigs is likely explained by the indeterminism between runs, see https://github.com/fenderglass/Flye/issues/509. `--scaffold` may join contigs into scaffold, but should not add new contigs.
