### ISSUE TITLE
Flye stuck at polishing step

### ISSUE THREAD

**Issue by andreaswallberg** [fenderglass/ABruijn#537]
Dear developers,

We work on a large and repetitive genome that is very challenging to assemble. We have gotten through the contigger step on a big 80-core machine and have a set of contigs in 30-contigger. However, the subsequent polishing step timed out.

The polishing step seems to take very long, while running at 1600% CPU on a 16-core node on which we resumed the job (which we can access for a longer period of time).

The last output printed to the log (three days ago) is:

`root: INFO: Correcting bubbles`

But it has not yet logged any percentage (although this could be due to the shared filesystem buffering output before printing to logs).

I wonder if the set of contigs produced in the previous contigger step could be taken as an acceptable assembly end-point and be polished with separate external tools.

Any thoughts on this issue and how to deal with it?

**Comment by mikolmogorov** [comment]
I don't remember seeing the polisher truly stuck, but it definitely may take longer for certain highly repetitive genomes (with high read depth). If the process is consuming all (or most) CPUs that were given to it, is is likely in process. 

You can certainly try using other polishers in the `30-contiger/contigs.fasta`.
