### ISSUE TITLE
about metaflye:  shortest length of contig is shorter than shortest length of reads

### ISSUE THREAD

**Issue by ye00ye** [fenderglass/ABruijn#538]
Hello

I used metaflye to conduct HiFi reads assembly under --pacbio-hifi mode, and i found that the shortest length of contigs was shorter than shortest length of reads. I want to know why?

thanks for helping.

**Comment by mikolmogorov** [comment]
Hi,

Flye/metaFlye is using repeat graphs that are capable of splitting reads into smaller fragments that form graph sequences. Most of the times, such short edges represent assembly artifacts and may be ignored, especially if the reported coverage is low.

**Comment by ye00ye** [comment]
Now I know, thanks for your help. So just ignoring these short contigs directly.


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | Mikhail ***@***.***> |
| Date | 10/29/2022 02:56 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [fenderglass/Flye] about metaflye: shortest length of contig is shorter than shortest length of reads (Issue #538) |

Closed #538 as completed.
