### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by skr3178** [fenderglass/ABruijn#539]
Hi, 
Thank you for this sharing this work. I watched your presentation on oxford nanopore event.
I am wondering is there a tutorial for getting started on applying this tool?
Thanks! 

example
![image](https://user-images.githubusercontent.com/79299617/196587687-1e7edf72-5f00-497d-8e0b-75f963f61ed1.png)

**Comment by mikolmogorov** [comment]
Hi,

The manual contains a "quick start" example with a small dataset. I would start with that. There is a metagenome assembly tutorial that covers some basics: https://github.com/fenderglass/jax-meta-tutorial

**Comment by skr3178** [comment]
Thank you @fenderglass

**Comment by skr3178** [comment]
@fenderglass 
I tried running the tutorial. Couldn't locate this file:SRR13128014_1gb.fastq.gz

However, I found substitute in european nucleotide database: https://www.ebi.ac.uk/ena/browser/view/SRX9569057

`minimap2 -ax map-hifi assembly_graph.fasta SRR13128014_1gb.fastq.gz -t 30 | samtools sort > graph_alignment.bam
samtools index graph_alignment.bam`
