### ISSUE TITLE
GFA file after polishing [feature request]

### ISSUE THREAD

**Issue by sjackman** [fenderglass/ABruijn#54]
I see that Flye produces two GFA files:

```
2-repeat/graph_before_rr.gfa
2-repeat/graph_final.gfa
```

Could Flye also produce a GFA file after polishing?

As a work around In the mean time, can I take the sequence from `contigs.fasta` or `scaffolds.fasta` and use it to replace the sequence in `2-repeat/graph_final.gfa` ?

The GFA graph has 13 contigs including two repeats. The `scaffolds.fasta` file however has only 11 contigs, and the two repeat contigs (each ~20 kbp) are missing. Is there an option to includes these repeats in the `scaffolds.fasta` file?

**Comment by sjackman** [comment]
I used this AWK script to take the sequence from `scaffolds.fasta` the graph from `2-repeat/graph_final.gfa` and produce an `assembly.gfa` file.
```sh
seqtk seq scaffolds.fasta | gawk -vOFS='\t' 'ARGIND == 1 { id = substr($1, 2); getline; x[id] = $1; next } $1 == "S" && x[$2] { $3 = x[$2] } 1' - 2-repeat/graph_final.gfa >assembly.gfa
```

In my assembly, `contigs.fasta` and `scaffolds.fasta` are identical. Which should I use with `2-repeat/graph_final.gfa`?

**Comment by sjackman** [comment]
I'd also like to say that I ran Flye for the first time ever, and my first experience is great! I love that there's no overlap between the output contigs. All `0M` edges in the GFA file. I'm trying giving that graph as the input to Unicycler's `--existing_long_read_assembly` option to produce a hybrid assembly with Illumina reads. Also as the input to `spades-gmapper`, which aligns long reads to an assembly graph GFA file.

**Comment by sjackman** [comment]
After reading `assembly_info.txt`, I've discovered what happened to the two repeat contigs. Even thought neither repeat was fully resolved, each repeat was appended to two adjacent sequences:
```
seq_name   length   cov.  circ.  repeat  mult.  graph_path
contig_1   168585   13    +      -       1      1
contig_2   352837   15    -      -       1      2
contig_3   84271    11    -      -       1      3
contig_4   417027   16    -      -       1      4,-7
contig_6   1676157  14    -      -       1      5,6
contig_8   420138   14    -      -       1      8,-5
contig_9   551507   14    -      -       1      7,9
```
I'd prefer to keep the repeats separate. Is it possible to skip this step of Flye? I'd still like to polish.

I'm going to try using the `2-repeat/graph_final.gfa` file, which does not appear to have the repeats expanded, and polish that file with Racon.

**Comment by mikolmogorov** [comment]
Hi,

There are indeed a few different assembly stages that produce sequence output and probably require additional explanations. This is also a bit of terminology difference with OLC-based methods, which might be confusing. We are using repeat graph, where edges store sequences, and nodes correspond to branching points (and do not store sequence). Thus, an edge of a repeat graph roughly corresponds to a unitig on a string/overlap graph. Each edge of the graph is classified into unique/repetitive based on coverage and/or graph structure. Contig is a *path* on the graph, which consists of *one* unique edge and possibly multiple repetitive. Scaffold contains multiple uniqe egdes (is basically a list of contigs interleaved with Ns). So, regarding the output:

* graph_before_rr.fasta - corresponds to the *edges* of the repeat graph before repeat resolution.
* graph_final.fasta - *edges* of the graph after repeat resolution (unitigs)
* graph_final.gfa - final graph in GFA form (edges are identical to graph_final.fasta)
* graph_paths.fasta - contig sequences (correspond to paths on the final graph)

None of the above is polished (as you noticed) - the expected error rate is 1-2%, but there might be short segments of raw read quality as well.

In the end Flye basically polish graph_paths file and produce "contigs.fasta" and "scaffolds.fasta". As you noticed, you can see how contigs/scaffolds traverse the graph from "assembly_info.file".

So is polished edges of the graph something that you are looking for? We probably can make it an optional feature in the next releases (or somehow polish both contigs/edges at once, but I am not sure how to do it from the top of my head).

**Comment by sjackman** [comment]
From your description, yes, it sounds like I'm looking for polished edges in a GFA, rather than the default output of polished contigs in a FASTA file. Thanks for your response!

Before reading your response, as a bit of a shot in the dark, I tried editing the file `asm_raw_reads.cfg` and setting `extend_contigs_with_repeats = 0` (default = 1), and it did affect the assembly, but did not have the desired effect.

**Comment by mikolmogorov** [comment]
This parameter controls whether contigs are extended using the graph structure, but if it is not set, Flye will still use flanking reads to extend contigs - it is used to slightly increase accuracy in "subasseblies" mode.

**Comment by mikolmogorov** [comment]
The latest version from the "flye" branch now outputs GFA with polished graph edges - let me know how it works for you.

**Comment by sjackman** [comment]
Thanks, Mikhail! In the mean time, I used `unicycler_align --no_fix_local`, which uses Pilon, to polish individual base errors of the Flye edges. See https://github.com/rrwick/Unicycler/blob/master/docs/unicycler-align.md

**Comment by sjackman** [comment]
I've noticed that the polished edges seem to extend past the edge of the repeat boundary. The following two plots show the contigs aligned to themselves using BLAST and visualized with Bandage.

# `2-repeat/graph_final.gfa`

![graph_final gfa](https://user-images.githubusercontent.com/291551/49318532-c36cb100-f4ad-11e8-9956-563696841834.png)

-----

# `3-polishing/polished_edges.gfa`

![polished_edges gfa](https://user-images.githubusercontent.com/291551/49318892-362a5c00-f4af-11e8-931e-ba260bb06291.png)

-----

In `2-repeat/graph_final.gfa` the contigs all end nice and bluntly at the repeat boundaries. In `3-polishing/polished_edges.gfa` the contigs seem to extend past the edge of the repeat boundary. Notice the purple contig in the bottom left and the brown contig in the top right bleed into their neighbours. That overlap is not indicated in the GFA file. All the CIGAR strings are `0M`.

Flye version 2.3.6. I'll try 2.3.7.

**Comment by mikolmogorov** [comment]
Must be a bug! Basically, I am extracting polished edges from the final contigs using alignment  - most likely something went wrong with the coordinates. Will you be able to send me the Flye output directory so I can reproduce the problem?

**Comment by sjackman** [comment]
I removed `1-consensus/minimap.sam` and `3-polishing/bubbles_1.fasta` because they were large. I've sent you a link to the tarball on Dropbox through a Twitter direct message.

Have a good weekend!

**Comment by mikolmogorov** [comment]
Thanks a lot for sending me this example! This was indeed a (very stupid) bug - I would never noticed it without someone carefully looking into the assembly results. I've pushed a fix into the main branch. Polished edges now look structurally similar to their unpolished version (see the dotplot).
![dotplot](https://user-images.githubusercontent.com/2475380/49411774-11d4b680-f71f-11e8-8b9f-f8c7a771738d.jpeg)

**Comment by sjackman** [comment]
Thanks for being so responsive, Mikhail!
