### ISSUE TITLE
Assembly size is double the genome size E. coli despite specifying --genome-size

### ISSUE THREAD

**Issue by gilmahu** [fenderglass/ABruijn#540]
Dear All, 

I have used flye to assemble two nanopore reads. One looks fine but one assembly even after the polishing step is twice the size of the genome size (i.e. 9.5MB instead of a maximum of 5MB). And this happened despite that I specified a --genome-size of 5m. 
Here is the command within my script: 
for f in *.fastq; do flye --nano-corr $f --genome-size 5m --out-dir ${f%}_outflye; done.

Does anyone have an idea what could have gone wrong and how to fix it? 

PS: The filtered size of the two reads were around 900MB... i just can't figure out why one is misbehaving 

Looking forward to any help out there. 

Best regards

**Comment by mikolmogorov** [comment]
`--genome-size` parameter does not control assembly size (and the option is not needed in most cases). Flye attempts to reconstruct all genomic sequence within the sample. If your assembly is longer than expected, this means there is something else in your sample - possibly do to contamination. You can take a look at the assembly graph - each bacterial genome should correspond to a circular connected component.

**Comment by gilmahu** [comment]
Thanks a lot.I found the issue it was a contamination.
