### ISSUE TITLE
Would it be possible to split the disjointig creation step to reduce memory for large genomes?

### ISSUE THREAD

**Issue by olawa** [fenderglass/ABruijn#541]
Hi,

I am running Flye on a 256Gb system but are running out of memory before the disjointig step finishes (nanopore reads) meaning flye is killed before  any output has been made and can thus not be restarted even if disjointigs were almost done. I wonder if the sequence or disjointig links could written to disk directly after each disjointig has been assembled? If so one could restart on a higher mem node if needed. Or perhaps memory usage could be reduced if not all overlaps need to be kept at this stage?

**Comment by mikolmogorov** [comment]
Hi,

Flye currently does not have such functionality. You can check the manual for tips to reduce memory usage, but 256Gb a bit tight for anything human-sized.
