### ISSUE TITLE
nano-raw and nano-hq

### ISSUE THREAD

**Issue by maguileraf** [fenderglass/ABruijn#542]
Hi,

We have nanopore reads sequenced with the Q20 but when I use nano-hq, there are no contigs assembled. However, when I use nano-raw, I get 4 contigs in the final assembly. Why do you think this is the case?

Best,
Marcela

**Comment by mikolmogorov** [comment]
`--nano-hq` assumes <5% read error rate. You can see the error rate distribution in the `flye.log`. it is possible that the actual error rate in your reads is higher.
