### ISSUE TITLE
Orientation of output?

### ISSUE THREAD

**Issue by rmormando** [fenderglass/ABruijn#544]
Are the resulting contigs from a de-novo flye assembly in a certain orientation? 

How do you establish what orientation the contigs are in?

This is the command I used: `flye --nano-raw FILE.fastq.gz --out-dir FILE_flyeoutput -t 20`

**Comment by mikolmogorov** [comment]
The orientation of the contigs is generally unknown, because the orientation of reads is also unknown. Sometimes you can tell if some contigs should be in the same orientation based on the graph structure (could be visualized with Bandage).
