### ISSUE TITLE
Stuck at Sequence divergence distribution but I am not getting any error

### ISSUE THREAD

**Issue by plnspineda** [fenderglass/ABruijn#545]
My run for 2.7Gb estimated genome with haplotyped reads ~52-54x coverage is stuck/stalled at Sequence divergence distribution part and is not progressing for 3 days. But Flye works well with the e.coli ONT test data. Does it really just takes long?

I used the following parameters:
`flye --threads 32 --nano-corr haplotype-Tuli_sire.fasta -o haplotype_flye_Tuli_sire`

but stuck for 3 days so I tried:
`flye --threads 32 --asm-coverage 50 -g 2.7g --nano-corr haplotype-Tuli_sire.fasta -o haplotype_flye_Tuli_sire`

but has the same stuck problem.

Flye version: Flye 2.8.1-b1676
Python version: 3.7.13

        [2022-10-31 13:02:49] DEBUG: Total RAM: 1511 Gb
        [2022-10-31 13:02:49] DEBUG: Available RAM: 1482 Gb
        [2022-10-31 13:02:49] DEBUG: Total CPUs: 32
        ...
        [2022-10-31 14:57:53] DEBUG: Peak RAM usage: 315 Gb
        ...
        [2022-10-31 15:10:05] INFO: Median overlap divergence: 0.0754414
        [2022-10-31 15:10:05] DEBUG: Sequence divergence distribution:
        <some graph>
        Q25 = 0.058, Q50 = 0.075, Q75 = 0.1

I think it's the same problem as this [#154](https://github.com/fenderglass/Flye/issues/154), but I am not getting any error. The run seems to just not progress at all.

Here is the [flye.log](https://github.com/fenderglass/Flye/files/9934461/flye.log).

I'd appreciate your feedback. Thank you very much!

**Comment by plnspineda** [comment]
I realised that my `Overlap-based coverage: 0` and I probably have the same Issue as [#128](https://github.com/fenderglass/Flye/issues/128). Still trying to see how to troubleshoot this.

I used Canu to separate my reads into haplotypes, therefore I used --nano-corr.
I am now running it twice: one with --nano-cor --meta, and the other with only --nano-raw to see if I could get result with overlap-base coverage. *update: I got overlap-base coverage result*

**Comment by mikolmogorov** [comment]
Hi,

The error rate of your reads seems to be much higher than expected from error-corrected reads (you can see the distribution in the log file). I would suggest to use `--nano-raw` instead, or even better: rebasecall with Guppy5+ and use `--nano-hq`.

Neither Flye nor Canu can currently produce diploid assembly from nanopore. But you can transform haploid into diploid using Hapdup.

**Comment by mikolmogorov** [comment]
Assuming that it is resolved now, please do follow up if you have more questions.
