### ISSUE TITLE
['flye-modules', 'polisher', '-h'] returned exit status 1

### ISSUE THREAD

**Issue by Jason-Hiatt** [fenderglass/ABruijn#548]
Hi,

Failed to run: `C:\WINDOWS\System32\bash.exe -c '/mnt/c/Users/#####/AppData/Local/Geneious/plugins/Flye/resources/Windows/bin/flye' --nano-raw input_0_Unpaired.fasta --threads 8 --genome-size 1m --iterations 1 --debug --out-dir out`
ERROR: Command '['flye-modules', 'polisher', '-h']' returned non-zero exit status 1
ERROR: Pipeline aborted.

(This runs via WSL Ubuntu)

Unfortunately we have not been able to obtain any further details as to what is happening at this stage. We can't reproduce it on our end yet, pending access to the users data, however at this stage I also suspect some sort of client machine set-up issue. One of the big issues we have here is the lack of debug information being returned even with --debug included. Any insights as to the likely cause or additional options to obtain potential error details would be greatly appreciated. There is also a chance of it being related to a version update problem, but again not enough info to have any confidence in it.

Cheers,
Jason

**Comment by Jason-Hiatt** [comment]
Update: We've gained access to our users data and can confirm that is not the cause of the issue. So it's specifically an installation or specific machine issue of some kind.

**Comment by mikolmogorov** [comment]
Hi,

If this is a problem specific to WSL system, I am not sure how I can help. Flye was not designed or tested for Windows machines. Why not run natively on Ubuntu?

**Comment by Jason-Hiatt** [comment]
Hi,

We've confirmed that this was ultimately an Ubuntu and WSL version issue, and so the immediate problem is resolved. It would still be great however to have some enhanced logging of some form to make this more obvious should it occur in the future, but I can accept this is arguably an enhancement to cater to a platform you don't intend to support.

To answer your question though, I'm one of the developers for [Geneious Prime](https://www.geneious.com/) which is multi-platform. And over time we've added support where feasible for installing wrapper plugins to facilitate piping data through popular external tools like Flye, and provided the WSL and Ubuntu versions are correct then Flye does work well on Windows so we've had no reason to prevent it, and usually if the versions are an issue it is immediately obvious from whatever error logs we receive.

**Comment by mikolmogorov** [comment]
Hi,

Glad that you figured out what was happening. If the executable is crashing for some (unknown) reason, that would be hard to log what happened in unmanaged code - I don't have a good multi-platform solution for that unfortunately.

Best,
Mikhail
