### ISSUE TITLE
some intsall errors,  need help!! 

### ISSUE THREAD

**Issue by whatabear** [fenderglass/ABruijn#551]
Is this installed? Some errors on the endline..ps:  I am a rookie...
flye
usage: flye (--pacbio-raw | --pacbio-corr | --pacbio-hifi | --nano-raw |
	     --nano-corr | --nano-hq ) file1 [file_2 ...]
	     --out-dir PATH

	     [--genome-size SIZE] [--threads int] [--iterations int]
	     [--meta] [--polish-target] [--min-overlap SIZE]
	     [--keep-haplotypes] [--debug] [--version] [--help] 
	     [--scaffold] [--resume] [--resume-from] [--stop-after] 
	     [--read-error float] [--extra-params] 
	     [--deterministic]
flye: error: argument -o/--out-dir is required

**Comment by bplants10** [comment]
If you see the help menu, you installed. In your code line, you need to specify the PATH for flye to write the output assembly files. Check the syntax of your code too, and make sure that you don't have any extra spaces.

**Comment by whatabear** [comment]
thanks a lot. I 'd read the usage seriously

**Comment by mikolmogorov** [comment]
I'm assuming it is resolved now - please do follow up if it's not.
