### ISSUE TITLE
question on assembly and high coverage region

### ISSUE THREAD

**Issue by katefgit** [fenderglass/ABruijn#552]
Hi,

I am looking into an area in the genome (Bacillus) with higher coverage (490 instead of average 140) and was trying to see if there are multiple copies in the assembly, but I cannot find anything. Is there any chance that I can tweak the parameters? I already tried the -meta (this is the only parameter that gives a circular assembly), whereas normal and --asm-coverage 50 don't give a complete assembly. I was expecting that even if there are repeats that cannot be resolved to get a complete assembly, there would be several other contigs. Or I might be completely wrong in my thinking here...

**Comment by tolot27** [comment]
How large is the high coverage region? 5-6 kb? Bacillus has several rRNA cassettes of two to three rRNAs which might have been collapsed.

**Comment by katefgit** [comment]
Thanks for your reply. The region is around 35kb and flanked by rrna genes. 
<img width="379" alt="Picture1" src="https://user-images.githubusercontent.com/74652982/204473064-9b951f03-23ca-4b29-ac54-b67b7724c622.png">
I am comparing this strain with another one, and although they have the same assembly size and I can find the exact same region in both, in this one the coverage is higher and in the other is not. The sequences of the 2 strains otherwise look otherwise exactly the same, but we have e.g. a PFGE showing that they are not and need to figure out by WGS if that's true. Is there is an explanation on why I cannot see that in e.g. assembly with bigger size and if the assembly could not be assembled "correctly", will the extra pieces appear as "extra fragmnets (e.g. in the --meta mode you might end up having many small contigs that could not be assembled, but not in this case) or if there is another reason?

**Comment by tolot27** [comment]
What is your read N50? Please filter for reads longer than 35 kb which span this region. Maybe, the complete region is duplicated. That happens sometimes in Francisella as well (with an 31 kb region).
You can also PM me. We sequenced and analysed quite a lot of Bacillus genomes.

**Comment by katefgit** [comment]
@tolot27 I cannot see the option for PM. I will try to write here :) your input is super useful, so I would be grateful if you could help me further/share your knowledge, as it gets more complicated - sorry for the long text.

The N50 was indeed low (11kb) and with 100k reads. I tried to filter the reads and I get the same assembly size (3.9 or not complete). I can understand the N50 would be an issue here, but does this mean that in such cases of low N50 and samples with many repeats, when doing flye you might miss some of the sequences that could not be assembled (since I don't even get the not circular fragments in the assembly file)?

I repeated the sequencing with the R10.4 flowcell and although I get the same low N50 and nr of reads, the assembly size is now 4.4 instead and when I have the --meta mode I even get another 24 kb circular fragment. And I find the same cassette 3x times in the 4.4 circular fragment and 1x time in the 24 kb circular fragment, and again flanked by 23S rrNA. Is this also a result of a bad assembly, due to the low N50? 
And my last question, do you have any suggestion for future analysis, as I would not normally have thought about this issue, when I could see that I have a complete assembly.

**Comment by mikolmogorov** [comment]
All good advice here! Flye can only resolve repeats if (i) there are reads that span their in full length or (ii) repeat copies are divergent enough to be separated on the graph before repeat resolution. If you could submit `flye.log` from your most successful run + the final `assmebly_graph.gfa`, I might have more specific recommendations.

**Comment by mikolmogorov** [comment]
Closed due to inactivity - feel free to reopen if you have any follow-ups.
