### ISSUE TITLE
Documentation out-of-date for assumed PacBio HiFi error rate?

### ISSUE THREAD

**Issue by rzelle-lallemand** [fenderglass/ABruijn#553]
I was wondering whether the current Flye 2.9.1 documentation is correct regarding the PacBio HiFi error rate. `flye --help` and USAGE.md both suggest the default assumed error rate for HiFi reads is about 1%:

https://github.com/fenderglass/Flye/blob/4bb3929e849738e8c6a5d9ceb6ae894f6761aa31/flye/main.py#L629-L630

https://github.com/fenderglass/Flye/blob/4bb3929e849738e8c6a5d9ceb6ae894f6761aa31/docs/USAGE.md?plain=1#L35-L46

The default values of "assemble_ovlp_divergence" and "repeat_graph_ovlp_divergence" were changed for PacBio HiFi from 0.01 to 0.001 in Flye 2.9 (https://github.com/fenderglass/Flye/releases/tag/2.9 and https://github.com/fenderglass/Flye/commit/a98898facad48374b2a56017442e033623c651a8). Does this mean that the assumed error rate is actually 0.1%, or do the values of these attributes not directly translate to read error rate? For comparison, I found the following values for these two settings in https://github.com/fenderglass/Flye/tree/flye/flye/config/bin_cfg for the various read types, which otherwise often closely match the error rates mentioned in the documentation:

asm_hifi.cfg, "assemble_ovlp_divergence" and "repeat_graph_ovlp_divergence" both set to 0.001 (documentation says <1% error rate for pacbio-hifi)
asm_corrected_reads.cfg, "assemble_ovlp_divergence" and "repeat_graph_ovlp_divergence" both set to 0.03 (documentation says <3% error rate for pacbio-corr and nano-corr)
asm_nano_hq.cfg, "assemble_ovlp_divergence" and "repeat_graph_ovlp_divergence" both set to 0.05 (documentation says <5% error rate for nano-hq)
asm_raw_reads.cfg, "assemble_ovlp_divergence" and "repeat_graph_ovlp_divergence" set to 0.10 and 0.08  (documentation says <20% error rate for pacbio-raw and nano-raw)

**Comment by rzelle-lallemand** [comment]
The reason I ask is that `--pacbio-hifi` gave a lot of genome duplication (presumably haplotype phasing) in a Flye 2.9.1 assembly of a PacBio HiFi data set of a triploid and quite heterozygous *S. cerevisiae* strain (ca. 12 Mbase haploid genome size), producing a 28 Mb genome sequence.

I thought that maybe raising the expected error rate would help in reducing haplotype phasing, which seems to be the case, as rerunning the assembly with `--pacbio-corr`, `--pacbio-hifi ... --read-error 0.03`, or `--pacbio-hifi ... --read-error 0.01` gave genome sequences of 12-13 megabase instead, which is what I was looking for. So I'm curious what the default expected error rate really is for `--pacbio-hifi`. Thanks!

**Comment by mikolmogorov** [comment]
Hi,

It's a bit more tricky, `0.01` was indeed used originally, and now the default value is `0.001` but in homopolymer-collapsed space.  Increasing this with `--read-error` is indeed a good strategy to force haplotypes to collapse. 

Hope this helps, please do follow up if there are any other questions.
