### ISSUE TITLE
 ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct

### ISSUE THREAD

**Issue by DorentinaH** [fenderglass/ABruijn#554]
I am getting this error while running flye assembler on Nanopore reads for a phage genome. As previously suggested, I have tried to add in two ways --genome-size --asm-coverage which solves this error but gives different results. Since I do not know the exact size of this phage genome I have used the parameters --genome-size 40000 and 37000 with --asm-coverage 50. 
The output is different, once I get an assembly of 36900 bp and when I use a genome size of 40000 I get 38211 bp assembly.

**Comment by mikolmogorov** [comment]
The newest versions of Flye should not be sensitive to genome size parameter. If the coverage is good, your phase should be assmebled into single contig. Flye may produce additional small contigs that may arise from artifacts or contamination - this might explain the size difference. In addition, I would try `--meta` option instead.

Hope this helps, feel free to follow up if you have more questions.
