### ISSUE TITLE
ERROR: No disjointigs were assembled 

### ISSUE THREAD

**Issue by nityendra21** [fenderglass/ABruijn#557]
Hi, I'm facing this issue on Flye v.2.9.1, where I'm using Flye to assemble SARS-CoV-2 raw reads. I used:
`flye --nano-raw ont.fastq --threads 16 -o flye_out` 
As suggested by you, in a previous issue I also tried both the `--meta` and `--asm-coverage 50` options, leading to the same error. I have added the command line log down below that was generated using the above command:
`[2022-12-14 17:13:21] INFO: Starting Flye 2.9.1-b1780`
`[2022-12-14 17:13:21] INFO: >>>STAGE: configure`
`[2022-12-14 17:13:21] INFO: Configuring run`
`[2022-12-14 17:13:21] INFO: Total read length: 44888064`
`[2022-12-14 17:13:21] INFO: Reads N50/N90: 825 / 410`
`[2022-12-14 17:13:21] INFO: Minimum overlap set to 1000`
`[2022-12-14 17:13:21] INFO: >>>STAGE: assembly`
`[2022-12-14 17:13:21] INFO: Assembling disjointigs`
`[2022-12-14 17:13:21] INFO: Reading sequences`
`[2022-12-14 17:13:23] INFO: Counting k-mers:`
`0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%` 
`[2022-12-14 17:14:02] INFO: Filling index table (1/2)`
`0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%`
`[2022-12-14 17:14:03] INFO: Filling index table (2/2)`
`0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%`
`[2022-12-14 17:14:04] INFO: Extending reads`
`[2022-12-14 17:14:14] INFO: Overlap-based coverage: 72`
`[2022-12-14 17:14:14] INFO: Median overlap divergence: 0.0905383`
`0% 100% `
`[2022-12-14 17:14:22] INFO: Assembled 0 disjointigs`
`[2022-12-14 17:14:22] INFO: Generating sequence`
`[2022-12-14 17:14:23] INFO: Filtering contained disjointigs`
`[2022-12-14 17:14:23] INFO: Contained seqs: 0`
`[2022-12-14 17:14:23] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct`
`[2022-12-14 17:14:23] ERROR: Pipeline aborted`

**Comment by mikolmogorov** [comment]
Please see if anything from this thread applies: https://github.com/fenderglass/Flye/issues/128. Feel free to follow up there if it does not resolve the issue. Based on your log, I suspect that reads are too short to assmeble.
