### ISSUE TITLE
Error: Duplicated IDs on Flye but not Canu

### ISSUE THREAD

**Issue by ykc21e8** [fenderglass/ABruijn#558]
Hi I got this error from a recent run.
`ERROR: The input contain reads with duplicated IDs. Make sure all reads have unique IDs and restart.`
and
`ERROR: Command` list of datasets + datalogs and followed with `returned non-zero exit status 1.`

I want to run these fastq files on flye and it ran on Canu with no problem. 
I'm running multiple files and they are fairly large in size, and these are open source data, I don't know how to even find the specific id that needs to be changed.

How can I solve this issue?

**Comment by mikolmogorov** [comment]
You would need to remove duplicated read names from these input files, there is no other way around unfortunately.
