### ISSUE TITLE
Balancing memory usage with --asm-coverage

### ISSUE THREAD

**Issue by ykc21e8** [fenderglass/ABruijn#559]
Hi 

My PC ran out of memory when I ran on default options.
I'm not too confident about the results I got with `--asm-coverage 100`.

Could you give me advice on whether to increase or decrease this number? I would like to get the best possible result without running out of memory. 
What does longest 40x reads for contig assembly mean?

**Comment by mikolmogorov** [comment]
Hi,

Sorry for the late response. We typically have good results with `--asm-coverage 40`, you rarely need more for disjointig assembly.
