### ISSUE TITLE
Flye potentially misses a plasmid

### ISSUE THREAD

**Issue by weishwu** [fenderglass/ABruijn#562]
I'm using Flye to assemble Nanopore reads into genome assemblies for some Klebsiella samples. We are almost certain that one sample should contain a plasmid, and I could find matches with some plasmid gene sequences in the raw reads using both minimap2 and Blast. However Flye produced a single ~5Mb contig and those plasmid sequences could not be found in the contig. Are there any parameters I can try tweaking for better plasmid sensitivity? Thanks.

**Comment by mikolmogorov** [comment]
I recommend using `--meta` in case there are big differences in coverage between chromosome and plasmid.

**Comment by weishwu** [comment]
Thanks!

**Comment by gbouras13** [comment]
Hi @weishwu, if you want to have a look at this issue in some more detail, check out this [paper](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000631) if you haven't already. I have tried to combat issue with plasmids in my program [plassembler](https://github.com/gbouras13/plassembler), which is designed for hybrid long-short reads. As you can see in the benchmarking, long-only Flye can miss or duplicate plasmids pretty often, though from limited data I have tried so far, it should be less of an issue with the new R10.4 Nanopore data. If you have only long reads, perhaps you could try plassembler with -k enabled.

George
