### ISSUE TITLE
Median overlap divergence

### ISSUE THREAD

**Issue by DiegoSafian** [fenderglass/ABruijn#566]
Hi,
I was wondering if there is some kind of problem in my commands that makes the median overlap divergence so slow. Somtimes it gets stuck at 10%, 80% or 90% for days. I trying to assemble a genome of about 700 mb using nanopore long reads (150G). These are my commands:

```
flye --nano-raw /camp/home/safiand/home/users/safiand/genome_assambly/guppy_PromethION/qc/guppy_prom_filtered2.fastq \
	--genome-size 0.8g -threads 64 --asm-coverage 50 --out-dir ./results_flye
```

I have attached a .log file of a job stucked at 90% as an example.
[flye.log](https://github.com/fenderglass/Flye/files/10511233/flye.log)

Many thanks in advance

**Comment by mikolmogorov** [comment]
This is disjointig assembly stage, it is typically the longest part of the pipeline. I don't see anything abnormal in the log.

My two suggestions may be trying to use `--nano-hq` (if you are using at least Guppy5), and you can also try to filter out a portition of reads with lowest quality (for example using https://github.com/rrwick/Filtlong).

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, feel free to follow up if not!
