### ISSUE TITLE
Is it meaningful to assemble only one chromosome instead of the whole genome? 

### ISSUE THREAD

**Issue by wx904** [fenderglass/ABruijn#568]
Hi,

I know that Flye is an excellent tool for the whole genome assembly, but at the meantime, it requires large RAM for genomes like human.  So, I'm wondering if it is meaningful or not to only assemble some specific chromosome instead of the whole genome?

Best,
WX

**Comment by mikolmogorov** [comment]
Sure, you can do local assembly with Flye if you are interested in a specific region / chromosome.

**Comment by wx904** [comment]
> Sure, you can do local assembly with Flye if you are interested in a specific region / chromosome.

Good to know that. Many thx.
