### ISSUE TITLE
subassemblies deprecated

### ISSUE THREAD

**Issue by fergsc** [fenderglass/ABruijn#569]
Hi,

I am trying to perform a global assembly on a collection of metagenome assemblies I have created. Metagenomes were assembled from short paired reads. The subassemblies mode within Flye may be a good tool for this, however it is deprecated, is there a reason for this?

thanks.

**Comment by mikolmogorov** [comment]
@fergsc we're not planning to support this feature to make the future maintenance easier. There are other tools that specialize on merging assemblies, like https://github.com/mahulchak/quickmerge.
