### ISSUE TITLE
Use .gv extension rather than .dot

### ISSUE THREAD

**Issue by sjackman** [fenderglass/ABruijn#57]
Consider renaming `assembly_graph.dot` to `assembly_graph.gv`. The preferred extension is `.gv` because `.dot` conflicts with Microsoft Word (document template).
See the sidebar at https://en.wikipedia.org/wiki/DOT_(graph_description_language)

**Comment by sjackman** [comment]
Double-clicking a `.dot` open Microsoft Word by default, whereas double-clicking a `.gv` file opens Graphviz.

**Comment by mikolmogorov** [comment]
Good suggestion - will change in the next version!

**Comment by sjackman** [comment]
Thanks!
