### ISSUE TITLE
Polishing time

### ISSUE THREAD

**Issue by FabianDK** [fenderglass/ABruijn#570]
Dear authors,

I am running Flye (2.9.1-b1780) on a 2.4Gb mammalian genome using Nanopore data in Docker with Ubuntu 20.04.2 LTS and Python 3.10.6 in a Nextflow pipeline: 
`flye --nano-hq org_filtered.fq.gz -g 2.4g -o assemblies/flye/org_filtered -t 75`
This is on an 80 cores machine with 620 GB RAM, with allocated resources 75 cores and 550 GB RAM.

It takes about 2 hours to reach the polishing stage, but then the polishing is already running for more than one day (at "Separating alignment into bubbles").
`htop` suggests that the flye processes are still running:

![image](https://user-images.githubusercontent.com/30504430/217209717-c6b76eea-a564-4b80-8c87-dba03293f12f.png)

Is it expected that polishing takes that long?

Thanks,
Daniel

**Comment by mikolmogorov** [comment]
Hi Daniel,

Polishing is definitely on the longer side, what is the coverage of the dataset? At the same time, 2 hours to reach the polishing stage is unexpectedly fast. It normally takes a day or two for large mammalian genomes to do initial assmebly.

Could you also share the full `flye.log`?

**Comment by FabianDK** [comment]
Thanks for looking into this. I have attached the flye log. This was with 200k reads with 61kb average read length from ONT (R9.4.1, PromethION).

In the 40-polished folder are 4 files: bubbles_1.fasta, minimap.stderr, minimap_1.bam, minimap_1.bam.bai

[flye_test.log](https://github.com/fenderglass/Flye/files/10697920/flye_test.log)

**Comment by FabianDK** [comment]
What I tried for now is to split up assembly (--stop-after contigger) and polishing steps (restarted with --resume), and allocate fewer CPUs to the polishing step to reduce memory needs. I did not define memory in the nextflow workflow for the polishing step. Polishing is running now since 1.5 days at "INFO: Separating alignment into bubbles".

I think it would be good if the flye log would show more progress info for this stage, as it is not clear to me if the polishing process is stuck or if I am too inpatient.

Here is the current htop screenshot:
![image](https://user-images.githubusercontent.com/30504430/218423873-05c88778-2b24-4efe-83e2-35863d305ded.png)

It looks like all the processes remain in sleep mode ("S") and never change to "R".

**Comment by mikolmogorov** [comment]
Sorry for the late response!

Indeed it seems that polishing processes get stuck for some reason, they are just not doing anything. This may be hard to debug, as there is not informative error message, and I have not seen this happening before.

I would start from trying using a different Python version (e.g. maybe 3.7 - 3.9 instead of 3.10), and if that does not work, try a different machine if possible, to rule a possible issue specific to the environment. Also, can you try running the bioconda package instead of Docker? Do other datasets finish normally on this machine?

Could you also tell more about the OS / environment you are using?

**Comment by FabianDK** [comment]
This issue has happened on different machines on larger and smaller sized data. All running Ubuntu 20.04.5 LTS. For now, I have switched ot using [bschiffthaler/flye:2.9 ](https://github.com/bschiffthaler/kogia/blob/main/flye/Dockerfile) (removed entrypoint from Dockerfile) for the assembly and polishing step.

The polishing is still extremely slow, but the processes do not jump to sleep mode anymore.
With 25 cpus and 400 gb memory, it took 3 days to polish a 4 x covered genome (genome size = 2.4 gb), and on a ~30x covered assembly it is currently running 8 days and is at 80% for the correcting bubbles step.

See the screenshot:
![image](https://user-images.githubusercontent.com/30504430/225608692-d0b914d3-98f6-4645-9b80-a27b4060019a.png)

This appears to be extremely slow. Is this normal? What would you recommend to speed this up (e.g. number of cores/memory)?

Thanks,
Daniel

**Comment by mikolmogorov** [comment]
Hi Daniel,

This is not normal, it seems that polishing threads spend most of their time in system calls. I suspect this has something to do with the docker image, and since I don't maintain those I won't be able to dig in. I suggest trying bioconda / source installation first to see if it results in faster processing.

**Comment by FabianDK** [comment]
Thank you for the suggestion. I have used the `bioconda::flye=2.9.1` image and the speed was much better.
With 16 cpus allocated, it now took 8 and 9 hours for the polishing of a 24x and 29x mammalian genome. 
For reference, the pre-polishing stage took 16.5h and 20h with 16 cpus and 286 GB memory allocated. 

It would be great if there was also an official Docker image available.

**Comment by mikolmogorov** [comment]
@FabianDK glad to hear! It could be that the Docker image you've been using was for a different CPU architecture. I think bioconda in fact provides complementary docker builds, maybe give it a try? https://bioconda.github.io/recipes/flye/README.html

**Comment by imdanique** [comment]
Hi, I have the same problem with polishing

I'm using the last version of flye (2.9.1-b1780) from bioconda, and Python 3.8.15. Polishing is stuck at Correcting bubbles step for almost a day:
```bash
[2023-04-01 15:52:37] root: INFO: >>>STAGE: polishing
[2023-04-01 15:52:37] root: INFO: Polishing genome (1/1)
[2023-04-01 15:52:37] root: INFO: Running minimap2
[2023-04-01 23:33:36] root: INFO: Separating alignment into bubbles
[2023-04-02 01:51:17] root: DEBUG: Generated 155197956 bubbles
[2023-04-02 01:51:17] root: DEBUG: Split 14644 long bubbles
[2023-04-02 01:51:17] root: DEBUG: Skipped 2193 empty bubbles
[2023-04-02 01:51:17] root: DEBUG: Skipped 324 bubbles with long branches
[2023-04-02 01:51:18] root: INFO: Alignment error rate: 0.060781
[2023-04-02 01:51:18] root: INFO: Correcting bubbles
```
htop shows no signs that something heavy is running. This error affects only one sample, while other samples had polished fine with flye at the same machine and at the same conda env. Do you have any suggestions how it could be solved?

**Comment by mikolmogorov** [comment]
Assuming this is now resolved, feel free to follow up if there are more questions!
