### ISSUE TITLE
how to solve the problem about flye-minimap2 consuming large memory resources?

### ISSUE THREAD

**Issue by ghost** [fenderglass/ABruijn#571]
Dear author,  thank you for developing the great assembler. I'm running assemble on Flye-2.9.1, but I always get stuck with the secondary step (consensus step). Because the flye-minimap2 consumes large memory. I found that flye-minimap2 doesn't have `-x hifi` parameter like minimap2. Although when I use the command `flye --pacbio-hifi ccs.fastq.gz -o ./ -g 7.9g -t 50 --resume-from consensus`, the flye-minimap2 still use the parameter `-x map-pb` and consumed large memory resouces. So I try to use minimap2 instead of flye-minimap2 to generate minimap.bam file. The command is here: `minimap2  -x map-hifi  -t 60 -a -p 0.5 -N 10 --sam-hit-only -L -K 5G -z 1000 -Q --secondary-seq -I 64G ./00-assembly/draft_assembly.fasta WN_YCY.ccs.fastq.gz | samtools sort -T -O bam -@ 60 -l 1 -m 4G -o ./10-consensus/minimap.bam`. But I don't know if this alternative choice ( using minimap2 instead of flye-minimap2 ) is reasonable ? And if the method is appropriate, I want to know how to generate consensus.fa from the minimap.bam by using flye? .

**Comment by mikolmogorov** [comment]
Answered in https://github.com/fenderglass/Flye/issues/516. I don't se a straightforward way currently. We're planning to update to a newer version of minimap2 (that supports map-hifi) in the next release.
