### ISSUE TITLE
Can I retrieve unassembled reads based on flye outputs?

### ISSUE THREAD

**Issue by dawnmy** [fenderglass/ABruijn#573]
Thank you for developing such a great assembler for long reads. I would like to get all the sequences including the assembled contigs and also the reads that are not represented by any contigs. I was wondering if I can retrieve the unassembled reads just based on the flye output?

**Comment by dawnmy** [comment]
Or is there a way to let Flye to generate contigs (may as short as input reads if no overlapping) representing all the reads.

**Comment by mikolmogorov** [comment]
@dawnmy Flye does not output unassembled reads, but you can align them against the contigs and extract the unaligned ones.

**Comment by lskatz** [comment]
If this ever becomes an option, I'd like to know!
