### ISSUE TITLE
Coverage calculation assembly_info.txt 

### ISSUE THREAD

**Issue by cdm-bio** [fenderglass/ABruijn#574]
Hello!

Thank you for creating this excellent tool.

I am new to its usage, and I am looking at the columns of the assembly_info.txt file.

I would like to ask if someone knows **how the coverage (third column) is calculated** and what can be considered a **high or low value**. I understand that this value might be closely related to the organism/specie/strain. For the purpose of learning let’s say that I have the same organism and strain (E.coli), in this scenario what values or range could be an indicator of an acceptable assembly?

**These are examples of the outputs:**

<img width="458" alt="Github_example" src="https://user-images.githubusercontent.com/106129962/220424823-2739c7cd-966c-4be3-82a0-dcfd2bc78f42.png">

Thank you!

**Comment by mikolmogorov** [comment]
Hi,

Coverage stands for "read coverage" or alternatively "read depth". It's a mean read depth calculated for every contig. It may vary depending on the sequencing yield and relative abundance of bacteria / plasmids (if there is multiple). So there is no "right" or "wrong" value.
