### ISSUE TITLE
Question: resolve multiple plasmids with same backbone

### ISSUE THREAD

**Issue by jagos01** [fenderglass/ABruijn#578]
Hello,
I have several small plasmids (2.2kb) in my sample that contain the same backbone.  The various inserts are between 300-400 bp.  Are there parameters that can be modified which would allow flye to assemble these mixed plasmid samples?  Samples were sequenced with kit 14 chemistry from Oxford Nanopore and assembled using flye --nano-hq --meta --read-error 0.03.  Some of the plasmids were partially assembled and none were circularized.   I also tried the --keep-haplotyp flag but it did not change the outcome.
Thanks,

**Comment by mikolmogorov** [comment]
Hi @jagos01 

If you have the same backbone and multiple smaller inserts, Flye will unlikely to assemble those plasmid copies in separate contigs, but instead will represent it as a "pangeonme" of plasmids, especially if you are using `--keep-haplotypes`. Try visualizing the assembly graphs using Bandage, you should be able to see your inserts as a separate graph nodes / contigs on this graph, that will be attached to the backbone sequence.

**Comment by mikolmogorov** [comment]
Assuming that the thread is resolved. But please do follow up if you have remaining questions!
