### ISSUE TITLE
flye generates different contig sizes based on number of threads used

### ISSUE THREAD

**Issue by admontecillo0428** [fenderglass/ABruijn#582]
I have been trying to assemble a bacterial genome and I kept on noticing that the number of threads used (--threads) greatly affects the final contig size.  Same -m, same -g inputs. Based on resulting blastn, --threads 12 and higher gives the correct assembly, while --threads 8 or lower has an extra 10kb due to repeats. I wonder if this should be the case? I tried this on 2 different machines (R7 8C/16T, and Xeon 20C).

--threads 12
	Total length:	4105610
	Fragments:	2
	Fragments N50:	4095629
	Largest frg:	4095629
	Scaffolds:	0
	Mean coverage:	99

--threads 8
	Total length:	4115591
	Fragments:	2
	Fragments N50:	4095629
	Largest frg:	4095629
	Scaffolds:	0
	Mean coverage:	99

**Comment by Sumsarium** [comment]
How many "replicate" runs have you done (I don´t think it is a --thread thing)? Generally, the assembly process has some stochastic elements, i.e. I would not expect 100 % reproducibility. I tested this a few months ago...

**Comment by admontecillo0428** [comment]
> How many "replicate" runs have you done (I don´t think it is a --thread thing)? Generally, the assembly process has some stochastic elements, i.e. I would not expect 100 % reproducibility. I tested this a few months ago...

Thank you for your response. Below is my latest run. I controlled for -m and -g. The result suggest stochastic and threads effects on the resulting assembly length. 

Organism: Proteus mirabilis

Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz   2.20 GHz  (2 processors)

-m 6000 -g 4.1m
		
Threads	Repetition	Total Length (bp)	
8	1	4105606
8	2	4105606
8	3	4105606
32	1	4115578
32	2	4115578
32	3	4105598

**Comment by admontecillo0428** [comment]
> How many "replicate" runs have you done (I don´t think it is a --thread thing)? Generally, the assembly process has some stochastic elements, i.e. I would not expect 100 % reproducibility. I tested this a few months ago...

Based on my latest runs/repetitions, it is suggested to perform multiple runs/repeats while adjusting for some params:

-m 6000 		
Threads	Repetition	Total length (bp)
8	1	4115591
8	2	4115591
8	3	4115591
16	1	4127668
16	2	4105610
16	3	4117689

**Comment by mikolmogorov** [comment]
Please see https://github.com/fenderglass/Flye/issues/509. Also this: https://github.com/fenderglass/Flye/pull/546 Feel free to continue the discussion in the earlier thread!
