### ISSUE TITLE
Allow for > 128 threads

### ISSUE THREAD

**Issue by Sumsarium** [fenderglass/ABruijn#583]
If possible, it would be great if Flye could support more than 128 threads. Feasible?

**Comment by mikolmogorov** [comment]
Flye will unlikely benefit from more than 128 threads. It may even degrade performance because of interprocess communication.

**Comment by DeadlineWasYesterday** [comment]
> Flye will unlikely benefit from more than 128 threads. It may even degrade performance because of interprocess communication.

Wouldn't minimap2 run faster with the extra threads? You could always set an upper limit to the number of processes but still make it a warning instead of an error.
