### ISSUE TITLE
2.9.2 local build and bioconda installation fails

### ISSUE THREAD

**Issue by xfengnefx** [fenderglass/ABruijn#585]
**Expected**: compile via make, or install from bioconda with `conda create -n env_flye -c bioconda flye=2.9.2`

**Happened**: make failed maybe due to LDFLAGS confusing autoconf in samtools; conda reports UnsatisfiableError, and defaults to v2.8.1 if no version number is specified.

---

**Local build**:

I tried to local build version 2.9.2 (60a89fd) on linux, and samtools' compilation failed. The directory is a clean git clone. The issue seems to come from the global definition of `export LDFLAGS += -lz # -L${MINIMAP2_DIR} -lminimap2` in the main Makefile (Flye/Makefile).

Flye/lib/samtools-1.9/configure [will need to eval](https://github.com/fenderglass/Flye/blob/60a89fd9fd0a84a971b07261167007ed1fd3dc6f/lib/samtools-1.9/configure#L2446) `ac_link_default` to test whether compiler is valid. The command expands to `$CC $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5`. This fails and reports that compiler is broken: `configure: error: C compiler cannot create executables` in main log, and the following in samtools' configure log:

```
configure:2449: checking whether the C compiler works
configure:2471: gcc   -lz -L/b/Flye/lib/minimap2 -lminimap2 conftest.c  >&5
/usr/bin/ld: cannot find -lminimap2: No such file or directory
collect2: error: ld returned 1 exit status
configure:2475: $? = 1
configure:2513: result: no
```

I'm not sure how to edit the Makefile for 2.9.2, but simple workaround works: compile and move samtools before make. I can successfully `make` 2.9-b1768 (tag/2.9), but not 2.9.1 (looks like the same issue as 2.9.2).

**Bioconda**:

Conda has a blank `UnsatisfiableError` for 2.9.2 when using `conda create -n env_flye -c bioconda flye=2.9.2` and with `conda config --set unsatisfiable_hints True`. Similarly, 2.9.1 and 2.9 also fails to install. `conda create -n env_flye -c bioconda flye` installs python3.7 and flye 2.8.1. I tried to see where is the conflict, but couldn't figure out. Sorry.

Thank you!

**Comment by mikolmogorov** [comment]
@xfengnefx that seems strange. Could you please provide full command lines that led to errors, and full terminal outputs?

For bioconda, does installing previous versions of Flye work (e.g. 2.9.1)? Whats is your OS and environemnt?

**Comment by xfengnefx** [comment]
Sorry, I think I made a few mistakes:

Local build: `make` goes through, but `make -j4` would produce the error above. 

Bioconda: conda's error message was not clear, I just needed a `-c conda-forge`. 

Thank you!
