### ISSUE TITLE
How do I assemble a mitogenome from whole genome data? 

### ISSUE THREAD

**Issue by imogen-foote** [fenderglass/ABruijn#587]
I am trying to figure out how to identify the mitogenome within my whole genome assembly from Nanopore reads. I have seen it done where the reads are filtered pre-assembly by subsetting reads that match mitogenomes of closely related species and then performing the nuclear and mitogenome assemblies separately. Is this the best way to do it, or does Flye have a built-in feature for separating the mitogenome? Are there any parameters I need to consider for a separate mitogenome assembly if that is the best way forward? I can't see any specific parameters related to mitogenomes in the documentation. 

My genome is ~1.2Gb, and closely related species mitogenomes are around 19kb. 

Thanks in advance!

**Comment by mikolmogorov** [comment]
Hi,

There are not specific parameters for mitogenome assembly. I would try using `--meta` switch on a whole set of reads first. It should assemble the mitogenome into a separate contig / graph connected component.

Misha
