### ISSUE TITLE
Flye parameter optimization for collapsed regions of high similarity

### ISSUE THREAD

**Issue by gwl2** [fenderglass/ABruijn#588]
I used flye for an assembly for a strain with a deposited reference genome.
When comparing a Contig with its reference, I noticed that the Flye assembly is slightly shorter. In the reference there are two regions with high similarity at the end right after each other(nicely visible in the dotplot after a self-alignment), these regions collapse in the flye assembly. The region is therefore shorter and the base sequence is a wild mix of the two regions.
When I map the reads to the assembly, I have a region with higher coverage exactly there. Also, you can see with your eye that there are two readsets with distinct base profiles mapping there.
Is there a way to optimize the flye parameters so that the region does not collapse and if so which one? This information is apparently available in the reads.

**Comment by mikolmogorov** [comment]
There are not too many parameters to optimize, as long as you are using the right options appropriate for your dataset.

What is the size of this duplication and is there any difference between copies. If it's a large nearly-perfect tandem duplication, this may be difficult to detect and assemble, and metaFlye may unfortunately collapse it.
