### ISSUE TITLE
Add depth of coverage to GFA file [feature request]

### ISSUE THREAD

**Issue by sjackman** [fenderglass/ABruijn#59]
[Bandage](https://rrwick.github.io/Bandage/) will draw the thickness of the unitig segments according to their depth when the segments include the read count (`RC:i`) attribute, and optionally colour the repeats in red.
See https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md#optional-fields-2

Unicycler also outputs the scaled depth of coverage in a tag `dp:f`, where 1.0 is the typical depth.

Could you please add `RC:i` and possibly also `dp:f` to `assembly_graph.gfa`?

**Comment by mikolmogorov** [comment]
Hi,

The newest developer version is actually using DP tag to output coverage - will merge it to the main branch shortly.

I was initially using KC to report coverage, but as I understand it basically correspond to "coverage * edge_length" value - and for long contigs this seemed to be causing integer overflows in Bandage (the coverage turned negative). 

Do you know how the RC tag is interpreted - is it just coverage or coverage * length? Is there any reason to have RC in addition to DP?

**Comment by sjackman** [comment]
`RC:i` is the absolute number of reads used to build a contig (or that align to a contig).
`dp:f` is the average (median or mean) depth of coverage of a contig.
Unicycler normalizes this value to 1.0 for typical coverage.
`dp:f` is not standardized by the GFA spec, so it should be in lower case.

> for long contigs this seemed to be causing integer overflows in Bandage

Wow. Were there more than 2 billion (2^31) reads aligned to the contig? That's a lot of reads.

**Comment by mikolmogorov** [comment]
I see. Read count probably is informative for Illumina assembly (where the read length is fixed), but I don't see much sense in it for PacBio/ONT assembly, where read length varies a lot.

The coverage output is important though. Based on the the Bandage code (https://github.com/rrwick/Bandage/blob/master/graph/assemblygraph.cpp , lines 670-700), it computes the coverage as ```RC:i / contig_length``` or ```KC:i / contig_length``` or as ```DP:f ``` (whatever is available).

> Wow. Were there more than 2 billion (2^31) reads aligned to the contig? That's a lot of reads.

To use ```KC``` for coverage output, I was multiplying coverage by contig length. So with a contig ~5mb and 1000x coverage you can get over 2^31. That is why I've switched to ```DP```.

**Comment by sjackman** [comment]
`dp:f:` works for me. Thanks, Mikhail! Does Flye report mean or median depth of coverage?

**Comment by mikolmogorov** [comment]
Sure, I will change the tag to lower case as you suggested. 

>Does Flye report mean or median depth of coverage?

Not in a very convenient way, but you can grep the log file for "Mean coverage" - that should do. Note that for coverages above 1000x it would be currently truncated to 1000 (hopefully, this kind of datasets are not very common :) )

**Comment by sjackman** [comment]
I wasn't clear in my question. I meant, does `dp:f` report the depth of coverage as the mean or median depth of coverage?

**Comment by mikolmogorov** [comment]
Ah, I see - it's a median coverage over 100 bp windows.

**Comment by mikolmogorov** [comment]
Resolved in aac22ec

**Comment by sjackman** [comment]
Thanks, Mikhail! (That commit link above is broken.)

**Comment by mikolmogorov** [comment]
Oups - must be 81aa281 and 7b22013, actually.
