### ISSUE TITLE
Final assemble genome size less than expected.

### ISSUE THREAD

**Issue by frsepulveda** [fenderglass/ABruijn#595]
Hi!

I was using flye to assemble a 100mb genome size of a red algae. But the final assemble size was only ~60Mb. 
How could i improve it? 
[flye.log](https://github.com/fenderglass/Flye/files/11252267/flye.log)
[assembly_info.txt](https://github.com/fenderglass/Flye/files/11252268/assembly_info.txt)

flye --threads 25 --pacbio-raw ../2A1.fa --out-dir ./ensamble --genome-size 100m --iterations 2

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Some suggestions are given in FAQ, and Flye does not have too many parameters to tune beyond that. 

I don't see anything suspicious in your log. Is the genome highly heterozygous? If so, is your genome size estimate haploid or diploid? Another reason for reduced assembly size could be many collapsed repeats.

**Comment by frsepulveda** [comment]
Hi!

My genome is haploid and 100Mb is their size. And probably is highly heterozygous. How could I assembly a probably high heterozygous genome and avoid the repeats? I read here in other post (#308) that may if i increase the minimum overlap parameter (i.e: -m 10000) it would be work, but i'm not sure.

**Comment by mikolmogorov** [comment]
Based on your info and provided logs, I don't have any other advice beyond what is already mentioned in FAQ and #308. Flye typically assembles all the unique sequence fairly well if the coverage is sufficient. It may collapsed similar haplotypes in diploid genomes - this remains a challenge, especially for the older data. The default parameters are optimized to work on various cases/genomes and tuning will unlikely result in substantial improvement.
