### ISSUE TITLE
Inconsistent depths between GFA and GV?

### ISSUE THREAD

**Issue by shigita** [fenderglass/ABruijn#597]
Hello,

I'm using Flye v2.9.2-b1786 to assemble a mitochondrial genome of a plant species.
Below is a visualization of two assembly graphs (GFA on the left, GV on the right) I got from a single run:

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/40628880/233137658-81ce0a89-03eb-4059-ba3b-93a68d02b441.png">

I found some inconsistencies in the depths of some edges.
For example, `edge_7` (`id 7`) has a depth of 260x in GFA, but only 33x in GV.
I wonder why they are different...🤔

[flye.log](https://github.com/fenderglass/Flye/files/11275229/flye.log)

Thanks,

**Comment by mikolmogorov** [comment]
Hi @shigita ,

Gfa coverage should be more recent. It is updated after read realignment and polishing, and the graphvis has the coverage prior to that.

The numbers should normally be largely consistent for long edges, but I see that it is not the case here. Not sure why is that, but it may be due a substantial number of reads that are shorter than minimum overlap threshold. Flye is not using these reads for graph operations, but they are used for polishing.

Hope this clarifies, let me know if you have any other questions!

**Comment by shigita** [comment]
Hi @fenderglass,

Thank you for the clear explanation!
Now it makes perfect sense, so closing this issue.

Thanks again,
