### ISSUE TITLE
How to add a supplementary polishing iteration 

### ISSUE THREAD

**Issue by ngirollet** [fenderglass/ABruijn#6]
Hello,
First, many thanks in giving access to this great tool. It works just fine on my pacbio sequences from a plant genome (500Mb). It's the only one abble to assemble the chloroplast and the mitochondrial in one contig each and give L50 metrics for less than 150 contigs.  
I've run Abruinj whith the default parameters except for the Kmer size that i've raise to 17. The polishing part iterated twice and  returned Alignment error rate: 0.208880757523 (Polishing genome (1/2)) then Alignment error rate: 0.165291041893 (Polishing genome (2/2)).
I suppose i will have to iterate more polishing steps to improve the quality of the assembly.
How can i launch only the Abruinj-polishing part of he tool ? 
Thank you for your reply.
\_(°-°)_/

**Comment by fenderglass** [comment]
Hi,
Thank you for your interest!
The reported alignment error rate is for the alignment of raw reads on the current assembly. Even if the assembly is polished, you would expect 12-16% errors comping from the reads, so the numbers you have does not necessarily mean that the genome requires more polishing.

Still, you can make an extra iteration and see if the statistics improve (most likely, for a tiny bit): use '--iterations 3' option together with '--resume' to add one polishing iteration to the existing assembly.

**Comment by zj-wien** [comment]
Hi,

I used the newest version of Flye (2.7-b1585) to handle nanopore reads (~60X, with default parameters except --asm-coverage 30). The assembly (N50: 14.7Mb) is much better than the one produced by Canu. Its Busco reaches almost 90%. The genome can annotate all of hox genes(39 genes) using homology-based prediction. But there are a lot of frameshift mutations in 38 genes.

**How to know how many iterations I need to polish?**  how about the Busco score? 

I also check if it's necessary to do more polishes with Racon. However, racon makes the quality of genome assembly worse. Busco score decreases to 86% and more hox genes get 'lost'.

Any suggestions are welcome.

Thanks a lot.

**Comment by mikolmogorov** [comment]
Polishing methods are now rapidly developing - it is hard to give a concrete advice on the best strategy. I'd suggest to look into recent literature - this might be a good start: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1727-y
