### ISSUE TITLE
assembly.fasta filename 

### ISSUE THREAD

**Issue by gryphon-98** [fenderglass/ABruijn#601]
Hi,
I am a new user and just wondering if there is a way to name the output assembly file name something more specific than assembly.fasta. I would like them to be coded to the sample name, I am currently outputing them each in their own folders and then changing the fasta file name manually, but I am hoping for a short cut. I am also very new to command line and programming speak, so please in English....
Thanks in advance.

**Comment by mikolmogorov** [comment]
Hi, 

There is no such functionality in Flye, but you can manually rename the file afterwards.
