### ISSUE TITLE
Creating 1 contig out of multiple contigs assembled from Flye

### ISSUE THREAD

**Issue by iek** [fenderglass/ABruijn#602]
Hello, I was wondering if you had suggestions on how to force merging of contigs that look very similar. For example, in the screenshot shown below, it seems that these two contigs could easily be merged into one because their variants are largely the same, so I was wondering if you had suggestions on how to do so? 

![Screen Shot 2023-05-03 at 2 12 43 AM](https://user-images.githubusercontent.com/12649783/235938283-715492e6-382e-408d-8a89-89e31c972576.png)

Note that my assembly has many of these contigs that seem like they can be merged further.

Thank you so much for your time and help.

**Comment by iek** [comment]
Hi, I just wanted to follow up and share that I tried using the "--no-alt-contigs" argument, and it seemed to make things even worse with more contigs at the same location that appeared to have the same variants:

<img width="301" alt="Screen Shot 2023-05-03 at 11 19 20 PM" src="https://user-images.githubusercontent.com/12649783/236105563-85758ecd-45b6-4297-97b4-cbf338065d45.png">

**Comment by mikolmogorov** [comment]
I think consider trying https://bitbucket.org/mroachawri/purge_haplotigs/src/master/. And filtering contigs my minimum length and coverage may also help.
