### ISSUE TITLE
assembly.gfa contains more contigs than assembly.fasta

### ISSUE THREAD

**Issue by mwittchen** [fenderglass/ABruijn#603]
Hello,
I am assembling ONT R10 LSK114 Reads of cultivated bacteria with flye (2.9-b1768). When I'm inspecting the assembly.gfa in Bandage, there is one more (short) contig than in the assembly.fasta. Shouldn't the number of contigs be identical in assembly.gfa and assembly.fasta as they are both the final output?

Best
Manuel

**Comment by mikolmogorov** [comment]
Hi Manuel,

One contig may contain multiple graph unitigs, this is why the number of sequences in `assembly.fasta` is often smaller.
