### ISSUE TITLE
get coverage information for uneven coverage assembly

### ISSUE THREAD

**Issue by wonaya** [fenderglass/ABruijn#604]
Hi, I was using Flye to get consensus sequence for unmapped reads of my alignment. 
Flye was able to identify an assembly but the average coverage was low <10x so I was wondering if there is a way to identify regions with higher coverage along this sequence. 

Thanks

**Comment by mikolmogorov** [comment]
@wonaya Flye does not have such functionality to annotate regions with high coverage, unfortunately.
