### ISSUE TITLE
What is assembly coverage?

### ISSUE THREAD

**Issue by ElderMedic** [fenderglass/ABruijn#605]
As far as I know, sequencing coverage refers to the proportion of a genome or a specific region that has been sequenced. Coverage is often given as a percentage. Therefore, I don't understand what asm-coverage actually is especially when it comes with an example of 40X, do you actually mean sequencing depth?
Also, why is it "reduced"? Your description on this parameter is quite vague, could you please explain the effect of tuning this parameter? What would happen if I set it higher or lower (will it leads to more overlapped longest reads to be used)?? 

Thank you!

**Comment by mikolmogorov** [comment]
Yes - in this context, it means "depth of coverage" or "read depth".
