### ISSUE TITLE
Working with PacBio and ONT

### ISSUE THREAD

**Issue by bplants10** [fenderglass/ABruijn#608]
Hi Mikhail, 
I have reads from both PacBio and ONT for the same species and I'm trying to utilize both in generating a final assembly. First, is there a way to feed both into Flye? 

If not, when I run --scaffoling, where is the scaffolding file being created so if I want to use an .agp file in something like quickmerge or ragtag?

**Comment by mikolmogorov** [comment]
Please see here: https://github.com/fenderglass/Flye/blob/flye/docs/FAQ.md#can-i-use-both-pacbio-and-ont-reads-for-assembly

Flye does not produce or take .agp as input.
