### ISSUE TITLE
can metaflye assembly long contigs and ngs contigs together

### ISSUE THREAD

**Issue by ye00ye** [fenderglass/ABruijn#611]
Hello, I'm now trying to get longer contigs through metaflye with my metagenomic datas. 

1, I sequenced the same sample with HiFi and NGS.
2, I assembly HiFi reads with metaflye and NGS reads with megahit, seperately. 
3, I put these two kinds of contigs together, and assembly them by metaflye, hoping to get longer contigs. 

But the results is opposite with what i thought, when i assembly these two kinds of contigs together with metaflye, i got less number of contigs, shorter sum length, and the max length is shorter than HiFi reads assembly, it seems that conducting second assemblying with HiFi_assembly contigs and NGS_assembly contigs is not a good way to get better result.   

                                                    number of contigs       sum length        min length       average length    max length
ngs_assembly (megahit)             402456	                         553305756	  500	            1374.8	               176906
HiFi_assembly (metaflye)            53559	                         416769874	  501	             7781.5	       799503
HiFi_ngs_assembly (metaflye)     632	                         8892894	          1333	             14071	               751904

I want to know the reason, thanks.

**Comment by mikolmogorov** [comment]
Hi @ye00ye

Flye is designed to assemble reads into contigs, but not for merging multiple assemblies. In general, merging assemblies from multiple technologies is not straightforward, and I am not aware of any push-button solutions. You may try something like quickmerge thohugh (https://github.com/mahulchak/quickmerge).

Misha
