### ISSUE TITLE
[question] is --asm-coverage used if coverage is lower?

### ISSUE THREAD

**Issue by JWDebler** [fenderglass/ABruijn#612]
Hi,

I'm putting a pipeline together and was wondering if I include `--asm-coverage` to reduce RAM for assemblies that have lots of reads, will that lead to a crash if fewer reads are available than the coverage target set via `--asm-coverage`, or will it get ignored in such a case?

Cheers

**Comment by mikolmogorov** [comment]
It should be fine if the coverage is lower.
