### ISSUE TITLE
Question: interpretation of telomeric and subtelomeric edges in GFA

### ISSUE THREAD

**Issue by castvox** [fenderglass/ABruijn#615]
Hello Dr. Kolmogorov,

I am an avid user of Flye for de-novo assemblies and wanted thank you for the continued maintence and updates on the software! 

Currently I am assembling multiple strains of our unicellular eukaryotic organism of interest (haploid linear genome). We generated nanopore sequencing data with the native barcoding kit14 on the R10.4.1 flow cells. This was basecalled on guppy with the with the HAC 5khz model which should be equivalent to SUP with less run-time. The base-called .fastq was filtered to remove host reads, read lengths <5kbp, and Qscore<10.

Flye was ran with the following parameters based on the FAQ suggestions: 
"--nano-hq --scaffold --trestle --no-alt-contigs --iterations 3 --extra-params output_gfa_before_rr=1"

Overall, the final assembly size is comparable to the chromosome lengths of current reference, but I had some questions interpeting some of the contigs and GFA paths. I've attached the "assembly.info.txt" and the GFA paths generated with Bandage.

**Example 1:**

| seq_name | length | cov | circ. | repeat | mult.| alt_group | graph_path
|--------|--------|--------|--------|--------|--------|--------|--------|
| contig_1 | 2386206 | 78 | N | N | 1 | * | 1 |
|contig_24 | 128858 | 112 | N| N| 1 | * | 24, *|
|contig_17|2328458|77|N|N|1|*|2, 17, *|
|contig_13|3882316|77|N|N|1|*|2, 13, *|

![image](https://github.com/fenderglass/Flye/assets/56974873/5f1b6b58-d222-46eb-aebd-23120c99ae07)

After reading the other users posts and your feedback on GFA paths,  it looks like:

 **Example: 1**":  "edge_24" contains a telomeric end but is inverted with "edge_1". Does this mean "edge_1" could be assembled end-to-end but flye is not merging them because there are no reads that span this repetitive region?  Therefore, would it be safe to manually merge and join the unitig sequences from "assembly_graph.gfa" and perform a round of polishing to resolve this region? 

Furthermore, I also know "edge_2" is a classical sub-telomeric repeat thats notoriously difficult to sequence through in our organism. Therefore, it would be the same idea to join "edge_24"+"edge_2"+"edge_13" and edge_24"+"edge_2"+"edge_17" to create finished chromosome level contigs for: contig_1, contig_13, contig_17.

I also see a similar pattern for two other assembled contigs in the assembly.

**Example 2:** 

| seq_name | length | cov | circ. | repeat | mult.| alt_group | graph_path
|--------|--------|--------|--------|--------|--------|--------|--------|
|contig_19|1196480|79|N|N|1|*|* , 19, 20, *|
|contig_21|3526781|79|N|N|1|*|* , -20, 21, *|

![image](https://github.com/fenderglass/Flye/assets/56974873/b6211192-8b1b-4ec4-8b57-fdcf10dbb750)

 **Example: 2**":  After flye polishing "contig_19" was assembled from "edge_19" + "edge_20" with both ends of the telomeres, but when "contig_21" was assembled it did not include the full sequence from "edge_20". However, contig_21 would be complete if those sequences were not trimmed. 

Overall I'm just wondering if I can use graph paths to logically merge/scaffold contigs to generate chromosome level assemblies. Previously when I scaffolded to the reference with Ragtag, I noticed there were disagreements with graph paths causing me to suspect misassemblies in the current reference. But I could also be over interpreting the GFA :-) 

Thank you for all the help!

**Comment by mikolmogorov** [comment]
Hi,

I think you understanding of these graphs is correct. The only caveat with sub-telomeric repeats is if these repeat copies are not exact, but have (for example) substitutions / small indels. You should be able to see that from read alignment profiles (e.g. in IGV). If there are small differences polishing procedure may not capture them properly.

Wrt to telomeres - sometimes they could be tricky. In general, a unique graph edge will be extended with a telomere if the read length is sufficient, but since there is an additional repeat in between chromosome and telomere, Flye won't do that. So you may need to estimate telomere lengths somehow. And in my experience with ONT, the telomeric parts are more prone to chimerism and basecalling artifacts - something to be aware of..

P.S. You can also try adding `--read-error 0.03`, which often improves R10 assmeblies.

Best,
Misha

**Comment by castvox** [comment]
Hello Dr. Kolmogorov,

Thank you for taking your time to answer! I definitely agree with you about ONT telomeric sequences. Prior data from the LSK109 with R9.4.1 flow cell data made it very difficult to resolve these regions, but there does appear to be an improvement with kit14 and the 5khz models. This is also why wanted to ask for your feedback on interpreting this :-). I will try adding "--read-error 0.03" to see if it improves the assembly. Thank you again! 

Update: My initial median overlap divergence from flye.log was 0.022792. I decided to increase -m from the default 8000 to 9000 and tried "--nano-hq --read-error 0.03". It significantly improved my assembly from 3/14 telomere ends to 10/14. Only issues were basecalling related where artificial repeats like GAGAGAGA would be introduced to my telomere ends so flye would add this on. Extra polishes would shorten the errogenous sequences but not completely remove them. However! I am very happy with the assembly and this is an easy fix by manually removing the problematic reads or trimming off these sequences.
