### ISSUE TITLE
Mapping raw reads to graph nodes

### ISSUE THREAD

**Issue by kdc10** [fenderglass/ABruijn#616]
Hi @fenderglass ,

Thanks for the great software! Is there information in the Flye output files stating which raw reads contributed to the construction/coverage of each graph node? I am looking through the various files and it is unclear to me if this information is stored and returned.

Thank you!

**Comment by mikolmogorov** [comment]
Hi,

Flye does not retain this information, but you can re-map reads with minimap2 and generate it.

Thanks,
Misha
