### ISSUE TITLE
Adjacent insertions in the assembly

### ISSUE THREAD

**Issue by sonaida** [fenderglass/ABruijn#617]
Dear all,
I am assembling viral genome with Flye using Nanopore reads. After verification with short Illumina reads
I found several similar mistakes in the assembly - two 1-2bp insertions located near each other.
Typical examples are shown below (the reference is a Flye assembly, reads are from Illumina):
<img width="448" alt="image" src="https://github.com/fenderglass/Flye/assets/77761689/84ecc036-57a1-499f-8156-c14077877fe3">
<img width="448" alt="image" src="https://github.com/fenderglass/Flye/assets/77761689/4e290091-5f0c-4ca6-b3fd-2fd6e939d5ed">

Is Flye prefer a basepair over deletion during collapsing of haplotypes? In the cases above insertions resulted in frameshifts.
Perhaps these cases (adjacent insertions) can be reviewed and removed during collapsing of haplotypes or polishing step?
Unfortunatelly, with --keep-haplotypes options viral genome can not be assembled as circular contig.
Best regards,
Sofia

**Comment by mikolmogorov** [comment]
Hi Sofia,

Indels, especially in homopolymer regions is a known issue for nanopore. Flye polisher theoretically should be smart enough to recognize a small insertion outside of homopolymers, but there is a small chance that it may not. This events should be random though.

How many events like this did you see overall? What is the coverage and chemistry? Is it just for one genome, or across multiple? Have you tried to add another polishing iteration? Also, what Flye version you are using?

Best,
Misha

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
