### ISSUE TITLE
Interest in test data

### ISSUE THREAD

**Issue by aclum** [fenderglass/ABruijn#62]
Hi, 
I was benchmarking on some of our validation data and found flye produced a misassembly that is correctly resolved by Canu and HGAP3.  Would you team be interested in this type of data to help improve the tool?
Thanks,
Alicia

**Comment by mikolmogorov** [comment]
Sure, it would be interesting to take a look. You can send the dataset to fenderglass@gmail.com if you prefer.

**Comment by mikolmogorov** [comment]
Thanks!
