### ISSUE TITLE
ValueError: invalid literal for int() with base 10:'[]\n'

### ISSUE THREAD

**Issue by RJKKK** [fenderglass/ABruijn#620]
Hi, Recently I am running flye 2.9, however the pipeline died with theValueError: invalid literal for int() with base 10:'[]\n' error.  The version of Python is 3.10. Could you please help me have a look? Thank you very much. 
![2e85b48ef7a58860f433ed73bcee8d1](https://github.com/fenderglass/Flye/assets/46342425/278b2f4b-2407-41ca-9f00-bdfe613ae4ed)

**Comment by mikolmogorov** [comment]
Very strange, is it specific to this particular dataset? You can check by running on the example dataset from the manual. If it specific to this dataset, could you please share `flye.log` and `40-polishing/contigs_stats.txt`?

Best,
Misha

**Comment by lhauff** [comment]
Hello,

I received the same error when attempting Flye with my data. Although when I ran Flye with the Loman_E.coli_MAP006-1_2D_50x.fasta dataset, there were no issues. I've attached my err log for the run and 40-polishing/contigs_stats.txt as recommended above. 

Thank you in advance for your help!

Best,
Lindsey

[contigs_stats.txt](https://github.com/fenderglass/Flye/files/12506668/contigs_stats.txt)
[flye.mem001.30667018.txt](https://github.com/fenderglass/Flye/files/12506729/flye.mem001.30667018.txt)

**Comment by mikolmogorov** [comment]
Thanks, this is very helpful! I think I know where the bug is - do you mind trying the version `2.9.1` and check if that works for you? Feel free to restart from the polishing stage.

**Comment by lhauff** [comment]
That worked, thank you!

**Comment by mikolmogorov** [comment]
Glad to hear! I've added a fix to the upstream github, and it will be incorporated into the next release.
