### ISSUE TITLE
Generating assembly_info.txt (mainly Coverage information) from BAM Files

### ISSUE THREAD

**Issue by wyanren** [fenderglass/ABruijn#624]
Hi,

I've been using various nanopore assembly methods and I'm trying to obtain a **assembly_info.txt** file containing **coverage** information when using other assembly methods. I've experimented with the **jgi_summarize_bam_contig_depths** (tool in [MetaBAT)](https://bitbucket.org/berkeleylab/metabat/src/master/) to extract coverage data from bam files. However, I noticed that the coverage data obtained from this tool is significantly different from the data in **assembly_info.txt**.

In this cases, I wonder is there **a standalone code** that can directly generate coverage information matching the format of **assembly_info.txt** by simply inputting a bam file? If not, could you recommend any bioinformatics tools or approaches to retrieve this information for comparison purposes with other software?

Thank you for your assistance!

### assembly_info.txt from **flye** 
| seq_name   | length  | cov. | circ. | repeat | mult. | alt_group | graph_path |
|------------|---------|------|-------|--------|-------|-----------|------------|
| contig_1   | 5338    | 147  | N     | N      | 147   | *         | *,1,*      |
| contig_100 | 22333   | 172  | N     | Y      | 1     | 214       | *,100,*    |
| contig_101 | 24625   | 143  | N     | Y      | 1     | 248       | *,101,*    |
| contig_104 | 9497    | 177  | N     | Y      | 1     | 216       | *,104,*    |
| contig_105 | 401337  | 318  | N     | N      | 1     | *         | 105        |
| contig_106 | 3568    | 88   | N     | Y      | 1     | 118       | *,106,*    |
| contig_107 | 6010    | 159  | N     | Y      | 1     | 202       | *,107,*    |
| contig_11  | 4839    | 160  | N     | Y      | 1     | 192       | *,11,*     |
| contig_13  | 28055   | 171  | N     | Y      | 1     | 230       | *,13,*     |
| contig_14  | 78751   | 166  | N     | N      | 1     | *         | 14         |
| contig_15  | 131440  | 146  | N     | N      | 1     | *         | 15         |
| contig_17  | 3244    | 121  | N     | Y      | 1     | 232       | *,17,*     |
| contig_18  | 7098    | 148  | N     | Y      | 1     | 218       | *,18,*     |

### Depth.txt from **jgi_summarize_bam_contig_depths** 
| contigName  | contigLen | totalAvgDepth | alignment.sorted.bam | alignment.sorted.bam-var |
|-------------|-----------|---------------|----------------------|--------------------------|
| contig_1    | 5338      | 6.91712       | 6.91712              | 15.9309                  |
| contig_100  | 22333     | 94.6815       | 94.6815              | 223.138                  |
| contig_101  | 24625     | 79.0988       | 79.0988              | 72.1433                  |
| contig_104  | 9497      | 99.1659       | 99.1659              | 96.1616                  |
| contig_105  | 401337    | 68.9705       | 68.9705              | 832.069                  |
| contig_106  | 3568      | 42.0012       | 42.0012              | 17.0177                  |
| contig_107  | 6010      | 81.2531       | 81.2531              | 6.68294                  |
| contig_11   | 4839      | 96.7827       | 96.7827              | 20.4398                  |
| contig_13   | 28055     | 103.85        | 103.85               | 209.217                  |
| contig_14   | 78751     | 89.5687       | 89.5687              | 254.594                  |
| contig_15   | 131440    | 74.3024       | 74.3024              | 144.239                  |
| contig_17   | 3244      | 59.1574       | 59.1574              | 10.1269                  |
| contig_18   | 7098      | 80.1744       | 80.1744              | 368.314                  |

**Comment by mikolmogorov** [comment]
Hello,

I am not sure how exactly `jgi_summarize_bam_contig_depths works`, so it is hard to tell exactly why you see this difference. Flye computes coverage as a median over 100bp windows, and it seems that jgi script computes average. This may explain the difference - as you see the variation is very high.

Flye does not standalone code to generate these statistics. There should be a varietly of tools such as `samtools depth` to copute similar statistics.

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
