### ISSUE TITLE
pacbio-hifi error

### ISSUE THREAD

**Issue by ngarud** [fenderglass/ABruijn#626]
Hello! 

I've been running some tests on smaller subsets of my data and am encountering an issue with the pacbio-hifi mode. My data is indeed pacbio hifi from a metagenome (human stool). I am able to assemble contigs with pacbio-raw, but when I run the same with pacbio-hifi, I get this error: 

ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct

The command I ran was:
flye --pacbio-hifi $data_path --out-dir $output_path --meta --debug

I'm worried with pacbio-raw mode, I may be joining reads that shouldn't be joined due to the higher assumed error rate. 

Many thanks in advance for your advice.

**Comment by mikolmogorov** [comment]
The most likely reason for not producing the assembly is the lack of coverage (10-20x+ for bacteria). I would try to assemble the full dataset first.

**Comment by ngarud** [comment]
Thanks so much for this response. When you suggest assembling the full
dataset first, do you mean with pacbio-raw? I managed to produce output for
that (17K contigs were produced).

Should I be concerned about reads being merged onto the same contig due to
the higher assumed sequencing error rate? If so, what can I do to
address this?

Finally, I have short reads too -- would polishing help with removing any
sequencing errors from the contigs?

Thank you!

**Comment by mikolmogorov** [comment]
You mentioned that you assembled a smaller subsets of your data, I am assuming it is a subset of HiFi reads? The best strategy is assemeble with HiFi, but the whole set, rather than a subset. You won't need short-read polishing with HiFi.

**Comment by ngarud** [comment]
Thanks for this response! I just tried assembling the entire dataset with the pacbio-hifi mode, but received this error:

"No disjointigs were assembled - please check if the read type and genome size parameters are correct"

The command I used was: flye --pacbio-hifi $data_path --out-dir $output_path --genome-size 100m --meta --debug

Once again, I was able to successfully assemble with pacbio-raw. 

Might you have any recommendations on how to proceed? I also have short reads, in case they can be used for a polishing step for the genomes assembled with pacbio-raw. Please advise!

**Comment by mikolmogorov** [comment]
I think this likely means you don't have enough read coverage to assemble. What is the total size of your reads? Could you also send `flye.log`? Does hifiasm_meta assemble your data?

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
