### ISSUE TITLE
Flye estimates the genome size to be too big

### ISSUE THREAD

**Issue by RacheliHadjez** [fenderglass/ABruijn#627]
Hello,
I am trying to assemble a genome of an organism called Henneguya salminicola. Its genome was assembled with Illumina and its genome size is about 60 Mb.
I am trying to assemble its genome again but with pacbio sequences, but in the assembly flye creates it gives 300 Mb in genome size.
The script I used to run it:
module load flye-2.9.2

flye --pacbio-hifi /dorotheeh/hadjez/FilteredResults_Q20.fastq --genome-size 70 --out-dir /dorotheeh/hadjez/Flye_HSA2 --threads 12 --iterations 1 

The error file I received:
[Flye error.txt](https://github.com/fenderglass/Flye/files/12406590/Flye.error.txt)

Do you have any idea what might be the problem?
Thank you!!

**Comment by mikolmogorov** [comment]
Hello,

Flye assemblies are not expected to contain large duplications, so it is likely that all assembled sequence is real. It could be that the your genome contains a lot of repeats / heterozygosity that Illumina failed to assemble. Or you may have contamination.

Best,
Misha

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
