### ISSUE TITLE
Very time consuming assembly (initial disjointing step)

### ISSUE THREAD

**Issue by dmjask** [fenderglass/ABruijn#628]
Hi,
We've been using Flye to assemble Atlantic salmon from ONT long reads, but experience that it requires a lot of time.
The genome is comparable in size to human, ~2.9Gb, but is additionally duplicated (partially tetraploid) with larger, more numerous repetitive regions. 
Assembling a genome with 17X coverage, using the --asm-coverage 40 and overlap of 10k, required ~13200 CPU hours using Flye 2.9.
The initial step of disjointing assembly consumes approx. 90% of the CPU hours. 
As we have several more assemblies to complete, is there any known issue with such assemblies, or optimizations to include in order to speed up the process?

**Comment by mikolmogorov** [comment]
Hello,

Sounds like a complex genome to assemble. In general, there are not too many parameters to tweak by design. What basecaller are you using? Is it `--nano-hq` or `--nano-raw` (former is usually much faster)? Could you also share `flye.log` file?

**Comment by dmjask** [comment]
We've been using --nano-raw, but I just found out Guppy v6.3.9 was used for basecalling so will try the --nano-hq instead. 

Attached the flye.log for the described example:
[flye.log](https://github.com/fenderglass/Flye/files/12534312/flye.log)

**Comment by mikolmogorov** [comment]
`--nano-hq` should be substantially faster, but let us know if you still have issues.

**Comment by dmjask** [comment]
We have two files basecalled with Guppy3, which we use as additional input to more recent (Guppy6) datasets of the same samples. 
Would --nano-hq also be applicable to these? Alternatively, would merging the files allow for use of --nano-hq?

**Comment by mikolmogorov** [comment]
It should work, but the best case scenario would be if you can rebasecall older data. But this can be a pain sometimes..

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, but feel free to follow up if you have any questions!
