### ISSUE TITLE
Errors during build for tag  2.3.6.

### ISSUE THREAD

**Issue by singhindresh** [fenderglass/ABruijn#63]
I'm getting following error during build for tag 2.3.6. Help is appreciated.
(flye):/usr/local/devel/BCIS/external_software/Flye $ git checkout tags/2.3.6
Note: checking out 'tags/2.3.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5fe67bb try to recover from wrong numWindows
(flye) isingh@lserver1:/usr/local/devel/BCIS/external_software/Flye $ python setup.py build
running build
make release -C src
make[1]: Entering directory `/usr/local/devel/BCIS/external_software/Flye/src'
g++ -c -I/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo -I/usr/local/devel/BCIS/external_software/Flye/lib/interval_tree -I/usr/local/devel/BCIS/external_software/Flye/lib/lemon -I/usr/local/devel/BCIS/external_software/Flye/src/include -I/usr/local/devel/BCIS/external_software/Flye/lib/minimap2 -Wall -pthread -std=c++11 -g -D_LOG -O3 -DNDEBUG repeat_graph/contig_extender.cpp -o repeat_graph/contig_extender.o
In file included from repeat_graph/repeat_graph.h:9:0,
                 from repeat_graph/contig_extender.h:7,
                 from repeat_graph/contig_extender.cpp:5:
repeat_graph/../sequence/sequence_container.h:140:2: error: expected class-name before ‘{’ token
repeat_graph/../sequence/sequence_container.h: In constructor ‘SequenceContainer::ParseException::ParseException(const string&)’:
repeat_graph/../sequence/sequence_container.h:143:22: error: expected class-name before ‘(’ token
repeat_graph/../sequence/sequence_container.h:143:22: error: expected ‘{’ before ‘(’ token
In file included from /usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/cuckoohash_map.hh:28:0,
                 from repeat_graph/../sequence/overlap.h:11,
                 from repeat_graph/repeat_graph.h:10,
                 from repeat_graph/contig_extender.h:7,
                 from repeat_graph/contig_extender.cpp:5:
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh: In member function ‘void libcuckoo_bucket_container<Key, T, Allocator, Partial, SLOT_PER_BUCKET>::clear()’:
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:222:9: error: ‘is_nothrow_destructible’ is not a member of ‘std’
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:222:46: error: expected primary-expression before ‘>’ token
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:222:47: error: ‘::value’ has not been declared
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:223:13: error: ‘is_nothrow_destructible’ is not a member of ‘std’
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:223:53: error: expected primary-expression before ‘>’ token
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:223:54: error: ‘::value’ has not been declared
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh: In member function ‘void libcuckoo_bucket_container<Key, T, Allocator, Partial, SLOT_PER_BUCKET>::destroy_buckets()’:
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:279:19: error: ‘is_nothrow_destructible’ is not a member of ‘std’
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:279:54: error: expected primary-expression before ‘>’ token
/usr/local/devel/BCIS/external_software/Flye/lib/libcuckoo/libcuckoo_bucket_container.hh:279:55: error: ‘::value’ has not been declared
make[1]: *** [repeat_graph/contig_extender.o] Error 1
make[1]: Leaving directory `/usr/local/devel/BCIS/external_software/Flye/src'
make: *** [all] Error 2
Compilation error:  Command '['make']' returned non-zero exit status 2

**Comment by mikolmogorov** [comment]
Hi,

Which compiler version are you using? Most likely it is due to an old version of GCC / Clang that does not fully support C++11.
