### ISSUE TITLE
Flye assembly stats on assemblies from different tools?

### ISSUE THREAD

**Issue by samnooij** [fenderglass/ABruijn#631]
My question is similar to #624: I would like to have output like Flye's `assembly_info.txt` on assemblies that are not from Flye. From a fasta file basically. 

I've been assembling bacterial genomes with Flye and other tools (Raven, Canu and Hifiasm). Now for the cases in which Flye does not yield a circular chromosome, I would like to try and combine assemblies and know if the resulting sequences are circular.

I noticed that the `--subassemblies` option does not work with PacBio HiFi input reads, and `--polish-target` only gives length and coverage information. Would there be another way to use the output from another assembly as additional input to Flye? Or to at least create the assembly info file? Or maybe just tell if a sequence is circular or not?
Thanks in advance.

**Comment by mikolmogorov** [comment]
Unfortunately there is no such functionality - this extra information is extracted from Flye graphs, but a fasta file won't have that.

**Comment by samnooij** [comment]
I was afraid so. Thank you for the swift reply! :)
In that case I think I should give Trycycler a try.
