### ISSUE TITLE
Identify alternative haplotypes in assembly

### ISSUE THREAD

**Issue by alexvasilikop** [fenderglass/ABruijn#632]
Hello,

I used the --keep-haplotypes option in v. 2.9.2 and I am interested to see which contigs are alternative haplotypes of one another and/or how many haplotypes were assembled per contig/region. Can I find this info somewhere in the output files?

Thanks
Alex

**Comment by mikolmogorov** [comment]
Hi Alex,

Take a look here, everything that was inside bubbles will have alternative group id: https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-flye-output

Hope this helps,
Misha
