### ISSUE TITLE
Duplication spanned by a single read

### ISSUE THREAD

**Issue by cstritt** [fenderglass/ABruijn#634]
Hi Mikhail,
We are using Flye to assemble bacterial genomes from PacBio HiFi reads, which works excellently. Now I've come across a case where Flye does not manage to close a  genome because of what seems to be a duplication. A closer look at the reads suggests that there is one single read that spans the duplication (purple read in the igv screenshot, showing the reads aligned against a closely related genome; the overlap on the right side is only ca. 140 bp). 

Is there a way to solve this by tweaking Flye? Or am I misunderstanding the evidence?

Many thanks for the excellent work!
Christoph

![graph](https://github.com/fenderglass/Flye/assets/35330730/e76b2179-7ea5-4d3d-8a8f-0eff54d8ec35)
![igv_snapshot](https://github.com/fenderglass/Flye/assets/35330730/43d5eccc-f4dd-4926-ac44-3f4f28b40ff1)

**Comment by mikolmogorov** [comment]
Hi @cstritt,

It does seem like there is a single spanning read. The problem for Flye is that it only works with alignments of size 500bp+, so the uniquely aligned tip of your read is shorter than this. This parameter is difficult to change without modifying the code, unfortunately.

One possibility to check is you may have more spanning reads, but there is disagreement between them. This may happen if there is heterogeneity in the culture, for example. If you can send your `flye.log` - I can take a look.

**Comment by cstritt** [comment]
Thanks for the fast reply, here is the log:
[flye.log](https://github.com/fenderglass/Flye/files/12645328/flye.log)

**Comment by mikolmogorov** [comment]
Sorry for the late reply - I don't see anything suspicious in the log. I think it wasn't resolved since the uniqe flanking sequence is below the required threshold.

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, but feel free to follow up if you have any questions!
