### ISSUE TITLE
Pooled low-input HiFi libraries for flye

### ISSUE THREAD

**Issue by deoliveira86** [fenderglass/ABruijn#636]
Dear @fenderglass,

How are you? I have a general question concerning flye in HiFi mode. We have sequenced using the low-input protocol five different individuals and the individual results are great in terms of completeness (i.e. BUSCO, merqury plots). However, since each low-input SMRT cell yields around 10-13x coverage for my target species and the genome is roughly 80% repeat-rich, the draft assemblies are a bit fragmented and I would like to pool all the libraries together and obtain a more contiguous genomic reference. My attempts so far with the 2, 3, 4 and the 5 pooled libraries with hifiasm have been unsuccessful. The pooled genome assembly is highly fragmented and the reconstructed genome size is way bigger than expected. I am assuming that this might be due the heterozigosity and the generation of a multitude of haplotigs during the sequence reconstruction.

To try to circumvent this issue, I think using flye would help since haplotigs are "squashed" by default during the assembly run. Do you have any recommendations of parameters or any experience with pooled HiFi libraries and hi-flye reconstructions? Below the GenomeScope2 plot containing the five pooled libraries.

![image](https://github.com/fenderglass/Flye/assets/54496369/5d87efbb-b63e-4627-873a-544e763209d2)

Best,
André

**Comment by mikolmogorov** [comment]
Hi André,

I think it may work. I'd try different values of `--read-error`, the default is 0.001, and I'd start with maybe `0.01`, and maybe eve a higher value if you expect heterozygosity to be higher.

**Comment by deoliveira86** [comment]
Hello @fenderglass,

Thanks for your input. The initial run with flye with and default parameters did not produce good results. The genome size is  ~3x bigger and it is really fragmented (>100k contigs). I will increase the error rate to 0.03 and check the results, and if better than the default parameters, I will play around with the error-rate values. 

I got great results merging the individual hifiasm assemblies into a "primary" assembly with ragtag (scaffold and merge), but I would like to see if I can produce nice results too using all the libraries in a single run.

Thanks again for the help. I keep you posted about the results. (I will close this issue by now and re-opened when I get the results).

Cheers,
André
