### ISSUE TITLE
Question for my understanding of the tool

### ISSUE THREAD

**Issue by Meer9234** [fenderglass/ABruijn#639]
Hello,

I am a masters student and I was working on the assembly of a genome and wondering about the contiguity and if I had all chromosomes. I sequenced with the 10.4.1 flow cells. As nanopore is improving so much I was wondering if the assembly tools were lagging behind, because I think it should with the 10.4.1 be possible to assemble a telomere to telomere genome?

Kind regards

**Comment by mikolmogorov** [comment]
Hello,

Thanks for your questions and your interest in gene assembly. In general, this issue board is only for issues/questions that are specific to Flye. I think https://www.biostars.org/ would be a better venue to ask more general questions, and you will likely get much more responses as well!
