### ISSUE TITLE
ERROR: Looks like the system ran out of memory (flye)

### ISSUE THREAD

**Issue by jokopebri** [fenderglass/ABruijn#641]
Hi there,

I tried to perform bacterial genome assembly of ONT sequencing data using flye (Flye 2.9.2-b1786). However, I encountered an error showing the system ran out of memory. I used laptop with 16GB RAM and the bacteria is bacillus, so I think this should not be the case. Attached is the log file.
[flye.log](https://github.com/fenderglass/Flye/files/13048375/flye.log)

for the input command:

flye --nano-raw merged.fastq.gz --out-dir flye_test

Any suggestions how to make this work?

Thanks a lot

**Comment by mikolmogorov** [comment]
Hi, 

You are running out of memory, the log shows that only 7Gb is available. The only solution is running on a machine with more memory, unfortunately. Please refer to the manual for the resource requirement estimates.

**Comment by jokopebri** [comment]
Hi Fenderglass,

Many thanks for your answer!

**Comment by olawa** [comment]
I am guessing it is just too high coverage - if you want to play around with it to get it to work on a laptop you can use Filtlong to remove lower quality reads and then run flye with nano-hq.

**Comment by jokopebri** [comment]
Hi Olawa,

Thanks for your suggestion! It works!

I changed the command of --nano-raw to --nano-hq and I managed to get the assembly to work. Before that, I used chopper to filter the reads instead of Filtlong. I still wonder why the --nano-hq was  able to work using my laptop.

Thanks once again.
