### ISSUE TITLE
what's the meaning of  repeat and mult. columns in assembly_info.txt with metagenomic data?

### ISSUE THREAD

**Issue by weiwei4396** [fenderglass/ABruijn#643]
Hi, Thank you for so great tools! But I have a bit of confuse of the output of flye result. After assembling my metagenomic data, I watch the assembly_info.txt and find some strange things for me.

> #seq_name       length  cov.    circ.   repeat  mult.   alt_group       graph_path
contig_1908     3592675 110     N       N       2       *       1908
contig_5851     662     10      N       Y       1       4632    5851

As you can see, some contigs are unique based on the 'repeat' column but the value of the 'mult.' column is not 1, which is not what I expected. Also, in contrast, some contigs are repeat but the value of the 'mult.' column is 1.
I have no idea about it. Is it because the metagenomic data? Based on your tutorial, I think when the 'repeat' column is 'Y' the value of 'mult.' column should not be 1 and vice versa. Do I misunderstand? I would be very grateful if you could give me your valuable advice.

**Comment by mikolmogorov** [comment]
Hi,

For metagenomic data, `multiplicity` column indeed does not make much sense - it's basically contig coverage divided by the median dataset coverage. `repeat` column should correspond to actual repeats, which are defined differently (not based on coverage) in the case of metagenome. You can check the metaFlye paper to see how we defined repeats in this context.

**Comment by mikolmogorov** [comment]
Marking as resolved, but feel free to follow up if you have more questions!
