### ISSUE TITLE
small deletion errors in assemblies

### ISSUE THREAD

**Issue by morgannprice** [fenderglass/ABruijn#644]
Hi,

I've been using flye to assemble bacterial genomes from PacBio HiFi reads. I also have some Illumina reads from these bacteria.

I noticed that several of my assemblies have small deletions of around 10-20 nucleotides. These deletions are not supported by either the HiFi or Illumina reads. And they occur at multiples of 1 million nucleotides.

Here's an example of the output from pilon. This was comparing Illumina reads to the flye assembly, but I verified that the HiFi reads also support these changes:

contig_4:999995 contig_4_pilon:999995-1000013 . GGGGCGTGCCGGTGGCGGG
contig_4:1999976 contig_4_pilon:1999995-2000003 . AACAACCTG
contig_4:2999968 contig_4_pilon:2999996-3000006 . AGAGTTGAAAT
contig_4:3999956 contig_4_pilon:3999995-4000003 . ATGGTCGGA

When I checked flye's intermediate files, I found that 30-contigger/contigs.fasta and 30-contigger/graph_final.fasta contain the correct sequence, and 40-polishing/filtered_contigs.fasta has the deletions..

I'm using flye 2.9-b1768, run with the --pacbio-hifi option. The hifi reads that I used to generate the assembly are at
http://morgannprice.org/tmp/GW822-FHT02A07.filtered.fastq.gz
and the results directory from flye is at
http://morgannprice.org/tmp/GW822-FHT02A07_flye.tar.gz

Thanks,
Morgan

**Comment by mikolmogorov** [comment]
Hi Morgan,

This issue was fixed in the 2.9.1 release. It was connected to the way Flye was chunking contigs into smaller parts for polishing.

Misha
