### ISSUE TITLE
Provide potential sequence circularity in Fasta headers

### ISSUE THREAD

**Issue by oschwengers** [fenderglass/ABruijn#647]
Hi and thanks a lot for developing & maintaining Flye!
For many downstream analyses (like genome annotation with Bakta), information on sequence completeness and circularity is precious and very important. Hence, it would be very helpful, if Flye could provide this information in the Fasta headers of resulting final sequences.

Currently, this information is contained implicitly in the graph (which seldom are used as annotation import) and explicitly in the `assembly_info.txt` file. However, this file is seldom available in downstream tasks and would require additional custom parsers. Providing this info in the Fasta headers would be much easier and more straightforward, since they would be stored together with assembled sequences.

For instance, Bakta is already able to extract such circularity tags from Unicycler (`circular=true`). Would it be possible to add such a circularity tag to the regular Fasta files of Flye's final results?

Thanks again and best regards
Oliver

**Comment by mikolmogorov** [comment]
Hi Oliver,

Flye had this output format for years now, and I'm reluctant to changing it because it will likely break things elsewhere. Fetching the circularity information from assembly_info and adding it to fasta should be a simple postprocessing task..

Misha
