### ISSUE TITLE
ERROR: Error running minimap2

### ISSUE THREAD

**Issue by AzlanNI** [fenderglass/ABruijn#648]
Hello everyone! 
I am using Fyle for the first time and i am trying to generate a genome with my Nanopore Reads. 
So i used the following code on our HPC : 

flye --nano-raw /input_path/Concat_first.fastq.gz -o /output_path/Flye_Results

I just get the Error: 
[2023-11-13 15:28:19] ERROR: Error running minimap2, terminating. See the alignment error log  for details: /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Flye_Results/10-consensus/minimap.stderr
[2023-11-13 15:28:19] ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Flye_Results/10-consensus/chunks.fasta /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Concat_first.fastq.gz -x map-ont -t 1 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Flye_Results/10-consensus/chunks.fasta -u - | flye-samtools sort -T /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Flye_Results/10-consensus/sort_231113_152819 -O bam -@ 4 -l 1 -m 1G']' returned non-zero exit status 1.
[2023-11-13 15:28:19] ERROR: Pipeline aborted

so i looked it up in in the .stderr file
[ERROR] unknown option in "/gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/Concat_first.fastq.gz"

So i tried to load the modules for minimap and SamTools into the HPC command. And now i am looking up the minimap2 code to understand why this Error occurs. 

And the unknown Option in minimap2 occurs if a unrecognized option is encountered. So am i missing anything in my flye code 

If Anyone know how i can resolve this i would be very thankful. 

kind regards, 

Azlan

**Comment by AzlanNI** [comment]
[flye.log](https://github.com/fenderglass/Flye/files/13336663/flye.log)
Thats the Log file

**Comment by mikolmogorov** [comment]
Hi Azlan,

It seems like you may have a corrupted fastq file. You can try running minimap2 with your fastq as output manually to double check.

Misha

**Comment by AzlanNI** [comment]
Alright i will try and give feedback, thanks!

**Comment by AzlanNI** [comment]
I just used minimap2 on my fastq.gz files with this command : 


for fastq_gz in *.fastq.gz; do
    file_name=$(basename "$fastq_gz" .fastq.gz)
    
    minimap2 -ax map-ont "$reference" "$fastq_gz" > "${file_name}_mapped.sam"
    
    
    samtools view -bS "${file_name}_mapped.sam" > "${file_name}_mapped_reads.bam"
    
    
    rm "${file_name}_mapped.sam"
done

and the result is a bam File with 224764 primary aligned reads so no Error at all. So maybe the problem is that i cat the .fast.gz files into a summarized File with cat *.fastq.gz and the resulting cat_fastq.gz File is used as input for Flye. 

Is it possible that i use a loop like the minimap2 loop to work through all .fastq.gz files with flye ? 

Else i would not understand the corrupted fastq cause minimap2 is running normal without any Errors. 

Thanks for ur help! 

Kind regards, 
Azlan

**Comment by mikolmogorov** [comment]
Yes, I suspect that your contatenation of fastqs might be corrupted, not the individual files.

**Comment by AzlanNI** [comment]
Okey i tried it now with only the fastq.gz files as input and also tried to ungzip the files and cat the fastq files. Both time i get the same Error: 
[ERROR] unknown option in "/gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/20220808_1049_MN35772_FAT66084_549a5f66/fastq_pass/barcode01/fastq_files/all_files.fastq"

This is the log file: 
[flye.log](https://github.com/fenderglass/Flye/files/13503224/flye.log)

I will try the same now with a different set of fastq files. But maybe u guys can see the problem in the log file. 

Thanks! 

Azlan

**Comment by mikolmogorov** [comment]
Could you please send the full minimap stderr file?

**Comment by AzlanNI** [comment]
[ERROR] unknown option in "/gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Bac_DNA_Sebastian/20220808_1049_MN35772_FAT66084_549a5f66/fastq_pass/barcode01/fastq_files/all_files.fastq"

This is everything which is in the stderr file. Sorry i cant download the entire file from the hpc cluster right now. 
I also tried the procedure with a different set of fastq.gz files and i still get the same Error. 

Maybe something is wrong with my command ? Because if u run Minimap2 separately on the fastqs it runs without problems.

**Comment by mikolmogorov** [comment]
I think something may be wrong with your installation. If you compiled from source, you may have an outdated version of minimap2 binary, which is shipped with Flye. I'd suggest either performing a clean reinstall from source, or trying a bioconda version in a separate environement. You should certainly expect the example datasets (that are provided in the manual) to work out of the box.

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, but feel free to follow up if not!
