### ISSUE TITLE
How can I aseemble Plasmid and Chromosome separately?

### ISSUE THREAD

**Issue by DaHye0205** [fenderglass/ABruijn#650]
I want to use flye using Nanopore results. My sample contains plasmid. However, currently Flye does not allow --plasmid, so a problem arises where the plasmid sequence is merged with the chromosome sequence.
I want to obtain Plasmid and Chromosome separately.
Please help me what to do.

Also, if the genome size is not known, is it okay to enter an arbitrary value (ex. 5.5m)?

$ flye --nano-raw /home/user/DAHYE/WGS/231019RUN/14/barcode14_porechop.fastq.gz --genome-size 5.5m --threads 16 --plasmid --out-dir dir

usage: flye (--pacbio-raw | --pacbio-corr | --nano-raw |
--nano-corr | --subassemblies) file1 [file_2 ...]
--genome-size size --out-dir dir_path [--threads int]
[--iterations int] [--min-overlap int] [--resume]
[--debug] [--version] [--help]
flye: error: unrecognized arguments: --plasmid

My version 2.3.1

Thank you.

**Comment by mikolmogorov** [comment]
Hello,

Flye does not have an option to only assemble plasmids. You can extract plasmid sequence from the final assembly.

**Comment by DaHye0205** [comment]
If a Fasta file with one contig is created, how can I extract the plasmid?

thank you

**Comment by mikolmogorov** [comment]
Plasmid would typically assemble into its own contig. If you have just one, it means the plasmid was not assmebled.

**Comment by DaHye0205** [comment]
thank you!
