### ISSUE TITLE
Assembling with "high" heterozygosity

### ISSUE THREAD

**Issue by barke042** [fenderglass/ABruijn#651]
I recently completed an assembly for an ~1.3 Gbp genome with ~25x coverage using Flye 2.9.2-b1786. The call was straightforward: `flye --pacbio-hifi hifi_reads.fastq.gz --out-dir flye_out --threads 32`

The resulting assembly was ~2.3 Gbp in length with a mean coverage of 12, both suggesting that haplotypes had not been collapsed. Blast searches of the assembly for a couple of genes both yielded two hits, both in adjacently-numbered contigs.

I aligned a couple of these haplotypes and estimate heterozygosity for the sequenced individual at around 0.003. There is also a fair amount of (mostly short) indel variation, of course. That doesn't seem too unusual for an outbred species with a relatively large population size, but maybe this is causing issues?

Any thoughts on approaches to collapsing haplotypes?

**Comment by mikolmogorov** [comment]
You can try using `--read-error` parameter. By default for hifi it is `0.001`, and you can try setting it to `0.005` or `0.01`. An alternative is to run `purge_haplotigs` after assembly. But collapsing heterozygosity during assembly should increase overall contiguity.

**Comment by barke042** [comment]
Thanks, I will give these a try!

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, but feel free to follow up if not!
