### ISSUE TITLE
[Question] How to estimate -g genome-size for --meta mode?

### ISSUE THREAD

**Issue by jolespin** [fenderglass/ABruijn#652]
I want to add this into my https://github.com/jolespin/veba software suite for the updated v2 release.  

A few questions regarding the `-g` argument:
1. How much does this value influence the performance and output of the assemblies? 
2. How can I estimate the genome size for a metagenome or a genome whose size is unknown w/ no close representatives?
3. Is there a tool used by Flye or Metaflye that can estimate this value?

**Comment by mikolmogorov** [comment]
Hello,

The new versions of Flye do not require this argument to be set. The only use case now if you want to downsample using `--asm-coverage`.

**Comment by jolespin** [comment]
Excellent.  I'm using the newest version 2.9.3-b179. 

So with this version, I do not need to set either `asm-coverage` or `--genome-size`?

**Comment by mikolmogorov** [comment]
Yes, unless you want to downsample.
