### ISSUE TITLE
Quetion about the assembly_info.txt file

### ISSUE THREAD

**Issue by isabelluo** [fenderglass/ABruijn#655]
It was mentioned in the READ.ME file that normally 50X coverage is considered acceptable for the assembly. However, I am just wondering whether the coverage mentioned here is actually the coverage calculated in the assembly_info.txt file? Also, how was the coverage in the assembly_info.txt file defined? average coverage or minimum or maximum?

**Comment by mikolmogorov** [comment]
@isabelluo assembly_info.txt contains median coverage per contig. That would be the measurement that is relevant to how well Flye would perform.

**Comment by mikolmogorov** [comment]
Assuming this is resolved now, but feel free to follow up if not!
