### ISSUE TITLE
Best parameters for ONT reads corrected with Illumina before assembly

### ISSUE THREAD

**Issue by zacksaud** [fenderglass/ABruijn#657]
Hi,

I appreciate that this might be a bit of a tricky question that is subject to so many different factors, but if I have corrected my ONT reads with Illumina reads prior to assembly (in my case using FMLRC2), what would you say is the best way to run Flye? My main query is what will the assembler do differently if I use nano-hq vs nano-corr flag but set the same -m and --read-error values? Are there differences between these two settings if the read error is set the same and if so, which is recommended for Illumina corrected ONT reads?

Many thanks once again for the amazing tool you have given us!

Best

Zack

**Comment by mikolmogorov** [comment]
Sorry for my late response! There is no principal difference between `--nano-hq` and `--nano-corr`. You can try either with a combination of `--read-error`. You can see the detailed config differences in `flye/config/bin_cfg`.

Misha
