### ISSUE TITLE
Assembling ONT Multiple Chromosomes  Form a Cluster

### ISSUE THREAD

**Issue by abcdot** [fenderglass/ABruijn#658]
hi,
when i use flye 2.9.2, run as
` flye --nano-hq read_subsets2/sample_04.fastq --asm-coverage 50 --threads 16 --out-dir flye_temp --genome-size 12m
`
i got bandage graph like this
<img width="814" alt="image" src="https://github.com/fenderglass/Flye/assets/26371258/a51af2ad-6887-42c8-b575-ce5b90f80ad4">

when i use raven got graph like
<img width="822" alt="image" src="https://github.com/fenderglass/Flye/assets/26371258/718975c2-820b-493a-8b60-988ff848a938">

it has 16 chromosomes.

Now I am very confused, why flye is not one by one, like second graph.
I know there is no problem with the assembly of the second picture set. Are the flye pictures normal?
i use trycycler recommend assembly combination.

Thanks.

**Comment by mikolmogorov** [comment]
Hello,

This looks normal to me. Raven and Flye graph building methods may be different.
