### ISSUE TITLE
Select minimum read length

### ISSUE THREAD

**Issue by irazoquimatias** [fenderglass/ABruijn#661]
Hi! First of all I'd like to thank you for such a great tool.
I have an experiment where lots of reads ended up being shorter than expected (median of ~700 bp), due to a not so great DNA extraction method. I noticed that Flye only uses reads of at least 1Kb, and I can't find a way to change this value. Is there any way to set a lower minimum read length, to 500bp for example?
Thank you in advance

**Comment by mikolmogorov** [comment]
Hello,

That's not possible unfortunately because many parts of the algorithm assume 1000+ read length.
