### ISSUE TITLE
Flye stops after minimap2 without any error message

### ISSUE THREAD

**Issue by Kat0610** [fenderglass/ABruijn#664]
Hello, 

i am facing the problem, that the Flye assembly does not compute the consensus sequence. It runs minimap2 and it appears to finish that step. 
The command ran was: 
flye --nano-raw /vol/data/20240116_reads/ont_merged.fastq.gz --out-dir 20240119_flye --threads 30 --resume & 

The 10-consensus folder contains the following files: 
total 57G
-rw-rw-r-- 1 ubuntu ubuntu 2.1G Jan 26 09:34 chunks.fasta
-rw-rw-r-- 1 ubuntu ubuntu 308K Jan 26 09:34 chunks.fasta.fai
-rw-rw-r-- 1 ubuntu ubuntu  55G Jan 26 12:29 minimap.bam
-rw-rw-r-- 1 ubuntu ubuntu  31M Jan 25 21:47 minimap.bam.bai

The flye log does not include any error messages it simply does not progress past this point: 

[2024-01-26 09:33:54] root: INFO: >>>STAGE: consensus
[2024-01-26 09:34:26] root: INFO: Running Minimap2
[2024-01-26 12:30:02] root: INFO: Computing consensus

It shouldn't be a memory issue as we have 3.5 TB available and I was monitoring the ram usage and it never went above 3% used. And the cache didnt fill up either. I attempted to resume the run but it restarted from minimap2 and stopped at the same point. 
Do you have any idea what else i could try?

**Comment by mikolmogorov** [comment]
Consensus computation may take a while, are you convinced that it has crashed? Is there any CPU activity? Does it work for you on smaller datasets? Any error messages in the terminal?

**Comment by Kat0610** [comment]
I believe it crashed, there's no more CPU activity and there is no more trace of flye on the job overview. I don't receive any error messages in the terminal or in any of the log files. It has previously worked for smaller datasets and i am able to run the example files without any issue. It just does not appear to move on from minimap2 for this dataset.

**Comment by mikolmogorov** [comment]
I think it is very likely that Python processes were killed by OS for some reason. This is system-specific and very hard to debug. I'd try to allocate more resources on your system (or reduce the number of threads in Flye). You can also check system logs for any Python instances that were killed.

**Comment by mikolmogorov** [comment]
Closed due to inactivity, feel free to reopen if you still need help with this issue!

**Comment by franztastic** [comment]
Hi @mikolmogorov , I've been using flye several times now and suddenly I'm in the same situation as stated above. 
I started using flye with 35 threads and after arriving to the same point, it just stopped. I then have used 8 threads instead and I has stopped again, I haven't found any error message by now.

![imatge](https://github.com/user-attachments/assets/2e154ea4-e220-455d-8816-2aa6b2f48969)


flye log: 
[2024-09-11 13:52:08] root: INFO: Resuming previous run
[2024-09-11 13:52:08] root: INFO: >>>STAGE: consensus
[2024-09-11 13:52:08] root: INFO: Running Minimap2
[2024-09-11 16:49:48] root: INFO: Starting Flye 2.9.2-b1794
[2024-09-11 16:49:48] root: DEBUG: Cmd: /usr/local/bin/flye --nano-raw Rr_duplex_trimmed_nodups.fastq -g 2.4g -o ../assembly_flye -t 8 --resume
[2024-09-11 16:49:48] root: DEBUG: Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
[2024-09-11 16:49:48] root: INFO: Resuming previous run
[2024-09-11 16:49:48] root: INFO: >>>STAGE: consensus
[2024-09-11 16:49:48] root: INFO: Running Minimap2
[2024-09-12 10:07:09] root: INFO: Computing consensus

Is there anything I can do?

Thank you very much for your help!

**Comment by franztastic** [comment]
Hi there, I just upgraded to Flye's last version and it finally went through "20-repeat", so it's working! thank you for your amazing tool!
