### ISSUE TITLE
Option to display unassembled reads?

### ISSUE THREAD

**Issue by MarionPerrier** [fenderglass/ABruijn#665]
Hi!

I have performed _de novo_ assemblies of Nanopore data for a fungal genome using Flye.
After checking the result, it seems like there is a possible misassembly in the biggest contig. To be sure of that, I would like to get the unassembled reads to check for potential breakpoints.

Is there a way to get the unassembled reads directly from Flye, rather than going over an alignment of the raw reads against the draft assembly? 

Thank you for your time,
Regards,
Marion Perrier

**Comment by mikolmogorov** [comment]
Hello,

Flye does not save this information, but you can realign the reads instead.

Misha
