### ISSUE TITLE
Is the name of the first contig in assembly.fasta always supposed to be contig_1?

### ISSUE THREAD

**Issue by jfnjdoh** [fenderglass/ABruijn#667]
Sometimes, but seemingly rarely, I get an assembly where the name of the first contig is `>contig_2` (or some other number) as opposed to `>contig_1`. I don't have any issue with this, but the CDC's phoenix pipeline (https://github.com/CDCgov/phoenix) does, because the way it determines which assembler you've used is by checking what the first line of the assembly you've pointed it to looks like, see here https://github.com/CDCgov/phoenix/blob/main/bin/rename_fasta_headers.py#L124.

So what I'm asking is, is it expected that `>contig_1` is supposed to be the first contig in the file and this is some kind of bug? Or is this normal behavior and I should suggest to the CDC that they allow the user to specify the assembler used and only attempt an auto-detection in lieu of user specification?

**Comment by mikolmogorov** [comment]
There are multiple reasons for this to happen, and it is not necessarily a bug. There is no guarantee that the first contig ID will start from 1.

**Comment by jfnjdoh** [comment]
Ok great, so I will open an issue with CDC's pipeline referencing this. Using >contig_1 as the assumption that the assembler was flye won't always work.

**Comment by mikolmogorov** [comment]
Thanks!
