### ISSUE TITLE
Using fly to detect contamination in a pure culture?

### ISSUE THREAD

**Issue by Ge0rges** [fenderglass/ABruijn#668]
Hello,

I am sequencing what I think to be a pure culture on Nanopore. When I assemble using flye I get a circular genome or near circular genome. 

However, I'd like to increase my confidence that the culture is not in fact a co-culture if two closely related bacteria. 

I was wondering if using `--meta` would be recommended in this case to reveal this "hidden contamination"? Or if instead it would be more apt to use `--keep-haplotypes`?

Thank you for your advice.

**Comment by mikolmogorov** [comment]
I think `--meta --keep-haplotypes` is good and should reveal any possible structural variants (500bp+). We are also working on Strainy that can phase small variants if there are any: https://github.com/katerinakazantseva/stRainy
