### ISSUE TITLE
Flye output only 1 contig

### ISSUE THREAD

**Issue by LaurenBaena** [fenderglass/ABruijn#675]
I'm assembling a ~5 Mb bacterial genome using ONT reads. I should have very high coverage based on pre-assembly calculations (~1400x), so I used the modifiers, --genome-size 5m --asm-coverage 50, as suggested in another thread about no disjointigs assembled. This finally let my assembly complete, but it produced only 1 contig for the output. The length is in the target range, but every tutorial and example I've seen with flye produces multiple contigs. This also produces weird comparisons to my reference genome when I run QUAST because of the single contig. Is a single contig in itself a bag thing? Could this be because of the high mean coverage (which my flye log puts at 1175x)? 

I'm attaching my flye log to this issue. Any insight is appreciated!

Thank you,
Lauren
[flye.log](https://github.com/fenderglass/Flye/files/14361687/flye.log)

**Comment by mikolmogorov** [comment]
Hi Lauren,

This happens fairly often with bacterial genomes, this likely means that your assembly is complete.

Misha

**Comment by mikolmogorov** [comment]
Assuming this has been answered, feel free to follow up if you have more questions!
