### ISSUE TITLE
Inclusion of reads <5000 results in increased fragmentation of assembly

### ISSUE THREAD

**Issue by OKyne1** [fenderglass/ABruijn#676]
Hi,

I'm working with ONT reads from O. tsutsugamushi, a bacteria with an extremely repetitive genome (making it hard to assemble). 

I've found I have the best assemblies when I exclude shorter reads (<5000) from the flye assembly pipeline. Do you have any idea why this might be the case, and is there a way I can modify the flye parameters to handle this (rather than prefiltering)?

Cheers!

**Comment by mikolmogorov** [comment]
Minimum read overlap parameter would indirectly cut off reads that are shorter than this threshold. Longer reads have better chances to span repeats.

**Comment by OKyne1** [comment]
Thank you, I will try it out
