### ISSUE TITLE
How does Flye resolve 'unbridged' repeats?

### ISSUE THREAD

**Issue by Matteo-Paini** [fenderglass/ABruijn#677]
Hi, thanks for you work on this tool and for the continuous upgrades!
I used Flye for several genome assemblies and it always worked perfectly.

I just have a thoeretical question: I studied the paper of Flye and I'm trying to understand how it resolves the "unbridged repeats". Can someone explain this passage to me?

Thanks in advanced!

**Comment by mikolmogorov** [comment]
Hi,

In short, Flye doesn't :) We used to have a trestle module, but it is now deprecated.

Misha

**Comment by Matteo-Paini** [comment]
Hello Misha, thanks for your reply!

So, does the depreciation of the Trestle module affect the accuracy of the final assembly?

A way to avoid this “unresolved bridges” could be the usage of ultralong reads by ont?

**Comment by mikolmogorov** [comment]
It may affect slightly, but Trestle was inactive for a few years now. The longer the reads, the more repeats can potentially be resolved.
