### ISSUE TITLE
direct RNA Seq data with flye?

### ISSUE THREAD

**Issue by Viola-TA** [fenderglass/ABruijn#680]
Hello fenderglass,

we are currently working with the direct RNA kit from ONT. We would also like to analyse our data with Flye, but unfortunately the pipeline with RNA data always aborts (--nano-raw and --nano-corr, Flye version 2.9.3-b1797)

Is it even possible to run data from ONT RNA sequencing with Flye? Or is the input not suitable for Flye? Or do you need certain settings in Flye?

Many thanks in advance,
Viola

**Comment by mikolmogorov** [comment]
Hi Viola - Flye currently does not support RNA assembly, unfortunately.
