### ISSUE TITLE
Metagenome

### ISSUE THREAD

**Issue by joao1980** [fenderglass/ABruijn#681]
Hi, My apologies if this is a basic question but it is the first time I am dealing with Nanopore sequencing data.
I plan to process metagenomes from GridION sequencing. I was reading you can use the meta option without the need to estimate genome size and only use asm-coverage. Should this be set to 40x? If I have plenty of computational resources can I just disregard setting the asm-coverage and genome-size options?
Thanks for the help!

**Comment by mikolmogorov** [comment]
Yes, you don't need to set `--asm-coverage` anymore unless you want to downsample.
