### ISSUE TITLE
What parameter for R10.4.1 FAST mode data

### ISSUE THREAD

**Issue by LogCrab** [fenderglass/ABruijn#688]
Hi, developers of Flye. Recently I acquired some  R10.4.1 sequencing data. But unfortunately, these data is sequenced by unprofessional technician in the hospital, who only saved the `FAST` basecalled data from `MinKnow`. I wonder what parameter should I use for achieving the best performance in Flye. Should it be `--nano-raw` since `FAST` mode contain many sequencing error?

**Comment by mikolmogorov** [comment]
Hello, as long as error rate is below 3-4%, you can still use `--nano-hq`
