### ISSUE TITLE
Can't resume from a definite polishing step ? 

### ISSUE THREAD

**Issue by ImagoXV** [fenderglass/ABruijn#689]
Hello, I have a question. 

I've been assembling my metagenome with four polishing steps. 

It took way longer that I expected compared to the regular assembly. 

My job timed out twice on my slurm cluster. It was more than 20 days long. 

As I ```--resume-from polishing``` it starts again from first polishing step (```--resume``` does the same)

Is there a way to specify to start from the last finished polishing step or are the tmp files lost somehow ? 

Thank you very much for your time

Arthur

**Comment by mikolmogorov** [comment]
Hi Arthur - unfortunately it is not possible to resume a particular polishing iteration. But for most assemblies, one iteration is sufficient.

**Comment by ImagoXV** [comment]
Thank you for your answer. 

I however observed differences with small metagenomes assemblies regarding the number of polishing iteration. 

I'm not sure to perfectly understand how the polishing works yet or how it can impact results differently than just improving confidence per base. But for sure, difference is there. 

As the guy who made the soft, you would only polish an environemental metagenome once ? 

What could you be expecting to increase the number of polishing steps ? 

Thank you very much Mikhail

Arthur

**Comment by mikolmogorov** [comment]
Yes, we typically use a single polishing iterations. You can check this blog for some in-depth analysis: https://rrwick.github.io/

**Comment by ImagoXV** [comment]
Thank you man, I'll go through this. 

Thanks for the chitchat
