### ISSUE TITLE
Last assembly before polishing? 

### ISSUE THREAD

**Issue by apredeus** [fenderglass/ABruijn#69]
Hello, 

I was wondering which file contains the last assembly before polishing. Would that be 2-repeat/graph_paths.fasta? 

Thank you

**Comment by mikolmogorov** [comment]
Yes - `graph_paths.fasta` contains contig sequences before polishing, and `graph_final.fasta` - edge sequences (contigs = edge sequences extended into flanking repeats).

**Comment by apredeus** [comment]
Thank you. 

How does one use the flye polisher only - e.g. with a different set of reads than were used to assemble the genome?

**Comment by mikolmogorov** [comment]
Just pushed a new version to the flye branch - it has a new option `--polish-target` that runs polisher on a given sequence.

**Comment by charlesfeigin** [comment]
Does Flye polish by default? In the paper I believe Pilon was also used for polishing. Regardless, do you feel that polishing with a tool like Pilon/Racon using Illumina data is wise if that data is available?

**Comment by mikolmogorov** [comment]
@charlesfeigin please refer to the FAQ for the discussion on Illumina polishing.
