### ISSUE TITLE
Flye assembler should support spaces in file paths.

### ISSUE THREAD

**Issue by sarahjeeeze** [fenderglass/ABruijn#693]
Although users should not have spaces in file and directory names it is fairly common and other tools support it. It would be great if Flye could support such files.

Currently Flye will return eg  `[2024-04-08 09:25:14] ERROR: Path to reads contain spaces:`
https://github.com/fenderglass/Flye/blob/21a7191dc39796d83afd5b6d1b387800a9f64380/flye/main.py#L421

**Comment by mikolmogorov** [comment]
It is - in general - bad practice to have spaces in flie path at UNIX-lie systems. It is an easy change to make on the user side, so I am not currently planning to add support for that.
