### ISSUE TITLE
Inferring number of elements in an assembly based on multiplicity

### ISSUE THREAD

**Issue by AceM1188** [fenderglass/ABruijn#694]
Hi there,

I am new to genome assembly but have performed whole genome bacterial assembly of some clinical isolates that I have which are very resistant to multiple antibiotics. Can numbers of extrachromosomal elements (e.g., plasmids) be inferred/determined from the multiplicity metric? For example, if I have the following contig data: 

#seq_name | length | cov. | circ. | repeat | mult. | alt_group | graph_path
-- | -- | -- | -- | -- | -- | -- | --
contig_2 | 5292913 | 189 | Y | N | 1 | * | 2
contig_18 | 52907 | 212 | N | N | 7 | * | 18,-10,-6,9,10,11,-8,-4,5
contig_1 | 20446 | 746 | Y | Y | 6 | * | 1
contig_19 | 19644 | 831 | N | Y | 12 | * | 19
...

-Contig_2 is the bacterial chromosome
-Contig_18 is some type of plasmid (containing several resistance genes based on prokka data) that could not be circularized based on the sequencing data
-Contig_1 is a plasmid with resistance genes that was able to be circularized
-Contig_19 is some other extrachromosomal element

Specifically, would it be reasonable to conclude that there are multiple copies of contigs_18, _1, and _19 relative to one bacterial genome (e.g., chromosome)? Or is this based on too many unvalidated assumptions? I ask because it would be reasonable to presume that multiple copies of a resistance element - particularly of a non-repeating contig that was able to be circularized (e.g., contig_1) - could confer such a phenotype. 

Thanks again in advance!

**Comment by mikolmogorov** [comment]
Sorry for my late response!

I this case, coverage is the only real measurement, and multiplicity is basically a guess. The assumption is that every cell that you sequence has similar genomic content. I think this should be mostly true for pure cultures and chromosomal elements. For plasmids - may not be.. You can certainly see that there is enrichment, but the exact multiplicity I think is a bit difficult to tell.

Hope this helps - let me know if you have more questions!
Misha

**Comment by mikolmogorov** [comment]
Assuming that this has been answered, feel free to follow up if you have more questions!

**Comment by goshng** [comment]
Can you tell us more about how you guess multiplicity from the coverage? thanks.

You have an answer to my question at https://github.com/mikolmogorov/Flye/issues/643#issuecomment-1801941530

"... multiplicity column indeed does not make much sense - it's basically contig coverage divided by the median dataset coverage. ..." 

How do I get the median dataset coverage? Or, how can I compute it from a long-read dataset?

**Comment by mikolmogorov** [comment]
Multiplicity is computed as mean contig coverage divided by mean dataset coverage in this case.
