### ISSUE TITLE
minimap2 and samtools issues in running consensus stage

### ISSUE THREAD

**Issue by Jerry-bioinformatics** [fenderglass/ABruijn#698]
Hi fenderglass, 
I installed Flye version 2.9.3-b1797 through conda in a independent env, and ran it in command **nohup time -v flye --nano-raw /public/share/wrj23/phasing/data/ont/HG002.nanopore.fastq --out-dir /public/share/wrj23/phasing/flye_nanopore/ --no-alt-contigs --threads 128 1> /public/share/wrj23/phasing/flye_nanopore/flye.nanopore.1.log 2> /public/share/wrj23/phasing/flye_nanopore/flye.nanopore.2.log &**
But it failed again and again, and time comsuming. Here are the **flye.log** and **minimap.stderr**.
[flye.nanopore.2.log](https://github.com/fenderglass/Flye/files/15195409/flye.nanopore.2.log)
[minimap.stderr.log](https://github.com/fenderglass/Flye/files/15195414/minimap.stderr.log)
I have difficulty in dealing with it.

**Comment by mikolmogorov** [comment]
Something is wrong with your Flye installation - minimap2 log says that it can't find the executable. I recommend a fresh install in a new bioconda environment. Hope this helps!
