### ISSUE TITLE
Update of install docs

### ISSUE THREAD

**Issue by colindaven** [fenderglass/ABruijn#7]
Hi, just started here. 
I think there are a couple of errors in the install docs

First, to build ABruijn, run:

python install.py build
I used
`python setup.py build`

ABruijn could be invoked with the following command:

bin/abruijn
`This then worked, I haven't tested out the full algorithm with test or my data yet though`

Additonally, you may install the package for the better OS integration:

python setup.pu install

Correction
`python setup.py install`

**Comment by fenderglass** [comment]
Thank you for catching this! It's fixed now.
