### ISSUE TITLE
Missing & misassembled plasmids

### ISSUE THREAD

**Issue by peradastra** [fenderglass/ABruijn#706]
Howdy, 

My name is Per and I would first like to thank you for developing Flye!
Anyway, I have been using Flye to assemble an *E. Coli* isolate from ONT data. 
I think that Flye is having 2 issues properly assembling plasmids from this isolate. 
I would greatly appreciate some help troubleshooting these issues!

## Issue No. 1: Not assembling small (<~2 kb)) plasmids. 
The final assembly info (Table 1) shows that Flye is assembling 2 plsamids and the main bacterial chromosome.

| #seq\_name | length | cov. | circ. | repeat | mult. | alt\_group | graph\_path |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| contig\_1 | 5072618 | 137 | Y | N | 1 | \* | 1 |
| contig\_3 | 122045 | 205 | Y | N | 2 | \* | 3 |
| contig\_2 | 8128 | 871 | Y | Y | 7 | \* | 2 |
##### Table 1. Final assembly info for isolate. 

However, based on NanoPlots (Fig 1) and gels produced from plasmid preps, we expect there to be 3 smaller plasmids. 

![newplot](https://github.com/fenderglass/Flye/assets/11907057/5c09bc68-58de-4bdf-aaa3-2bb52bdded8f)
## Issue No. 2: Missassembly of a plasmid
While Flye assembled an 8 kb contig, there isn't a corresponding peak in the NanoPlot (Fig 1.). Further examination 
of the alignments profile of reads (Fig 2) and low number of supplemental alignments suggests to me that this is a repeat 
that has been duplicated in tandem and then circularized. 

![igv_snapshot](https://github.com/fenderglass/Flye/assets/11907057/8306e28d-a571-42c9-9f27-0330eebd37ec)
##### Fig 2. IGV screenshot of reads used for assembly mapped back to contig_2. I sorted alignments by tag (SA) with MAPQ set to 0.  

There are a few reads that span this 8kb region (Fig 3) so I suspect that this is sequence duplication exists somewhere 
else in this *E. coli* genome but not as an 8 kb plasmid. 

![mapq_30_igv_snapshot](https://github.com/fenderglass/Flye/assets/11907057/669ed30a-7d2c-409f-940f-fb0acbc96102)
## Logs
Here are logs for 2 seperate attempts to assembly this genome. I saw that you [previously addressed this issue with another user](https://github.com/fenderglass/Flye/issues/562) by suggesting the use of the meta tag, so I tried that, but it did not help. 

[flye_meta.log](https://github.com/fenderglass/Flye/files/15473991/flye_meta.log)
[flye.log](https://github.com/fenderglass/Flye/files/15473992/flye.log)

Best, 
Per

**Comment by mikolmogorov** [comment]
Hi Per,

Thanks for the detailed report! Indeed, this is a known issue that Flye sometimes may miss short plasmids or duplicate them. It is somewhat hard to come up with a general-purpose solution that will fix this in the existing framework. As suggested in the other thread, a specialized plasmid assembler (https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000631) may help.
