### ISSUE TITLE
Stuck in repeat stage for low coverage sample

### ISSUE THREAD

**Issue by JWDebler** [fenderglass/ABruijn#707]
Hi,

I have several fungal isolates of the same species at different sequencing depths.

I just noticed that one of them has been stuck at the 'repeat' stage for several hours.
I also noticed that this is one of the samples with low coverage at about 24x. 

I have started assembly of a different isolate at 100x coverage and it just raced past the repeat stage in a few minutes.

Is this a problem with the low coverage of the particular sample? If so, is there a way around this?

I'm running version 2.9.4

These are the stats for the reads for this sample and the assembly is meant to be 41 mb:

```
id                  reads          bases           avg_len       N50
duplex .fastq.gz    16,876         59,276,326      3,512.5       4,946
simplex.fastq.gz    212,112        943,499,131     4,448.1       6,320
```

Cheers,
Johannes

**Comment by JWDebler** [comment]
The process eventually finished, but it too several hours for that step alone, while it only takes a minutes for other samples.

**Comment by DingJingZhi** [comment]
[2024-06-04 21:53:18] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 

waiting........

**Comment by DingJingZhi** [comment]
> The process eventually finished, but it too several hours for that step alone, while it only takes a minutes for other samples.

the same as you. so I break them, then turn other app

**Comment by mikolmogorov** [comment]
Ok, since the run has finished - I'm assuming this is now resolved. Different stages of assembly may take longer sometimes, depending on the complexity of the sample.
