### ISSUE TITLE
Suggestions on using --keep haplotypes

### ISSUE THREAD

**Issue by riyasj327** [fenderglass/ABruijn#709]
Greetings,

Thanks for this wonderful tool!
I have been using flye with --keep haplotypes option and then later hapdup for getting the diploid assemblies. I am wondering if it is suggested to use --keep haplotypes if running hapdup afterwards or it doesn't really matter?

Any insights on this would be really helpful!

thanks,
Riya

**Comment by mikolmogorov** [comment]
Hi Riya,

For Hapdup, you need a collapsed assembly, so it is better not to use `--keep-haplotypes`.

**Comment by riyasj327** [comment]
thank you so much! @mikolmogorov
