### ISSUE TITLE
Conda installation 

### ISSUE THREAD

**Issue by Narmatha99** [fenderglass/ABruijn#712]
Hi, I am quite new to sequencing analysis so I might have made a mistake. But I tried to install Flye through conda on my computer (Mac Pro, M2 Ultra, Sonoma 14.5). However I get the following error: 

![Scherm­afbeelding 2024-06-26 om 11 10 59](https://github.com/mikolmogorov/Flye/assets/96242285/92abacb4-18a3-461a-9a51-f060ceccdac9)

I have the correct channels I think, so what am I doing wrong? Thank you in advance!

**Comment by mikolmogorov** [comment]
Hello,

bioconda builds are not available for Mac Arm architecture, unfortunately. This should help: https://github.com/conda/conda/issues/11216

**Comment by mencian** [comment]
Hi @Narmatha99,

ARM64 builds are now available on conda: [bioconda-recipes/#49468](https://github.com/bioconda/bioconda-recipes/pull/49468).
