### ISSUE TITLE
problem in opening GFA

### ISSUE THREAD

**Issue by lfaino** [fenderglass/ABruijn#717]
Dear 

I just finished to assemble a gnome and I was trying to open the GFA file with Bandage but I was not able.The software Bandage runs for ever. I made an assembly with another software and I was able to open the GFA file indicating that Bandage works.

can you please help me

L

**Comment by mikolmogorov** [comment]
Hi @lfaino ,

Most likely explanation is that the graph is too big and complex. You can try BandageNG, which is better with larger graphs: https://github.com/asl/BandageNG
