### ISSUE TITLE
Resuming from a previous stage, pipeline ver 2

### ISSUE THREAD

**Issue by harish0201** [fenderglass/ABruijn#72]
Hi!

I have been working on a smaller genome this time, though due to some memory allocation issues the assembly got killed at the trestle stage after a day.

I'm attaching the last couple of lines from the dump here. Trying to resume from the threstle step doesn't seem to work [flye.log](https://github.com/fenderglass/Flye/files/2795432/flye.log)
![2019190414 55 23jan](https://user-images.githubusercontent.com/9093815/51736908-50e50f80-20b1-11e9-91a9-3df7abf94b02.png)

Contents of the 21-trestle folder have been shared in the screenshot (for some reason the markdown formatting isn't playing well with ls)
![2019190414 51 49jan](https://user-images.githubusercontent.com/9093815/51736710-cb615f80-20b0-11e9-9470-7434c34f83d2.png)

It seems that the "resume-from" option isn't picking up the version changes in the pipeline? However the "resume" option is working well.

Edits: Formatting and user-error issues.

**Comment by mikolmogorov** [comment]
Thank you! `--resume-from` takes the name of the stage, so it should be `--resume-from trestle`. Did you get the final assembly (without trestle)? Could you also post the output of `cat $(find 21-trestle/ -name "log.txt")`

**Comment by harish0201** [comment]
Hi,

Apologies for the delayed reply, was traveling a bit. I was able to able to finish the assembly with trestle once I was able to grab the format required for inputting the stage name.

I have attached the log in the first post though, however here is the 
[trestle specific log](https://github.com/fenderglass/Flye/files/2802195/trestle.log)

But is there any particular reason that the assembly size would be smaller? I've noticed it between 3-4 other assemblies as well. While BUSCO's and assembly metrics are really good the assembly size's seem to be about 75% of the provided genome size. Is there a way to fix it? I have been providing data upto 50x coverage.

**Comment by mikolmogorov** [comment]
Thank you - glad to hear that it worked for you. 

I suspect that the reduced genome size might be a result of many collapsed repeats (that were not bridged by reads). I can see that the the conservative BUSCO genes are likely to belong to less repeat-reach parts of the genome that are easier to assemble, thus you a getting a good BUSCO coverage.

**Comment by harish0201** [comment]
Ah, so it's pretty much what I had suspected and this is what wtdbg2 and minimap give as well.

So, the current dataset is basically a haplotype separated dataset using Canu, so I will be getting Canu's output in a couple of days as well to compare.

Shall I mark the issue closed till then?

**Comment by mikolmogorov** [comment]
Yep, closing the issue. Let me know if you have other questions.
