### ISSUE TITLE
Flye does not continue into consensus stage

### ISSUE THREAD

**Issue by Niels1804** [fenderglass/ABruijn#720]
Hi everyone,

I am trying to build a reference genome from nanopore fastq data. I would like to use flye for this.

My system is 32CPU and has 250GB of RAM and 400GB of storage. I use Flye 2.9.2 and minimap 0.2.

Flye runs fine when I use the code:
flye --nano-raw imput.fastq --out-dir assembly_output_imput_Flye32CPU --threads 32

It however gives an error at the consensus stage, the minimap.stderr reads:
[ERROR] unknown option in "/home/share/Genome_Assembly_nanopore/SRR22891206.fastq"
[main_samview] fail to read the header from "-".
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "-"

So I assume that there is something wrong with the headers, but I dont know what... The first 10 headers look like this:
niels:/home/share/Genome_Assembly_nanopore$ awk '/^@/ {print; count++; if (count==10) exit}' SRR22891206.fastq
@SRR22891206.1 1 length=6589
@SRR22891206.2 2 length=6881
@SRR22891206.3 3 length=10034
@SRR22891206.4 4 length=1120
@SRR22891206.5 5 length=312
@SRR22891206.6 6 length=2783
@SRR22891206.7 7 length=9373
@SRR22891206.8 8 length=19636
@SRR22891206.9 9 length=113
@SRR22891206.10 10 length=12757

Is anyone familiar with this error and has any tips on solving this?

Thanks in advance,
Niels

**Comment by mikolmogorov** [comment]
You have errors in your fastq format - it seems that you've converted it from bam, the top lines look like a sam header.
