### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by tnn111** [fenderglass/ABruijn#721]
I'm getting a core dump from flye. It's odd because it only seems to happen when I use a FASTA file as input. Any thoughts?

Thanks!

[samfaipath] build FASTA index...
flye-samtools: bgzf.c:305: bgzf_open: Assertion `compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE' failed.
[M::mm_idx_gen::0.061*1.00] collected minimizers
[M::mm_idx_gen::0.075*5.45] sorted minimizers
[M::main::0.076*5.44] loaded/built the index for 1 target sequence(s)
flye-samtools: bgzf.c:351: bgzf_hopen: Assertion `compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE' failed.
[M::mm_mapopt_update::0.083*5.05] mid_occ = 10
[M::mm_idx_stat] kmer size: 17; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.088*4.84] distinct minimizers: 666250 (95.48% are singletons); average occurrences: 1.052; average spacing: 5.496; total length: 3850630
/bin/bash: line 1: 497048 Broken pipe             flye-minimap2 '/Spawn/Isolates/LT001001/results_flye_correct/00-assembly/draft_assembly.fasta' '/Spawn/Isolates/LT001001/LT001001_correct_nano.fasta' -x map-ont -t 32 -k 17 -a -p 0.5 -N 10 --sam-hit-only -L -K 1G -z 1000 -Q --secondary-seq -I 64G
     497049 Aborted                 (core dumped) | flye-samtools view -T '/Spawn/Isolates/LT001001/results_flye_correct/00-assembly/draft_assembly.fasta' -u -
     497050 Aborted                 (core dumped) | flye-samtools sort -T '/Spawn/Isolates/LT001001/results_flye_correct/10-consensus/sort_240825_192934' -O bam -@ 4 -l 1 -m 1G -o '/Spawn/Isolates/LT001001/results_flye_correct/10-consensus/minimap.bam'

**Comment by tnn111** [comment]
I just reinstalled it and now I got this one:

flye -h
Traceback (most recent call last):
  File "/home/torben/opt/micromamba/bin/flye", line 5, in <module>
    from flye.main import main
  File "/home/torben/opt/micromamba/lib/python3.12/site-packages/flye/main.py", line 19, in <module>
    import flye.polishing.alignment as aln
  File "/home/torben/opt/micromamba/lib/python3.12/site-packages/flye/polishing/alignment.py", line 18, in <module>
    import flye.utils.fasta_parser as fp
  File "/home/torben/opt/micromamba/lib/python3.12/site-packages/flye/utils/fasta_parser.py", line 26, in <module>
    from flye.six.moves import range
ModuleNotFoundError: No module named 'flye.six.moves'

But six is installed......

**Comment by mikolmogorov** [comment]
Please see https://github.com/mikolmogorov/Flye/issues/669
