### ISSUE TITLE
Core dump with Python 3.9

### ISSUE THREAD

**Issue by tnn111** [fenderglass/ABruijn#722]
I did a fresh install of flye with micromamba. Python is 3.9.

I get a core dump on the minimap2 step. Any suggestions? 

Thanks!

 less /Spawn/Isolates/LT001001/results_flye_correct/10-consensus/minimap.stderr
[samfaipath] build FASTA index...
flye-samtools: bgzf.c:305: bgzf_open: Assertion `compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE' failed.
[M::mm_idx_gen::0.061*1.01] collected minimizers
flye-samtools: bgzf.c:351: bgzf_hopen: Assertion `compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE' failed.
[M::mm_idx_gen::0.076*5.21] sorted minimizers
[M::main::0.076*5.21] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.084*4.82] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.089*4.62] distinct minimizers: 634261 (89.75% are singletons); average occurrences: 1.133; average spacing: 5.364; total length: 3854817
/bin/bash: line 1: 512917 Broken pipe             flye-minimap2 '/Spawn/Isolates/LT001001/results_flye_correct/00-assembly/draft_assembly.fasta' '/Spawn/Isolates/LT001001/LT001001_correct_nano.fasta.gz' -x map-ont -t 32 -a -p 0.5 -N 10 --sam-hit-only -L -K 1G -z 1000 -Q --secondary-seq -I 64G
     512918 Aborted                 (core dumped) | flye-samtools view -T '/Spawn/Isolates/LT001001/results_flye_correct/00-assembly/draft_assembly.fasta' -u -
     512919 Aborted                 (core dumped) | flye-samtools sort -T '/Spawn/Isolates/LT001001/results_flye_correct/10-consensus/sort_240826_133759' -O bam -@ 4 -l 1 -m 1G -o '/Spawn/Isolates/LT001001/results_flye_correct/10-consensus/minimap.bam'

**Comment by mikolmogorov** [comment]
@tnn111 sorry for the late response! Looks like an internal error in minimap2. It is possible that something is inconsistent in your conda environment, likely to do with different versions of libz. I would try reinstalling into a fresh environment. If that does not solve the issue, I would try building from source or using the docker container. If that works - it is likely conda that causing the problem.

**Comment by mikolmogorov** [comment]
Closed due to inactivity, feel free to reopen if there are any follow ups!

**Comment by tnn111** [comment]
Sorry; I solved the problem but forgot to follow up!

I forced a reinstall of libz and the problem went away.

Thanks!
