### ISSUE TITLE
Pipeline aborting because flye-samtools and flye-minimap2 not found

### ISSUE THREAD

**Issue by gwaldbieser** [fenderglass/ABruijn#725]
Hello Mikhail,
We upgraded our OS from CentOS7 to a fresh install of RedHat 9.4 on a new HDD, reinstalled miniconda, then installed flye into a new environment. Our assemblies crash in the consensus stage when Minimap2 is invoked. We tried v2.9.2, 2.9.3, and 2.9.5 installations and all have the same behavior. Flye completes the assembly on a similar machine running CentOS 7. 
The only other difference is that the RHEL 9.4 machine has conda 24.7.1 and the CentOS machine runs conda 23.9.0.
____________________________________________________________
(flye292)geoff$ cat 10-consensus/minimap.stderr
bash: flye-samtools: command not found
bash: flye-samtools: command not found
bash: flye-minimap2: command not found
____________________________________________________________

However, 'flye-minimap2' and 'flye-samtools' can be called from the command line:
____________________________________________________________
(flye292)geoff$ flye-minimap2
Usage: minimap2 [options] <target.fa>|<target.idx> [query.fa] [...]
Options:
  Indexing:
    -H           use homopolymer-compressed k-mer (preferrable for PacBio)
    -k INT       k-mer size (no larger than 28) [15]
...
...
    -x STR       preset (always applied before other options; see minimap2.1 for details) []
                 - map-pb/map-ont - PacBio CLR/Nanopore vs reference mapping
                 - map-hifi - PacBio HiFi reads vs reference mapping
                 - ava-pb/ava-ont - PacBio/Nanopore read overlap
                 - asm5/asm10/asm20 - asm-to-ref mapping, for ~0.1/1/5% sequence divergence
                 - splice/splice:hq - long-read/Pacbio-CCS spliced alignment
                 - sr - genomic short-read mapping

See `man ./minimap2.1' for detailed description of these and other advanced command-line options.
____________________________________________________________
(flye292)geoff$ flye-samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.9 (using htslib 1.9)

Usage:   samtools <command> [options]

Commands:
  -- Indexing
     dict           create a sequence dictionary file
...
...
...
 -- Viewing
     flags          explain BAM flags
     tview          text alignment viewer
     view           SAM<->BAM<->CRAM conversion
     depad          convert padded BAM to unpadded BAM

**Comment by mikolmogorov** [comment]
Sorry for the late response. For some reason the python code can not invoke the binaries. It could be that they either were not properly installed, or bioconda did not properly set PATH, or in some cases it could be that filesystem does not allow executions from particular folders. I'd try compiling from source - if that works, then the problem is with bioconda.

**Comment by gwaldbieser** [comment]
Here is the path within the conda environment.
(flye_295) [geoff]$ echo $PATH
/home/geoff/miniconda3/envs/flye_295/bin:/home/geoff/miniconda3/condabin:/home/geoff/.local/bin:/home/geoff/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

I can execute flye-minimap2 and flye-samtools from the command line, so I don't think it' a path problem.

**Comment by gwaldbieser** [comment]
I did get it to work using this bash script in a conda environment:
(flye_295) [geoff]$ cat runflye.sh
#!/bin/bash -l

conda activate flye_295

flye --nano-hq S14-452.q15L1k.fastq --genome-size 5m --threads 16 --out-dir S14-452_v2.9.5
