### ISSUE TITLE
question: min coverage trimming?

### ISSUE THREAD

**Issue by kevfengler227** [fenderglass/ABruijn#726]
I am trying to use flye for targeted assembly of ONT reads to manually fill gaps in T2T assemblies by assembling the flanking and soft-clipped reads aligned at a gap. This works pretty well except for the ends of the targeted contig have low-coverage and consequently low accuracy where the coverage drops at the tails (down to 1x at the ends). Is there a way to just output the assembled bases above a certain coverage threshold?

**Comment by mikolmogorov** [comment]
@kevfengler227 you can find per-based coverage of polished contigs in the `40-polishing/base_coverage.bed.gz` file. You should be able to use it for trimming low-quality ends.

**Comment by kevfengler227** [comment]
OK, thanks. Yes, I found that file but I was hoping for a parameter that could do the same thing, like minimal base coverage or someway to force the desired behavior. I am selecting reads that align to a given target position, so it's pretty much a vertical stack of reads, but length outliers are making the ends lower quality.

**Comment by mikolmogorov** [comment]
Currently there is now such parameter.

**Comment by mikolmogorov** [comment]
Close due to inactivity, feel free to reopen if there are any follow ups!
