### ISSUE TITLE
How to adjust parameters

### ISSUE THREAD

**Issue by hanxintong5887** [fenderglass/ABruijn#728]
The following image is built based on GFA. What can I do with the parameters to make them to one circle? 

![微信截图_20240926162921](https://github.com/user-attachments/assets/7a665eba-8b12-47f9-8098-dbf791d3d0f0)

**Comment by mikolmogorov** [comment]
Flye does not have many parameters to tweak, and the default parameters should work for most cases. You can see FAQ section for more info. This is likely an unresolved repeat that is longer than read length of your sequencing data.
