### ISSUE TITLE
Does flye deal with haplotigs in subassemblies?

### ISSUE THREAD

**Issue by TomHarrop** [fenderglass/ABruijn#73]
Hi,

I'm trying `flye` with 40x nanopore data on a highly heterozygous, diploid insect species.

I have some 'haplotigs' from Illumina reads that I assembled with `meraculous` in diploid mode, where it essentially doesn't try to resolve heterozygous regions but instead assembles each haploid genome separately.

I'm wondering whether this will cause problems if I feed it to `flye` using the `--subassemblies` argument.

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Do I understand correctly - you want to assemble the nanopore data first, and then merge it with the Illumina assembly? This should work, but the merged assembly will most likely be more fragmented than the nanopore only (see #68 for more details).

**Comment by TomHarrop** [comment]
Thanks for the reply.

I was planning to assemble the nanopore reads with `flye`, while passing the illumina assembly using `--subassemblies`.

My initial question was if duplicate contigs (so-called "haplotigs") in the illumina subassembly would cause duplicate contigs in the output of `flye`.

So I think you answered my question in #68. For comparison I'll also try to assemble the nanopore reads alone.
