### ISSUE TITLE
assembly_info.txt for edge not for contig?

### ISSUE THREAD

**Issue by goshng** [fenderglass/ABruijn#732]
I would like to have an output file like assembly_info.txt but for edge sequences not for contigs. Is there an such output file from Flye? Or, do I have to make one?

In that assembly_info.txt, I need the following columns:

- Edge id
- Length
- Coverage
- Multiplicity (based on coverage)

In other issue, I also asked the following question:

Can you tell us more about how you guess multiplicity from the coverage?

You have an answer to my question at #643 (comment)

"... multiplicity column indeed does not make much sense - it's basically contig coverage divided by the median dataset coverage. ..."

How do I get the median dataset coverage? Or, how can I compute it from a long-read dataset?

Thank you for the great assembly software.

**Comment by goshng** [comment]
I have tried to compute the multiplicity by dividing the coverage by the median of the coverage values in the assembly_info.txt. My values tend to be greater than the multiplicity values from the assembly_info.txt. So, I guess that flye seems to have a better way of computing the median dataset coverage, which I would like to know so that I could have another assembly_info.txt for edge-based not contig-based one.

I appreciate any idea on this issue.

Thank you!

**Comment by mikolmogorov** [comment]
Sorry for the late response! I think your method is fine. In general, for long unitigs / contigs you should get the same coverage / multiplicity values, compared to the assembly_info. For short sequences, it may be more variable if the coverage is for some reason uneven. 

Median coverage is computed over all the sequence in the dataset, but it's weighted by unitig length. Maybe this is why your method yield different values?

**Comment by goshng** [comment]
Thank you for your kind explanation.
