### ISSUE TITLE
Cannot make Flye

### ISSUE THREAD

**Issue by Ciznetwork** [fenderglass/ABruijn#735]
Hi, 
I am finding it difficult to make flye  following cloning from github. Please see the error screen. 
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/749e9bd8-07a2-42aa-bffb-655d3060dd3b">
I look forward to your timely reply.
Thank you

**Comment by mikolmogorov** [comment]
You may be in the wrong directory (repository name is `Flye`, you are in `flye`). Or something is wrong with your developer environment. I suggest use the bioconda installation instead.
