### ISSUE TITLE
Q: input settings for HERRO-corrected ONT reads

### ISSUE THREAD

**Issue by aistBMRG** [fenderglass/ABruijn#738]
Hi,

Small question -- it was touched upon in another thread but I could not find exactly what I was looking for. For HERRO-corrected ONT reads, would it be possible to suggest the best type of input format to specify? I guess the quality approaches that of PacBio HiFi, but the input should be nano-hq, is my understanding correct?

Thank you for your time and amazing assembler.

Best,

Dieter

**Comment by mikolmogorov** [comment]
Hi Dieter,

Sorry for my late response! We have not tested HERRO-corrected input extensively, but I think `--nano-hq` should work. I also recommend setting the expected read error rate to a lower value using `--read-error`

**Comment by aistBMRG** [comment]
Thank you very much for clarifying. I understand, and will give it a try  - I will let you know if any unexpected results show up.

Dieter
