### ISSUE TITLE
severe differences in output in v 2.4 compared to 2.3.7

### ISSUE THREAD

**Issue by lsterck** [fenderglass/ABruijn#74]
Up until recently I was using version 2.3.7 of Flye, but due to issue #68 I switched to version 2.4. 
That version runs technically OK but I noticed the differences in the result are remarkable.
for the v2.3.7 when I look at the `graph_paths.fasta` file it had a size of ~10Gb (which is indeed in the range of my genome size estimate), however if I run the exact some command but with v 2.4 that file (which is now in the 30-contigger folder, correct?) is only 1.6Gb !
It thus looks like I only get a fraction of the result I got before.

I must add (and admit) I did not check the change logs to see if there is anything that could explain this behavior.

thx in advance.

**Comment by mikolmogorov** [comment]
It's really hard to tell without extra information. What is the input? Is it `--subassemblies` mode? What is the target genome? 

Can you provide log files from both runs? Can you also post the outputs of `ls -Rl` inside working directories of both assemblies?

**Comment by lsterck** [comment]
Hi,
sincere apologies for the slow (non) answering, I have been severely side-tracked on different projects.

Yes, it's the subassemblies mode indeed. 
the input is an assembly of short reads and a long read assembly I did with Flye

here is ls -Rl (older Flye version):
```
total 391680
drwxrwsr-x 2 vsc vsc      4096 Jan  8 15:19 0-assembly
drwxrwsr-x 2 vsc vsc      4096 Jan 13 12:38 2-repeat
drwxrwsr-x 2 vsc vsc      4096 Jan 16 10:20 3-polishing
-rw-rw-r-- 1 vsc vsc 400773267 Jan 18 09:12 flye.log
-rw-rw-r-- 1 vsc vsc        87 Jan 15 10:19 params.json

./0-assembly:
total 11187712
-rw-rw-r-- 1 vsc vsc 11456109626 Jan  8 15:22 draft_assembly.fasta

./2-repeat:
total 38905856
-rw-rw-r-- 1 vsc vsc    16558442 Jan 13 11:21 contigs_stats.txt
-rw-rw-r-- 1 vsc vsc  9230359682 Jan 14 19:37 graph_before_rr.fasta
-rw-rw-r-- 1 vsc vsc   159602656 Jan 13 11:02 graph_before_rr.gv
-rw-rw-r-- 1 vsc vsc  9811632523 Jan 14 19:37 graph_final.fasta
-rw-rw-r-- 1 vsc vsc  9795043082 Jan 14 19:37 graph_final.gfa
-rw-rw-r-- 1 vsc vsc   134054790 Jan 13 12:30 graph_final.gv
-rw-rw-r-- 1 vsc vsc 10688924042 Jan 14 19:37 graph_paths.fasta
-rw-rw-r-- 1 vsc vsc      870012 Jan 13 12:29 repeats_dump.txt
-rw-rw-r-- 1 vsc vsc       43288 Jan 13 11:24 scaffolds_links.txt

./3-polishing:
total 103242752
-rw-rw-r-- 1 vsc vsc 50467626757 Jan 15 13:24 bubbles_1.fasta
-rw-rw-r-- 1 vsc vsc   204303048 Jan 16 00:34 bubbles_1.fasta.1stgb.gz
-rw-rw-r-- 1 vsc vsc    16561840 Jan 15 13:26 consensus_1.fasta
-rw-rw-r-- 1 vsc vsc 55031076987 Jan 15 11:46 minimap_1.sam

```
and here for the newest Flye version:
```
total 3586560
drwxrwsr-x 2 vsc vsc       4096 Jan 22 02:39 00-assembly
drwxrwsr-x 2 vsc vsc       4096 Jan 22 17:47 20-repeat
drwxrwsr-x 2 vsc vsc       4096 Jan 22 18:07 30-contigger
drwxrwsr-x 2 vsc vsc       4096 Jan 22 21:45 40-polishing
-rw-rw-r-- 1 vsc vsc 1736964293 Jan 22 21:45 assembly_graph.gfa
-rw-rw-r-- 1 vsc vsc   43151141 Jan 22 18:06 assembly_graph.gv
-rw-rw-r-- 1 vsc vsc    4450714 Jan 22 21:46 assembly_info.txt
-rw-rw-r-- 1 vsc vsc  157004043 Jan 22 21:46 flye.log
-rw-rw-r-- 1 vsc vsc        109 Jan 22 21:45 params.json
-rw-rw-r-- 1 vsc vsc 1729907935 Jan 22 21:46 scaffolds.fasta

./00-assembly:
total 11188736
-rw-rw-r-- 1 vsc vsc 11457060640 Jan 22 02:42 draft_assembly.fasta

./20-repeat:
total 11848704
-rw-rw-r-- 1 vsc vsc    51912287 Jan 22 17:47 graph_after_rr.gv
-rw-rw-r-- 1 vsc vsc  1717940562 Jan 22 17:51 graph_before_rr.fasta
-rw-rw-r-- 1 vsc vsc    51887785 Jan 22 17:46 graph_before_rr.gv
-rw-rw-r-- 1 vsc vsc   131576039 Jan 22 17:47 read_alignment_dump
-rw-rw-r-- 1 vsc vsc    60284545 Jan 22 17:47 repeat_graph_dump
-rw-rw-r-- 1 vsc vsc 10118266822 Jan 22 17:51 repeat_graph_edges.fasta

./30-contigger:
total 5092352
-rw-rw-r-- 1 vsc vsc    4629070 Jan 22 18:06 contigs_stats.txt
-rw-rw-r-- 1 vsc vsc 1717300234 Jan 22 18:55 graph_final.fasta
-rw-rw-r-- 1 vsc vsc 1730675473 Jan 22 18:55 graph_final.gfa
-rw-rw-r-- 1 vsc vsc   43151141 Jan 22 18:06 graph_final.gv
-rw-rw-r-- 1 vsc vsc 1717300234 Jan 22 18:55 graph_paths.fasta
-rw-rw-r-- 1 vsc vsc          0 Jan 22 18:06 scaffolds_links.txt

./40-polishing:
total 49983488
-rw-rw-r-- 1 vsc vsc 11665613341 Jan 22 19:53 bubbles_1.fasta
-rw-rw-r-- 1 vsc vsc  3759862351 Jan 22 21:30 consensus_1.fasta
-rw-rw-r-- 1 vsc vsc     2521134 Jan 22 21:36 contigs_stats.txt
-rw-rw-r-- 1 vsc vsc  1766885242 Jan 22 21:39 edges_aln.sam
-rw-rw-r-- 1 vsc vsc 28788365664 Jan 22 19:28 minimap_1.sam
-rw-rw-r-- 1 vsc vsc  1729907935 Jan 22 21:36 polished_1.fasta
-rw-rw-r-- 1 vsc vsc  1730753087 Jan 22 21:45 polished_edges.fasta
-rw-rw-r-- 1 vsc vsc  1736964293 Jan 22 21:45 polished_edges.gfa

```

I'll look for the log files and provide them to you.
thx

**Comment by lsterck** [comment]
Hi again,

here is a tarball with the logs for both old and new version:
[flye_old_new_logs.tgz](https://floppy.psb.ugent.be/index.php/s/eU82bkiZ5FqOIdq)

**Comment by lsterck** [comment]
Hi @fenderglass ,

does this imply this issue might be resolved by the new commit?
Can I help somehow? test it out or such for instance?

thx nonetheless already

**Comment by mikolmogorov** [comment]
Thank you, I think I was able to identify the problem. I pushed a fix to the main github branch (and was running some tests). Let me know if it works for you.

**Comment by lsterck** [comment]
Hi,

I've now tested it (a few time even) but my end result does not really change I'm afraid.
Perhaps I'm doing something wrong? I did a `git pull` and then ran the `python setup.py build` . Can I simply install it in the folder I was using before or should I do a complete new/clean install?

The pipeline runs correctly but the result is nothing near the one I obtained with v2.3.7 and is actually pretty much similar to runs prior to your fix.

While I'm at it: I also don't understand the message Flye prints in the beginning where it says that the coverage is only ~1 . Is this not expected when running the --subassem mode ? Perhaps you need to account for that (at least for the printing of this message), For any --subassem run the coverage can roughly only be reflecting the # input assemblies , no?

**Comment by lsterck** [comment]
UPDATE: let me first check if am actually running the newest code of Flye :/

**Comment by mikolmogorov** [comment]
To make sure, try to clone into a new directory, then do `make` and run locally by invoking `bin/flye`. It will show the version tag in the beginning of the log - it should end with `1d08def `. Let me know if it's not working - can you send me the resulting log in this case?

**Comment by lsterck** [comment]
Hi,
yes, done the re-cloning in the meanwhile.
however I can't get versioning info :/ , the only thing I get (when doing `flye --version`) is `2.4.1-release`
and in the log file (when I start a new run) I get: `INFO: Starting Flye 2.4-release`

Is there anywhere else I can/should look?

somewhat down in the log file file I found this message: `Build date: Jan 18 2019 09:02:04` , does that help?

**Comment by mikolmogorov** [comment]
This means you are running a version that was installed into your system (not the local one). Which command do you use? It should be `bin/flye` from the cloned directory.

**Comment by lsterck** [comment]
I get the same output when doing `bin/flye `in the Flye folder.

on the other hand I do indeed have another version laying around (in my miniconda2 install folder). Should/will clean that up.

**Comment by mikolmogorov** [comment]
This seems strange, what about the version in terminal output? If you are using the same output directory, Flye does not overwrite the log file, so the top lines might be from the past runs.

**Comment by lsterck** [comment]
OK, 
bloody hell (and stupid me as well ;) ) , apparently the flye version installed in this miniconda folder was overruling the newer install indeed. 
And I have been using that one all along apparently (since somewhere February), no idea how it then got this fix for the IUPAC code in it ....

anyway, you can kinda forget all I wrote so far, Will test with the correct version.
Apologies!

**Comment by lsterck** [comment]
the output part of `bin/flye`  (`--version`) is what I sad it was however

even if I call it from within the new git-cloned folder:  `2.4.1-release`
and in the logs when running flye it says `INFO: Starting Flye 2.4-release`

**Comment by lsterck** [comment]
OK, I can confirm. The newest version does indeed return the result I was expecting (at least size-wise). Thx for it.

One last comment to finish this off: I still think it is a bit weird to provide a warning message that the coverage is only around ~1x when using the subassemblies option. This is something to be expected, no (== that the coverage will be linked to the number of subassemblies provided?) so this message will only unnecessary 'scare' users I'm afraid.

**Comment by mikolmogorov** [comment]
Glad to hear that it worked. I will change this warning for the subassemblies mode.
