### ISSUE TITLE
Install from git failed

### ISSUE THREAD

**Issue by BryceLBL** [fenderglass/ABruijn#75]
I'm trying a new installation for flye but it fails with "No such file or directory"

`
[root@7ef29d0996d7 /]# git clone https://github.com/fenderglass/Flye
Cloning into 'Flye'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (282/282), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 11893 (delta 181), reused 176 (delta 101), pack-reused 11611
Receiving objects: 100% (11893/11893), 9.57 MiB | 14.55 MiB/s, done.
Resolving deltas: 100% (8574/8574), done.
[root@7ef29d0996d7 /]# cd Flye
[root@7ef29d0996d7 Flye]# ls -l  
total 40
-rw-r--r-- 1 root root 1499 Feb  5 12:18 LICENSE
-rw-r--r-- 1 root root  823 Feb  5 12:18 Makefile
-rw-r--r-- 1 root root 5516 Feb  5 12:18 README.md
drwxr-xr-x 2 root root 4096 Feb  5 12:18 bin
drwxr-xr-x 2 root root 4096 Feb  5 12:18 docs
drwxr-xr-x 9 root root 4096 Feb  5 12:18 flye
drwxr-xr-x 6 root root 4096 Feb  5 12:18 lib
-rw-r--r-- 1 root root 1515 Feb  5 12:18 setup.py
drwxr-xr-x 9 root root 4096 Feb  5 12:18 src
[root@7ef29d0996d7 Flye]# python setup.py build
running build
error: No such file or directory`

**Comment by mikolmogorov** [comment]
Something might be wrong with your Python environment. What OS is this? Do bioconda builds work for you? You can try to get a clean Conda python environment and install Flye inside it.

P.S. It's unrelated, but working under root is never a good idea..

**Comment by BryceLBL** [comment]
I agree working under root isn't good but this is inside a docker container.

I was using a fresh Centos image from docker.

**Comment by BryceLBL** [comment]
I found a docker container to use, so this shouldn't be a high priority 
ticket to work on.

**Comment by mikolmogorov** [comment]
It is likely that a fresh CentOS is missing developer environment. I think in your cause automake/gcc is missing. Closing for now, feel free to reopen if there will be any other issues.
