### ISSUE TITLE
Discrepancy between the final graph and sequence files

### ISSUE THREAD

**Issue by ilnamkang** [fenderglass/ABruijn#76]
Hi,

I'm trying to assemble the genome sequence of a bacterial strain belonging to the genus Streptomyces. (The genus Streptomyces is known to have a linear chromosome with terminal inverted repeat.)

When I assembled the genome using Flye, the final "scaffolds.fasta" file contained a single contig (~8.6 Mbp), with no N. The final graph file showed two edges, with a short edge representing a terminal inverted repeat clearly. I've attached an image of the graph file as visualized by Bandage ("graph.png"). The attached "assembly_info.txt" file also indicated that the genome has a terminal inverted repeat. So, I expected that the starting terminal region (~18 kb) of the contig would be identical to the ending terminal region. But, the two terminal regions showed only ~91% identity to each other. Is this possible? If possible, what should I take as the final result?

(If you need other output files including the scaffold sequence, would you let me know your email address so that I can send the files? I'm just helping my colleagues who're working on this strain, so I'm a little bit cautious on the public sharing of the data.)

Thanks.

![graph](https://user-images.githubusercontent.com/11887252/52338302-5f3a1080-2a4d-11e9-9860-a0653c726f46.png)
[assembly_info.txt](https://github.com/fenderglass/Flye/files/2836093/assembly_info.txt)

**Comment by mikolmogorov** [comment]
Hi,

I think it is possible, yes. Flye extends contigs using both reads the graph structure. Basically, starting from a unique edge (contig_1), it finds a longest read that extends from the end of the edge (and is consistent with the graph structure) and adds this extra sequence to the corresponding contig (this is done in both directions). So contig = unique graph edge + possible extension into unresolved repeat(s). In case the terminal repeat copies have 9% difference, Flye should capture it - and this single contig you are getting would be your full genome.

One caveat hare is that sometimes the consensus quality on contig ends is reduced (since less reads are mapped there). I would actually try to run multiple polishing iterations (`-i` option) and check if the terminal sequence converges. You can also inspect the intermediate .sam files in `40-polishing` dir and check if you have enough read coverage on the ends of contigs (for example, with IGV).

**Comment by ilnamkang** [comment]
Hi,

Thank you for explanation.

(1) I ran multiple rounds of polishing following your suggestion, but the result is not much different from the previous one obtained with default settings.

(2) I performed the mapping of raw PacBio reads onto the final scaffold sequence using minimap2, to check read coverage on the contig ends. Below, I attach IGV snapshot images of both ends. It seems that no reads were mapped onto the start region of the contig. The sequence of 'contig_2' edge (extracted from the graph) was identical to the end region of the contig, but showed ~9% difference from the start region. Most of the differences were found within the non-mapped region.

So, I'm confused about where the sequence of non-mapped start region (~10 kb) was originated.

Thanks.
  
(Start region of the contig)
![igv_snapshot minimap2scaffolds start](https://user-images.githubusercontent.com/11887252/52461549-d4732600-2bb2-11e9-977a-667f40823da0.png)

(End region of the contig)
![igv_snapshot minimap2scaffolds end](https://user-images.githubusercontent.com/11887252/52461597-0b493c00-2bb3-11e9-98a1-b8458ce147e9.png)

**Comment by mikolmogorov** [comment]
Ok, seems like an interesting case. On the first screenshot, there is actually one read that aligned to the contig perfectly (without any indels, which in not expected for a PacBio read). So I think this read most likely gave rise to the contig sequence (as I described in the previous post). 

I think, what happened was that you initially had an unpolished contig with two terminal repeats (which in reality are similar or almost similar). But, somehow one copy (on the right) had a bit better quality before polishing - so it attracted more reads during minimap alignment. As a result, left copy was left unpolished - and this is why you see this 9% divergence (close to the error rate of raw reads).

So the bottom line is - the assembly structure most likely is correct, but there is an issue with polishing. In general, polishing repeats is difficult and I don't know if any of the available long-read polishers does a decent job on them (people are more concerned about unique protein-coding parts). Telomeric repeats are even more difficult - in this situation, as you see, read coverage drops significantly at both contig ends. I'm not sure why though - could it be some kind of read sampling bias? As an experiment, you can try to artificially separate the contig into two and polish them separately (the latest github version has an option to run the polisher separately). This should solve the problem of two repeat copies competing for reads and you should be able to see if you really have read coverage for both telomeric ends.

**Comment by ilnamkang** [comment]
Oh, I missed that one read that was aligned perfectly to the contig.

Following your suggestion, I separated the contig into two halves and performed mapping separately. While there were little changes in the right end, the number of reads mapped to the left end increased dramatically. See the attached image below. So, I think your inference is right.

Thank you for your help.

![image](https://user-images.githubusercontent.com/11887252/52542777-96f6de80-2de6-11e9-9b7e-9a42e5fd26bd.png)

**Comment by mikolmogorov** [comment]
Seems that the issue was resolved - closing for now. Feel free to reopen if you have more questions.
