### ISSUE TITLE
resume stage

### ISSUE THREAD

**Issue by HTaekOppa** [fenderglass/ABruijn#77]
Dear Flye,

Hope this email finds you well.
I managed to reach the stage of "1-consensus". Due to an internal glitch of HPC, the process was disrupted. Not fully sure whether this stage was fully completed, either. 
What I can see from the folder "1-consensus" is 
879706423109 Jan 28 03:38 minimap.sam 

FYI,
[flye_log.txt](https://github.com/fenderglass/Flye/files/2859041/flye_log.txt)

Bioconda environment, Flye 2.3.7 (updated as 2.4 but did not work due to "inconsistent pipeline version". So I had to re-install it as flye=2.3.7).

I used "--resume-from repeat" but I got this error.
[2019-02-13 13:37:20] INFO: Running Flye 2.3.7-release
[2019-02-13 13:37:20] INFO: Resuming previous run
[2019-02-13 13:37:20] ERROR: Can't resume: stage repeat incomplete

I have also attached the log file.

Is there any option I can re-submit the job that could pick it up from the interrupted stage?

Any advice would be greatly appreciated!

Cheers,

Taek

**Comment by mikolmogorov** [comment]
Hi Taek,

The consensus stage is incomplete (the log is a bit misleading..). You need to do either  `--resume` or `--resume-from consensus`
