### ISSUE TITLE
ERROR: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by palfalvi** [fenderglass/ABruijn#80]
Hi,

First of all, thank you for the software and the support, great job!

I was about to run a test Flye (pun intended) on one of my ONT dataset (~1G plant genome 27x coverage), when it quickly throw me back the following error just before the assembly:
```
ERROR: [Errno 7] Argument list too long
```
I think it is due to the nanopore fastq file numbers. I fed Flye the fastqs something like: `/home/user/nanopore-raw/?_run/*.fastq` where I have 5 run folders and each contains fastqs as nanopore outputs them, 40k seq/file. The file list may be out of the limit to feed to python. If it is possible i do not want to concatenate all the fastqs into one huge fastq file. Do you have any fix or workaround for this issue? 

Thanks in advance!

**Comment by mikolmogorov** [comment]
Hi,

There is a system limitation on the number of command line arguments - so it can't be changed. The right way is to concatenate all fastqs from each run into a single file.

**Comment by palfalvi** [comment]
Hi,

Thanks for the answer. I know it is not a bug in flye but a system limitation and there are workarounds for this, but it would be way more easier if there would be some built-in protection for this. 
Maybe someone would like to play around to include or exclude runs, or rerun with more created libraries without modifying code or input file. It would be an improvement in my opinion, but it is up to you if you care about this.

e.g. in the beginning of the run it could just store all the `fastq`s in a `reads_temp.fastq.gz` file. 
Or at least you could include in the man page to use something like this:

```
flye --nano-raw `cat /home/user/run_?/*.fastq` ...
```

Not as elegant, but works.

**Comment by mikolmogorov** [comment]
To concatenate the files inside the pipeline, you would still need to pass these files as arguments to Flye - and hit the same limitation. Same thing with the command line you gave - there is a maximum length limitation on a command line argument, and I don't think the entire fastq file will fit.

**Comment by peterjc** [comment]
I just hit this too (first time using fyle) and wondered about concatenation as a workaround. Perhaps it deserves an FAQ entry?

Or, could you accept a directory name (and infer any FASTA or FASTQ files present with standard extensions should be used)?
