### ISSUE TITLE
How to use RS-II raw data 

### ISSUE THREAD

**Issue by golden75** [fenderglass/ABruijn#87]
Hi,
I have RS-II pacbio data which I am want to use it in Flye.

`
└── raw_data  
    ├── Analysis_Results  
    │   ├── m_s1_p0.1.bax.h5  
    │   ├── m_s1_p0.1.subreads.fasta  
     │   ├── m_s1_p0.1.subreads.fastq 
    │   ├── m_s1_p0.2.bax.h5  
     │   ├── m_s1_p0.2.subreads.fasta  
    │   ├── m_s1_p0.2.subreads.fastq  
     │   ├── m_s1_p0.3.bax.h5  
    │   ├── m_s1_p0.3.subreads.fasta  
    │   ├── m_s1_p0.3.subreads.fastq  
    │   └── m_s1_p0.metadata.xml  
    ├── m_s1_p0.bas.h5 

`

Do I need to pre-process the data into a fasta file before I use it to assemble using Flye? 
If so can I use flye to convert the above or do I need to use another software to do it ?

**Comment by mikolmogorov** [comment]
You can supply multiple fasta/q files separated by spaces: `--pacbio-raw m_s1_p0.1.subreads.fasta m_s1_p0.2.subreads.fasta m_s1_p0.3.subreads.fasta`. You can do fastq instead, but it won't make any difference on the assembly.
