### ISSUE TITLE
ERROR: Minimap2 is not installed

### ISSUE THREAD

**Issue by zijiangyang** [fenderglass/ABruijn#93]
Hi, I already installed minimap2 (minimap2 works fine from the command line) however it keeps return with this message.

**Comment by MichelMoser** [comment]
Do you run Flye on a cluster?

**Comment by mikolmogorov** [comment]
Hi, 

Flye is using it's own version of minimap. This message likely means that you did not build / install Flye properly. Please follow the instructions in `docs/INSATLL.md` or alternatively use bioconda release.

**Comment by zijiangyang** [comment]
Yes, currently I'm working on a cluster. I'll try to re-install Flye to see what happens.  Thanks!!!
