### ISSUE TITLE
Overcollapsing?

### ISSUE THREAD

**Issue by rotifergirl** [fenderglass/ABruijn#95]
Hi,

I just ran flye on some pacbio reads we have (~50x coverage) of a monogonont rotifer.

The sequence comes from an inbred line, but we likely have some (ancient) polyploidy going on, and the genomes are highly repetitive. This one in particular is probably upwards of 60% repeats. The total nuclear DNA content (we measured this by flow cytometry since we have genome size variations in this species) is 568Mbp, so the haploid estimate (assuming diploidy) is 283Mbp, and this is the genome size I gave to flye.

We have one genome assembly using Falcon- 230 Mbp
One using Canu- 219 Mbp

The flye assembly using default parameters came out at 175.7 Mbp, but when I check some of the intermediate files (eg 10-consesus/consensus.fa) the assembly size is 270 Mbp, which is obviously closer to what we are expecting.

So I have a few questions really:
1) Is flye very dependent on the genome size estimate you give it? If so, is genome size, the 1C genome size, or the total nuclear DNA?
2) How does flye deal with polyploid inbred genomes? Do you think it is prone to collapsing genic regions that may be paralogues? 
3) Any tips for dealing with this genome? I've already found the thread about the min overlap, but I have doubts that this would drastically change my assembly size?

Thanks!
Julie

**Comment by mikolmogorov** [comment]
Hi Julie,

1. Flye should not be very sensitive for the genome size parameter. It is mainly used in the very beginning to construct solid k-mer index, and does not affect repeat graph analysis stage. The input parameter should be roughly equal to the total assembled sequence (one main haplotype + alternatives in case they contain novel sequence).

2. I am not sure I understand how polyploid inbreed is different from diploid.. Do polyploid inbred genomes have higher sequence divergence between paralogues? Flye performance is currently somewhat limited on highly heterozygous genomes - you should be able to get all unique sequence assembled, but not necessarily as contiguous as a diploid assembler would do.

3. Overall, I think it is possible that Flye over-collapses alternative alleles or (which sounds more likely to me) repetitive content. Could you send me a log file of your run? I would also try to run Flye on the corrected reads (since you already have Canu / Falcon results) - this might help in case of overcollapsing repeats with a few % copy divergence.

**Comment by rotifergirl** [comment]
Hi,

Sorry for the slightly slow reply, I was running flye with a few different parameters to check a few things.

My main concern with 2 is that our genome is very homozygous (because of the inbreeding), and the heterozygous sites in the assembly likely represent paralogues (though I don't know how diverged the two paralogues are). So my concern is that the paralogues are collapsed like homologues typically would be, but this doesn't appear to have happened with either canu or Flacon. 

I've attached the log files from two different assemblies, both with default settings, one on the raw pacbio reads and the other on the canu corrected reads. I noticed in both log files that the mean coverage is much higher than the predicted coverage

[flye.log_corr_reads.log](https://github.com/fenderglass/Flye/files/3088399/flye.log_corr_reads.log)

[flye.log_default.log](https://github.com/fenderglass/Flye/files/3088394/flye.log_default.log)

**Comment by mikolmogorov** [comment]
Thank you! Hard to tell, what exactly is going on - both logs look ok. I think it might be possible that Flye  collapses repeats - we saw this previously in repeat-rich assemblies. Here are a few things you could check:

1. See, what proportion of Falcon assembly is in "alternative" contigs - so you can roughly estimate heterozygosity level.

2. Assembly contiguity is also important. I suggest to run QUAST (without reference) on all assemblies and check cumulative length plots - they are robust to different assembly sizes.

3. You can also turn on gene prediction in QUAST - so you will if Flye assembly is missing some coding sequence (or it's just the repeats).

3. Could also send me the graph of the raw assembly (`assembly_graph.gv`), so I can take a look?

**Comment by rotifergirl** [comment]
Hi again,

I think you are right that Flye is collapsing my repeats, I have run BUSCO on it (I had already run this on my other two assemblies) and the output is comparable to the Canu and Falcon assemblies (~90% of metazoan genes complete).

Unfortunately I don't currently have access to the other Falcon output files (just the assembly) as someone else made it, but we know we have low heterozygosity in the wildtype genomes, so it will be even lower in this inbred genome.

Should I email you the .gv file? Github wont let me upload it (I can say that the genome graph is more tangled for this than the Canu assembly)

**Comment by mikolmogorov** [comment]
Thank you! Highly repetitive genomes are definitely a challenge. In particular, if there are many repeat families with divergent copies (a few %), Flye might overcollapse these copies in the repeat graph. On the other hand, OLC methods that are not aiming for "transitive" repeat representation might perform better as a result. Is it a plant genome by the way? 

Sure, you can send the graph to fenderglass@gmail.com

**Comment by mikolmogorov** [comment]
Closing an old issue, feel free to reopen if you have more questions.
