### ISSUE TITLE
High RAM usage for ONT with flipflop  basecalls

### ISSUE THREAD

**Issue by stephrom** [fenderglass/ABruijn#97]
dear,

I tried a few versions (including 2.4.2) of Flye the past weeks with the same problem each time.
I'm trying to assemble a 1Gb genome using ONT reads that I called using guppy v2.3.7 with the flipflop model. My minion run is pretty good with lots of read >100Kb (read N50 >10Kb) longest read ~640K. I assembled the same run with reads called with albacore successfully though. Looking at the reads with albacore the lengths are shorter (longest read in that case 230K). So, even thought the data looks better, Flye seems to have problems with it.
[flye.log](https://github.com/fenderglass/Flye/files/3070346/flye.log)

**Comment by mikolmogorov** [comment]
Hi,

So, as I understand you can assemble the same reads called with Albacore, but flip-flip basecalls are causing Flye to run out of memory? Yes, I had similar reports from other users - it looks like flipflop reads have lower error rate, and as a result you have more matching k-mers and you need more memory to store them. I think this should be solved by some parameter adjustments - I am planning to take a look on it in the near future.

In the mean time, you might try to assembled with `--meta` option. It has a different approach for k-mer selection, which might save you some memory.

Best,
Mikhail

**Comment by stephrom** [comment]
Hi Mikhail,

Thank you for the fast response. 
I tried with '--meta' option but that didn't help...
[flye.log](https://github.com/fenderglass/Flye/files/3072228/flye.log)

**Comment by mikolmogorov** [comment]
Thank you. It seems that there actually one small publicly available dataset with flipflop basecalls - will look into this.

**Comment by stephrom** [comment]
Dear Mikhail,

I made some more tests concerning this issue, and it seems that all runs fine when allocating more RAM/core. In other words, I ran the same command line using only 5 cores, but with 48Gb RAM/core.
I didn't test how low I could go with the RAM to still make it work though.

best
Stephane

**Comment by mikolmogorov** [comment]
Thank you,

I'm glad it worked out. Do I understand correctly - Flye consumed less RAM in total when running with reduced number of threads? Or you have some kind of control on how much RAM each thread is using (which seems strange to me since threads should be sharing the memory allocated by the program). Could you also send me the log of the successful run?

Best,
Mikhail

**Comment by stephrom** [comment]
Dear Mikhail,

when we submit a job to our cluster we allocate the amount of RAM/core. But that package of RAM * core is then further managed by the program running on the cluster. So we do not have control on how the RAM is being managed by the program running. In most cases the program is being told how many core are available and manages/allocates the RAM as it see fit. If the program requires more RAM than initially requested for the whole job (at the time of submission), then the job will crash.
So I guess flye is being told to use x cores and manages the amount of RAM. In the case of the "flipflot"-reads, the core(s) busy counting kmers probably need more RAM compared on how the RAM is currently distributed over the cores (just a guess)
[flye.log.gz](https://github.com/fenderglass/Flye/files/3111273/flye.log.gz)

.

best
Stephane

**Comment by mikolmogorov** [comment]
Thank you. Various cluster setups / grid systems are mystery to me - the way they manage resources (CPU / RAM) varies a lot for different setups. 

Overall, RAM required for building the index (that takes most of the memory) theoretically should not depend on the number of threads (with respect to small fluctuations, perhaps). But during disjointig extension (next step) extra threads might require additional memory for local index - which also highly dependent on a particular genome.

**Comment by cjw85** [comment]
@fenderglass,

If you want or need more data to test parameters with flipflop basecalls, we have a set of small genomes here: https://github.com/nanoporetech/zymo-data.

@nickloman has similar here: https://github.com/LomanLab/mockcommunity

**Comment by mikolmogorov** [comment]
Thank you - this should help! 

I did try to assemble Nick's data before, but did not see any significant differences in performance. On the other hand, some other flipflop assemblies (based on the log files I've seen) show a clear increase in the number of matching k-mers - and memory usage grows as a result. I suspect there might be  variation in the basecaller model versions / pores used.

**Comment by stephrom** [comment]
Dear,

an other observation due to the drop in error rate thanks to the flipflop model.

I have the impression that we get more haplo-tigs the better the reads become.
The layout at the start of the assembly process is up to double the expected size of the haploid genome. The length of the reads are also to blame in this case.

So if one has a good run, with a read N50 over the 25Kb, and a lower error rate, gets extra haplo-tigs resulting in larger that expected genome at the layout step.
with the next steps in the assembly process, the total assembly size drops again, but some haplo-tigs remain.

best
Stephane

**Comment by mikolmogorov** [comment]
I ran some tests with the new flip-flop datasets (both fast and HAC). Looks like it has slightly increased memory consumption, but not very significant. Closing this issue for now. feel free to reopen if you still have specific issue with flip-flop RAM consumption.
