### ISSUE TITLE
Can I use mixed (PacBio+ONT) input data ?

### ISSUE THREAD

**Issue by jvhaarst** [fenderglass/ABruijn#98]
I'm trying to use a dataset that contains mostly PacBio, and some extra NanoPore data.

I have tried it like this : 
`flye --pacbio-raw $PBREADS --nano-raw $ONTREADS --out-dir $OUTPUTDIR`

But that doesn't seem to be the correct way, as I get an error  :
`flye: error: argument --nano-raw: not allowed with argument --pacbio-raw`

Is there a way to use both datasets with Flye ?

**Comment by mikolmogorov** [comment]
Hi,

You can do this as follows:
 
First, start with all reads, but use either `--pacbio-raw` or `nano-raw` for all of them, also add `--iterations 0` to stop before polishing. 

Once the pipeline finishes, run the same command line but with only PacBio reads specified (`--pacbio-raw`), add `--resume-from polishing` argument and remove `--iterations 0`. This should run polishing with PacBio reads only.

**Comment by jvhaarst** [comment]
Worked like a charm, thanks !
Adding the ONT data didn't really change much, but as we have it, we might as well use it.

**Comment by jolespin** [comment]
Let's say one had 2 assemblies with one generated from pacbio reads and the other generated from nanopore reads on the sample biological sample.  Is it logical to use the `--subassemblies` parameter with both of these assemblies to generate a consensus assembly?

**Comment by mikolmogorov** [comment]
It is a possibility, but it is better to mix two read sets in one assembly - this might help to resolve more repeats in an optimal way.

**Comment by jolespin** [comment]
I have half and half pacbio/nanopore.  Are you suggesting the following commands? 

```bash
OUTPUTDIR=flye_output
PACBIO_READS=path/to/pacbio.fastq.gz
NANOPORE_READS=path/to/nanopore.fastq.gz 
cat $PACBIO_READS $NANOPORE_READS > merged_reads.fastq.gz
flye --pacbio-raw merged_reads.fastq.gz --out-dir $OUTPUTDIR --iterations 0 
flye --pacbio-raw merged_reads.fastq.gz --out-dir $OUTPUTDIR --resume-from polishing
```

Does it polish the pacbio and nanopore reads differently or does it not matter if I use `--pacbio` or `--nanopore`?

**Comment by jvhaarst** [comment]
What I did is this :
```
flye --pacbio-raw $PBREADS $ONTREADS --iterations 0                         --out-dir $OUTPUTDIR  --genome-size 3.5g --threads $THREADS
flye --pacbio-raw $PBREADS                          --resume-from polishing --out-dir $OUTPUTDIR  --genome-size 3.5g --threads $THREADS
```

So, first do the assembly with both datasets, and then polish with only the PacBio data.

**Comment by jolespin** [comment]
Thanks for the example!  I’m going to try this today.  I could probably try this and the opposite with nanopore as the main.  Do you know if the polishing step with only work on the Pacbio reads or is that a kind of dummy variable to get it to run from the polishing step on everything? 

Also, does it polish the disjointigs from Pacbio and nanopore differently?
