### ISSUE TITLE
Queries regarding Metagenome assembly

### ISSUE THREAD

**Issue by harish0201** [fenderglass/ABruijn#99]
Hi Mikhail!

I have some doubts regarding metagenome assemblies using PacBio/ONT read datasets.

Since Flye also needs a genome size parameter for the assemblies, I was wondering how to decide on the assembly size.

Should I initially bin the reads at a family or a genus level and then perform multiple assemblies for each binned data pool?

Or should I hypothesize the number of genomes that might be contained (say 10 genomes of average size 5Mb, so total 50Mb) and take a sum of genome sizes as the input parameter?

What other parameters should/can be tweaked for a decent assembly? (Other than the --meta option)

**Comment by mikolmogorov** [comment]
Hi,

Metagenome mode is not very sensitive to the genome size parameter. You can use all reads from your sample together, and provide an estimate of your total metagenome assembly size (including all genomes). No other parameter tweaking is required.

Hope this helps,
Mikhail

**Comment by harish0201** [comment]
Hey,

Apologies for the delay, I'll get back to you once I get the datasets. Thanks for the help!

I'm closing it in the mean time.
